### ISSUE TITLE
How to register external threads?

### ISSUE THREAD

**Issue by SamtFischer001** [Microsoft/ptvsd#1003]
The function “ptvsd.debugger.new_external_thread()” no longer exists. Is there another way to register an external thread?

**Comment by karthiknadig** [comment]
4.* does not have this feature. @int19h, other than forcing a debug break i can't think of an alternative to  `new_external_thread`? @fabioz, is there a way to tell pydevd about external threads, i remember you could do settrace without stopping as a way to identify external threads?

**Comment by fabioz** [comment]
Yes, doing pydevd.settrace(suspend=False) should do the trick.

**Comment by SamtFischer001** [comment]
pydevd.settrace(suspend=False) solves the problem. Thanks.

**Comment by int19h** [comment]
I think we should provide an implementation of `new_external_thread` that wraps this, though. For back-compat if anything, but also, if we are officially supporting this method, it should be a part of our API, and we should have a test for it.
