### ISSUE TITLE
Unable to debug with latest version of ptvsd with pydevd 1.4.0

### ISSUE THREAD

**Issue by schwab** [Microsoft/ptvsd#1007]
New Error message with lastest vscode/ptvsd/pydevd when attempting to debug : ModuleNotFoundError: No module named '_pydevd_bundle.pydevd_comm_constants'

## Environment data

- PTVSD version: 4.2.0
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: vscode 1.28.2

## Actual behavior

Attempting to start debugger always gives: 

`  File "/home/mcstar-dev/.local/lib/python3.6/site-packages/ptvsd/daemon.py", line 9, in <module>
    from ptvsd import wrapper, options, multiproc
  File "/home/mcstar-dev/.local/lib/python3.6/site-packages/ptvsd/wrapper.py", line 37, in <module>
    import _pydevd_bundle.pydevd_comm_constants as pydevd_comm_constants  # noqa
ModuleNotFoundError: No module named '_pydevd_bundle.pydevd_comm_constants'
`
 and debugger won't start.

## Expected  behavior

Debugger should start and function as normal.  This worked fine until the latest version of vscode (last week??)

## Steps to reproduce:
1. install the latest pydevd `pip3 install pydevd` and ptvsd `pip3 install ptvsd`
2. Attempt to start current file or flask debugging with :`{
            "name": "Python: Flask (0.11.x or later)",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "${file}"
            },
            "args": [
                "run",                
                "--no-reload"
            ]
        },`
3. results in no debugger and following in terminal...
` ... File "/home/mcstar-dev/.local/lib/python3.6/site-packages/ptvsd/daemon.py", line 9, in <module>
    from ptvsd import wrapper, options, multiproc
  File "/home/mcstar-dev/.local/lib/python3.6/site-packages/ptvsd/wrapper.py", line 37, in <module>
    import _pydevd_bundle.pydevd_comm_constants as pydevd_comm_constants  # noqa

ModuleNotFoundError: No module named '_pydevd_bundle.pydevd_comm_constants'`

**Comment by karthiknadig** [comment]
@schwab Can you confirm if by chance you have pydevd installed?

**Comment by schwab** [comment]
I've tried it with and without pydevd.  In fact, I only added pydevd because ptvsd starting raising the error "cannot import module pydevd" some time last week.

**Comment by karthiknadig** [comment]
does this repro with any python file or is it specific to flask? Does it occur with ptvsd 4.1.4?

**Comment by schwab** [comment]
I've found that if I remove all ptvsd with multiple iterations of pip3 uninstall ptvsd until none are found, then run the debugger, it works fine.  But the next time I try to run it, it fails with this error: `Traceback (most recent call last):
  File "/home/mcstar-dev/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd_launcher.py", line 15, in <module>
    import ptvsd.debugger as vspd
  File "/home/mcstar-dev/.local/lib/python3.6/site-packages/ptvsd/debugger.py", line 7, in <module>
    from ptvsd._local import run_module, run_file, run_main
  File "/home/mcstar-dev/.local/lib/python3.6/site-packages/ptvsd/_local.py", line 8, in <module>
    import pydevd
ModuleNotFoundError: No module named 'pydevd'

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new`  Next I removed them and did a freeze after the first run, the

**Comment by schwab** [comment]
Found it... one of my packages had ptvsd==3.0.0 specified in the requirements.  This was being force installed whenever the package was built.   Still it's odd that vscode would not always pick/use only the latest if it was installed.

**Comment by DonJayamanne** [comment]
Awesome.
Closing as the issue has been resolved and in favor of https://github.com/Microsoft/vscode-python/issues/3283
