### ISSUE TITLE
Python debug not working with breakpoints in multi-threaded Django app

### ISSUE THREAD

**Issue by Verkurkie** [Microsoft/ptvsd#1021]
## Environment data

- PTVSD version: 2018.10.1
- OS and version: Windows 10, 64-bit, Version 10.0.17134 Build 17134
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.15, 64-bit, miniconda
- Using VS Code or Visual Studio: VS Code (1.27.0) and VS code Insiders (1.29.0)

## Actual behavior

When running debugger for my Django app with the basic Django config from launch.json, the debugger will (a) run the startup command and immediately freeze (no threads in call stack) or (b) run the startup command, start the app thread(s), stop at breakpoints and suddenly freeze (usually after hitting F5/F10/F11)

## Expected  behavior

Debugger should start, run the startup command, stop at breakpoints and continue running after hitting F5/F10/F11

## Steps to reproduce:

1. Open Django app in VS code
2. Set a few breakpoints
3. Create basic Python configurations in launch.json if not present
4. Select the "Python - Django" debug configuration
5. Start the debugger (F5)
6. Check the debug window/terminal to see if startup command is run correctly
7. Use the "call stack" pane to check if the Main Thread (and other child threads) have started
8. If the debugger stops at a breakpoint, hit F10/F11 to see if it freezes

**Comment by karthiknadig** [comment]
Can you give me the launch configuration? also, the layout of your project. If possible can you share the project where the debugger freezes. I am not able to repro with a minimal django app on miniconda2:
![image](https://user-images.githubusercontent.com/3840081/48574860-2b73a280-e8c5-11e8-938e-2c89e918e46a.png)

**Comment by karthiknadig** [comment]
This could potentially be a multi-threading problem

**Comment by karthiknadig** [comment]
Please reopen when there is more info.
