### ISSUE TITLE
'continued' event doesn't always get sent

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1028]
It looks like there's a race condition when issuing a `continue` request such that the script then runs to completion - by the time `on_pydevd_thread_resume_single_notification` is called, the resumed thread has already completed, and debuggee has exited. When that happens, you see this sequence in the logs:

- `continue` request
- `continue` response
- `exited` event
- `terminated` event

(i.e. the `thread` event for terminated thread doesn't get fired, either).

**Comment by int19h** [comment]
Aside from not following the spec, it also causes occasional test failures for all the tests that do something like:
```py
continue_request = debug_session.send_request('continue')
debug_session.wait_for_next(Response(continue_request) & Event('continued'))
```

In all those cases, the tests don't actually need the event, though. The only reason why they wait for it, I think, is to ensure that it is observed. This can be done with `debug_session.timeline.observe_all(Event('continued'))` instead - I'll make that change as part of my other work.

**Comment by int19h** [comment]
Actually, that doesn't quite work, because the event might happen either before or after the response; if it happens after, if we do `observe_all` immediately after `wait_for_response`, it might not be there yet.

So, for now, the event is going to be on `ignore_unobserved` list, so that tests don't have to wait for it. Once this bug is fixed, it can be removed, and tests can be returned to observing it again.

**Comment by int19h** [comment]
Same thing happens with `output` event, if it immediately follows `continue`, and script runs to completion fast enough.

**Comment by karthiknadig** [comment]
There is one more subtle thing. The `continued` event should occur if a thread starts without a command from the user. So, if the `continued` event occurs before `continue` command, it is actually an issue that the test has to capture.

**Comment by int19h** [comment]
Yep. Hence why the current change is adding it to `ignore_unobserved` on a test-by-test basis, only in those tests that do `continue` - it's still not on the default list of ignored things. Once we fix the bug with the event being swallowed on exit, those test-specific mentions can be removed.

**Comment by karthiknadig** [comment]
I had marked this issue incorrectly. The PR referencing this was a workaround.
