### ISSUE TITLE
Code coverage is not collected from live ptvsd in tests

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#1033]
The way we currently collect coverage information with codecov, it only applies to the test process itself. Thus, any tests that exercise the product code by spinning up live ptvsd in a subprocess and communicating with it over DAP, don't get counted. In particular, that includes all of the new pytest-based tests.

**Comment by int19h** [comment]
Once we merge the Tox PR, this can be done via sitecustomize.py inside the virtualenv that Tox sets up for the test run, as described here.

https://coverage.readthedocs.io/en/coverage-4.2/subprocess.html

Note though that this still requires the process to complete cleanly such that `atexit` handlers run. This is not always the case for ptvsd today though - in particular, when the "terminate" request is involved (by design). We might need to force coverage to write out info explicitly somehow for those tests.

**Comment by int19h** [comment]
This is fundamentally broken, because coverage uses the trace hook (`sys.settrace`), and so does the debugger. So they end up stepping on each other's toes, and we get partial results at best, and subtly (or not so subtly) broken debugger at worst.

As far as codecov is concerned, this is basically [not a supported scenario](https://coverage.readthedocs.io/en/coverage-4.5.1x/trouble.html#things-that-don-t-work).

Hypothetically, it could be made to work by forking the coverage module, and modifying it so that it's pydevd-aware. This would probably require changes on pydevd side of things as well. However, that is a substantially larger item than what we planned here.

**Comment by DonJayamanne** [comment]
Yes that makes sense. We don't support debugging unit tests in VSC with coverage turned on, for the same reason you have outlined.
