### ISSUE TITLE
ptvsd hangs on subprocess.Process.join

### ISSUE THREAD

**Issue by sjdv1982** [Microsoft/ptvsd#1036]
## Environment data

- PTVSD version: /extensions/ms-python.python-2018.10.1
- OS and version: Ubuntu 18.04.1
- Python version (& distribution if applicable, e.g. Anaconda): 
Python 3.6.6, Anaconda 2.7.13, Python 2.7.16
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Subprocess code gets never executed
Subprocess remains alive after 5 seconds
On Python2, the debugged main process never terminates either

## Expected  behavior

Subprocess code to be executed and to terminate immediately
This happens for all three Python versions if the entire code is executed directly

## Steps to reproduce:
```python
from multiprocessing import Process

def run():
    print("RUN")

p = Process(target=run)
p.start()
print("JOIN")
p.join(5.0)  # wait for 5 secs to let the process finish
print(p.is_alive())  # should be False
```

**Comment by int19h** [comment]
If you do this:
```py
from multiprocessing import Process

def run():
    print("RUN")

if __name__ == "__main__":
  multiprocessing.set_start_method('spawn')  # note this line
  p = Process(target=run)
  p.start()
  print("JOIN")
  p.join(5.0)  # wait for 5 secs to let the process finish
  print(p.is_alive())  # should be False
```
Does it work for you on 3.6?

(Note that the `__main__` thing is necessary in any case if your want your code to be portable to Windows.)

**Comment by int19h** [comment]
It disables `fork` altogether. When `multiprocessing` operates in this mode, no data is shared across processes at all, except what you pass as arguments to the function.

We don't support multiprocessing with fork currently - https://github.com/Microsoft/ptvsd/issues/943 tracks this feature, so I'll close this one as a dupe.
