### ISSUE TITLE
Debugging fails in python 2.7 when using print

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1038]
Original issue can be found here https://github.com/Microsoft/vscode-python/issues/3320

**Comment by karthiknadig** [comment]
Confirmed. This looks like a side effect of how we shutdown. Currently there is no way to flush all the messages out before disconnecting. Events should not occur after we disconnect. But currently they do. I am marking this as blocked by the refactor work item. One of the goals with that item is to address the issues with closing the connection.

**Comment by karthiknadig** [comment]
Dupe #1028
