### ISSUE TITLE
Debugger doesn't start process if breakpoints are set

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1040]
Original issue can be found here https://github.com/Microsoft/vscode-python/issues/3061

**Comment by karthiknadig** [comment]
@int19h is this a `spawn` vs `fork` issue?

**Comment by int19h** [comment]
It could be, need to look at the code of the library being used.

**Comment by mike-pt** [comment]
@int19h  any clues on this one? Its stopping us from using vscode entirely :( 

Let me know if there's any more details I can provide that would help track this

**Comment by karthiknadig** [comment]
@mike-pt if you are using `multiprocessing` library try setting the `multiprocessing.set_start_method('spawn')` before using it. Also enable `"subProcess": true` in launch.json. See if that helps.

Currently the debugger does not support `fork`, #943 should address that.

**Comment by karthiknadig** [comment]
Also the `NoneType` issue that you encountered is known bug. We are trying to investigate it here: #987

**Comment by mike-pt** [comment]
Hun this code is actually using pathos so I don't think I can even do this without changing that ...

I'll try It later on a different project with pyton multiprocessing  and see how that goes.

**Comment by mike-pt** [comment]
Yeah a few more searching lead me to that... I had no idea, but I guess this means until #943  is fixed I have no luck in this one... 

thanks for the hints for python3 though

**Comment by karthiknadig** [comment]
#943 to track support for fork
