### ISSUE TITLE
Auto-complete does not work for global variables

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#1051]
Microsoft/vscode-python#3427

```python
global_var = None

def main():
  local_var = None
  print('break here')

if __name__ == "__main__":
  main()
```

If you try to auto-complete at the `print()` call you can complete on `local_var` but not on `main` or `global_var`.

**Comment by karthiknadig** [comment]
Does not repro in latest release or master:
![image](https://user-images.githubusercontent.com/3840081/52232008-3577c280-2870-11e9-9ae2-9969b6c3ecfd.png)

![image](https://user-images.githubusercontent.com/3840081/52232030-44f70b80-2870-11e9-99b1-458beb82c9f0.png)
