### ISSUE TITLE
pydev debugger: warning: trying to add breakpoint to file that does not exist:

### ISSUE THREAD

**Issue by yaohengzhi** [Microsoft/ptvsd#1059]
ptvsd in linux: 4.2.0
vscode: 1.29.1
Python version (& distribution if applicable, e.g. Anaconda): Anaconda
python extend:  2018.11.0 (29 Nov 2018)

I'm trying to attach a linux server by ptvsd from windows.

Script in the code:
import ptvsd
ptvsd.enable_attach()
print("waiting for remote debug to attach!")
ptvsd.wait_for_attach()

Related settings in workspace setting:
```
"launch": {
		"configurations": [
			{
				"name": "Python: Attach",
				"type": "python",
				"request": "attach",
				"host": "10.160.210.171",
				"port": 5678,
				"pathMappings": [
					{
						"remoteRoot": "/home/yao/task_detection/yao_tf_pipeline/",
						"localRoot": "W:\\yao\\task_detection\\yao_tf_pipeline\\", 
					}
				]
			}
		],
		"compounds": []
	}
```
I got: pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/yao/task_detection/yao_tf_pipeline\yao_legacy_train.py (will have no effect)
the path is correct, but the last "**\\**" should be "/".

I tried many combination of "/" and "\\" in the "Root" settings. but none of them work.
what should i to to use the attach again?

**Comment by yaohengzhi** [comment]
Solved... I modified the pydevd_file_utils.py in the server:

```
def _NormPaths(filename):
    try:
        return NORM_PATHS_CONTAINER[filename]
    except KeyError:
        if filename.__class__ != str:
            raise AssertionError('Paths passed to _NormPaths must be str. Found: %s (%s)' % (filename, type(filename)))
        abs_path = _NormPath(filename, os.path.abspath)
        real_path = _NormPath(filename, rPath)
        real_path = real_path.replace("\\","/") # yao's modification

        # cache it for fast access later
        NORM_PATHS_CONTAINER[filename] = abs_path, real_path
        return abs_path, real_path
```

**Comment by DonJayamanne** [comment]
Reopening so it gets fixed in the repo

**Comment by karthiknadig** [comment]
Not seeing this issue in master.
