### ISSUE TITLE
Stepping over fails in debugger with message Unable to open '&lt;string&gt;' FIle not found

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1071]
@malmaud commented on [Wed Nov 21 2018](https://github.com/Microsoft/vscode-python/issues/3426)

Getting this error when debugging this file:

```python
import typing
from dataclasses import dataclass, field


@dataclass
class Thing:
    a: typing.Any
    b: typing.Any
    c: typing.Any = field(init=False, repr=False)

    def __post_init__(self):
        self.c = self.a + self.b


Thing(a=1, b=2)
```

If I set a breakpoint at the `self.c = ` line and then click 'step over', I see 

```
Unable to open '&lt;string&gt;': File not found (file:///Users/malmaud/Dropbox (MIT)/Desktop/fun/&lt;string&gt;).
```

I guess this is related to https://github.com/Microsoft/vscode-python/issues/3063.

VSCode 1.29.1
Python 3.6.7 with `dataclasses` package  installed via ` pip install dataclasses`
Extension 2018.10.1

Screenshot:
<img width="1552" alt="screen shot 2018-11-21 at 11 45 30 am" src="https://user-images.githubusercontent.com/987837/48859330-6a9d6a00-ed83-11e8-8a36-33d0f662c494.png">

---

@DonJayamanne commented on [Wed Nov 21 2018](https://github.com/Microsoft/vscode-python/issues/3426#issuecomment-440897012)

What's the name of the file you are debugging

---

@malmaud commented on [Wed Nov 21 2018](https://github.com/Microsoft/vscode-python/issues/3426#issuecomment-440897509)

`/Users/malmaud/Dropbox (MIT)/Desktop/fun/debug.py`

**Comment by qqgg231** [comment]
I have similar message box:

<img width="960" alt="2018-12-16 1" src="https://user-images.githubusercontent.com/11590960/50058248-e2d63000-0175-11e9-8461-3ccc94f71caf.png">


i made some investigation:


![python debugger bug](https://user-images.githubusercontent.com/11590960/50058516-c805ba80-0179-11e9-8543-2afd2532329c.gif)

**Comment by joseortiz3** [comment]
Nobody has mentioned that `Step Into` also fails, however it fails silently without any error.

**Comment by karthiknadig** [comment]
This is fixed. In cases such as `dataclass`, step-over should work. For step-in/out cases we currently show a temp file with message saying that we couldn't retrieve sources. IDE should not show `File Not Found` for those cases.
