### ISSUE TITLE
Test runs on windows running with Tox are timing out

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#1089]
## Environment data

- PTVSD version: master
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): any
- Using VS Code or Visual Studio: Azure pipelines test runs

## Steps to reproduce:
1. Queue automated test run on azure

**Comment by karthiknadig** [comment]
Does not repro locally. But repros on azure

**Comment by karthiknadig** [comment]
Assigned to @int19h since he is already fixing this issue

**Comment by int19h** [comment]
I created a separate issue for the one remaining test, since it's very specific and narrow (Windows, Python 3.5): #1124

All other tests are passing on Windows now.
