### ISSUE TITLE
Launch module from VSC broken in master

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#1108]
## Environment data

- PTVSD version: master
- OS and version: any
- Python version (& distribution if applicable, e.g. Anaconda): any
- Using VS Code or Visual Studio: any

launching modules as specified in this issue is broken. https://github.com/Microsoft/ptvsd/issues/1010#issuecomment-444992883

**Comment by int19h** [comment]
It wasn't properly adding '' (i.e. current directory) to `sys.path`, like Python's own `-c` and `-m` do. This wasn't visible in our test runs, since they do not import from current directory, but instead explicitly add the test module directory to path.
