### ISSUE TITLE
Debug keyboard shortcuts F9, F10, F11 not working

### ISSUE THREAD

**Issue by navmed** [Microsoft/ptvsd#1112]
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

I created an empty folder, and added this file to it: https://gist.github.com/methane/1432916

I hit F9 on my keyboard and it does not set a breakpoint. I confirmed that it's the right shortcut key set for setting a breakpoint. 

https://dl.dropboxusercontent.com/s/ov9vz2z70iafuyr/shot_190121_163542.png

The breakpoint however can be set using the Debug Menu -> Toggle breakpoint.

I should add that my function keys work fine - I'm not using a keyboard that maps the function keys to brightness, volume or something like that.

Update: Looks like F10, F11 don't work either.

**Comment by karthiknadig** [comment]
This looks like an extension issue, `ptvsd` does not come into picture until debugging has been started.
@navmed Can you provide the python extension version? I have version `2018.12.1` and i am not able to repro this on that version.

@DonJayamanne I see that F10/F11 does not start debugging. Should F10/F11 start debugging if **not** already started?

**Comment by DonJayamanne** [comment]
Depends on what those keys are mapped to.
Will create an issue to track this in our repo.

**Comment by fabioz** [comment]
@navmed the most common issue for this is that you have some other program installed which is grabbing those keybindings before it ever arrives in the editor.

This is actually very common in Linux (where some desktop environments grab those by default). For Windows the usual culprit is some program installed (I've seen some graphics drivers grab keybindings as well as some media players -- besides faulty keyboards where keys don't really work), so, it'd be nice if you can double-check if those keybindings actually work on some other program and that you don't have some program which is preventing the keys from getting to VSCode (I know you said that function keys work fine, so, sorry if you already did this check, just wanted to double-check it's not something specific to your system).

**Comment by navmed** [comment]
@fabioz You're right, it was CloudShot hogging the keys. I should have checked this first. Thanks everyone for your help and my apologies for the unrelated issue.

**Comment by fabioz** [comment]
Great that you found the culprit ;)

-- closing issue
