### ISSUE TITLE
Python dicts in debug toolbar: hashes after keys look ugly

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ptvsd#1114]
@abetkin commented on [Tue Jan 22 2019](https://github.com/Microsoft/vscode-python/issues/4073)

![vscode](https://user-images.githubusercontent.com/2223279/51541030-e0e44880-1e68-11e9-90b6-c7f2da4af596.png)

Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.19.15-300.fc29.x86_64

Python extension version: 2018.12.1

## Expected behaviour
dict is shown as `{'path': '/create'}`

## Actual behaviour

dict is shown as `{'path' (139743920924800): '/create'}`

**Comment by karthiknadig** [comment]
same as #45
