### ISSUE TITLE
Path mappings not working when attaching to code running in docker container

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1115]
## Environment data

- PTVSD version: Master
- OS and version: Windows 10 (Client) + Linux Docker (Host)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: VSC

* Code running in docker = django + ptvsd 4.2.0
* Start docker container (with `enable_attach`)
* Attach debugger with path mappings of `"c:\\.... -> src/`
    * In this instance VSC will pass lowercase drive letter (as that's what's been hardcoded)
    * Add a breakpoint, and VSC will send file names with lower case drive letter.
    * All good so far, no warnings nor errors send back by PTVSD.
	* Run the code and a break point is hit
	* Unfortunately a new window is opened in VSC.
	* Path mappings in PTVSD are not working correctly
	* The stack trace returned contains the remote source file names and we're getting responses back with `source references`. 
	* I.e. even though path mappings have been added, PTVSD is returning source references.

**Comment by DonJayamanne** [comment]
Give me a few minutes

**Comment by karthiknadig** [comment]
This seems to work fine. Use the following launch.json:
```js
        {
            "name": "Python: Attach",
            "type": "python",
            "request": "attach",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/src"
                }
            ],
            "port": 3000,
            "host": "localhost"
        }
```
