### ISSUE TITLE
Cython speedup extension is not found

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#112]
This is on Python 3.6 32-bit - the following message is printed when debugging starts:
```
warning: Debugger speedups using cython not found. Run '"C:\Python\3.6-32\python.exe" "C:\Python\3.6-32\lib\site-packages\ptvsd\pydevd\setup_cython.py" build_ext
--inplace' to build.
```
This is despite `.pyd` files being in their usual locations. Probably this is happening because Cython stuff is loaded dynamically, and by the time pydevd tries to load it, we've already removed the `sys.path` entry.

**Comment by DonJayamanne** [comment]
@int19h @zooba 
Currently we're bundling PTVSD with VSC, and when we start the debugger we're getting these messages.
Is there anything we need to do in VSC to get the cython optimizations?

**Comment by int19h** [comment]
Which Python version is that? IIRC the binaries are 3.x-only.
