### ISSUE TITLE
Call stack  in Debug panel only shows 20 frames.

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1138]
@ruoyu0088 commented on [Fri Jan 11 2019](https://github.com/Microsoft/vscode-python/issues/3961)

## Environment data

- VS Code version: 1.30.2
- Extension version : 2018.12.1

## Expected behaviour

I want the full call stack, but it only shows the recent 20 frames.

![image](https://user-images.githubusercontent.com/826871/51034107-e760fd80-15e8-11e9-8ebc-0660ebf9bc7d.png)

**Comment by karthiknadig** [comment]
This limit is coming from VSC, This is the request we get from VSC:
```json
{
    "command": "stackTrace",
    "arguments": {
        "threadId": 1,
        "startFrame": 0,
        "levels": 20
    },
    "type": "request",
    "seq": 9
}
```
Set levels to `0` to get full stack frames.

/cc @DonJayamanne
