### ISSUE TITLE
Unable to run tests from terminal on a Mac

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1166]
## Environment data

- PTVSD version: Master Branch
- OS and version: OSX
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.6 64bit
- Using VS Code or Visual Studio: N/A

## Actual behavior

* Type `pytest ./tests` in terminal and it fails with the following error:
```bash
ImportError while loading conftest '/Users/donjayamanne/Desktop/Development/vscode/ptvsd/tests/conftest.py'.
tests/conftest.py:14: in <module>
    from . import helpers
tests/helpers/__init__.py:93: in <module>
    from .printer import print
tests/helpers/printer.py:10: in <module>
    from ptvsd.compat import queue
E   ImportError: bad magic number in 'ptvsd': b'\x03\xf3\r\n'```

**Comment by fabioz** [comment]
@DonJayamanne this usually means some `.pyc` is corrupted... try removing your `.pyc` files and try it again.

**Comment by DonJayamanne** [comment]
Thanks
