### ISSUE TITLE
ptvsd\socket.py", line 203  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by osowp** [Microsoft/ptvsd#1180]
## Environment data

- PTVSD version: 4.2
- OS and version: Windows 10 Enterprise  / Windows 10 IoTCoreDefaultApp 3.4.1.0
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.1
- Using VS Code or Visual Studio: Visual Studio 2017 15.9.7
- Target Raspberry Pi 3 B+

## Source code
```py
#!python3
# Add your code here to run in your startup tasks
myStr = "Hello World"
print(myStr)
```

## Actual behavior
From Visual Studio - Debug - Start Debugging
```
Sun Feb 24 19:06:04 2019: Finished Py_Initialize
'backgroundTaskHost.exe' (Win32): Loaded 'C:\Windows\system32\Windows.Web.dll'. Cannot find or open the PDB file.
'backgroundTaskHost.exe' (Win32): Loaded 'C:\Windows\system32\iertutil.dll'. Cannot find or open the PDB file.
Python debugger is present
Python arguments: Python.exe visualstudio_py_remote_launcher.py 5678 a7280818-bfba-4d56-9d85-0c9e2c7d326f StartupTask.py
Sun Feb 24 19:06:04 2019: Starting Py_Main...
'backgroundTaskHost.exe' (Win32): Loaded 'U:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\PythonHome\DLLs\_socket.pyd'. Cannot find or open the PDB file.
'backgroundTaskHost.exe' (Win32): Loaded 'U:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\PythonHome\DLLs\select.pyd'. Cannot find or open the PDB file.
'backgroundTaskHost.exe' (Win32): Loaded 'U:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\PythonHome\DLLs\_ssl.pyd'. Cannot find or open the PDB file.
'backgroundTaskHost.exe' (Win32): Loaded 'U:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\PythonHome\DLLs\pyexpat.pyd'. Cannot find or open the PDB file.
'backgroundTaskHost.exe' (Win32): Loaded 'U:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\PythonHome\DLLs\_bz2.pyd'. Cannot find or open the PDB file.
'backgroundTaskHost.exe' (Win32): Loaded 'U:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\PythonHome\DLLs\_ctypes.pyd'. Cannot find or open the PDB file.
Traceback (most recent call last):
  File "visualstudio_py_remote_launcher.py", line 27, in <module>
    import ptvsd
  File "C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\ptvsd\__init__.py", line 15, in <module>
    from ptvsd.attach_server import (  # noqa
  File "C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\ptvsd\attach_server.py", line 5, in <module>
    from ptvsd._remote import (
  File "C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\ptvsd\_remote.py", line 14, in <module>
    from ptvsd.pydevd_hooks import install
  File "C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\ptvsd\pydevd_hooks.py", line 13, in <module>
    from ptvsd import multiproc
  File "C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\ptvsd\multiproc.py", line 24, in <module>
    from ptvsd.socket import create_server, create_client
  File "C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\BackgroundApplication1VS.Debug_ARM.1138526\ptvsd\socket.py", line 203
    with ignored_errno(*ignored or ()):
                                 ^
SyntaxError: invalid syntax
Python script completed execution: Failure
```

## Expected  behavior

Debugger starts and "hello world" printed in the output window

## Steps to reproduce:

New instal of Windows IOT on a raspberry Pi 3B+  (modified to boot and installed network driver)
New version of Visual Studio 2017  with support for python and windows 10 IoT
upgraded PTVSD from 4.1 to 4.2 (to fix different error stating ver 4.1 was too old)
created hello world app in Visual studio
Started debugger

app does get installed to the pi
above line does not throw a syntax error on my PC, so I suspect that the PI has a different version of python.  but I am new to PI programming using Visual Studio so I'm just guessing.

**Comment by int19h** [comment]
This is certainly something to do with Python versions. You can check the version that's running on your Pi with something like `print(sys.version_info)` - if it's lower than 2.7 (which I think is the case here), then it's not supported. But also not quite what you want anyway, because your script says that it's meant to be Python 3 in the shebang.

**Comment by osowp** [comment]
> This is certainly something to do with Python versions. You can check the version that's running on your Pi with something like `print(sys.version_info)` - if it's lower than 2.7 (which I think is the case here), then it's not supported. But also not quite what you want anyway, because your script says that it's meant to be Python 3 in the shebang.

but how exactly do you do that on windows 10 IoT.  and more importantly how do I upgrade it if its wrong?  Windows IoT seems like MS typical do it my way but hide/bury the documentation

**Comment by int19h** [comment]
Try running your script on the device with Ctrl+F5 (i.e. without debugging) and see if you get the output that it produces with `print(sys.version_info)` back.

**Comment by osowp** [comment]
The problem with running without the debugger is that you can't see the output on Win 10 IoT.

But I guess it doesn't matter.   during my troubleshooting today I came across this thread:
https://github.com/Microsoft/PTVS/issues/2872

Which states "Pyton IoT support in VS has been removed in dev16."
if it's being discontinued there is no point in me starting a new python project targeting IoT
