### ISSUE TITLE
Verify django and jinja2 exceptions context

### ISSUE THREAD

**Issue by fabioz** [Microsoft/ptvsd#1181]
See: https://github.com/Microsoft/ptvsd/pull/1179/files/90dc0b17a0bceadbc0dad958be04ad5f2fa81404#diff-a3b5595e743c389ebd7b61a7ab4c3c80R131

**Comment by karthiknadig** [comment]
I am not getting a suspend event for exception break in the following cases.

Use this branch, I have the django and flask tests updated there.
https://github.com/karthiknadig/ptvsd/tree/issue694
For Django run this test:
```
./tests/func/test_django.py::test_django_template_exception_no_multiproc[launch]
```

For Flask run this test [fails on 2.7 only]:
```
./tests/func/test_flask.py::test_flask_template_exception_no_multiproc[launch]
```

**Comment by fabioz** [comment]
Will take a look at it.

**Comment by fabioz** [comment]
Just to note, the problem happens when just-my-code is turned on along with django exceptions (still working on a fix).
