### ISSUE TITLE
Implement PEP 553 to support `debugger()` breakpoints

### ISSUE THREAD

**Issue by belgiancoder** [Microsoft/ptvsd#1194]
VSCode should implement PEP 553 to support `debugger()` statements.

This will enable developers to share buggy code across platforms (platform independent and debugger independent).

>Python 3.7 includes the new built-in breakpoint() function as an easy and consistent way to enter the Python debugger.  
Built-in breakpoint() calls sys.breakpointhook(). By default, the latter imports pdb and then calls pdb.set_trace(), but by binding sys.breakpointhook() to the function of your choosing, breakpoint() can enter any debugger. Additionally, the environment variable PYTHONBREAKPOINT can be set to the callable of your debugger of choice. Set PYTHONBREAKPOINT=0 to completely disable built-in breakpoint().

The way this could be implemented is by setting the `PYTHONBREAKPOINT` to the VSCode debugger.

**Comment by fabioz** [comment]
Hi @belgiancoder, this should be working, although it's `breakpoint()` and not `debugger()` (so, closing this ticket... If `breakpoint()` is not working for you, please let me know).
