### ISSUE TITLE
Re-attach tests fail on Mac Py2.7

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#1195]
## Environment data

- PTVSD version: master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Using VS Code or Visual Studio: Automated Test run

## Actual behavior

Following tests fail:
tests/func/test_attach.py::test_reattach[file-attach_socket_cmdline]
tests/func/test_attach.py::test_reattach[module-attach_socket_import]

## Expected  behavior

Should not fail.

**Comment by karthiknadig** [comment]
I am not seeing this failure on azure anymore. Looks like this might be fixed?

**Comment by int19h** [comment]
You're right. I had an older enlistment on Mac that had this, but syncing to master either fixed it, or made it  much less likely to repro. It didn't come up in an overnight run-in-a-loop (although there were other spurious failures).
