### ISSUE TITLE
Background python parser crashes importing sklearn.cluster in VS2017

### ISSUE THREAD

**Issue by jaybo** [Microsoft/ptvsd#1197]
## Environment data

- PTVSD version: 4.2.0 and 4.2.4
- OS and version: Windows 10, 1607, 14393.2670
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.6.8
- Using VS Code or Visual Studio: VS2017, 15.9.7

## Actual behavior

Background code parser crashes importing sklearn.cluster.  

## Expected  behavior

The background code parser should never crash.  On PTVSD 4.2.0 If I dismiss the crash dialog, it will reappear after about one minute, presumably when the background parser is auto-restarted.

## Steps to reproduce:
1. `pip install scikit-learn`

2. Load a python script which can be as simple as:

```
from sklearn.cluster import KMeans
```
3. Wait a moment, then:
![image](https://user-images.githubusercontent.com/1607323/53778229-dc23a300-3eb0-11e9-9457-64b81eafe5ce.png)

4. The program will run successfully.

**Comment by int19h** [comment]
Could you clarify the steps to reproduce - is there another step there to launch it somehow, e.g. F5? Or by "load", do you mean just opening it in the editor and then waiting?

**Comment by jaybo** [comment]
Just opening it in the editor and then waiting a moment will trigger the problem.

**Comment by int19h** [comment]
Issue moved to [Microsoft/python-language-server #713](https://github.com/Microsoft/python-language-server/issues/713) via [**ZenHub**](https://www.zenhub.com/)
