### ISSUE TITLE
debugger behaves differently with and without breakpoint 

### ISSUE THREAD

**Issue by tonyxwz** [Microsoft/ptvsd#1198]
## Environment data

- PTVSD version: "version": "4.2.4"
- OS and version: Windows 10 64 bit enterprise
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7, conda 
- Using VS Code or Visual Studio: vscode

## Actual behavior

With a break point, the debugger throw out GeneratorExit exception when click continue. Without the break point, code runs normally. I tested in PyCharm which uses pydev as the debugger but no similar issue. The code is some massive numpy array operation, however, exception happens at the **first** iteration. My project is not related to Generator. 

```text
Exception has occurred: GeneratorExit
exception: no description
  File "D:\HIFU.py\pyHIFU\ray.py", line 375, in get_area_at
    area = np.linalg.norm(np.cross(p1 - p0, p2 - p0)) / 2
  File "D:\HIFU.py\pyHIFU\ray.py", line 382, in get_intensity_at
    A1 = self.get_area_at(d)
  File "D:\HIFU.py\pyHIFU\box\box.py", line 57, in update_lattice
    I[x, y, z] += tr.get_intensity_at(t)
  File "D:\HIFU.py\pyHIFU\box\box.py", line 46, in <lambda>
    update_func = lambda x, y, z: self.update_lattice(x, y, z, tr, I, ph, counter)
  File "D:\HIFU.py\pyHIFU\box\box.py", line 120, in traversal_along
    func(X,Y,Z)
  File "D:\HIFU.py\pyHIFU\box\box.py", line 47, in intersect_trident
    self.traversal_along(tr.pow_ray, func=update_func)
  File "D:\HIFU.py\pyHIFU\HIFU\HIFU.py", line 136, in run_te_wrapper
    box.intersect_trident(tr, I, ph, counter)
  File "D:\HIFU.py\pyHIFU\HIFU\HIFU.py", line 92, in run
    False  # whether running in pararllel
  File "D:\HIFU.py\case1.py", line 57, in run_hifu
    n_core=n_core)
  File "D:\HIFU.py\case1.py", line 78, in <module>
    run_hifu(config_path, pyd_path, verbose=False, n_core=n_core)
```

Function at the second last line of which Exception is thrown, calculating the area formed by three points
(`np.ndarray` shape=(3,)). Data from the variable browser of vscode:

p0: array([ 0.14431354,  0.00692588, -0.00280266])
p1: array([ 0.14439976,  0.0062278 , -0.00283418])
p3: array([ 0.14418676,  0.00694253, -0.00351847])

```python
    def get_area_at(self, distance: float):
        """
        https://proofwiki.org/wiki/Norm_of_Vector_Cross_Product
        """
        p0 = distance * self.pow_ray.unit_vector + self.pow_ray.p
        # new Plane instance too slow

        plane = Plane(p0, self.pow_ray.d)
        p1 = plane.intersect_line(self.aux_ray1)
        p2 = plane.intersect_line(self.aux_ray2)

        area = np.linalg.norm(np.cross(p1 - p0, p2 - p0)) / 2
        return area
```

## Expected  behavior

Stop at the break point and continue normally.

## Steps to reproduce:

It cannot be reproduced with only one piece of code. But if you could analyze which part of the code you would like me to check I can do that when it's convenient.

**Comment by fabioz** [comment]
Hi @tonyxwz, I can't really reproduce the error with the info provided... 

My guess is that your generator is being consumed when you're inspecting something, but from the provided code I can't really discover what's making it be consumed... do you think you can provide some standalone code where this can be reproduced?

**Comment by karthiknadig** [comment]
@fabioz It could be `SafeRepr` that might be consuming this. /cc @int19h

**Comment by int19h** [comment]
It does a bunch of `len` checks to detect collections that are too long to repr, which would indeed force the generator. But it also has this check before it does any of that:
```py
            # Iterable is its own iterator - this is a one-off iterable
            # like generator or enumerate(). We can't really count that,
            # but repr() for these should not include any elements anyway,
            # so we can treat it the same as non-iterables.
            if obj is iter(obj):
                return False
```
so it shouldn't be trying to do that on generators.

**Comment by karthiknadig** [comment]
Please reopen when more details are available.
