### ISSUE TITLE
VSC Debugger does not work with google drives designated as g: or any drive letter

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1205]
@Manigrid commented on [Wed Mar 06 2019](https://github.com/Microsoft/vscode-python/issues/4658)

Breakpoints on a simple file containing Python 3.7 code:

print('hello')
print('1234') 
print('watete')

Breakpoints were applied to all three lines. 
Error

G:\My Drive\BSc.Classes\Programming1-Spring19\CS151\Code>C:/Anaconda3/Scripts/activate

(base) G:\My Drive\BSc.Classes\Programming1-Spring19\CS151\Code>conda activate base
pydev debugger: warning: trying to add breakpoint to file that does not exist: g:\my drive\code\hello.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: g:\my drive\code\hello.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: g:\my drive\code\hello.py (will have no effect)

hello
123
watete

Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

NOTE: This problem was reported May 2018, and a patch fixed it. Two weeks after (remarkable).
I think an update about 2 or 4 weeks ago, caused this problem.
I did not try with dropbox or other cloud drives. 

## Environment data

- VS Code version: XXX
- Extension version (available under the Extensions sidebar): XXX
- OS and version: XXX
- Python version (& distribution if applicable, e.g. Anaconda): XXX
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX 
- Relevant/affected Python packages and their versions: XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:
1. XXX

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
XXX
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

---

@Manigrid commented on [Wed Mar 06 2019](https://github.com/Microsoft/vscode-python/issues/4658#issuecomment-470222985)

Yes, if the code is on C drive, it works nicely.

**Comment by karthiknadig** [comment]
@Manigrid Can you provide more details on how you have mapped the drive and how you start VSC. Also, provide the launch configuration you are using for this. I am not able to repro this using mapped or un-mapped google drive.

Mapped: 
![image](https://user-images.githubusercontent.com/3840081/54324616-a6bb3b80-45bb-11e9-99cd-a6f0e5358051.png)

Unmapped:
![image](https://user-images.githubusercontent.com/3840081/54324638-baff3880-45bb-11e9-8e81-9ea3a78c482d.png)

Using the default launch config:
```js
        {
            "name": "Terminal",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
```

**Comment by Manigrid** [comment]
The mapping is done by Google Drive Stream. You click on the Google Drive Stream icon in the system tray and you assign the letter. The default letter is G:
local cache directory is in C:\Users\manigrid\AppData\Local\Google\DriveFSC:\Users\myap\AppData\Local\Google\DriveFS
Here is launch.json:
{ // Use IntelliSense to learn about possible attributes. // Hover to view descriptions of existing attributes. // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387 "version": "0.2.0", "configurations": [ { "name": "Python: Current File (Integrated Terminal)", "type": "python", "request": "launch", "program": "${file}", "console": "integratedTerminal" }, { "name": "Python: Remote Attach", "type": "python", "request": "attach", "port": 5678, "host": "localhost", "pathMappings": [ { "localRoot": "${workspaceFolder}", "remoteRoot": "." } ] }, { "name": "Python: Module", "type": "python", "request": "launch", "module": "enter-your-module-name-here", "console": "integratedTerminal" }, { "name": "Python: Django", "type": "python", "request": "launch", "program": "${workspaceFolder}/manage.py", "console": "integratedTerminal", "args": [ "runserver", "--noreload", "--nothreading" ], "django": true }, { "name": "Python: Flask", "type": "python", "request": "launch", "module": "flask", "env": { "FLASK_APP": "app.py" }, "args": [ "run", "--no-debugger", "--no-reload" ], "jinja": true }, { "name": "Python: Current File (External Terminal)", "type": "python", "request": "launch", "program": "${file}", "console": "externalTerminal" } ]}




 

    On Wednesday, March 13, 2019, 6:15:29 PM PDT, Karthik Nadig <notifications@github.com> wrote:  
 
 
@Manigrid Can you provide more details on how you have mapped the drive and how you start VSC. Also, provide the launch configuration you are using for this. I am not able to repro this using mapped or un-mapped google drive.

Mapped:


Unmapped:


Using the default launch config:
        {
            "name": "Terminal",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },

**Comment by fabioz** [comment]
I was actually checking this and installed google drive stream and initially I couldn't replicate... digging a bit further, it seems that the only way I can replicate this is if the setting to disable short path name creation is disabled on windows (i.e.: https://support.microsoft.com/en-us/help/121007/how-to-disable-8-3-file-name-creation-on-ntfs-partitions).

Now given that this is a setting which the user can set as he wants and we can't control, I don't think we can rely on this mode and will have to always use a different method.

Note: I'm going to close this issue in favor of: https://github.com/Microsoft/ptvsd/issues/1330 as it seems to be duplicated (and I'll take these details into account when solving it).
