### ISSUE TITLE
Code navigation not found in remote debugging

### ISSUE THREAD

**Issue by ZackLord** [Microsoft/ptvsd#1211]
It seems like code navigation is out of functionality when ptvsd is used to debug code on a remote machine. Here's my case: I configured launch.json as ready to attach a remote process, and in my current workspace folder was the single script file I wanted to debug. Debugging went nicely as ptvsd itself looks, but how can I navigate to other library files and interface it refers to on the remote machine? 
I know it's easy to access code navigation in local workspace, how or whether is it able to tackle this remotely? If there is a way, please offer instructions.

**Comment by karthiknadig** [comment]
Moving this to Python extension
