### ISSUE TITLE
pydevd support for BREAK_SYSTEMEXIT_ZERO 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1223]

**Comment by karthiknadig** [comment]
1.	All cases below apply to **Launch** scenario only, this is **NOT** supported for attach
2.	If **WAIT_ON_NORMAL_EXIT** is True then:
a.	If the user code is done and there **WERE NO** exceptions then debugger should print 'Press any key to continue . . . ' only in the terminal and wait. See  https://github.com/microsoft/ptvsd/blob/v4.2.10/src/ptvsd/daemon.py#L25
3.	If **WAIT_ON_ABNORMAL_EXIT** is True then:
a.	If the user code is done and these were exceptions then the debugger should print 'Press any key to continue . . . ' only in the terminal and wait.
4.	If **BREAK_SYSTEMEXIT_ZERO** is True then:
a.	This is SystemExit specific. If System exit code is zero then break into debugger.
b.	Note: for Django there are multiple success exit codes. See https://github.com/microsoft/ptvsd/blob/v4.2.10/src/ptvsd/wrapper.py#L1239

/cc @fabioz, @int19h

**Comment by karthiknadig** [comment]
WONE = WaitOnNormalExit
WOAE = WaitOnAbnormalExit
BOSEZ = WaitOnAbnormalExit 


| WONE | WOAE | BOSEZ | Expected Behavior |
|-----|-----|-----|-------------------|
| False | False | False | <ul><li>Don't break on SystemExit exception if exitcode = 0</li><li>Don't break on SystemExit exception if exitcode ≠ 0</li> <li>Don't wait for user input</li></ul> |
| False | False | True | <ul><li>Always break on SystemExit exception</li><li>Don't wait for user input</li></ul> |
| False | True | False | <ul><li>Don't break on SystemExit exception if exitcode = 0</li><li>Break on SystemExit exception if exitcode ≠ 0</li><li>Wait for user input if exitcode ≠ 0</li></ul> |
| False | True | True | <ul><li>Always break on SystemExit exception</li><li>Wait for user input if exitcode ≠ 0</li></ul> |
| True | False | False | <ul><li>Don't break on SystemExit exception if exitcode = 0</li> <li>Break on SystemExit exception if exitcode ≠ 0</li><li>Wait for user input if exitcode = 0</li></ul> |
| True | False | True | <ul><li>Always break on SystemExit exception</li> <li>Wait for user input if exitcode = 0</li></ul> |
| True | True | False | <ul><li>Don't break on SystemExit exception if exitcode = 0</li><li>Break on SystemExit exception if exitcode ≠ 0</li><li>Always wait for user input</li></ul> |
| True | True | True | <ul><li>Always break on SystemExit exception</li><li>Always wait for user input</li></ul> |

* On break the debugger should send a `stopped` event to ide with reason `exception`, and the SystemExit or relevant exception details.
* Waiting for user should print the line `Press any key to continue . . .` in terminal only. See https://github.com/microsoft/ptvsd/blob/v4.2.10/src/ptvsd/daemon.py#L25

**Comment by int19h** [comment]
We discussed this, and concluded that wait for normal/abnormal exit feature - i.e printing out "Press any key to continue ..." - is best done on the adapter side. The reasons were discussed [here](https://github.com/microsoft/ptvsd/issues/1399#issuecomment-488793937) previously.

Thus, pydevd only needs to support the `SystemExit` part, since that one requires being in-proc to see the exception at the point where it's raised, and being able to inspect the associated value before it gets stringified.
