### ISSUE TITLE
Solaris sock.setsockopt TCP_KEEPIDLE OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by LambiekNL** [microsoft/ptvsd#1237]
Previously I used ptvsd 3 with joy and success on Linux (vscode) and Solaris 11.3 hosting my Application. When time advanced it seems that vscode is not compatible anymore with ptvsd 3 so I upgraded to 4.2.4. In the mean time I also upgraded Solaris to version 11.4. This version let the debugger not connect and it fails apparently on line 173 in `ptvsd/socket.py`.

This is reproducable using the following code using Python on Solaris 11.4:

```
>>> import socket
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
>>> sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
>>> sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```

As workaround to get the debugger connecting again I changed line 128 in `ptvsd/socket.py` from `IDLE = 1` to `IDLE = 0`

**Comment by gramster** [comment]
Fixed in the new adaptor.
