### ISSUE TITLE
[Feature request] Step back/IntelliTrace-like debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1238]
@lstolcman commented on [Thu Mar 14 2019](https://github.com/Microsoft/vscode-python/issues/4754)

## Environment data

- VS Code version: 1.31.1
- Extension version (available under the Extensions sidebar): 2019.2.5558
- OS and version: Macos high sierra 1.13.6 
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv 
- Relevant/affected Python packages and their versions: all/not relevant

## Expected behaviour

Ability to step back in code when debugging

## Actual behaviour

Not possible to do step back

## Steps to reproduce:
1. create a breakpoint
2. run an app in debug mode
3. should have an option to step back to previous ran line

## Logs
none

It is working well in regular Visual studio and PyCharm. Will be very useful feature to have in VS Code

https://docs.microsoft.com/en-us/visualstudio/debugger/historical-debugging?view=vs-2017

**Comment by karthiknadig** [comment]
#1017
