### ISSUE TITLE
Error in subprocess debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1242]
## Environment data

- PTVSD version: Latest release
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio:VSC

## Actual behavior

Error during sub process debugging
<img width="1183" alt="Screen Shot 2019-03-15 at 11 49 25 AM" src="https://user-images.githubusercontent.com/1948812/54455194-6e7d3f80-4718-11e9-8bf3-2724cd1f91b6.png">

## Expected  behavior

No errors

## Steps to reproduce:
* Debug the following python code with sub process debugging:
```python
import subprocess

p = subprocess.Popen(['python3', '-c', 'import time; time.sleep(10000)'])
print(p.pid)
p = subprocess.Popen(['python3', '-c', 'import time; time.sleep(10000)'])
print(p.pid)
p = subprocess.Popen(['python3', '-c', 'import time; time.sleep(10000)'])
print(p.pid)
p.wait()
```
* As soon as you start, it throws an error
* Here's the `launch.json`:
```js
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
			"subProcess": true
        },
```

**Comment by karthiknadig** [comment]
Does not repro with master (tested on Linux/Windows/Mac). Please reopen, if seen again.
