### ISSUE TITLE
Empty line not rendered in debug console (Python)

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1249]
@aamartinoli commented on [Tue Mar 19 2019](https://github.com/Microsoft/vscode-python/issues/4821)

Issue Type: <b>Bug</b>

VSCode with Python 3.7 (x64). 
Load and run this piece of python code in VSCode:

# start of python code
print(1)
print()
print(2)
print()
print(3)
# end of python code

Original code: [test_py.zip](https://github.com/Microsoft/vscode-python/files/2982914/test_py.zip)

Execution in terminal results in five lines: first line display value 1, second line is empty (\n), third row display 2, fourth line is empty (\n), fifth line display value 3.
If you look at debug console you se only three lines with the 1,2,3 values. No empty lines (\n) between lines.

Output in terminal:
1
-empty line-
2
-empty line-
3

Output in debug console:
1
2
3

![VSCODE-Console](https://user-images.githubusercontent.com/20819083/54600584-68030680-4a3d-11e9-83e5-93f626a7b7cd.JPG)
![VSCODE-Integrated-Terminal](https://user-images.githubusercontent.com/20819083/54600596-6d605100-4a3d-11e9-919c-4e4fdcd2a987.JPG)

Extension version: 2019.2.5558
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|47.41GB (36.74GB free)|
|Process Argv|D:\Andrea\Desktop\test.py D:\Andrea\Desktop"|
|Screen Reader|no|
|VM|57%|

</details>

**Comment by karthiknadig** [comment]
This is fixed in the insiders VSCode:
![image](https://user-images.githubusercontent.com/3840081/56939215-031ae180-6abc-11e9-96a5-34049dbee5e3.png)
