### ISSUE TITLE
Django apps don't work without --nothreading option

### ISSUE THREAD

**Issue by qubitron** [Microsoft/ptvsd#1256]
Look into this

**Comment by karthiknadig** [comment]
Verified that this now works:
![image](https://user-images.githubusercontent.com/3840081/55179551-f1ed5680-5144-11e9-8df7-27fa32c71dbc.png)

**Comment by qubitron** [comment]
@karthiknadig looks like this might still be an issue for some: https://github.com/Microsoft/vscode-python/issues/4988, or perhaps this is a new issue

**Comment by karthiknadig** [comment]
Interesting, I tried "--nothreding" with a significantly large "django-oscar" based eCommerce website. I seems to work fine. I think we may be missing detail in some way. I am not able to repro the nothreading issue on my end. 

I do see that the user has template issues. We did some work recently on improving template exceptions. But that is a separate issue.
