### ISSUE TITLE
Failed to debug in Docker

### ISSUE THREAD

**Issue by gramster** [Microsoft/ptvsd#1264]
@xiaofeng0123 commented on [Tue Mar 26 2019](https://github.com/Microsoft/python-language-server/issues/824)

Visual Studio Code - Insiders: 1.33.0-insider
python-insider: 2019.4.6071-alpha
python version: Python 3.7.3 64bit
Make sure docker installed
Repro steps:
1.Git clone https://github.com/qubitron/pydemo
2.Open Anaconda Prompt window
3.Cd pydemo
4.Run py -3 setup.py
5.Open "stackoverflow-flask" folder and open "app->main.py"
6.Set a breakpoint in line 6
7.Switch to "dockerized" branch
![image](https://user-images.githubusercontent.com/41426540/54988470-77f88880-4ff1-11e9-849e-08cf1ce56525.png)
8.Change "DEBUG" configuration to "Python: Run in Docker"
![image](https://user-images.githubusercontent.com/41426540/54988487-83e44a80-4ff1-11e9-9652-50ec06484366.png)
9.Start to debug
Expect Result:
Debug in Docker successfully
Actual Result:
Invalid link shown
![image](https://user-images.githubusercontent.com/41426540/54988642-d887c580-4ff1-11e9-8b33-711bce70e001.png)

---

@MikhailArkhipov commented on [Tue Mar 26 2019](https://github.com/Microsoft/python-language-server/issues/824#issuecomment-476649402)

LS does not have any debugger related functionality. This should go either to https://github.com/Microsoft/vscode-python or https://github.com/Microsoft/ptvsd

**Comment by qubitron** [comment]
This is by design, while confusing it’s printing out the literal output of the app running inside of the container, which is bound to 0.0.0.0.
