### ISSUE TITLE
locals behaviour different between debug and start without debugging - Windows

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1265]
@derirreIre commented on [Tue Mar 26 2019](https://github.com/Microsoft/vscode-python/issues/4918)

Similar to another issue, but this time on windows
https://github.com/Microsoft/vscode-python/issues/581 - locals behaviour different between debug and start without debugging

The solution to take the latest development build worked on linux, however it seems not to be solved on windows.

The issue doesnt show up with other IDE's or when using PDB from the command line.

## Environment data

- VS Code version: 1.32.3
- Extension version (available under the Extensions sidebar): XXX
- OS and version: Windows 7 - Service Pack 1
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Issues shows up with venv, and the native Python 3.6 installation
- Relevant/affected Python packages and their versions: Standard python 3.6.4 on windows 7.

- MS Python extension for VSCode:
Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
Version: 2019.3.5807-dev
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

## Expected behaviour

that with or without the vscode debugger the behavour is the same

## Actual behaviour

When running with the vscode debugger local() returns recursive references to itself

## Steps to reproduce:
1.  run the following code
~~~~
class myTestClass(object):
    def __init__(self, a):
        args = locals()
        self.a = a
    
        print(args)

    
if __name__ == "__main__": 
    my_class = myTestClass('letter_a')
~~~~

Without the debugger produces:
{'a': 'letter_a', 'self': <__main__.myTestClass object at 0x0024B490>}

With the debugger (insert a break point on line 6):
{'a': 'letter_a', 'self': <__main__.myTestClass object at 0x034B6610>, 'args': {...}}

**Comment by int19h** [comment]
`locals()` can return different things depending on when it's called, exactly, and most of that is not guaranteed by API docs. In this particular example, you can repro the behavior without any debugger at all just by adding a single call to it:
```py
class myTestClass(object):
    def __init__(self, a):
        args = locals()
        locals()
        self.a = a
    
        print(args)
    
if __name__ == "__main__": 
    my_class = myTestClass('letter_a')
```

That the docs say that `locals()` "*update* and return a dictionary representing the current local symbol table".  Thus, calling it again may affect the dict from the previous call. 

Since debugger may need to enumerate local variables at times, there's not much we can do here. The code should make a copy of `locals()` if it needs a static snapshot.

**Comment by karthiknadig** [comment]
@derirreIre Please reopen this if it does not address your question.

**Comment by derirreIre** [comment]
Hi guys, thanks for the quick feedback.


replacing 
~~~~~
args = locals()
~~~~~
by
~~~~~
args = locals().copy()
~~~~~
fixes the issue.


For the record, my usecase was something like this:
~~~~
def check_args(arguments):
    for k, v in iter(arguments.items()):
        if k != "self" and k != 'a':
            if not v is None:
                assert 1 == 0

class myTestClass(object):
    def __init__(self, a):
        args = locals() # replace me with: args = locals().copy()
        self.a = a
    
        check_args(args)
    
if __name__ == "__main__": 
    my_class = myTestClass('letter_a')
~~~~~
The assert is only triggered when a breakpoint is set when running the debugger.
