### ISSUE TITLE
Breakpoints not showing in the editor

### ISSUE THREAD

**Issue by luabud** [Microsoft/ptvsd#1269]
## Environment data

- PTVSD version: 0.2.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1 (global)
- Using VS Code or Visual Studio: VS Code Insiders

## Actual behavior

I added breakpoints by clicking on the margin of the editor and they show up in the Breakpoints window, but not in the editor
![image](https://user-images.githubusercontent.com/45497113/55113933-d7ac6d80-509d-11e9-9525-c3d50c866fa1.png)

## Steps to reproduce:
It happened three times but I don't know how to reproduce it. Twice when I reloaded the window with the interactive window open, but it doesn't happen all the time

**Comment by karthiknadig** [comment]
@luabud Can you enable logs? one way is to set the environment variable 'PTVSD_LOG_DIR' to some directory.

**Comment by karthiknadig** [comment]
Also, were you already debugging or was this before running?

**Comment by luabud** [comment]
Yes, I was already debugging. Now I can reproduce it. Have the debugger to stop on a breakpoint and open the interactive window, and then reload VS Code. 
[ptvsd-19488.log](https://github.com/Microsoft/ptvsd/files/3015502/ptvsd-19488.log)

**Comment by karthiknadig** [comment]
Looks like the debugger is already disconnected (looking at the end of the code).  On reload the debugger is shutdown, and wont be started unless it is launched again. Extension should look into what is going on here.

**Comment by karthiknadig** [comment]
Issue moved to [Microsoft/vscode-python #4975](https://github.com/Microsoft/vscode-python/issues/4975) via [**ZenHub**](https://www.zenhub.com/)
