### ISSUE TITLE
Debugging: Cannot inspect inside variables of section "Watch"

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1273]
@DavidDuranPerez commented on [Thu Mar 28 2019](https://github.com/Microsoft/vscode-python/issues/4984)

## Environment data

- VS Code version: 1.32.3
- Extension version (available under the Extensions sidebar): 2019.3.6139
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv 

## Expected behaviour

I should be able to inspect inside any variable placed in the "Watch" section.

## Actual behaviour

Yesterday, I was able to inspect inside any variable placed in the "Watch" section. However, today, I can only inspect the automatic variables placed under "Locals". See image below:

![image](https://user-images.githubusercontent.com/25606109/55145050-4cd17e80-5142-11e9-907b-f86f1b663240.png)

This happens also to a colleague of mine since today. Is it because an update of the extension?

---

@0000Paula01 commented on [Thu Mar 28 2019](https://github.com/Microsoft/vscode-python/issues/4984#issuecomment-477518285)

I am also getting the same issue

**Comment by karthiknadig** [comment]
@fabioz Looks like we are not providing `variableReference` correctly for evaluations.
what it should return:
`{"result": "[1, 2, 3]", "variablesReference": 6, "type": "list", "presentationHint": {}}`
actual:
`{"result": "[1, 2, 3]", "variablesReference": 0, "type": "list", "presentationHint": {}}`

**Comment by fabioz** [comment]
Will take a look at it.
