### ISSUE TITLE
django breakpoints not hit

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1274]
@Transel commented on [Thu Mar 28 2019](https://github.com/Microsoft/vscode-python/issues/4991)

## Environment data

- VS Code version: 1.32.3
- Extension version (available under the Extensions sidebar):2019.3.6139
- OS and version: Debian 9
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.13
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: django 1.3.5

## Expected behaviour

breakpoints hit in vscode

## Actual behaviour

no breaks

## Steps to reproduce:
1. 
install vscode
install extension
add breakpoints

launch file
{
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "console": "integratedTerminal",
            "args": [
                "runserver",
                "--noreload",
            ],
            "django": true,
            "env":{"DJANGO_SETTINS_MODULE":"transelchina.settings"}
        },

I set the venv in python: Select interpretor

[cant provide the project]

## Logs

sometimes im getting [error32] pipe break
yesterday it worked once
today it worked once

I tried various versions of vscode and python extension

(venv) transel@groupplan:~/transelchina-new/transelchina$ cd /home/transel/transelchina-new/transelchina ; env DJANGO_SETTINS_MODULE=transelchina.settings PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/transel/transelchina-new/transelchina/venv/bin/python /home/transel/.vscode/extensions/ms-python.python-2019.2.5558/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 39109 /home/transel/transelchina-new/transelchina/manage.py runserver --noreload 
Validating models...

0 errors found
Django version 1.3.5, using settings 'transelchina.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[28/Mar/2019 17:25:52] "GET /contact HTTP/1.1" 200 9664
[28/Mar/2019 17:25:52] "GET /contact HTTP/1.1" 200 9664
[28/Mar/2019 17:26:15] "GET /contact HTTP/1.1" 200 9664
[28/Mar/2019 17:26:15] "GET /contact HTTP/1.1" 200 9664

---

@qubitron commented on [Thu Mar 28 2019](https://github.com/Microsoft/vscode-python/issues/4991#issuecomment-477699016)

@Transel can you check if there's additional processes using the same port? We've seen this happen where old processes were running in the background so your web request is going to a process that's not being debugged.

**Comment by int19h** [comment]
Note that there's additional discussion on the original issue (https://github.com/Microsoft/vscode-python/issues/4991).

**Comment by karthiknadig** [comment]
User closed this issue. https://github.com/Microsoft/vscode-python/issues/4991#issuecomment-481232595
