### ISSUE TITLE
When exiting with exception the process return code and the one given by the DAP don't match.

### ISSUE THREAD

**Issue by fabioz** [microsoft/ptvsd#1278]
I think a proper solution would only be available when a separate process is launched (although maybe `ptvsd.__main__` could be changed to at least return a code != 0 in this case).

See references in the code for places to fix (had to do some workarounds in tests due to this).

**Comment by int19h** [comment]
`__main__` reraises the `SystemExit` that it catches, though - is that not sufficient?

**Comment by fabioz** [comment]
This issue isn't really related to SystemExit, it's related to other exceptions (sorry I wasn't clear enough).

The problem is if the user code is something as:

```
raise RuntimeError('Some error')
```

then the process return code will be `!= 0` but the `exitCode` from `ptvsd` will be `== 0`.

If it was an external process it should be straightforward to get the value and return it (and would work even for crashes), but as it stands right now, maybe returning `1` in that case would be a reasonable compromise (that's the return code for me on Python 2.7 and 3.6 on windows).

**Comment by int19h** [comment]
It looks like we also have an issue where the return code is not reported correctly for attached processes in general - i.e. with explicit `ptvsd.enable_attach()` etc, if the process exits with a non-zero code, even explicitly via `sys.exit`, we still report `exitCode: 0`.

**Comment by fabioz** [comment]
@int19h maybe we should wait until `ptvsd` uses `pydevd` out of process to fix this issue (considering this will be done) as that should be much more straightforward in that case...

**Comment by int19h** [comment]
Yep. This is mainly to document the issue for reference purposes in the tests that have to work around this for now.

**Comment by int19h** [comment]
There's a reverse issue there in that some tests are failing because they check the actual exit code of the process (via `DebugSession.expected_returncode`), and expect it to be non-zero, but it's incorrectly reported as zero. This is a test issue, though - we're not retrieving the exit code correctly in `DebugSession`.

**Comment by gramster** [comment]
Fixed for launch in new adaptor; no way to fix for attach.
