### ISSUE TITLE
Unable to expand variables in watch window

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1284]
@DonJayamanne commented on [Sun Mar 31 2019](https://github.com/Microsoft/vscode-python/issues/5035)

* Old version of Debugger (December Release)
	* `sys.argv` can be expanded in `watch` window
* Latest version
	* `sys.argv` cannot be expanded.

**Nothing can be expanded in the `watch window`**

**Old Version (December)**
<img width="624" alt="Screen Shot 2019-03-31 at 3 41 11 PM" src="https://user-images.githubusercontent.com/1948812/55296273-e65f9100-53cb-11e9-966d-bd49321aff15.png">

**New debugger**
<img width="611" alt="Screen Shot 2019-03-31 at 3 41 53 PM" src="https://user-images.githubusercontent.com/1948812/55296274-e65f9100-53cb-11e9-9b69-00d2a5d4709c.png">

**Comment by karthiknadig** [comment]
dupe #1273
