### ISSUE TITLE
[WSL] Pydev uses Windows locations instead of Linux

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1297]
@HayashiEsme commented on [Tue Apr 02 2019](https://github.com/Microsoft/vscode-python/issues/5075)

## Environment data

- VS Code version: 1.32.3
- Extension version (available under the Extensions sidebar): 2019.3.6215
- OS and version: Windows_NT x64 10.0.16299, Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

Pydev should be able to resolve the paths fine and start debugging

## Actual behaviour

pydev debugger: warning: trying to add breakpoint to file that does not exist: /mnt/c/Users/limxuan/Desktop/PYTHON Entity Graph Webapp/Dependency_Grapher/C:/Users/limxuan/Desktop/PYTHON Entity Graph Webapp/Dependency_Grapher/graph_handler.py (will have no effect)

## Steps to reproduce:
1. Have this in your launch.json:

        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "127.0.0.1",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        }

## Logs
Nothing exciting, so I won't post it

Apologies if there are duplicates, didn't catch any when I ran this

**Comment by quoctruong** [comment]
@DonJayamanne, @karthiknadig, I can repro this issue with version 4.2.6 of `ptvsd` on VSCode version 1.33. It seems downgrading the VSCode version to 1.32.3 will actually fix the issue. So I think there's a bug in the integration between `ptvsd` and VSCode version 1.33.

**Comment by fabioz** [comment]
This seems to be the same issue at: https://github.com/Microsoft/ptvsd/issues/1311, so, closing this one.

@quoctruong please take a look at the comment at: https://github.com/Microsoft/ptvsd/issues/1311#issuecomment-481231104 as it contains instructions on how to configure things so that it doesn't happen (while a final fix is not available).
