### ISSUE TITLE
Debugger breaks in the wrong place for no reason

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1321]
## Environment data

- PTVSD version: 4.2.6
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): PyOrg
- Using VS Code or Visual Studio: VSC

## Actual behavior

Debugger has stopped at a weird place

## Expected  behavior

* Add breakpoints in unit test code (python `unit tests`)
* Start debugging
* Debugger stops at some random location!

## Steps to reproduce:
**Difficult to repro, it is flaky, first time I've seen this.**

**Screen shot is evidence of bug**
Please do not close even though this cannot be reproduced:

![download](https://user-images.githubusercontent.com/1948812/55740583-3c41c380-59e0-11e9-96c1-5932dfeb0c84.png)

**Comment by int19h** [comment]
I wonder if it has anything to do with break-on-entry being enabled?

This will almost certainly require ptvsd logs to properly diagnose, though.

**Comment by int19h** [comment]
Also, do you remember what the location of the source file with the breakpoint was? Is there any possibility that it was filtered out as stdlib?

**Comment by DonJayamanne** [comment]
> I wonder if it has anything to do with break-on-entry being enabled?

No it was off.

> Is there any possibility that it was filtered out as stdlib?

Nope.

> Also, do you remember what the location of the source file with the breakpoint was?


Lines 33 and two others.

Basically these are some UI tests running on the CI server.
I'll enable logging and ensure the logs are attached with the errors if and when we have errors.

I'll check if we get this again. Either way it's a very interesting bug. As you can see it seems to have stopped due to a break point, that's what the message indicates - near stack Trace.

**Comment by DonJayamanne** [comment]
**Happened again, unfortunately I forgot to configure the tests to capture the logs.
Will do so. Please leave this issue open.**

![download](https://user-images.githubusercontent.com/1948812/56483380-81ed9a00-647e-11e9-812f-33dd67570905.png)

**Comment by karthiknadig** [comment]
Can you give a list of all launcher files? I believe those should all be in no trace list, not just the exclude. Let me know if there is any reason the launcher file should be traced at all?

**Comment by DonJayamanne** [comment]
> Can you give a list of all launcher files? I believe those should all be in no trace list, not just the exclude. Let me know if there is any reason the launcher file should be traced at all?

These are tests running on CI, I haven't enabled logging.
Will have to write code to turn it on, capture it and attach the files with the error.
Will get this done before filing another issue.

**Comment by karthiknadig** [comment]
@DonJayamanne do you have any updates on this? In either case can you answer my question, it shouldn't require logs to get the answer for that.

**Comment by DonJayamanne** [comment]
We're excluding all files in the extension directory. Hence launcher is excluded.

> ? I believe those should all be in no trace list, not just the exclude.

What's the difference. I didn't know there were two separate lists!

**Comment by karthiknadig** [comment]
The rules define filters when an event like exception, step, etc. occurs. If the files are excluded then those events are ignored until the event occurs in a file that is included. With no trace, there won't be any event, those frame won't have tracing set on them. This is how we set the debugger files to never show up anywhere.

**Comment by DonJayamanne** [comment]
> This is how we set the debugger files to never show up anywhere.

So the no Trace last would be an internal implemention, not something users would want to set themselves

**Comment by karthiknadig** [comment]
Correct.

**Comment by karthiknadig** [comment]
We have a don't-trace list. However, that list requires the files to have unique names to avoid conflict with user files. So prefixed files like `ptvsd_launcher.py` are good for that list. This is intentional to provide fast filtering while tracing. We don't want to use glob patterns here.

For all other cases you have to use `rules`. Rules support glob patterns and can be used to exclude entire directories, modules, particular files, etc.

Please file a separate bug if this repro again with logs and details.
