### ISSUE TITLE
Debugger - ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1323]
@felipecrp commented on [Sun Apr 07 2019](https://github.com/Microsoft/vscode-python/issues/5151)

## Environment data

- VS Code version: 1.33.0
- Extension version (available under the Extensions sidebar): 2019.3.6352
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda):  3.7.3
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv

## Expected behaviour

Debug python code

## Actual behaviour

Error.

## Steps to reproduce:
1. Create a simple python file, such as:
```python
print('hello')
```
2. Start debugger

## Logs

Traceback (most recent call last):
  File ".vscode\extensions\ms-python.python-2019.3.6352\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File ".vscode\extensions\ms-python.python-2019.3.6352\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
ValueError: source code string cannot contain null bytes

**Comment by DonJayamanne** [comment]
FYI, I too was able to replicate this issue yesterday (flaky).

**Comment by fabioz** [comment]
This seems like some corrupted `.pyc` issue... 

@felipecrp  can you try removing the `.pyc` files under `.vscode\extensions\ms-python.python-2019.3.6352\pythonFiles` to see if it fixes it for you?

**Comment by felipecrp** [comment]
> This seems like some corrupted `.pyc` issue...
> 
> @felipecrp can you try to (recursively) remove the `.pyc` files under `.vscode\extensions\ms-python.python-2019.3.6352\pythonFiles` to see if it fixes it for you?

I deleted the .pyc but it did not solved the problem. But I realized that there was two versions of ms-python on .vscode\extensions:
```
ms-python.python-2019.3.6558
ms-python.python-2019.3.6352
```
I deleted the old one and the debugger started working again.

**Comment by DonJayamanne** [comment]
I to came across this issue.
I'll see if it can be replicated at my end with the latest ptvsd.

**Comment by AJ007s** [comment]
Hey! guys can anyone solve my problem? Whenever i want to run my module it gives me this error:

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from flaskblog import app
  File "C:\Users\Zain\AppData\Local\Programs\Python\Python38\Flask_Blog\f
laskblog\__init__.py", line 2, in <module>
    from flask_sqlalchemy import SQLAlchemy
  File "C:\Users\Zain\AppData\Local\Programs\Python\Python38\Flask_Blog\e
nv\lib\site-packages\flask_sqlalchemy\__init__.py", line 13, in <module>
    import sqlalchemy
ValueError: source code string cannot contain null bytes
