### ISSUE TITLE
Python debuggers sends extra newlines

### ISSUE THREAD

**Issue by luabud** [Microsoft/ptvsd#1327]
@isidorn commented on [Tue Apr 09 2019](https://github.com/Microsoft/vscode-python/issues/5173)

Latest insiders, latest python extension. Mac OSX
Original issue https://github.com/Microsoft/vscode/issues/71964

Have the following code:
```pyhton
print('1')
print('2')
print('3\n4')
print('5')
```

Step over each line and notice how the python debugger after each output event sends an extra output event which contains only the newline.
Due to that the output in the debug console looks like this
Users are hitting this now becuase vscode stopped trimming empty lines it seems (and we plan to continue behaving this way, empty lines should be respected when comming from debug adapters).

![Screenshot 2019-04-09 at 11 02 58](https://user-images.githubusercontent.com/1926584/55787647-0cb1ba80-5ab7-11e9-9a38-1e2ecf56210a.png)

![Screenshot 2019-04-09 at 11 02 40](https://user-images.githubusercontent.com/1926584/55787634-04597f80-5ab7-11e9-93dc-b69511933cd1.png)

**Comment by karthiknadig** [comment]
Same as #1324
