### ISSUE TITLE
on_ptvsd_systemInfo should be ported to pydevd

### ISSUE THREAD

**Issue by fabioz** [Microsoft/ptvsd#1336]

**Comment by karthiknadig** [comment]
I don't think this should be ported to `pydevd` this is specific to `ptvsd`, it is used to identify version of `ptvsd` running on remote or locally by Visual Studio.

**Comment by fabioz** [comment]
@karthiknadig if the idea is running `pydevd` in a different process, then `pydevd` should answer that no? (at least I was thinking that `ptvsd` would work as the adapter which would run along `vscode`/`vs` and `pydevd` would then be run on the user process).

**Comment by karthiknadig** [comment]
The main use of this one is in getting the adapter version (essentially `ptvsd` version), specifically to match the adapter host in VS with `ptvsd` for feature support. If we need additional system info, such as python that the user code is running on (after the split), we can add that to `pydevd` later. For now this is not needed.

**Comment by fabioz** [comment]
Got it.
