### ISSUE TITLE
on_setDebuggerProperty should be ported to pydevd

### ISSUE THREAD

**Issue by fabioz** [Microsoft/ptvsd#1337]
Note: right now the current implementation in `wrapper` doesn't seem to work (so, it's probably not tested?) as it just changes the wrapper debug options and doesn't forward anything to `pydevd` (I think that right now all the code related to `just my code` is in `pydevd` already).

I see that there are some methods which are still in `wrapper` but are unused (i.e.: `_should_debug` and things that it calls), so, we should probably remove those.

**Comment by karthiknadig** [comment]
This has been ported with some items pending, (see #1355 for pending items)
