### ISSUE TITLE
Django 2.2: request.get() throws exception although it is in a try except block

### ISSUE THREAD

**Issue by ohlr** [Microsoft/ptvsd#1348]
## Environment data

- OS and version: Ubuntu 16
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Django version: 2.2
- Using VS Code or Visual Studio: VS Code

```
Version: 1.33.0
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:08:57.775Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic
```
launch.config:
```
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/isarsoft/manage.py",
            "console": "integratedTerminal",
            "args": [
                "runserver",
                "--noreload",
                // "--nothreading",
            ],
            "django": false
        },
```

my code:
```
try:
    EC2_PRIVATE_IP = requests.get('http://169.254.169.254/latest/meta-data/local-ipv4', timeout=0.01).text
except requests.exceptions.RequestException:
    pass
```

## Actual behavior

> Exception has occurred: ConnectTimeout

## Expected  behavior

works fine with `python manage.py runserver` used to work with the debug console too

**Comment by fabioz** [comment]
@ohlr sorry, I didn't really understand what the issue is... Is that `Exception has occurred: ConnectTimeout` shown in the console or is it a caught exception? Can you show a screenshot to make things clearer?

**Comment by ohlr** [comment]
` EC2_PRIVATE_IP = requests.get('http://169.254.169.254/latest/meta-data/local-ipv4', timeout=0.01).text
`

```
Exception has occurred: ConnectTimeout
HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/local-ipv4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2c50be6e48>, 'Connection to 169.254.169.254 timed out. (connect timeout=0.01)'))
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/user/Nextcloud/Isarsoft/ElasticBeanstalk/isarsoft/isarsoft/settings.py", line 36, in <module>
    EC2_PRIVATE_IP = requests.get('http://169.254.169.254/latest/meta-data/local-ipv4', timeout=0.01).text
  File "/home/user/anaconda3/envs/EB/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/user/anaconda3/envs/EB/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/user/Nextcloud/Isarsoft/ElasticBeanstalk/isarsoft/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/user/anaconda3/envs/EB/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
```

**Comment by ohlr** [comment]
this error does only occur with the vs-code debugger. It does not apear with `python manage.py runserver`

**Comment by fabioz** [comment]
Have you tried raising the timeout? It's somewhat expected that the debugger will change the speed of your program...

**Comment by fabioz** [comment]
Another thing, do you by any chance have some sort proxy enabled? 

Also, have you checked if your environment variables when running from vscode match the one you have in the shell? (it's possible that you have different settings in your program depending on those)

**Comment by ohlr** [comment]
increased timeout to 5s nothing changes

environment should be the same, both times I use my conda environment

did you try to reproduce?

**Comment by fabioz** [comment]
> did you try to reproduce?

Yes (although I tried with `google.com` as I don't have access to the ip you're using).

When I do:

```
import requests
print(requests.get('https://www.google.com/', timeout=0.01).text)
```

it always times out, but raising the timeout (or not passing it), makes it work (but I have the same behavior in the shell or from vscode and I can't really envision how the debugger could be affecting that other than having things working a bit slower than without the debugger).

If you do a regular launch from vscode (without the debugger, just a plain run), does it work?

**Comment by ohlr** [comment]
"I don't have access to the ip you're using" - me neither, the code is only supposed to get the `EC2_PRIVATE_IP` in production thats why there is the try except statement, but the debugger seems to ignore it. Instead of executing `pass` it throws an exception.

This was not the case in previous releases that's why I think it's a bug.

What do you mean with plain run?

**Comment by karthiknadig** [comment]
@ohlr `Ctrl-F5` in VSCode should run this in no-debug mode, but it will still use the same infrastructure to launch and run your code.

**Comment by ohlr** [comment]
Okay, with that it works. However, shouldn't the debugger understand a `try except`-statement ?

**Comment by fabioz** [comment]
@ohlr... you mean it pauses in the debugger at that point? 

That actually seems correct if you have the `Raised Exceptions` checked in the `breakpoints` section as you'd be asking the debugger to stop at any raised exceptions even if it was handled (there were fixes related to that in the latest releases, and if it's just pausing in the debugger that behavior seems correct in this case).

-- if you don't have `Raised Exceptions` checked in the `breakpoints` section then this is a bug...

**Comment by ohlr** [comment]
Can you tell me where I find the `breakpoints` section?

**Comment by fabioz** [comment]
Sure:

![breakpoints](https://user-images.githubusercontent.com/117621/56313724-b2a19c80-6129-11e9-9e5a-4821a7f18bc9.png)

**Comment by ohlr** [comment]
Thank you guys - it was checked - so it was not a bug but a feature that have been added with the latest release. Sorry for wasting your time!
