### ISSUE TITLE
Cannot continue to debug for conditions breakpoint  when pressing F11 several times with Python2.7 env

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/ptvsd#1353]
VS Version: 16.1.0 Preview 2.0 [28811.223.d16.1stg]
Python Tool Version: 16.1.19098.1

Repro step:
1.Create python application
2.Type code in default .py file
      Repro step:
1.Create python application
2.Type code in default .py file
```
from math import cos, radians
def make_dot_string(x):
    rad = radians(x)  
    numspaces = int(20 * cos(radians(x)) + 20)  
    st = ' ' * numspaces + 'o' 
    return st
def main():
    for i in range(0, 1800, 12):
        s = make_dot_string(i)
        print(s)
main()
```
3.Intall the latest ptvsd in Python2.7 environment
4.Set a conditions breakpoint, hover on red dot and click breakpoint setting
![image](https://user-images.githubusercontent.com/41426540/56020965-e8fea680-5d3a-11e9-93b2-b1b403cf24e9.png)
5.Create expressions using Python code like i > 1600
6.F5 to start debug
7. Press F11 several times

Expect Result:
It can debug to end

Actual Result:
It is interrupted in the middle and can not continue when pressing any key
![image](https://user-images.githubusercontent.com/41426540/56021917-2d8b4180-5d3d-11e9-8c5e-26328f627854.png)

Note:
1. Attachment is Debug Adapter Host Log
2. This issue is not repro on Python3.7 env
[Debug Adapter Host Log.txt](https://github.com/Microsoft/PTVS/files/3072245/Debug.Adapter.Host.Log.txt)

**Comment by fabioz** [comment]
From the log, the requests/responses seem ok, the one thing that doesn't seem correct is that in the last message the debugger says that there are `"totalFrames": 2`, but then only returns 1 frame in `"stackFrames"` (so, maybe this is making `PTVS` misbehave).

```
 1> [DebugAdapter] <--   E (stopped): {"body": {"preserveFocusHint": false, "description": null, "text": null, "allThreadsStopped": true, "reason": "breakpoint", "threadId": 1}, "type": "event", "event": "stopped", "seq": 375}
 1> [DebugAdapter] --> C (threads-66): {"command":"threads","arguments":{},"seq":66,"type":"request"}
 1> [DebugAdapter] <--   R (stepIn-65) [25 ms]: {"request_seq": 65, "body": {}, "seq": 376, "success": true, "command": "stepIn", "message": "", "type": "response"}
 1> [DebugAdapter] <--   R (threads-66) [12 ms]: {"request_seq": 66, "body": {"threads": [{"id": 1, "name": "MainThread"}]}, "seq": 377, "success": true, "command": "threads", "message": "", "type": "response"}
 1> [DebugAdapter] --> C (stackTrace-67): {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1,"format":{"parameters":true,"parameterTypes":true,"parameterNames":true,"line":true,"module":true}},"seq":67,"type":"request"}
 1> [DebugAdapter] <--   R (stackTrace-67) [16 ms]: {"request_seq": 67, "body": {"totalFrames": 2, "stackFrames": [{"column": 1, "source": {"path": "C:\\Users\\vxiaofz\\source\\repos\\PythonApplication11\\PythonApplication11\\PythonApplication11.py", "sourceReference": 0}, "line": 11, "id": 1, "name": "__main__.main : 11"}]}, "seq": 378, "success": true, "command": "stackTrace", "message": "", "type": "response"}
```

**Comment by fabioz** [comment]
Actually, PTVSD passed `"startFrame:0"` and `"levels:1"`, so, it seems correct that only 1 frame returned (in which case things seem correct on the `ptvsd` side. 

@karthiknadig do you see some issue there?

**Comment by karthiknadig** [comment]
@xiaofeng0123 we might need more detailed logs for this. Can you set PTVSD_LOG_DIR environment variable in your project? You can do that in the project settings. Set it to some directory, like `PTVSD_LOG_DIR=C:\logs`, ensure that `C:\logs` exists.

**Comment by xiaofeng0123** [comment]
@karthiknadig Attachment is the log of PTVSD.
[ptvsd-14244.log](https://github.com/Microsoft/ptvsd/files/3087610/ptvsd-14244.log)

**Comment by xiaofeng0123** [comment]
When I test on VS 16.1.0 Preview 3.0 [28824.243.d16.1stg] with python build 16.1.19113.1, I found it will cannot continue to debug for breakpoint when pressing F11 several times on python2.7.
Below is PTVSD log
[ptvsd-1692.log](https://github.com/Microsoft/ptvsd/files/3115438/ptvsd-1692.log)

Below is repro video:
![stopdebug](https://user-images.githubusercontent.com/41426540/56713947-d71ef980-6765-11e9-8e03-5334910ce26a.gif)

**Comment by karthiknadig** [comment]
Looks like this is fixed in the latest version. Please reopen if it still repros.
