### ISSUE TITLE
I can't debug code in 3rd party libraries installed via pip

### ISSUE THREAD

**Issue by agalazis** [Microsoft/ptvsd#1354]
## Environment data

- PTVSD version: 4.2.5
- OS and version: uname -a 'Linux thinkpadx260.local 5.0.5-200.fc29.x86_64'
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Using VS Code or Visual Studio: Vs Code 1.33

## Actual behavior
I can't debug code in  3rd party libraries and crashes in libraries are not made available to the debugger when raised or uncaught exceptions are enabled. This used to work in 4.2.0 (packages were installed in an activated virtualenv) but due to other bugs in that  version I stick to the latest

## Expected  behavior

Debugging and breaking on exceptions  of packages installed in a vritualenv should be doable again

## Steps to reproduce:
1. make a virtual env local to your project directory in docker container and activate it before running your python server, try to set a breakpoint or make a library crash(while having raised exceptions ticked in vscode). You 'll see that the debugger is misbehaving.

**Comment by fabioz** [comment]
This was actually a fix in the debugger in the latest version (exceptions handling was not respecting the flag to debug the standard library or not -- the default is not to debug the standard library).

As in your case you want to debug the standard library, please add `DebugStdLib` to `debugOptions` in your launch configuration.

See: https://code.visualstudio.com/docs/python/debugging for more details.

**Comment by agalazis** [comment]
Thank you for your response. I have just checked it and it works.

**Comment by agalazis** [comment]
That config has also changed to `justMycode: false` recently

**Comment by martinGithub** [comment]
@fabioz , it would be good to have "justMycode": false by default. it would have saved me (and i guess many people) losing time before eventually finding the solution here. Should we reopen the issue ?

**Comment by karthiknadig** [comment]
@martinGithub the `justMycode` setting default comes form the IDE. This is a good question to ask on the pyhton extension and/or PTVS. 

From our experience with the usage of the debugger, the common scenario is where users want to debug their code only. Debugging library code is a less common scenario. But in either of these cases the main issue is the discover-ability of this setting. That is something the IDE should address.

/cc @DonJayamanne @huguesv
