### ISSUE TITLE
variable not updating in debug pane when using debug console

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1356]
@asaflotz commented on [Sun Apr 14 2019](https://github.com/Microsoft/vscode-python/issues/5250)

## Environment data

- VS Code version: 1.33.3
- Extension version (available under the Extensions sidebar): 2019.3.6558
- OS and version: linux ubuntu 16.04
- Python version (& distribution if applicable, e.g. Anaconda): python 3.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv 
- Relevant/affected Python packages and their versions: all

## Expected behavior

in debug mode on breakpoint, when changing a var in debug console- automatically show change in watch and variable

## Actual behavior

no change is shown until at least one step in code is made.

## Steps to reproduce:
1. breakpoint on line after 'a=1'
2. change in debug console a=8
3. see no change in vars and watches

**Comment by karthiknadig** [comment]
@DonJayamanne We don't get a new `variables` or `evaluate` request after executing debug console request. The DAP protocol does not provide a way to tell the IDE that there is a change in variables state and that it needs to issue a new variables request.

**Comment by DonJayamanne** [comment]
@karthiknadig 
Please can you check upstream VSC issues to see whether there's a solution for this:
https://github.com/microsoft/vscode/issues/2399
https://github.com/microsoft/vscode/issues/15520
https://github.com/microsoft/vscode/issues/8118
https://github.com/microsoft/vscode/issues/2399

Looks like they fixed this in VSC, if the problem still persists, please report on VSC. 

Re-opening as this is deemed to be working for other debuggers (node), and not for Python. Hence we still need to look into this - as its a bug (could be an upstream issue though).

**Comment by YoniChechik** [comment]
Thanks for the reopening- it can be very useful for data-science with python!

**Comment by karthiknadig** [comment]
Created an issue on VSCode https://github.com/microsoft/vscode/issues/75359 . I will keep this open, and see what they say about this issue.

**Comment by YoniChechik** [comment]
@karthiknadig [https://github.com/microsoft/vscode/issues/75359](this issue) is now fixed. please update about what you think

**Comment by karthiknadig** [comment]
@YoniChechik @DonJayamanne I verified the fix in the Insiders build of VSCode.
