### ISSUE TITLE
Extra line feeds in VS Code debug console

### ISSUE THREAD

**Issue by wizardkids** [Microsoft/ptvsd#1371]
Visual Studio Code 1.33.1
Windows-7-6.1.7601-SP1 AMD64
CPython 3.7.1 (64-bit)
ptvsd 4.2.7

This may be a repeat of or related to issue #489, but I don't think so. Since upgrading to VS Code 1.33.1, the debug console appears to be adding extra line feeds to output. For example, running a script where the following is the _only_ line of code:

print("I think", "I can.")

...prints in either the external or integrated terminals correctly as:

"I think I can."

...but in the debug console, it prints as:

"I think"

"I can."

I do not recall the debug console behaving like this previously. Is this the expected behavior or is this a bug in the debug console?

**Comment by karthiknadig** [comment]
Same as #1324
