### ISSUE TITLE
print does not produce output in VS Code

### ISSUE THREAD

**Issue by leonbrag** [microsoft/ptvsd#1377]
## Environment data

- PTVSD version: Visual Studio Code with Python extension latest as ofr 4-21-19
- OS and version: Win10 
- Python version (& distribution if applicable, e.g. Anaconda):  Python 3.7 32bit
- Using VS Code or Visual Studio:

## Actual behavior

I have print statement in Python code. Py file is executed in Visual Studio Code (latest version). 

When executed under debugger (using Cntrl-F5) output is not shown.
When executed without debugger (using F5) output is not shown.
To produce output, I must hit a break point and then resume, to see output of the print statement

Screenshot: https://1drv.ms/u/s!ApLAgjXPHhbmg_pdoAETPyKTH4RyBQ 

## Expected  behavior

see results of Print

## Steps to reproduce:
write one liner PY code with print ("Hello"), execute in Visual Studio code

**Comment by karthiknadig** [comment]
I am not able to repro it with 3.7, I tried both 32bit and 64bit python. 
![image](https://user-images.githubusercontent.com/3840081/56517123-0973f100-64f1-11e9-9c37-f9286fdecc4f.png)
Can you set following environment variable to get the logs: `"PTVSD_LOG_DIR": "C:\\logs"`. You should be able to pass this in launch.json using `env`. Make sure that the logs directory exists.

There might be some race that is occurring here. I am wondering if we receive an event from pydevd here, but ptvsd is not forwarding it to IDE. I believe #530 should address this, if it is a race.

**Comment by karthiknadig** [comment]
Please reopen when logs are available for this issue.
