### ISSUE TITLE
DAP: pydevd support for disconnect/reconnect.

### ISSUE THREAD

**Issue by fabioz** [microsoft/ptvsd#1382]
- Upon reconnect, threads creation messages have to be sent back again.
- Messages shouldn't be sent anymore after disconnected.

**Comment by fabioz** [comment]
Some dev notes (related to the VSCode client, which may or not be true for other clients, but it's what's being considered in the implementation):

- It seems that the `disconnect` request is actually meant to terminate the program (even if `supportsTerminateRequest=True` there's no separate icon to terminate nor disconnect).

- When we have a `launch`, `disconnect` is sent from an icon resembling terminate and when we have an `attach`, `disconnect` is sent from an icon resembling a disconnect (so, it appears that`disconnect` in a `launch` config should kill the program, whereas a `disconnect` in an `attach` config should keep the program running (and it should be able to connect again later on).

- The idea is having `pydevd` as the debug target and `ptvsd` as the debug adapter, so, killing the process/subprocesses should be done from `ptvsd` (upon `disconnect`, `ptvsd` doesn't really need to call the `pydevd` disconnect if it was a `launch` -- it can just promptly kill the process/subprocesses, whereas if it was an `attach` it should call the `pydevd` `disconnect` to let threads run).

**Comment by fabioz** [comment]
@int19h @karthiknadig I have a question here:

If the user does:

```
ptvsd.enable_attach(host='127.0.0.1', port=3456)
ptvsd.wait_for_attach()

# make attach launch
...  
# disconnect from UI
```

Should he be able to reconnect using that previous connection or does he need to call `ptvsd.enable_attach(host='127.0.0.1', port=3456)` again? -- i.e.: should that socket remain open and listening for new connections on disconnect or should it be closed?

**Comment by karthiknadig** [comment]
You only need to call `enable_attach` once. You should be able to re-connect to it without calling `enable_attach` again for that process.
