### ISSUE TITLE
Unhandled exception when remote debugging

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1383]
@lephuongbg commented on [Mon Apr 22 2019](https://github.com/Microsoft/vscode-python/issues/5424)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): 2019.3.6558
- OS and version: Ubuntu 18.04
- Python version: Docker lambci/lambda:python3.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

Debugger stopped at breakpoint successfully.

## Actual behaviour

Debugger doesn't stopped at breakpoint. Exceptions are thrown in the console.

## Steps to reproduce:

1. Add ptvsd code:
```python
print('Waiting for debugger')
# Allow other computers to attach to ptvsd at this IP address and port.
ptvsd.enable_attach(address=('0.0.0.0', debug_port),
                    redirect_output=True)

# Pause the program until a remote debugger is attached
ptvsd.wait_for_attach()
print('Debugger connected')
```
2. Run `flask ... --no-reload`
3. Flask server stopped at "Waiting for debugger"
4. Run launch configuration to attach to debugger server:
```json
        {
            "name": "Python: Remote Debug",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}/api",
                    "remoteRoot": "/var/task"
                }
            ]
        }
```
5. Flask server continued to "Debugger connected"
6. Request an arbitrary route
7. Exceptions thrown as below

## Logs

```
Debugger connected

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

Unhandled exception in thread started by
<_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7f6e3b6e95f8>

SystemError
:
/opt/brazil-pkg-cache/packages/LambdaLangPython36/LambdaLangPython36-x.200144.0/AL2012/generic-flavor/src/python/Objects/codeobject.c:851: bad argument to internal function


The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/task/.venv/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 675, in __call__
  File "/var/lang/lib/python3.6/threading.py", line 884, in _bootstrap
  File "/var/lang/lib/python3.6/threading.py", line 912, in _bootstrap_inner
  File "/var/lang/lib/python3.6/threading.py", line 912, in _bootstrap_inner
SystemError
:
PyEval_EvalFrameEx returned a result with an error set


During handling of the above exception, another exception occurred:
SystemError
:
/opt/brazil-pkg-cache/packages/LambdaLangPython36/LambdaLangPython36-x.200144.0/AL2012/generic-flavor/src/python/Objects/codeobject.c:851: bad argument to internal function


The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/task/.venv/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 678, in __call__
  File "/var/task/.venv/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 978, in notify_thread_not_alive
SystemError
:
<built-in method __enter__ of _thread.lock object at 0x7f6e3b1b1300> returned a result with an error set
```

**Comment by int19h** [comment]
The failing line inside codeobject.c appears to be in a call to `_PyCode_SetExtra`, so this is probably triggered by the frame evaluator code somehow. Also, judging by the exact line number, this is Python 3.6.0 or 3.6.1, since later versions have moved things around a bit. 

@lephuongbg, can you try doing this with `PYDEVD_USE_FRAME_EVAL` environment variable set to `NO` (note: case-sensitive)? This should disable that optimization, and hopefully make it work for you while we figure out the problem.

**Comment by karthiknadig** [comment]
Please reopen when more information is available.

**Comment by lephuongbg** [comment]
Our python version has moved to 3.7 and I can't reproduce this problem anymore.
