### ISSUE TITLE
Could not load source '<string>': Source unavailable.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1389]
@TurboCooler commented on [Thu Apr 25 2019](https://github.com/Microsoft/vscode-python/issues/5477)

Reproduced by doing the following:

Create an application using Flask
Create a Jinja Template
Create methods similar to the following
```
@app.route('/pingpretty')
def pingPretty():
     return render_template('pingpretty.html')

@app.context_processor
def context_processor():
     return dict(App_Startup=appStartTime.strftime('%Y%m%d'),Deployment_Env=os.environ["DEPLOY_ENV"],Computer_Name=os.environ["COMPUTERNAME"])
```

In your template, have something similar to this 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pretty Ping</title>
    <style>
        table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        }
        th, td {
        padding: 15px;
        text-align: left;
        }
    </style>
</head>
<body>
<table style="width:50%">
  <table style="width:50%">
  <tr>
    <th>Attribute</th>
    <th>Value</th> 
  </tr>
  <tr>
    <td>App Startup Time</td>
    <td>{{ App_Startup }}</td>
  </tr>
  <tr>
    <td>Deployment Environment</td>
    <td>{{ Deployment_Env }}</td>
  </tr>
  <tr>
    <td>Computer Name</td>
    <td>{{ Computer_Name }}</td>
  </tr>
</table>
</body>
</html>
```

The code executes fine outside of the debugger.  When using the debugger once it steps into the template you get the error shown in the title before it gets to any Jinja code, this happens as it is stepping through the Meta Tag headers.  This will prevent me from debugging the template to resolve an issue we are having.

---

@weltenrand commented on [Sat Apr 27 2019](https://github.com/Microsoft/vscode-python/issues/5477#issuecomment-487341245)

Having the same issue when executing `requests.get(some_url)`

**Comment by karthiknadig** [comment]
@TurboCooler I am not able to repro this locally. Can you provide more details about your environment? like python version, venv, launch config, etc. Anything that might be relevant.
- PTVSD version: 
- OS and version: 
- Python version (& distribution if applicable, e.g. Anaconda): 

![image](https://user-images.githubusercontent.com/3840081/56924831-bb2b9880-6a82-11e9-9ab9-10be0edaaa0b.png)


when you see `'<string>': Source unavailable.` that could mean, debugger is attempting to load source for generated code. But it should not block you, you should be able to step-over/step-out of that frame ( and that file). Let me know if that is not possible.

Also, we support template breakpoints. you should be able to set template breakpoints and get to that point. Let me know if this is not working for you either.
![image](https://user-images.githubusercontent.com/3840081/56925295-d8ad3200-6a83-11e9-9398-25a943aa8bd5.png)

**Comment by TurboCooler** [comment]
Unlike what you show in your picture, I cannot set a breakpoint in the Jinja file.

once I receive this error "Could not load source '<string>': Source unavailable."

I cannot step through it.  Below is my whole environment.  

OS and version: Windows 10 Version 1809 (Build 17763.437)
python --version
Python 3.7.2

ptvsd 4.2.8

VS Code Env:
Version: 1.33.1 (system setup) 
Commit: 51bOb28134d51361cfE6d2fOa1c698247aeabd8 
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6 
Chrome: 66.0.3359.181 
Node.Js: 10.2.0 
V8: 6.6.346.32 
OS: Windows NTx64 10.0.17763 

Visual Studio Code Extensions Installed
MagicPython Version: 1.1.0
Python Version: 2019.4.12954 Publisher: Microsoft
Python Docs Version: 0.8.3
Python Extension Pack Version: 1.4.0
Python for VSCode Version: 0.2.3
Python Preview Version: 0.0.4
python snippets Version: 1.0.2

Main environment (not venv)
Package           Version
----------------- ----------
astroid           2.2.0
certifi           2019.3.9
chardet           3.0.4
colorama          0.4.1
idna              2.8
isort             4.3.9
lazy-object-proxy 1.3.1
mccabe            0.6.1
pip               19.1
pipenv            2018.11.26
ptvsd             4.2.8
pylint            2.3.0
pymongo           3.7.2
requests          2.21.0
setuptools        40.6.2
six               1.12.0
typed-ast         1.3.1
urllib3           1.24.1
virtualenv        16.4.3
virtualenv-clone  0.5.3
wrapt             1.11.1

**venv** in which the error occurred
Package           Version
----------------- --------
aiofiles          0.4.0
astroid           2.2.5
boto3             1.9.138
botocore          1.12.138
certifi           2019.3.9
chardet           3.0.4
Click             7.0
colorama          0.4.1
docutils          0.14
Flask             1.0.2
httptools         0.0.13
idna              2.8
isort             4.3.17
itsdangerous      1.1.0
Jinja2            2.10.1
jmespath          0.9.4
lazy-object-proxy 1.3.1
MarkupSafe        1.1.1
mccabe            0.6.1
multidict         4.5.2
pip               19.1
ptvsd             4.2.8
pylint            2.3.1
python-dateutil   2.8.0
redis             3.2.1
requests          2.21.0
s3transfer        0.2.0
sanic             19.3.1
setuptools        40.6.2
six               1.12.0
typed-ast         1.3.4
urllib3           1.24.2
websockets        6.0
Werkzeug          0.15.2
wrapt             1.11.1

**Comment by int19h** [comment]
Can you share the configuration from your launch.json that you are using to start debugging?

**Comment by karthiknadig** [comment]
Also, Can you share the extension you have installed? If you have any extension that applies to django/jinja2 specifically, try disabling it. That should allow you to set breakpoints.

**Comment by TurboCooler** [comment]
> Can you share the configuration from your launch.json that you are using to start debugging?

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Flask Weather.py",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "weather.py",
                "DEPLOY_ENV": "localPC"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true
        }
    ]
}

**Comment by TurboCooler** [comment]
> Also, Can you share the extension you have installed? If you have any extension that applies to django/jinja2 specifically, try disabling it. That should allow you to set breakpoints.

Visual Studio Code Extenstions Installed
MagicPython Version: 1.1.0
Python Version: 2019.4.12954 Publisher: Microsoft
Python Docs Version: 0.8.3
Python Extension Pack Version: 1.4.0
Python for VSCode Version: 0.2.3
Python Preview Version: 0.0.4
python snippets Version: 1.0.2
Jinja Version: 0.0.8

**Comment by int19h** [comment]
It looks like you have this extension installed, and it conflicts with built-in Jinja support in the Python extension:

https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja

**Comment by TurboCooler** [comment]
> It looks like you have this extension installed, and it conflicts with built-in Jinja support in the Python extension:
> https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja

What have installed is the same extension.  if I try to remove it tells me it cannot because it has a dependency on the extension pack.

The only thing I was thinking of doing is just removing ALL of the extensions and starting over adding them in again one by one.  Provided the extension is the issue.

**Comment by karthiknadig** [comment]
You should be able to disable it, reload window. You shouldn't have to uninstall it.

**Comment by TurboCooler** [comment]
> You should be able to disable it, reload window. You shouldn't have to uninstall it.

Unable to disable just one, there are dependencies.  All the dependencies have to be disabled at that point I might as well as uninstall and then reinstall

**Comment by TurboCooler** [comment]
I uninstalled and reinstalled and things are still not working.
As you can see from the image, it now attempt to debug on a commented out line.  I eventually get the same exact error.

![image](https://user-images.githubusercontent.com/28705640/57039879-ddace580-6c2b-11e9-872f-a32b77b34cd4.png)

**Comment by karthiknadig** [comment]
Can you add environment variable `"PTVSD_LOG_DIR": "<directory-to store-logs>",` to launch json? This should generate log file from the debugger. Please share the logs after removing any personal information. 
```js
{
            "name": "Python: Flask Weather.py",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "weather.py",
                "DEPLOY_ENV": "localPC",
                "PTVSD_LOG_DIR": "<directory-to store-logs>",
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true
        }
```

It is strange that is not allowing you to step-out/over the file or place where you hit `'<string>': Source unavailable.`. The log files should help us understand what is going on.

**Comment by TurboCooler** [comment]
Enclosed is the log file but I have no idea what to look for in the file.

[ptvsd-19984.log](https://github.com/Microsoft/ptvsd/files/3136000/ptvsd-19984.log)

**Comment by TurboCooler** [comment]
I create a new Windows 10 VM in Hyper-V and installed all the patches to get to the same version as my laptop

I then did a clean install of Python and VS Code to the latest versions.
I then installed all my dependencies (e.g. Flask, etc.)
I installed a single VS Code Extension

Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
Version: 2019.4.12954
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

No other extension is installed.

I once again attempted to run my Flask application  using this Launch config

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "weather.py",
                "FLASK_ENV": "development",
                "FLASK_DEBUG": "0",
                "DEPLOY_ENV": "localPC"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true
        }
    ]
}

I get the set error.  On the Jinja Template, the Debugger does not even highlight nor display on the currently executing line.  It is off on some other line which makes no sense.  If I hover over the Jinja variables, an empty outline of a box appears but no value.

I am not sure what else to try.  I pretty much installed a new Win 10 OS on a VM.  Reinstalled VS Code, pip installed all my dependencies, and it still does not work.  Actually, it works differently, now the page is fully rendered and sent back before I get Could not load source '<string>': Source unavailable. which is not helpful as I cannot effectively debug into a Jinja page.  IMHO, the bug is in either VS Code or Extension or the two are out of sync.

**Comment by karthiknadig** [comment]
Thanks for the logs. Looking through it, as far as i can tell, `source unavailable` occurs on `__new__` for `namedtuple__URLTuple` returned in `werkzeug.urls`. But as per the logs you stepped through that and the template rendering was complete. The template rendering thread then shuts down. For some reason with the same setup, I don't seem to hit that frame. 

While I investigate further, you could try `"justMyCode": false` in launch.json. That will allow you to step into flask internal code, and the debugger will not skip any frame.

**Comment by karthiknadig** [comment]
We have an idea of what is going on here. I filed a separate bug with minimal repro, this is #1398

**Comment by karthiknadig** [comment]
We will track this issue via #1398
