### ISSUE TITLE
get_contents_debug_adapter_protocol from pydevd resolvers should use start/count from variables request.

### ISSUE THREAD

**Issue by fabioz** [microsoft/ptvsd#1392]

**Comment by karthiknadig** [comment]
Note that this should only be supported if `supportsVariablePaging` is `true` in the `initialize` request.

**Comment by fabioz** [comment]
I'll take a look at this.

I think this may also fix https://github.com/microsoft/ptvsd/issues/788.

**Comment by fabioz** [comment]
I'm going to close this one in favor of https://github.com/microsoft/ptvsd/issues/788.
