### ISSUE TITLE
Module name for templates is not set

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1397]
## Environment data

- PTVSD version: master
- OS and version: windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VS

## Actual behavior

![image](https://user-images.githubusercontent.com/3840081/57096993-629b0c00-6ccb-11e9-9c96-04cdb9adefac.png)

## Expected  behavior

Should have either the name of the template or `template`.

## Steps to reproduce:
1. run a django app set breakpoint in a template.

/cc @huguesv

**Comment by gramster** [comment]
Low priority; closing.
