### ISSUE TITLE
Recursion when using locals() in Python Debug Mode

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1417]
@jamesmundy commented on [Fri May 10 2019](https://github.com/microsoft/vscode-python/issues/5600)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): Python 2019.4.12954
- OS and version: Windows Version 10.0.17134 Build 17134
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv

## Expected & Actual behaviour

I''ve recently started suffering from the exact same issue as this previous issue:
https://github.com/microsoft/vscode-python/issues/581

This library uses `locals()` which seems to serialise itself in debug mode leading to recursion:
https://github.com/liampauling/betfair/blob/master/betfairlightweight/filters.py#L94
This only happens when debugging in VSCode. I had this code running ok a few weeks ago so something has possibly changed since.

## Steps to reproduce:
This issue here has all the necessary steps:
https://github.com/microsoft/vscode-python/issues/581#issuecomment-357600776

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```[Info  - 23:15:54] Microsoft Python Language Server version 0.2.66.0
[Info  - 23:15:54] Initializing for C:\Users\jemun\AppData\Local\Programs\Python\Python36\python.exe
[Info  - 23:16:07] GetCurrentSearchPaths c:\Dev\market-data-capture\env\Scripts\python.exe 
##########Linting Output - pylint##########

--------------------------------------------------------------------

Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

[Info  - 23:16:07] Python search paths:
[Info  - 23:16:07]     c:\dev\market-data-capture\env\lib
[Info  - 23:16:07]     c:\dev\market-data-capture\env\scripts
[Info  - 23:16:07]     c:\users\jemun\appdata\local\programs\python\python36\lib
[Info  - 23:16:07]     c:\users\jemun\appdata\local\programs\python\python36\dlls
[Info  - 23:16:07]     c:\dev\market-data-capture\env
[Info  - 23:16:07]     c:\dev\market-data-capture\env\lib\site-packages
[Info  - 23:16:07]     c:\dev\betfair
[Info  - 23:16:07] Configuration search paths:
[Info  - 23:16:11] Microsoft Python Language Server version 0.2.66.0
[Info  - 23:16:11] Initializing for c:\Dev\market-data-capture\env\Scripts\python.exe```

**Comment by fabioz** [comment]
The reason this happens is explained at: https://github.com/microsoft/ptvsd/issues/1265#issuecomment-476807912

The fix on the library would be inlining the call to locals() or doing a copy of what's returned... as in the explanation, it may not be fixable in the debugger at all because it needs to access the frame locals and just by accessing it, it mutates and adds `args` to the locals.

Note: please leave this issue open, I'll investigate to see if something can be done on the debugger (although I don't have high hopes and this isn't high priority right now).

**Comment by jamesmundy** [comment]
Thanks for the information @fabioz, I can confirm that changing the library's code to `locals().copy()` fixes the issue.
What is strange is that this code worked fine about 2 weeks ago so perhaps something changed in the debugger and caused it to appear? Most notably I installed Visual Studio 2019 and the Python tools in the interim though I have no idea how much is shared between the two libraries, if any.

**Comment by fabioz** [comment]
@jamesmundy not sure... note that the reason it breaks is pretty much dependent on where you break or step / get return values (it depends a lot, so, if your scenario changed just a bit that code may break or not).

**Comment by int19h** [comment]
It is entirely possible that something changed in the debugger to make the difference, as well - when and where we call `locals()` is basically an implementation detail. It's not something that we can realistically maintain as a stable public contract. 

VS and VSC both use ptvsd for debugging, but they both come with their own bundled versions, so one shouldn't affect the other in any way.

**Comment by karthiknadig** [comment]
Closing this. Since this is external.
