### ISSUE TITLE
DAP: Stop on entry should be ported to pydevd

### ISSUE THREAD

**Issue by fabioz** [microsoft/ptvsd#1418]
Blocked by:

https://github.com/microsoft/ptvsd/issues/1387
https://github.com/microsoft/ptvsd/issues/1413

**Comment by karthiknadig** [comment]
I might be able to move this fairly easily with the #1387 change. It looks straight forward.

**Comment by fabioz** [comment]
Sure... some things to check though:

- We should add an API to do the stop on entry in `PyDevdAPI`.
- There is actually a command `CMD_STOP_ON_START` already (implemented in `PyDevdAPI.cmd_stop_on_start`) -- it should use the new API (not sure why `ptvsd` wasn't using it already).
- Processing the debug adapter settings (in `_PyDevJsonCommandProcessor._set_debug_options`) should use the new API.

-- if you want to implement this along with that change, feel free to do it ;)

**Comment by karthiknadig** [comment]
Ok. I will push an update to the PR.
