### ISSUE TITLE
Remove or replace usage of non json commands

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1419]
* CMD_REDIRECT_OUTPUT : https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/wrapper.py#L1288

* CMD_THREAD_RUN : https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/wrapper.py#L1291

* CMD_PYDEVD_JSON_CONFIG : https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/wrapper.py#L1211

* CMD_VERSION : https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/wrapper.py#L1214

* CMD_RUN: https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/wrapper.py#L1180

**Comment by fabioz** [comment]
@karthiknadig 

It seems some of those can just have the behavior moved to `pydevd` and some already have counterparts.

`cmd_redirect_output` should be just moving that to `on_disconnect` on `pydevd`.

`cmd_thread_run` can just be changed for a `continue request` .

`cmd_pydevd_json_config` can be moved to `_PyDevJsonCommandProcessor._set_debug_options`.

`cmd_version` the client OS can probably set in the `setDebuggerProperty` request.

`cmd_run` should not be needed (doing a `configurationDone` request already starts running the process in `pydevd`), so, I think just removing that code should be Ok.

Let me know if you need help with something there.

**Comment by karthiknadig** [comment]
I don't see wrapper calling pydevd for config Done. We should add that request when removing cmd_run.

**Comment by karthiknadig** [comment]
@fabioz See `_ensure_pydevd_requests_handled` is that really needed? I see that we are setting cmd_version in two places in the wrapper. I feel like the one in is the only one we need.

**Comment by fabioz** [comment]
Well `_ensure_pydevd_requests_handled` seemed to be mostly about the shortcomings of `pydevd` not sending acknowledgement of breakpoints, but now that `pydevd` supports the DAP that doesn't seem needed anymore (as there's a confirmation for the breakpoints from `pydevd` now).
