### ISSUE TITLE
Incorrect Information of starting server for Pyramind debugging.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1421]
@zhouwangyang commented on [Mon Apr 22 2019](https://github.com/microsoft/vscode-python/issues/5400)

Visual Studio Code - Insiders: 1.34.0-insider
python-insider: 2019.4.6962-rc

repro step:
1.Open folder in VSC and create virtual envrionment 
2.Set virtual environment as current environment.
3.Select debugging configuration "Pyramid" 
4.Press F5 to start debugging

except result:
1.Starting server information should show in terminal as this: **Serving on http://localhost:6543/**, and this should a link and user can click it to turn to Brower
2.Only one message is displayed for the same message

actual result:
Repeated display information and server Info was not link.
![image](https://user-images.githubusercontent.com/39871640/56492857-9b92ee00-651f-11e9-9ecf-c43b6f076613.png)

**Comment by fabioz** [comment]
Hi @zhouwangyang -- can you share your launch config to make sure we're seeing the same thing?

If you run that command out of VSCode, do you still have the 2 messages?

@DonJayamanne the link in the terminal must be created by VSCode (and not through ptvsd) right?

**Comment by karthiknadig** [comment]
@fabioz that is correct. We don't need to do anything specific in `ptvsd` to create a link here.

**Comment by karthiknadig** [comment]
Please reopen when more information is available.

**Comment by zhouwangyang** [comment]
this issue reproed in this environment:
![image](https://user-images.githubusercontent.com/39871640/62856469-97394d80-bd27-11e9-9140-258fc78f37c4.png)
![image](https://user-images.githubusercontent.com/39871640/62856592-eaab9b80-bd27-11e9-9e0f-8ab4542cab5c.png)
