### ISSUE TITLE
sys.stdin.read never returns when terminal set to raw mode 

### ISSUE THREAD

**Issue by sgorestodd** [microsoft/ptvsd#1423]
## Environment data

- PTVSD version: 4.2.9
- OS and version: Kubuntu Linux kernel 5.0
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3
- Using VS Code or Visual Studio: VS Code

## Actual behavior

sys.stdin.read never returns, even if Enter key is pressed. This is only if the terminal is set to raw mode. Otherwise it works normally.

## Expected  behavior

sys.stdin.read should return characters that have been entered into stdin while in raw mode. This is a popular method of reading single characters without newlines in Linux as can be seen in these stackoverflow posts.

[Python read a single character from the user](https://stackoverflow.com/questions/510357/python-read-a-single-character-from-the-user)
[Reading a single character (getch style) in Python is not working in Unix](https://stackoverflow.com/questions/1052107/reading-a-single-character-getch-style-in-python-is-not-working-in-unix)

## Steps to reproduce:
1. Toggle character reading via the short program below.

```import os
import sys
import termios
import tty

fd = sys.stdin.fileno()
old_settings = termios.tcgetattr(fd)
tty.setraw(fd)
# ch = os.read(fd, 1)           # Works
# ch = sys.stdin.buffer.read(1) # Works
ch = sys.stdin.read(1)          # Never returns!
print(ch)
termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
```
2. Run the program in the integrated terminal with launch.json settings as below.

```{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal"
    }
  ]
}
```

**Comment by fabioz** [comment]
I'll investigate.
