### ISSUE TITLE
variable not updating in debug pane when using debug console

### ISSUE THREAD

**Issue by asaflotz** [microsoft/ptvsd#1424]
## Environment data

- PTVSD version: XXX
- OS and version: XXX
- Python version (& distribution if applicable, e.g. Anaconda): XXX
- Using VS Code or Visual Studio:

## Actual behavior

XXX

## Expected  behavior

XXX

## Steps to reproduce:
1. XXX

**Comment by int19h** [comment]
Looks like a dupe of #1356.

**Comment by karthiknadig** [comment]
This is the bug you can track in the extension for this issue:
https://github.com/microsoft/vscode-python/issues/5250
