### ISSUE TITLE
Naming source file `code.py` breaks ptvsd attach mode

### ISSUE THREAD

**Issue by s-kovacevic** [microsoft/ptvsd#1428]
## Environment data

- PTVSD version: 4.2.9
- OS and version: macOS 10.14.4 (also reproduced in a `python:3.7-alpine` docker container)
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.7
- Using VS Code or Visual Studio: VSCode (but it doesn't matter actually)

## Actual behavior
Having a module called `code.py` in the same directory as module containing `ptvsd.enable_attach()` raises an exception. Package named `code`  or having `code.py` in a package has no negative effects.
It seems to me that there is a namespacing issue and ptvsd tries to import `InteractiveConsole` from my `code` module.

```
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevconsole.py", line 9, in <module>
app_1    |     from code import InteractiveConsole
app_1    | ImportError: cannot import name 'InteractiveConsole' from 'code' (/usr/src/app/code.py)
```
This is the exception that I cherry-picked, there are actually multiple chained exceptions, [here is the full traceback](https://pastebin.com/HJdygMxa).

## Expected  behavior
No exception.

## Steps to reproduce:
1. Have a file structure like this:
```
.
├── app.py
├── code.py
└── venv
```
in `app.py`:
```
import ptvsd
ptvsd.enable_attach()
```
`code.py` can be left empty.

2. Run `app.py`

**Comment by fabioz** [comment]
This happens because `code` is a python standard library module upon which the debugger relies, so, the actual solution is not shadowing the `code` standard library modules in your own code (i.e.: rename your own module to something else) -- the debugger itself relies on being able to use the standard library.
