### ISSUE TITLE
Update SetDebuggerProperty arguments in debugProtocolCustom.json

### ISSUE THREAD

**Issue by fabioz** [microsoft/ptvsd#1430]
We should change debugProtocolCustom.json and update the protocol-related classes for the `setDebuggerProperty` arguments -- we should be accessing by attributes in the arguments in `on_setdebuggerproperty_request` (checking for None if it's optional) instead of checking kwargs in the arguments (and change those properties to camelCase).

**Comment by karthiknadig** [comment]
Fixed via https://github.com/microsoft/ptvsd/pull/1431
