### ISSUE TITLE
Venv, debugging, pythonpath broken

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1440]
@ST33LDI9ITAL commented on [Sun May 19 2019](https://github.com/microsoft/vscode-python/issues/5690)

## Environment data

- VS Code version: 1.35.0-insider
- Extension version (available under the Extensions sidebar): 2019.4.12954
- OS and version: Win 10x64 10.0.17763
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.7.3 and WinPy 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv 
- Relevant/affected Python packages and their versions: XXX

## Expected behaviour

Venv to be detected and activated
Debugging to work with venv

## Actual behaviour

Doesn't detect or activate venv
Debugging doesn't work with venv, no breakpoints trip

## Steps to reproduce:
1. Set python path to "python.pythonPath": "${workspaceFolder}\\Scripts\\python.exe", 
Open python venv project folder, open any file, set breakpoints, run debug

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
##########Linting Output - pylint##########

--------------------------------------------------------------------

Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)



[Info  - 8:03:49 PM] GetCurrentSearchPaths c:\Dev\Python\examples\Scripts\python.exe 
[Info  - 8:03:49 PM] Python search paths:
[Info  - 8:03:49 PM]     c:\python\winpy\python-3.7.2.amd64\dlls
[Info  - 8:03:49 PM]     c:\python\winpy\python-3.7.2.amd64\lib
[Info  - 8:03:49 PM]     c:\python\winpy\python-3.7.2.amd64
[Info  - 8:03:49 PM]     c:\dev\python\examples
[Info  - 8:03:49 PM]     c:\dev\python\examples\lib\site-packages
[Info  - 8:03:49 PM] Configuration search paths:
[Info  - 8:03:53 PM] Microsoft Python Language Server version 0.2.82.0
[Info  - 8:03:53 PM] Initializing for c:\Dev\Python\examples\Scripts\python.exe
```

```


---

@webji commented on [Sun May 19 2019](https://github.com/microsoft/vscode-python/issues/5690#issuecomment-493829939)

Same issue:

Version: 1.35.0-insider (system setup)
Commit: 6ac87465f297a9068bf767f45d6f372fc5697de9
Date: 2019-05-17T17:48:07.036Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763



---

@DonJayamanne commented on [Mon May 20 2019](https://github.com/microsoft/vscode-python/issues/5690#issuecomment-494077472)

Issue moved to [microsoft/ptvsd #1439](https://github.com/microsoft/ptvsd/issues/1439) via [**ZenHub**](https://www.zenhub.com/)

**Comment by karthiknadig** [comment]
@ST33LDI9ITAL Set `"justMyCode": false` in your launch configuration. That should help with this issue. Let me know if that does not work.

**Comment by ST33LDI9ITAL** [comment]
Thanks, that was driving me crazy, it works.. but, how can I set that to automatically generate for "Python: Current File" auto generated debug config? I added it to default.launch.json but default.launch.json doesn't have "Python: Current File". Seems it's generated per workspace folder. So basically, how can I get it auto generated to the workspace folder debug config so I don't have to add that manually every time??

**Comment by karthiknadig** [comment]
@ST33LDI9ITAL you should not have to use that flag. The reason you ran into this issue was due to the fact that we are still fine tuning that particular feature. Try `ptvsd==v4.2.10` we made some changes to handle `venv` specific scenario in the debugger. That version will likely ship in the next release of the python extension.

@DonJayamanne Can you answer the the `default.launch.config` question?

**Comment by DonJayamanne** [comment]
Please copy the `Python Current File` configuration `json` from the workspace `launch.json` into the `default.launch.config`

**Comment by ST33LDI9ITAL** [comment]
Ok, thank you for the help and for your work, looking forward to next release.

**Comment by ST33LDI9ITAL** [comment]
Whenever I add block or config to default.launch.config it doesn't register in drop down list.

**Comment by karthiknadig** [comment]
I am closing this issue since the `ptvsd` side of this has been addressed.

@ST33LDI9ITAL you may want to open a new issue in the extension repo to address the config bug.
