### ISSUE TITLE
Debug is adding extra white space/carriage returns

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1442]
@walkingbytrees commented on [Sat May 18 2019](https://github.com/microsoft/vscode-python/issues/5680)

Issue Type: Bug

I can't figure out why I'm getting extra white space between my output. If I code for a space with " ", I get a line break. No idea how to find a solution.

VS Code version: Code 1.33.1 (51b0b28, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

Here's what it looks like on my screen:
![Screen Shot 2019-05-16 at 1 24 17 PM](https://user-images.githubusercontent.com/30348663/57968281-0a544300-7936-11e9-8358-9d3b4ffd77e6.png)

Extension | Author (truncated) | Version
-- | -- | --
anaconda-extension-pack | ms- | 1.0.1
python | ms- | 2019.4.12954
vscode-yaml | red | 0.4.0

**Comment by karthiknadig** [comment]
@walkingbytrees Can you get the debugger logs for this? You can get the debugger logs by setting this environment variable `PTVSD_LOG_DIR`. Like this:

```js
{
    "name": "Terminal",
    "type": "python",
    "request": "launch",
    "pythonPath": "${config:python.pythonPath}",
    "program": "${file}",
    "cwd": "${workspaceFolder}",
    "console": "integratedTerminal",
    "env":{
        "PTVSD_LOG_DIR": "<path to logs directory>"
    }
},
```

**Comment by fabioz** [comment]
I just checked here... this was a problem in VSCode itself (I reproduced in 1.33.1 and verified that it doesn't reproduce on 1.34.0), so, closing this issue.
