### ISSUE TITLE
it doesnt go in other files not added into workspace when debugging.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1467]
@byehack commented on [Fri May 24 2019](https://github.com/microsoft/vscode-python/issues/5752)

in debugging when i want to "jump into" i need to go to the some modules thats are not in my project.

**Comment by karthiknadig** [comment]
@byehack We treat files in your workspace as user code and everything outside of it as library code. there are two ways to fix this issue.
* **Option 1 :** Add `"justMyCode": false` in launch.json. This has the side effect that it will now include any loaded python file while stepping.
```js
{
    "name": "Terminal",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "justMyCode": false,
},
```
* **Option 2**: Add rules to include directories and files. with this option you can specifically include the external files or directories. This will continue to exclude any standard library files or paths that you don't include.
```js
{
    "name": "Terminal",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "rules": [
        {"path": "<path to directory/glob pattern>", "include": true}, // To include directory, file, or pattern
        {"path": "<path to directory/glob pattern>", "include": false}, // To exclude directory, file, or pattern
    ],
},
```

**Comment by fabioz** [comment]
I'm closing this one as this should be expected and the comments from @karthiknadig should solve the issue (please reopen if they don't).

As a note, https://github.com/microsoft/ptvsd/issues/1298 is already tracking notifying about that and giving instructions, so, there's not much more to be done in this issue.
