### ISSUE TITLE
Change references from debugStdLib to justMyCode internally (keeping backward compatibility).

### ISSUE THREAD

**Issue by fabioz** [microsoft/ptvsd#1469]

**Comment by karthiknadig** [comment]
Note that for now. VSC itself is doing this translation. I recommend we do this along with https://github.com/microsoft/ptvsd/issues/1219. All settings should either happen via launch json or via `setDebuggerProperties`. We should not have to parse and extract settings like we do now.

**Comment by int19h** [comment]
We're doing the rewriting in the extension - pydevd is still only accepting "debugStdLib", so far as I can tell (but some error messages reference "justMyCode").

**Comment by int19h** [comment]
@fabioz, since  #1219 is done, can you take a look at this one, as well? It just needs an alias.

**Comment by fabioz** [comment]
I'm taking a look at this.
