### ISSUE TITLE
cannot debug python use cur file configuration

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1470]
@yang200050 commented on [Sun May 26 2019](https://github.com/microsoft/vscode-python/issues/5789)

- VS Code version: 1.34.0
- Extension version: 2019.4.12954
- OS and version: win10
- Python version: python 2.7.14

issue:when i start debug python cur file use Start Debugging(F5), it cannot debug. The traceback is:
**Traceback (most recent call last):
  File "c:\Users\刘洋\\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\ptvsd_launcher.py", line 43, in <module>**
after i debugging ptvsd, i found the Traceback start from:ptvsd/wrapper.py(line 86) 
the reason is ascii codec can't decode byte.because my path string is not utf-8.
i changed the function code as below to let the debug run.It is only a temporary solution.
![微信截图_20190527025326](https://user-images.githubusercontent.com/13652549/58385937-ce526980-802a-11e9-9961-0d477b6a7b8f.png)
please solve this kind of issues.
by the way: how to change the default extension download directory.

**Comment by karthiknadig** [comment]
@yang200050 Can you provide the result of this in your environment?
```py
print(sys.getfilesystemencoding())
```

**Comment by yang200050** [comment]
@karthiknadig 
sys,getfilesystemencoding():mbcs
sys.getdefaultencoding():ascii
locale.getdefaultlocale(): ('zh_CN', 'cp936')
locale.getpreferredencoding(): cp936

**Comment by karthiknadig** [comment]
@yang200050 This code path has changed since then. If this continue to be a issue please reopen.
