### ISSUE TITLE
launch.json arg that begins with a '#' char is treated as an actual comment

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1474]
@warrenstephens commented on [Fri May 24 2019](https://github.com/microsoft/vscode-python/issues/5758)

## Environment data

- VS Code version: 1.34.0
- Extension version (available under the Extensions sidebar): Python 2019.4.12954
- OS and version: Mac Mojave 10.14.5
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.4 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): not virtual
- Relevant/affected Python packages and their versions: n/a

## Expected behaviour

I am getting the sys.argv list the way shown (2nd arg thru the end of the list), but I can see the issue directly in sys.argv in the debugger.

    arg_list = (sys.argv[2:] if len(sys.argv)>2 else [])

I would expect that the "#midweek" arg would be in the sys.argv list, but it and the subsequent "2019-05-20" arg are not there.  It is like the '#' char _within_ the string is being treated as an actual python comment character.

        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args":[
                "hestia",
                "mdv-armadillo-production",
                "day",
                "#midweek",
                "2019-05-20"
            ]
        },

arg_list is:
0: 'mdv-armadillo-production'
1: 'day'

and nothing else.

## Actual behaviour

If I change the '#' character to "//" then the args are all available in sys.argv.

       {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args":[
                "hestia",
                "mdv-armadillo-production",
                "day",
                "//midweek",
                "2019-05-20"
            ]
        },

arg_list is:
0: 'mdv-armadillo-production'
1: 'day'
2: '//midweek'
3: '2019-05-20'

## Steps to reproduce:

Make the changes to launch.json for the 2 cases shown above, assign the sys.argv list to a variable.

In my case specifically, I am using the following assignment:

    arg_list = (sys.argv[2:] if len(sys.argv)>2 else [])

to get the 2nd thru last args.

**Comment by karthiknadig** [comment]
@DonJayamanne @warrenstephens This looks like a issue with how the arguments are passed to python itself.
![image](https://user-images.githubusercontent.com/3840081/58851398-7b3e6f00-8647-11e9-80fe-bf2aab9c416f.png)

you could fix this in launch json by passing the args like this:
```js
        {
            "name": "Terminal",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args":[
                "hestia",
                "mdv-armadillo-production",
                "day",
                "'#midweek'",
                "2019-05-20"
            ],
        },
```

**Comment by karthiknadig** [comment]
Reopened the original issue on the extension.
