### ISSUE TITLE
pydev debugger: warning: trying to add breakpoint to file that does not exist

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1481]
@mswarrow commented on [Thu May 30 2019](https://github.com/microsoft/vscode-python/issues/5839)

## Environment data

- VS Code version: 1.34.0
- ms-python.python: 2019.5.17059
- OS and version: Windows 10, Ubuntu 16.04
- Python version: 3.6.7 (Windows) and 2.7.12 (Ubuntu)
- Type of virtual environment used: N/A

## Expected behaviour

Python debugger is expected to hit breakpoints set in VS Code.

## Actual behaviour

When starting debugging (F5), the code is executed without stopping at the set breakpoints. The corresponding warnings appear in Python Debug Console.

## Steps to reproduce:
1. Consider the following Python project, consisting of a single - for simplicity - script, but placed in a workspace subfolder.
```
project/
  subfolder/
     script.py
     simple.json
```
2. Let the scrpit read the JSON file.
```json
import json

json.load(open('simple.json')
```
3. In order to debug script.py from the project folder, create this configuration in launch.json.
```json
{
     "name": "Python: script.py",
     "type": "python",
     "request": "launch",
     "program": "${workspaceFolder}/subfolder/train.py",
     "console": "integratedTerminal",
     "cwd": "${workspaceFolder}/subfolder"
}
```
Note: ```cwd``` parameter is set so that ```json.load``` can read simple.json
4. Set a breakpoint and start debugging. The script runs without hitting the breakpoint and showing the warning message below.

## Logs
```
pydev debugger: warning: trying to add breakpoint to file that does not exist: c:\path\to\project\subfolder\subfolder\script.py (will have no effect)
```

## Notes
So, it looks like ```program``` and ```cwd``` are combined together for pydev, but the script itself executes correctly.

Strangely, this project structure and this launch configuration worked for me for a couple of days (with VS Code installed using Ubuntu's ```sudo snap install --classic code``), but it stopped working today (after I reinstalled VS Code from a .deb package manually)

**Comment by DonJayamanne** [comment]
@karthiknadig Adding `P0` label as this is a regression in the latest release of the  extension. We'll need a fix for a point release or we might have to consider rolling back based on the severity of the issue.

**Comment by karthiknadig** [comment]
This is a extension issue. See for root cause, and temp solution. https://github.com/microsoft/ptvsd/issues/1480#issuecomment-497392812
