### ISSUE TITLE
Add tests for path mappings in launch request

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1484]
## Environment data

- PTVSD version: N/A
- OS and version: N/A
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When passing path mappings of `.` -> `${workspaceFolder}` and having a `cwd` in `launch.json`, then debugger fails to attach breakpoints.

## Expected  behavior

Adding breakpoints should work.

## Steps to reproduce:
1. Add a file named `hello_world.py` in a sub directory named `hello`
2. Set cwd to `${workspaceFolder}/hello`
3. Add a breaktpoint to the file `hello_world.py`
4. Start debugging

PTVSD will display an error indicating the debugger cannot be set.

# Please add tests in PTVSD to handle this situation.

**Comment by DonJayamanne** [comment]
Closing, no point adding tests in PTVSD

**Comment by karthiknadig** [comment]
What is the test supposed to validate? In this case the settings passed were incorrect, if the client and server are on the same machine. But this may be a perfectly valid setting when client and server are on different machines.

**Comment by DonJayamanne** [comment]
Lol race condition, 3 seconds off...
