### ISSUE TITLE
open() can't open a local file

### ISSUE THREAD

**Issue by mclemente** [microsoft/ptvsd#1507]
@Anapo14 requested me to post this bug.

## Environment data

- PTVSD version: 2019.5.18875 (6 June 2019)
- OS and version: Windows 10 Pro 1803
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.2 64-bit
- Using VS Code or Visual Studio: VS Code

## Actual behavior
I have a Python program that reads a JSON file that is on the same folder as the program. When running the following line through the VS Code Debug:
`with open("file.json", "r") as read_file:`
It returns the following:
`FileNotFoundError: [Errno 2] No such file or directory: 'file.json'`

## Expected  behavior

When running the program through Python's IDLE, it returns no errors.
The bug isn't related to JSON, as it happens to any file.

## Steps to reproduce:
1. Have the following program (Test.py):
```
with open("test.txt", "r") as read_file:
        pass
```
2. Have a test.txt file in the same folder (being empty or not doesn't change the behavior).
3. Run the program on both VS Code and IDLE. On VS Code, it'll return the error above. On IDLE, it'll run without any errors.

**Comment by int19h** [comment]
How does your `launch.json` look like? There's a setting there for current working directory in which the program is going to be run. By default, it's set to your workspace folder. So if you're running a script from a subfolder, the current directory is still going to be the top of the workspace.

**Comment by mclemente** [comment]
```
"configurations": [
                {
                        "name": "Python: Current File",
                        "type": "python",
                        "request": "launch",
                        "program": "${file}",
                        "console": "integratedTerminal"
                }
        ]
```
So that was the problem! Changing the cwd to ${fileDirname} fixed it.
I've tried changing it before but somehow was having problem with it (I've probably tried changing program to `"program": "${fileDirname}\\${fileBasename}"`, which didn't help it at all.
