### ISSUE TITLE
Refactor test layout to match the new package layout

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1510]
We need to cleanly separate ptvsd tests for common stuff, adapter, debug server, and testing infrastructure. New layout:

- tests/
(test helpers)
- tests/ptvsd/
(nothing here)
- tests/ptvsd/common/
(tests for `ptvsd.common`)
- tests/ptvsd/adapter/
(tests for `ptvsd.adapter`)
- tests/ptvsd/server/
(tests for `ptvsd.server`)
- tests/tests/
(tests for test helpers)

**Comment by karthiknadig** [comment]
This move is done. I think we should close this item and open new one to address the running issues.

**Comment by karthiknadig** [comment]
I updated the estimate to reflect the actual amount of time it took.
