### ISSUE TITLE
Handing events from pydevd that use `pydevd_cmd_id` in json

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1523]
These are events that are handled via `pydevd_events.handler` in `wrapper.py`. the json for these events has `pydevd_cmd_id` in addition to event name. In some cases where there isn't a DAP equivalent there may not be a event name.

**Comment by karthiknadig** [comment]
For this I think we will need translation from `pydevd_cmd_id` should be translated to command name. Then we can have `pydevd_<cmd_name>_event` in `ServerMessages`.

**Comment by int19h** [comment]
Do those messages omit the name entirely? Or do they have both name and ID?

**Comment by karthiknadig** [comment]
This is how the message looks like:
```js
{
 "type": "event",
 "event": "stopped",
 "body": {
 "reason": "breakpoint",
 "threadId": 1,
 "preserveFocusHint": false,
 "allThreadsStopped": true
 },
 "seq": 18,
 "pydevd_cmd_id": 157
 }
```

**Comment by int19h** [comment]
This one would be just `stopped_event` then.

Are there any cases where they only have an ID, but not a name?

**Comment by karthiknadig** [comment]
CMD_INPUT_REQUESTED That one does not have an equivalent name. I am not sure what is the name in that case. That is the one that got me thinking about this.
