### ISSUE TITLE
debugger cache

### ISSUE THREAD

**Issue by loftusa** [microsoft/ptvsd#1528]
I'm not sure if there's a way to do this that I just haven't found

I have a data analysis pipeline written in Python that takes a long time to run, and every time I set a breakpoint near the end of the program it takes 10 minutes to get to that point.

It would be nice to see a cache for the debugger, such that you only have to run a long program once, and then you can debug parts near the end without having to wait 10 minutes for each debugging session to start.

Not sure if there's already a way to do this or how technically feasible it is :)

**Comment by karthiknadig** [comment]
@loftusa  Can you clarify this?

> every time I set a breakpoint near the end of the program it takes 10 minutes to get to that point.

Particularly, does it take 10 mins to reach that point when you run it directly like `python script.py`. Or it takes that long only when running under debugger. Also, do you see a difference with or without break-point set.

**Comment by karthiknadig** [comment]
@loftusa In the master branch of the debugger we have a feature that allows you to enable or disable tracing as needed.
```py
ptvsd.tracing(False) # Turn off tracing

# Tracing will be turned off function called here

ptvsd.tracing(True) # Turn on tracing
```

**Comment by karthiknadig** [comment]
Please reopen with more details if this is not enough.
