### ISSUE TITLE
Why breakpoint can't used in last release?

### ISSUE THREAD

**Issue by oOTnTOo** [microsoft/ptvsd#1533]
## Environment data

- VS Code version: 1.35.1
- Extension version (available under the Extensions sidebar): 2019.5.18875
- OS and version: win10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.0
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

breakpoint in main thread is ok,but in other thread is invaild,program can't breaking in breakpoint.

## Logs
launch config:
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python: 当前文件",
			"type": "python",
			"request": "launch",
			"program": "${file}",
			"console": "integratedTerminal",
			"args": [
				"1",
				"2",
			]
		}
	]
}

**Comment by karthiknadig** [comment]
@oOTnTOo can you provide a minimal repro?

**Comment by int19h** [comment]
Might be that issue with `breakpoint()` being on the last line in the block.

@oOTnTOo, in addition to sharing the code, can you also try sticking e.g. `()` - just like that, on a single line all by itself - immediately after `breakpoint()`, and see if that does anything for you?

**Comment by oOTnTOo** [comment]
![image](https://user-images.githubusercontent.com/31060590/60151792-b2500c80-9810-11e9-8b0f-a35c0dc25d76.png)
look this，the program is running，but breakpoints doesn't work, and it's in other thread。
when I am press F6:
![image](https://user-images.githubusercontent.com/31060590/60151936-36a28f80-9811-11e9-817e-3ff52c7687d6.png)
its break this, means program use this code, but breakpoint doesn't work.
In main thread, breakpoint is normal:
![image](https://user-images.githubusercontent.com/31060590/60152013-81bca280-9811-11e9-8254-5b1b4aa9fb31.png)
this is bug or unsupport?

**Comment by oOTnTOo** [comment]
Oh, i am use Pyqt5 lib in this program

**Comment by int19h** [comment]
At the moment, you need to call `ptvsd.debug_this_thread()` on your background thread, as soon as it starts.

Unfortunately, for threads that aren't started via Python itself (i.e. `threading` module), the debugger currently cannot do so automatically.

**Comment by oOTnTOo** [comment]
> At the moment, you need to call `ptvsd.debug_this_thread()` on your background thread, as soon as it starts.
> 
> Unfortunately, for threads that aren't started via Python itself (i.e. `threading` module), the debugger currently cannot do so automatically.

It works thank you.

before use ptvsd.debug_this_thread() should:
import ptvsd
