### ISSUE TITLE
Script to clean up development artifacts for local testing

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1535]
When working on ptvsd development, it's not uncommon to run into issues such as #1531 that have to do with various Python artifacts (.pyc / .pyo cached bytecode, .pyd modules in pydevd, pytest and tox caches etc) getting stale in a way that is not recoverable by the tools.

We need to have a dev cleanup script in the repo that takes care of all this, giving a "clean slate". It can't just blow away all files that aren't in the repo - this needs to be a targeted blacklist of stuff to delete.

Might also be good to wire that into https://code.visualstudio.com/docs/editor/tasks

**Comment by gramster** [comment]
Done
