### ISSUE TITLE
attach_socket_import tests hang waiting for "process" event

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1552]
(https://github.com/microsoft/ptvsd/tree/dbg_adapter_refactor)

When running multiple tests with `start_method` set to `attach_socket_cmdline` or `attach_socket_import`, subsequent tests fail because they cannot reuse the port number. It looks like ptvsd is not getting shut down properly, or the next test starts running before ptvsd exits. 

Estimate is uncertain, because this needs to be investigated to determine the root cause.

Only happens on Python 2.7.

**Comment by int19h** [comment]
I misindentified the root cause. This is actually a consistent issue in all tests that use `start_method="attach_socket_import"`. For some as yet unclear reason, this gets ptvsd into such a condition whence the "process" DAP event never gets reported. And the implementation of `debug.Session` expects that event in `handshake()`.

Thus, the test hangs, and eventually times out. But debuggee process is still out there, and it still has the debug server in it listening on a port. Thus, the next test that does any form of "attach_socket" will fail because the port it needs is hogged.

The problem itself is specific to "attach_socket_import", though - "attach_socket_cmdline" works fine by itself. The only reason why cmdline was failing is because of the port being in use.

**Comment by fabioz** [comment]
As a note, on pydevd I use a new port for each new test... Seeing the way that the port is gotten on ptvsd tests (`get_unique_port` in `helpers.py`), I think it's possible that the port being gotten from the `PYTEST_XDIST_WORKER` could be a port we can't really use (and it could be making tests fail).

As a reference, the way that `pydevd` uses to get new ports is in: `pydev_localhost.py - get_socket_name`.

**Comment by int19h** [comment]
The port logic itself shouldn't result in any clashes, because every worker uses its own distinct port, and every worker runs tests sequentially on that port.

This bears out in practice - DebugSession can connect to ptvsd, and starts talking to it. It also starts talking to pydevd, and e.g. successfully sets protocol to JSON. It breaks down sometime after, once it gets to handling "attach".
