### ISSUE TITLE
PTVSD port not opend when FLASK use debug mode on.

### ISSUE THREAD

**Issue by kssim** [microsoft/ptvsd#1560]
## Environment data

- PTVSD version: 4.2.10
- OS and version: "python:3.6.5-slim-stretch" container in docker (Debian 9, 4.9.125-linuxkit)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5
- Using VS Code or Visual Studio: VS Code 1.35.1

## Actual behavior
PTVSD port is opend.

## Expected  behavior
PTVSD port is not opend.

## Steps to reproduce:
1. Make the sample flask code.
  - In this case, I get the sample code as "remote-debugging-flask" in "vscode-python-sample"
    - URL : https://github.com/DonJayamanne/vscode-python-samples.git
2. Fix the some configuration and code.
  - app.py
```Python
import ptvsd
ptvsd.enable_attach(address=('0.0.0.0', 3500))

from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello():
    return "Hello World!"

if __name__ == '__main__':
    app.run()
```

  - .env
```bash
FLASK_APP="app.py"
FLASK_ENV="development"
FLASK_DEBUG=True
FLASK_RUN_PORT=8000
```
3. Run the flask server and check the open port.
```bash
# flask run
 * Serving Flask app "app.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 989-143-182

(use another console)
# lsof -i
COMMAND   PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
flask   55916 root    3u  IPv4 6410027      0t0  TCP localhost:8000 (LISTEN)
python  55919 root    3u  IPv4 6410027      0t0  TCP localhost:8000 (LISTEN)
python  55919 root    4u  IPv4 6410027      0t0  TCP localhost:8000 (LISTEN)
```
4. Check the PTVSD debug port is not opened.

5. Change the flask debug mode in env file to false.
  - .env
```bash
FLASK_APP="app.py"
FLASK_ENV="development"
FLASK_DEBUG=False
FLASK_RUN_PORT=8000
```

6. Run the flask server and check the open port.
```
# flask run
 * Serving Flask app "app.py"
 * Environment: development
 * Debug mode: off
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)

(use another console)
# lsof -i
COMMAND   PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
flask   55930 root    7u  IPv4 6411880      0t0  TCP *:3500 (LISTEN)
flask   55930 root    9u  IPv4 6411881      0t0  TCP localhost:8000 (LISTEN)
```

7. Check the PTVSD debug port is opened.

**Comment by karthiknadig** [comment]
@kssim can you share your launch json?

**Comment by kssim** [comment]
Sure, bus VS Code is not work,
because the remote machine(docker container) has not opened debug port.
And launch command is "flask run".
That command works with ".env" configuration file.

* VS Code launch json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 3500,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}/[Actual Code Dir]",
                    "remoteRoot": "[Actual Code Dir]"
                }
            ]
        }
    ]
}
```

**Comment by karthiknadig** [comment]
Try these steps and let me know if somethig doesn't work:

1. remove `ptvsd` from your app.py, use the code below. We will use `ptvsd` command line to do this. Ensure that you do the `set_start_method`. See here for why and that will not be needed soon https://github.com/microsoft/ptvsd/blob/master/TROUBLESHOOTING.md#1-multiprocessing-on-linuxmac

```py
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello():
    return "Hello World!"

if __name__ == '__main__':
    import multiprocessing
    multiprocessing.set_start_method('spawn', True)
    app.run()
```

2. Use this command line to launch your app. After setting all the environment variables.
```
python3 -m ptvsd --host 0.0.0.0 --port 3500 --multiprocess --wait -m flask run
```

3. Use this for your launch json:
```js
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 3500,
            "host": "localhost",
            "jinja": true,
            "subProcess": true,
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ],
        },
```

**Comment by kssim** [comment]
Thank you for your kind and fast answer.

I thinks your answer is maybe works.
I went to Step 2 and it worked.
But, There is a problem in Step 3.
When I attaching Debug in VS Code, Flask is working and I'm getting an error right away.

Error is <code>Failed to attach (connect ECONNREFUSED 127.0.0.1:43320)</code>.

I know what is the problem.
Because I used the docker environment, and I need to open the port in container.

I tried to open the exact port, but I can't.
Because that port is totally random.

I tried a few time, and I saw the below errors in VS Code.

```
Failed to attach (connect ECONNREFUSED 127.0.0.1:43320)
Failed to attach (connect ECONNREFUSED 127.0.0.1:43119)
Failed to attach (connect ECONNREFUSED 127.0.0.1:34035)
```

So, if it's not a docker environment then maybe it works.

However, I have to use a docker environment and can not deal with random ports,
so I can not solve this problem with that solution.

**Comment by karthiknadig** [comment]
I see. There is one thing you can try: Use VSCode remote containers https://code.visualstudio.com/docs/remote/containers . This will put your entire development environment inside the container.

Looks like this is one of those cases that could be addressed by: #868 or #993

**Comment by kssim** [comment]
Oh, I saw that document and tried it.
But it was not satisfactory.

If I follow the instructions in that document, I have to launch the container and run the program, but we start the program right up the container.
And there are some issues ...(Some development tools need to be installed in the docker container.)
Of course, we can accommodate them and change our production.

Hmm, So What happens to this issue?
Are you checking more? Or is it just ending here?

**Comment by int19h** [comment]
I'm a bit confused - why is the port random? You specifically set 3500 to be the port for ptvsd, so far as I can see, and 8000 as the port for Flask itself. Can't those be mapped to stable container ports?

**Comment by karthiknadig** [comment]
@kssim The issue here is basically reload in Flask. Currently the way we handle that is by running the debugger in each of the sub-processes that get launched by flask. FLASK_DEBUG=True causes flask to start these sub-processes. 

You could try running flask with `--no-reload`. But i think you will need `--no-debug` as well. For most cases you will probably not need FLASK_DEBUG. This will ensure that flask is running in a single process and you will only need the flask port and debug port exposed from the container. 
```
python3 -m ptvsd --host 0.0.0.0 --port 3500 --multiprocess --wait -m flask run --no-reload --no-debug
```

Note that you can debug flask internals by setting `"justMyCode": false` in your launch json.

Until #868 or #993 is addressed this is a limitation of the current version of the debugger.

**Comment by kssim** [comment]
@int19h I don't know why the port is randomly assigned.
I specifically set 3500 and 8000 for PTVSD and Flask. And I set those config in my docker-compose file.
Hmm.  I don't know what exactly mean "Can't those be mapped to stable container ports?".
Can you give me a more explanation?


@karthiknadig Thank you for your kind answer.
I'll try that, and check there are no matter in my product.
Now I got it why this is happening.
I'll find out if there's another way, including <code>--no-reload</code> and <code>--no-debug</code> options.

Thanks

**Comment by int19h** [comment]
@kssim I misunderstood the scenario. In your case, because you're not using no-reload, Flask creates a separate child process that actually runs your code (which it can then kill & restart when it needs to reload). The port number you specify for ptvsd is for the parent Flask process. The child process cannot reuse the same port, and so it automatically assigns some random ephemeral port to itself. 

As @karthiknadig had said, unfortunately, this is just not a supported scenario in Docker (or other environment where you can't connect to those ephemeral ports) at the moment. But running Flask in no-reload (and possibly also no-debug - not entirely sure) mode should do the trick, if that is acceptable.

Another possibility is running the container with `docker run --network host` - this should also work, because all ports in the container will be mapped directly to the host, and then VSCode should be able to connect to that random port.

**Comment by kssim** [comment]
I figured out the way.
VS Code already use the "--no--reload" option and "--no-debug" when debugging python code with ptvsd.

This is the execute log when I run the Flask debugging with VS Code native(not docker environment).

```bash
...ptvsd_launcher.py --default --client --host localhost --port 57309 -m flask run --no-debugger --no-reload 
 * Serving Flask app "app.py"
 * Environment: development
 * Debug mode: on
```

The point is I can select Flask debug mode set on and use the above two options both.
So I thinks I'll just use the docker file with both options (--no-reload and --no-debug)

Thanks to you guys(@karthiknadig, @int19h) discussing it with me, I found a solution.
In fact, it was a simple matter to look at ...

Thank you anyway.
I think you can close this issue if you do not need it.

**Comment by int19h** [comment]
You're welcome!
