### ISSUE TITLE
Debug:Evaluate has old indent bug

### ISSUE THREAD

**Issue by YoniChechik** [microsoft/ptvsd#1570]
## Environment data

VS Code version: 1.36
Extension version (available under the Extensions sidebar): 2019.6.22090
OS and version: windows 10
Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

send selected rows to debug console that works

## Actual behaviour

![image](https://user-images.githubusercontent.com/16686924/60760713-b535d300-a042-11e9-8c05-a4c6afc85796.png)

**Comment by karthiknadig** [comment]
The shortcut part of this bug has to be addressed by the python extension.

**Comment by YoniChechik** [comment]
any news about the subject?

**Comment by YoniChechik** [comment]
another reference https://github.com/microsoft/vscode-python/issues/6680

**Comment by int19h** [comment]
@karthiknadig , this looks like it's strictly about the Python extension to me? Since ptvsd doesn't have any control over how the lines get (un)indented when they're submitted to the Debug Console from the editor. The issue in vscode-python that @YoniChechik referenced above is the one tracking it there.

**Comment by karthiknadig** [comment]
The reason i moved it over is, if a evaluate string starts with an indent should we remove the white space? It will be an indentation error anyway. and we can detect that before we execute. In the case of block of code we should be able to just dedent right?

**Comment by int19h** [comment]
Oh, I misunderstood the repro. I thought this was about sending lines one by one, but in this case they're all sent as a single multiline block to execute?

Yeah, we can make it work in this case, with the same dedent logic we currently use for `@pyfile` in the tests.

**Comment by ychechik** [comment]
hi, any new updates?
