### ISSUE TITLE
Output tests fail sporadically

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1585]
This is everything in test_output.py, and also test_log_point in test_breakpoints.py.

The problem is the same as before - ptvsd (or rather pydevd) currently doesn't guarantee that all output is flushed by the time the debuggee process exits. 

Until this can be fully fixed, we need to provide some internal hook in the debugger, specifically for the tests, which would then ensure that all pending `output` messages are flushed before exiting. Otherwise, tests will have to resort to hacks such as sleeping (which are not 100% reliable).

**Comment by int19h** [comment]
@fabioz, perhaps there's something in pydevd already that can be hooked?

**Comment by fabioz** [comment]
@int19h `pydevd` actually has something to handle this: `pydevd.CheckOutputThread`.

It's a non-daemon thread which only exits when the only threads alive are `pydevd` threads and the writer is empty.

But I know that even on `pydevd` tests it's possible that the last acknowledgement of a command is not received when the process is shutdown on tests, so, there's still some scenario which the implementation is not covering properly (but I haven't actually investigated further).

Taking a look at the code, another problem may be that `ptvsd` exits early when the socket managed by the `_pydevd_bundle.pydevd_comm.WriterThread` is closed.

p.s.: as a note, taking a look at the tests mentioned, the output is always checked after hitting a breakpoint, which is done only after all the output is printed -- aside from the `test_with_no_output` -- so, in this case I find it really strange that this is related to the process exit (or maybe I'm looking at the wrong branch?)

**Comment by karthiknadig** [comment]
This is in `dbg_adapter_refactor` branch. But the test should do the same thing (i.e., stop at the last line to get all the output events), at least for the output tests.

**Comment by int19h** [comment]
Stopping at the breakpoint doesn't guarantee that all output has been received, either, unless I'm missing something? The print statements have executed, sure... but the `output` events are still async, no? Or is there a hard guarantee that if a breakpoint is hit, then all output events have been sent?

**Comment by fabioz** [comment]
Well, on the `pydevd` side, `sys.stdout.write` should do `py_db.writer.add_command` instantly (not in a thread) and when a breakpoint is hit, it should also do `py_db.writer.add_command` to add the break to the same queue (i.e.: in `_pydevd_bundle.pydevd_comm.WriterThread`), which is processed sequentially, so, I think that in this case all output events should be sent first (unless I'm missing something). 

Can you provide a link to a failing test? (the `pydevd` log should show the order in which things are written).

**Comment by int19h** [comment]
Ah, I thought they're still added from a background thread. If it's immediate, then yeah, waiting for a breakpoint should fix it just fine.

I don't know of any test failures for this reason in the main branch (which has breakpoint stops in those tests). I just incorrectly assumed that it was a best-effort attempt to make sure the output is flushed, but that it was not 100% reliable.
