### ISSUE TITLE
Debug adapter supports the 'disassemble' request, but the debug engine does not specify that it supports disassembly

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1586]
Warning from the Debug Adapter Host logs for PTVS:
```console
WARNING: Configuration mismatch. The debug adapter supports the 'disassemble' request, but the 
debug engine does not specify that it supports disassembly.
```

@RaymonGulati1 @huguesv If the debugger is not returning anything here should the Adapter assume that `disassembly` is available? That seems wrong.

**Comment by int19h** [comment]
We're correctly reporting *not* supporting disassembly, so I don't think this is a ptvsd bug in any case. We can revisit if it causes some specific issue on VS side that needs a workaround.
