### ISSUE TITLE
Appengine breakpoints not being hit

### ISSUE THREAD

**Issue by flaker** [microsoft/ptvsd#1606]
## Environment data

- PTVSD version: 4.2.10
- OS and version: Linux - Alpine v3.8 (host) - maOS High Sierra (client)
- Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.15
- Using VS Code or Visual Studio: VS Code

This is an appengine application running in the development server. The start up command line is:

```
exec /google-cloud-sdk/bin/dev_appserver_orig.py --host 0.0.0.0 --port ${APP_PORT} \
                      --python_startup_script /app/src/www/pydev_startup.py \
                      --admin_host 0.0.0.0 --admin_port 8550 \
                      --api_host 0.0.0.0 --api_port 8551 \
                      --datastore_path=${DATASTORE_FILE} \
                      --enable_sendmail=true \
                      --require_indexes=true \
                      --skip_sdk_update_check=true \
                      --max_module_instances=1 \
                      --application=service-hrd \
                      --enable_host_checking=false \
                      --enable_console=true \
                      --log_level=${LOG_LEVEL} \
                      --watcher_ignore_re="\/app\/src\/www\/(.*)_datastore|\/app\/src\/www\/test\/(.*)|\/app\/src\/www\/frontend\/(.*)|\/app\/src\/www\/webpack_manifests\/(.*)" \
                      ${SCRIPT_DIR}/${APP_CONFIG}
```
The content for `pydev_startup.py`

```
import ptvsd
ptvsd.enable_attach(log_dir='/var/log')
print("Google App Engine has started, ready to attach the debugger")
```

## Actual behavior

A log file is created named: ptvsd-24.log
That pid belongs to:
`   24 root     20:20 /usr/bin/python /google-cloud-sdk/platform/google_appengine/_python_runtime.py /tmp/tmpLHFln2 /tmp/tmpUt3gdN`

I also see the information on the breakpoints I've set in VS Code. Like:

```
bash-4.4# head -n 60 ptvsd-24.log
I00000.009: Linux-4.9.125-linuxkit-x86_64-with x86_64
            CPython 2.7.15 (64-bit)
            ptvsd 4.2.10

I00000.009: enable_attach(('0.0.0.0', 5678), None)

D00000.009: Installing pydevd hooks.

D00000.009: Monkey-patching multiprocess functions.

D00000.010: Starting connection listener thread

D00000.011: Waiting for pydevd ...

D00000.011: pydevd.settrace()

D00000.013: Starting server daemon on ('0.0.0.0', 5678).

D00000.013: Server socket created on Address(host='0.0.0.0', port=5678, isserver=False)

D00000.016: Unblocking pydevd.

D00000.016: Getting next session...

D00000.016: Session lock acquired.

D00000.016: Getting session socket...

D00009.041: Starting session...

D00009.044: IDE <-- {
                "event": "output",
                "type": "event",
                "body": {
                    "category": "telemetry",
                    "output": "ptvsd",
                    "data": {
                        "version": "4.2.10"
                    }
                },
                "seq": 0
            }

D00009.047: Session started.

D00009.048: IDE --> {
                "command": "attach",
                "type": "request",
                "arguments": {
                    "justMyCode": true,
                    "type": "python",
                    "workspaceFolder": "/Users/fdelgadodoyle/dev/main_service/src/www",
                    "request": "attach",
                    "port": 5678,
                    "pathMappings": [
                        {
                            "localRoot": "/Users/fdelgadodoyle/dev/main_service/src/www",
                            "remoteRoot": "/app/src/www/"
                        }
                    ],
```
and some more.

It does not matter what I do, breakpoints never stop execution. It is as if I am debugging the completely wrong PID.

My launcher config:
  ```
      {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "app.mainservice.test",
            "debugOptions": [
                "Multiprocess"
            ],
            "pathMappings": [
                {
                    "localRoot": "/Users/fdelgadodoyle/dev/main_service/src/www",
                    "remoteRoot": "/app/src/www/"
                }
            ]
        },
```

## Expected  behavior
Since I managed to successfuly connect and send all the breakpoints information. Execution will trigger one of the several breakpoints

I am not sure how to properly debug this issue on my own, if you provide some pointers I am glad to help. Thanks.

**Comment by karthiknadig** [comment]
@flaker  Can you share he full debugger logs that you collected?

**Comment by flaker** [comment]
Sure.

```
I00000.009: Linux-4.9.125-linuxkit-x86_64-with x86_64
            CPython 2.7.15 (64-bit)
            ptvsd 4.2.10

I00000.009: enable_attach(('0.0.0.0', 5678), None)

D00000.009: Installing pydevd hooks.

D00000.009: Monkey-patching multiprocess functions.

D00000.010: Starting connection listener thread

D00000.011: Waiting for pydevd ...

D00000.011: pydevd.settrace()

D00000.013: Starting server daemon on ('0.0.0.0', 5678).

D00000.013: Server socket created on Address(host='0.0.0.0', port=5678, isserver=False)

D00000.016: Unblocking pydevd.

D00000.016: Getting next session...

D00000.016: Session lock acquired.

D00000.016: Getting session socket...

D00009.041: Starting session...

D00009.044: IDE <-- {
                "event": "output", 
                "type": "event", 
                "body": {
                    "category": "telemetry", 
                    "output": "ptvsd", 
                    "data": {
                        "version": "4.2.10"
                    }
                }, 
                "seq": 0
            }

D00009.047: Session started.

D00009.048: IDE --> {
                "command": "attach", 
                "type": "request", 
                "arguments": {
                    "justMyCode": true, 
                    "type": "python", 
                    "workspaceFolder": "/Users/fdelgadodoyle/dev/main_service/src/www", 
                    "request": "attach", 
                    "port": 5678, 
                    "pathMappings": [
                        {
                            "localRoot": "/Users/fdelgadodoyle/dev/main_service/src/www", 
                            "remoteRoot": "/app/src/www/"
                        }
                    ], 
                    "name": "Python: Remote Attach", 
                    "host": "app.mainservice.test", 
                    "showReturnValue": true, 
                    "__sessionId": "42c6d01a-4b87-4c0f-9c6f-8c8b90dd408a", 
                    "debugOptions": [
                        "Multiprocess", 
                        "RedirectOutput", 
                        "UnixClient", 
                        "ShowReturnValue"
                    ]
                }, 
                "seq": 2
            }

D00009.062: (while handling {u'command': u'attach', u'type': u'request', u'seq': 2})
            PYD <-- CMD_SET_PROTOCOL 1000000000 json

D00009.063: (while handling {u'command': u'attach', u'type': u'request', u'seq': 2})
            IDE <-- {
                "type": "response", 
                "request_seq": 2, 
                "body": {}, 
                "seq": 1, 
                "success": true, 
                "message": "", 
                "command": "attach"
            }

D00009.064: IDE --> {
                "command": "initialize", 
                "type": "request", 
                "arguments": {
                    "supportsVariablePaging": true, 
                    "clientID": "vscode", 
                    "pathFormat": "path", 
                    "columnsStartAt1": true, 
                    "adapterID": "python", 
                    "clientName": "Visual Studio Code", 
                    "linesStartAt1": true, 
                    "supportsRunInTerminalRequest": true, 
                    "supportsVariableType": true, 
                    "locale": "en-us"
                }, 
                "seq": 1
            }

D00009.065: (while handling {u'command': u'initialize', u'type': u'request', u'seq': 1})
            IDE <-- {
                "type": "response", 
                "request_seq": 1, 
                "body": {
                    "supportsGotoTargetsRequest": true, 
                    "supportsHitConditionalBreakpoints": true, 
                    "supportsSetExpression": true, 
                    "supportsCompletionsRequest": true, 
                    "supportsDelayedStackTraceLoading": true, 
                    "supportTerminateDebuggee": true, 
                    "supportsConfigurationDoneRequest": true, 
                    "supportsExceptionOptions": true, 
                    "supportsDebuggerProperties": true, 
                    "supportsSetVariable": true, 
                    "supportsExceptionInfoRequest": true, 
                    "supportsModulesRequest": true, 
                    "supportsValueFormattingOptions": true, 
                    "supportsConditionalBreakpoints": true, 
                    "supportsEvaluateForHovers": true, 
                    "exceptionBreakpointFilters": [
                        {
                            "label": "Raised Exceptions", 
                            "default": false, 
                            "filter": "raised"
                        }, 
                        {
                            "label": "Uncaught Exceptions", 
                            "default": true, 
                            "filter": "uncaught"
                        }
                    ], 
                    "supportsLogPoints": true
                }, 
                "seq": 2, 
                "success": true, 
                "message": "", 
                "command": "initialize"
            }

D00009.069: (while handling {u'command': u'initialize', u'type': u'request', u'seq': 1})
            IDE <-- {
                "event": "initialized", 
                "type": "event", 
                "body": {}, 
                "seq": 3
            }

D00009.072: IDE --> {
                "command": "setBreakpoints", 
                "type": "request", 
                "arguments": {
                    "lines": [
                        134, 
                        192
                    ], 
                    "source": {
                        "name": "audience.py", 
                        "path": "/Users/fdelgadodoyle/dev/main_service/src/www/mixins/core_model/audience.py"
                    }, 
                    "sourceModified": false, 
                    "breakpoints": [
                        {
                            "line": 134
                        }, 
                        {
                            "line": 192
                        }
                    ]
                }, 
                "seq": 3
            }

D00009.075: IDE --> {
                "command": "setBreakpoints", 
                "type": "request", 
                "arguments": {
                    "lines": [
                        557
                    ], 
                    "source": {
                        "name": "layer.py", 
                        "path": "/Users/fdelgadodoyle/dev/main_service/src/www/mixins/core_model/layer.py"
                    }, 
                    "sourceModified": false, 
                    "breakpoints": [
                        {
                            "line": 557
                        }
                    ]
                }, 
                "seq": 4
            }

D00009.094: IDE --> {
                "command": "setBreakpoints", 
                "type": "request", 
                "arguments": {
                    "lines": [
                        104
                    ], 
                    "source": {
                        "name": "segment_tracking.py", 
                        "path": "/Users/fdelgadodoyle/dev/main_service/src/www/services/segment_tracking.py"
                    }, 
                    "sourceModified": false, 
                    "breakpoints": [
                        {
                            "line": 104
                        }
                    ]
                }, 
                "seq": 5
            }

D00636.540: IDE --> {
                "command": "setExceptionBreakpoints", 
                "type": "request", 
                "arguments": {
                    "filters": [
                        "raised"
                    ]
                }, 
                "seq": 6
            }

D00636.542: (while handling {u'command': u'setExceptionBreakpoints', u'type': u'request', u'seq': 6})
            PYD <-- {
                "command": "setExceptionBreakpoints", 
                "type": "request", 
                "arguments": {
                    "filters": [
                        "raised"
                    ]
                }, 
                "seq": 1000000001
            }

```

**Comment by karthiknadig** [comment]
Is there any particular reason you are setting the remote root explicitly? This should work.
```js
"pathMappings": [
              {
                  "localRoot": "${workspaceFolder}",
                  "remoteRoot": "."
              }
          ]
```
Do you see any warnings that some thing along the lines of "breakpoints were not set"?
Can you tell the location of python binary, site-packages, user site-packages on the remote?

**Comment by flaker** [comment]
> Do you see any warnings that some thing along the lines of "breakpoints were not set"?
No warnings, visually all seems to be fine.

> Is there any particular reason you are setting the remote root explicitly? This should work.

Just wanted to be as explicit as possible. I will test to go back to that default.

Python info:
Path: /usr/bin/python
Site-packages: /usr/lib/python2.7/site-packages/
User site-packages: there is none. My user in the container (root) has none.

**Comment by flaker** [comment]
Tried the `localRoot` change. No difference.
I know I mentioned I am using Alpine to run the container. Do you think that might make a difference? (not using glibc)

**Comment by flaker** [comment]
Rebuilt from master (0e173e9170ec28ed4f164891315f5c273fa02dc5)
There was no change using a start up script (break points are cosmetically there but nothing happens)
BUT with this version I can execute the command line option to try to attach to a running process. Interestingly I found this:

```
bash-4.4# python -m ptvsd --host 0.0.0.0 --port 5678 --pid 10
Attaching with arch: i386:x86-64
Running: gdb --nw --nh --nx --pid 10 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture i386:x86-64' --eval-command='call dlopen("/usr/lib/python2.7/site-packages/ptvsd-4.3.0b2-py2.7.egg/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='call (int)DoAttach(0, "import sys;sys.path.append(\"/usr/lib/python2.7/site-packages/ptvsd-4.3.0b2-py2.7.egg\");sys.path.append(\"/usr/lib/python2.7/site-packages/ptvsd-4.3.0b2-py2.7.egg/ptvsd\");import attach_script_ptvsd_pid;attach_script_ptvsd_pid.attach(port=5678, host=\"0.0.0.0\", client=False, log_dir=\"\");", 0)'
Running gdb in target process.
stdout: The target architecture is assumed to be i386:x86-64

stderr: ptrace: Operation not permitted.
Target 'None' cannot support this command.
No symbol table is loaded.  Use the "file" command.
No symbol table is loaded.  Use the "file" command.
```

I don't know if this also impacts the non-command line version.

**Comment by flaker** [comment]
by adding
```
    cap_add:
      - SYS_PTRACE
```
I am able to run the command line. My own breakpoints are not being hit. But now I:
 - See a list of running threads.
 - If I choose "Raised Exceptions" in VS Code, the code does stop from time to time.
But my own breakpoints are ignored.

**Comment by int19h** [comment]
In this case you're using attach-by-PID, which is generally more flaky than attach-by-port (it's the same thing in the end, but attach-by-PID has to inject the code into the process that ultimately calls `ptvsd.enable_attach()`). 

It's interesting that you see the list of running threads with this approach, but not with the one where you do `enable_attach` directly. The primary difference is that the attach-by-PID version, after it does `enable_attach`, also does `wait_for_attach` - thus, no further code runs in your process until you attach the debugger. If you do that in your original repro, does it make any difference?

Also, there's a way to do programmatic breakpoints: `ptvsd.break_into_debugger()`. If you use that somewhere in your code, does it break, and what do you see in the stack?

**Comment by flaker** [comment]
Hi @int19h to confirm.
You suggest to leave the start up script with

```
import ptvsd
ptvsd.enable_attach(log_dir='/var/log')
```

and later on in my code do:

```
    import ptvsd
    ptvsd.break_into_debugger()
```
while being already attached from VS Code.

 I tried that. I didn't get a break, only some warning message:

>  PYDEV DEBUGGER WARNING:
>  sys.settrace() should not be used when the debugger is being used.
>  This may cause the debugger to stop working correctly.
>  If this is needed, please check:
>  http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
>  to see how to restore the debug tracing back correctly.
>  Call Location:
>    File "/usr/lib/python2.7/site-packages/ptvsd-4.3.0b2-py2.7.egg/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 291, in <module>
>      sys.settrace(_temp_trace)

I noticed something. My processes look like:

```
PID   USER     TIME  COMMAND
    1 root      0:00 python /google-cloud-sdk/bin/dev_appserver.py --host 0.0.0.0 --port 80 --admin_host 0.0.0.0 --admin_port 8550 --python_startup_script /app/src/www/pydev_startup.py --api_host 0.0.0.0 --api_port 8551 --datastore_path=www_datastore --enable_sendm
    9 root      0:29 /usr/bin/python /google-cloud-sdk/platform/google_appengine/dev_appserver.py --skip_sdk_update_check=True --datastore_emulator_cmd=/google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator --host 0.0.0.0 --port 80 --admin_hos
 2356 root      0:00 /usr/bin/python /google-cloud-sdk/platform/google_appengine/_python_runtime.py /tmp/tmpZivkXm /tmp/tmpPb1bLS
```

Process 2356 started as soon as I started processing a request. I am unsure about its lifetime.
My startup script runs in process 9. But I suspect actual execution (of my code) takes place in 2356. I cannot confirm that because `import os; os.getpid()` returns -1.

Using `python -m ptvsd blah blah` on process 9 will show running threads but never break in my breakpoints. If I just use the start script approach, I see nothing. That confuses me a lot. Why attaching to the same PID will result on two different behaviors?

Also, running in PID 9, will spawned processed also be under the debugger?

**Comment by int19h** [comment]
It looks like it uses some kind of multiprocess arrangement to run your code. We support that to some extent, but it depends on how exactly the child process is spawned - in particular, forking is not supported at all (but we're working on it: #943).

Because of this, we currently consider it to be experimental, and it is not enabled by default. But you can try to enable it by adding this to your launch.json config:
```json5
"subProcess": true,
```

If this works correctly, you should see VSCode attaching to the child process automatically when it is spawned.

One more thing. This warning that you got indicates that GAE is also trying to do something with `sys.settrace`. This isn't directly related to multiprocessing, but it may interfere with the operation of the debugger, because this is _the_ Python API that debuggers use to implement stepping and breakpoints. Thus, it is possible that breakpoints might not work even if you attach to the child process, depending on what exactly GAE does to that hook.

**Comment by int19h** [comment]
Also, it looks like there's a known issue with GAE constraining the Python APIs available inside the process, possibly to the point where the debugger cannot run because it requires some of those blocked APIs (#830). It's a bug from last year, so things might have changed since then. But watch out for it if you succeed in attaching to that child process.

**Comment by karthiknadig** [comment]
Another thing, you may have to follow this https://github.com/microsoft/ptvsd/blob/master/TROUBLESHOOTING.md#1-multiprocessing-on-linuxmac to get it working right. This is only temporary until we fix #943.

**Comment by flaker** [comment]
So, the good news is that I managed to hit my breakpoint. The bad one is that I took an axe to the dev app server. Going over it I find that it gets rid many (many) modules. In between those modules is the one that keeps the debugger from running properly. So far, I've reduced the list to these modules and I am getting the most interesting ones to see if I get lucky.

```
__future__
_abcoll
_bisect
_codecs
_collections
_ctypes
_functools
_hashlib
_heapq
_io
_json
_locale
_lwpcookiejar
_mozillacookiejar
_multiprocessing
_random
_socket
_sqlite3
_sre
_ssl
_struct
_sysconfigdata
_warnings
_weakref
_weakrefset
abc
array
atexit
base64
basehttpserver
binascii
bisect
bz2
calendar
cgi
code
codeop
collections
concurrent
configparser
contextlib
cookie
cookielib
copy
copy_reg
cpickle
cstringio
ctypes
cython_runtime
datetime
decimal
dis
distutils
django
errno
exceptions
fancy_urllib
fcntl
fnmatch
functools
gc
genericpath
glob
grp
gzip
hashlib
heapq
httplib
imp
importlib
importlib.sys
inspect
io
ipaddr
ipaddr.struct
itertools
json
keyword
linecache
locale
logging
marshal
math
mimetools
mimetypes
multiprocessing
ntpath
numbers
opcode
operator
os
os.path
pickle
pkg_resources
pkgutil
platform
plistlib
posix
posixpath
pprint
pwd
pydoc
pyexpat
pyexpat.errors
pyexpat.model
queue
quopri
random
re
repr
rfc822
select
shutil
signal
simplejson
simplexmlrpcserver
socket
socketserver
sre_compile
sre_constants
sre_parse
ssl
stat
string
stringio
strop
struct
subprocess
sysconfig
tempfile
textwrap
thread
threading
time
token
tokenize
trace
traceback
types
unicodedata
urllib
urllib2
urlparse
userdict
uu
warnings
weakref
wrapper_util
wsgiref
xml
xml.etree
xml.parsers
xml.parsers.expat
xml.parsers.pyexpat
xml.sax
xmlrpclib
yaml
zipfile
zipimport
zlib
```

**Comment by flaker** [comment]
while building the sandbox, the sdk removes a (large) number of modules. I added the following:

```
is_wanted = name.startswith('os') or 'pydev' in name or 'ptvsd' in name
```
to the evaluation of modules to keep and the debugging is working. For reference, at least in my case, it was the function `_should_keep_module` in the file: /platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py

Maybe there is a way to make this cleaner. Like knowing what inside `os` is being missed, or some configuration option. 

Thank you everyone for being so patient. 

Thanks everyone!

**Comment by int19h** [comment]
You could get the list of modules by running the debugger on some simple app - do breakpoints, some stepping etc - and then printing out `sys.modules` at the very end of it.

But as I understand, the point of GAE dev server removing the modules is to present the environment that is identical to what you'll see in production - so that you don't accidentally rely on some module in your code during development, only to find that it's missing when you deploy. So re-adding those missing modules somewhat defeats the purpose of that sandbox.

I don't think we can really do much about it, unfortunately. There's no real way to isolate the debugger from the running code, so if it needs those stdlib modules, the "rest of the world" will also see them in `sys.modules` (even if we e.g. muck around with `sys.path` to load them from outside of the sandbox), and thus they will be importable.

**Comment by flaker** [comment]
@int19h 

Sorry I wasn't clear. It's working now. I only needed to let `os` go through (and ptvsd if you want to call it directly). As you say, the idea of the dev server is to look as PROD as possible so this solution is not advisable at all, but works for me for the moment.

Thanks!

**Comment by int19h** [comment]
You're welcome!

**Comment by jdwestwood** [comment]
@flaker  Have you opened an issue for this in the Google issuetracker?  For something as basic as debugging, one would hope Google would make the dev_appserver sandbox play nice with a well-established debugger like ptvsd/pydevd.

**Comment by flaker** [comment]
@jdwestwood 

They do provide instructions on Eclipse + Pydev in a local environment

https://cloud.google.com/appengine/docs/standard/python/tools/setting-up-eclipse

In my case the environment was different and there where a couple of blog posts with people successfully running ptvsd + VS Code just by installing the module and using  python_startup_script. In my case, that was not enough. That said, it's my first GAE experience so I could have missed something.

**Comment by int19h** [comment]
Looking at that page, it makes me feel like there's some magic going on behind the scenes there, since otherwise I don't see how pydevd would work without having to do basically the same thing you did.

I tried to see if there's any special treatment of pydevd in Google Cloud SDK code, but I can't find it there. The only mention of `_should_keep_module` that I can find is in this: https://github.com/GoogleCloudPlatform/python-compat-runtime - and as I understand, this is a legacy version that is no longer maintained? Does the issue repro on the current stable version of the SDK?

**Comment by jdwestwood** [comment]
Actually, debugging dev_appserver in Eclipse + Pydev is broken as well and has been for quite awhile, also due to sandbox restrictions.  I had recently decided to try VSCode, hoping that debugging would work out of the box.

**Comment by flaker** [comment]
@jdwestwood 
Local is not an option for me, but please let us know!!

@int19h 
Unfortunately I am not able to use newer versions. They do state that the startup script can be used to setup debuggers. But remote and with my version I am not sure what kind of debuggers they meant.

For local pydev, yeah ... they can do some trickery as you say. The interpreter is there.

**Comment by int19h** [comment]
@jdwestwood, good to know, thank you!

I'm not sure what they can really do on their end alone, either, given that this is fundamentally an issue with Python's own debug API in general - any Python debugger that is itself written in Python (which it has to be to work with PyPy, Jython etc) cannot be fully isolated from the code being debugged. Thus, any sandbox necessarily affects it, and supporting it requires breaking the sandbox in some ways.

One possibility would be for them to provide a way to selectively break out of the sandbox in the development environment, at least wrt imports. Something like:
```py
with no_sandbox:
  import os

@no_sandbox:
def foo():
  os.walk(...)
```
that would essentially maintain two versions of `sys.modules` and `sys.path` - one used for code that's inside such blocks, and one for code outside of them. And then any package that wants to specifically support the GAE sandbox without being constrained by it would have to put those in every module and on every function. 

Or they could hack their sandbox version of Python to automatically do that swap by itself, depending on `f_code.co_filename` of the current frame.

**Comment by jdwestwood** [comment]
@flaker Based on your finding about the modules that are needed in the dev_appserver sandbox,  here is a pydev_startup.py script that works for me without the need to modify the '_should_keep_module' function in google\\appengine\\tools\\devappserver2\\python\\runtime\\sandbox.py on the file system:
```
import sys
import os

PTVSD_PATH = "<your user directory\\.vscode\\extensions\\ms-python.python-2019.6.24221\\pythonFiles\\lib\\python"
sys.path.append(PTVSD_PATH)

# Replace sandbox._prune_sys_modules with this function.  This is probably better than patching
# _should_keep_module in case Google changes the modules whitelisted there in future releases
# of dev_appserver.
def _prune_sys_modules():
  """Prune sandboxed modules from sys.modules."""
  for name in list(sys.modules):
    if not _should_keep_module(name):
      # https://github.com/microsoft/ptvsd/issues/1606
      if name.startswith('os') or 'pydev' in name or 'ptvsd' in name:
        pass
      else:
        _removed_modules.append(sys.modules[name])
        del sys.modules[name]

# Needed if dev_appserver is starting services in addition to the default service.
# https://docs.google.com/document/d/1CCSaRiIWCLgbD3OwmuKsRoHHDfBffbROWyVWWL0ZXN4/edit
if ':' not in config.version_id:
    # Default service is starting.
    # Exceptions in the startup script are caught in runtime.py and not sent to the terminal,
    # so catch and print them here.
    try:
        from google.appengine.tools.devappserver2.python.runtime import sandbox
        # The following is adapted from
        # https://stackoverflow.com/questions/41858147/how-to-modify-imported-source-code-on-the-fly
        import inspect
        source_lines = inspect.getsource(_prune_sys_modules)
        exec(source_lines, sandbox.__dict__)
        # Note using 'sandbox._prune_sys_modules = _prune_sys_modules' also works for debug
        # functionality, but has side-effects on dev_appserver logging behavior, strangely
        # enough.  The method above does not have any side effects that I have noticed so far.
    except Exception as e:
        print('Exception in python startup file while patching sandbox._prune_sys_modules: ', e)

    try:
        import ptvsd
        ptvsd.enable_attach(address = ('localhost', 5678))
        # The debug server has started and you can now use VS Code to attach to the application for debugging
        print("Google App Engine has started, ready to attach the debugger")
    except Exception as e:
        print('Exception in python startup file while starting the ptvsd debug server: ', e)
```
In my tasks.json, I have two dev_appserver tasks, one that does not run this script and the other for debugging which does run it.  That way in my app code if I inadvertently use an os function that is disallowed in the sandbox, dev_appserver will complain when I am not debugging.

Also, fyi and for anyone who might stumble on this thread in the future, I noticed that the "--automatic_restart=no" option is not in your dev_appserver command line.  In my case, I definitely need it.  I also have "--threadsafe_override=False", but am not sure I need it.

@int19h This link (the same as the one in one of the comment lines in the code above) [https://docs.google.com/document/d/1CCSaRiIWCLgbD3OwmuKsRoHHDfBffbROWyVWWL0ZXN4/edit](url) gives an example of using threading.settrace in a startup script to be able to write messages to a file while app code is running in the sandbox.  The level of the code is frankly beyond me, but I wonder if the same approach might be useful when setting up the ptvsd debug server in the startup script, perhaps together with adding import hooks to the ptvsd code, to be able to access needed os module functionality (getpid, etc) when attached to dev_appserver processes.  Not sure if that makes sense -- any thoughts are appreciated.

**Comment by flaker** [comment]
wow @jdwestwood that is an approach that might work in a somehow cleaner way!! using the startup script itself to do all the magic. Now, after some tinkering this is the minimum change I could get. This patch enables debugging.

```
442a443
>   is_debugger = 'pydev' in name or 'ptvsd' in name
452c453
<           'mysql' in name.lower())
---
>           'mysql' in name.lower() or is_debugger)
947d947
<         default_stub=stubs.os_error_not_implemented,
952c952
<                    'walk'],
---
>                    'walk','getpid', 'unlink', 'rename', 'popen'],
961d960
<             'getpid': stubs.return_minus_one,
```
So.

-  allow to load ptvsd/pydevd (the reason for this is to allow proper clean up when you kill the service)
-  enabling getpid, unlink, rename, popen
-  stop the generic "not implemented"

it works.

I will try to adjust your script to only do that so I don't need to edit the sandbox file.

Thank you!!

**Comment by int19h** [comment]
@jdwestwood, very interesting, thank you! 

This basically gives a hook to pre-import the necessary modules, and stash them away somewhere they can be retrieved from later once the sandbox is in effect. If that hook pre-imports all ptvsd and pydevd modules, then any top-level imports in them would be preserved (as global variables) into the sandbox.

However, any local imports would be affected, as would be `open()`, which I think we use in a few places. So I don't think this would work right off the bat... but it's definitely a much smaller change than I anticipated.

**Comment by jdwestwood** [comment]
@flaker Thank you for posting those refinements.  I had tried to fiddle with the _MODULE_OVERRIDE_POLICIES, but could not make it work.  Thanks for showing the way!
