### ISSUE TITLE
Core dump when run few steps.

### ISSUE THREAD

**Issue by fuzihaofzh** [microsoft/ptvsd#1617]
## Environment data

- PTVSD version: 4.2.2
- OS and version:  CentOS Linux release 7.6.1810 (Core)
- Python version (& distribution if applicable, e.g. Anaconda): Miniconda 3.7.3
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Segmentation fault      (core dumped)

The core file is as follows:

gdb python core.47715
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/maple/ProgramFiles/miniconda3/bin/python3.7...done.

warning: core file may not match specified executable file.
[New LWP 47715]
[New LWP 47722]
[New LWP 47741]
[New LWP 47721]
[New LWP 47743]
[New LWP 47747]
[New LWP 47745]
[New LWP 47753]
[New LWP 47757]
[New LWP 47755]
[New LWP 47749]
[New LWP 47762]
[New LWP 47758]
[New LWP 47760]
[New LWP 47763]
[New LWP 47765]
[New LWP 47718]
[New LWP 47750]
[New LWP 47754]
[New LWP 47748]
[New LWP 47720]
[New LWP 47756]
[New LWP 47752]
[New LWP 47744]
[New LWP 47761]
[New LWP 47764]
[New LWP 47759]
[New LWP 47742]
[New LWP 47751]
[New LWP 47746]
[New LWP 47719]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /home/maple/ProgramFiles/miniconda3/lib/python3.7/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0
Missing separate debuginfo for /home/maple/ProgramFiles/miniconda3/lib/python3.7/site-packages/torch/lib/libgomp-4f651535.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/bc/06d853a00724b96cd6653b4a93431563da904c.debug
Core was generated by `python -m ptvsd --host 0.0.0.0 --port 5678 --wait ./fairseq/train.py output/dat'.
Program terminated with signal 11, Segmentation fault.
#0  _PyDict_LoadGlobal ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/dictobject.c:1414
1414    /tmp/build/80754af9/python_1553721932202/work/Objects/dictobject.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.6.x86_64 libgcc-4.8.5-36.el7_6.2.x86_64 libstdc++-4.8.5-36.el7_6.2.x86_64

bt

#0  _PyDict_LoadGlobal ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/dictobject.c:1414
#1  0x00005633d2233619 in _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:2114
#2  0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x5633d8fef558, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#3  0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#4  0x00005633d217a800 in _PyFunction_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#5  0x00005633d217a966 in _PyObject_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#6  0x00005633d2191c43 in _PyObject_Call_Prepend ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#7  0x00005633d218695e in PyObject_Call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:245
#8  0x00005633d2235250 in do_call_core (kwdict=0x2b1fc750e4c8, callargs=0x2b1fc5126c88,
    func=0x2b1fc487aec8)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4645
#9  _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3191
#10 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1fc752a5a0, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#11 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#12 0x00005633d217a800 in _PyFunction_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#13 0x00005633d217a966 in _PyObject_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#14 0x00005633d2191c43 in _PyObject_Call_Prepend ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#15 0x00005633d21d416a in slot_tp_call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/typeobject.c:6379
#16 0x00005633d218695e in PyObject_Call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:245
#17 0x00005633d2235250 in do_call_core (kwdict=0x2b1fc75069d8, callargs=0x2b1fc5126128,
    func=0x2b1fc51265f8)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4645
#18 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3191
#19 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1fc75a0be8, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#20 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#21 0x00005633d217a800 in _PyFunction_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#22 0x00005633d217a966 in _PyObject_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#23 0x00005633d2191c43 in _PyObject_Call_Prepend ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#24 0x00005633d218695e in PyObject_Call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:245
#25 0x00005633d2235250 in do_call_core (kwdict=0x2b1fc7506dc8, callargs=0x2b1f34ec9048,
    func=0x2b1f7e19ff48)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4645
#26 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3191
#27 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1fcbf29240, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#28 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#29 0x00005633d217a800 in _PyFunction_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#30 0x00005633d217a966 in _PyObject_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#31 0x00005633d2191c43 in _PyObject_Call_Prepend ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#32 0x00005633d21d416a in slot_tp_call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/typeobject.c:6379
#33 0x00005633d218695e in PyObject_Call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:245
#34 0x00005633d2235250 in do_call_core (kwdict=0x2b1fcbf1ae58, callargs=0x2b1f34ec9048,
    func=0x2b1fc51264a8)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4645
#35 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3191
#36 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1fc50b2848, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#37 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#38 0x00005633d21db9c5 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#39 0x00005633d2237ed9 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#40 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3093
#41 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1fc75a0618, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#42 0x00005633d21797da in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#43 0x00005633d217a5d5 in _PyFunction_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#44 0x00005633d217a966 in _PyObject_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#45 0x00005633d2191c43 in _PyObject_Call_Prepend ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#46 0x00005633d218695e in PyObject_Call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:245
#47 0x00005633d2235250 in do_call_core (kwdict=0x2b1fc75611b0, callargs=0x2b1fc75f55c8,
    func=0x2b1fc49df888)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4645
#48 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3191
#49 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1fcbf29048, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#50 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#51 0x00005633d217a5d5 in _PyFunction_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#52 0x00005633d217a966 in _PyObject_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#53 0x00005633d2191c43 in _PyObject_Call_Prepend ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#54 0x00005633d21d416a in slot_tp_call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/typeobject.c:6379
#55 0x00005633d21dcd2b in _PyObject_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:199
#56 0x00005633d2238026 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4619
#57 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#58 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1f3dd1f9d0, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#59 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#60 0x00005633d21db9c5 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#61 0x00005633d2233ad0 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#62 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3110
#63 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x5633d8fdfbc8, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#64 0x00005633d2179db9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#65 0x00005633d21dba27 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#66 0x00005633d2233ad0 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#67 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3110
#68 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x5633d6059fe8, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#69 0x00005633d21db79b in function_code_fastcall (globals=<optimized out>, nargs=4,
    args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:283
#70 _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:408
#71 0x00005633d2233846 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#72 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#73 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x5633d56d4fc8, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#74 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#75 0x00005633d21db9c5 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#76 0x00005633d2233846 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#77 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#78 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1fc4f65648, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#79 0x00005633d21db79b in function_code_fastcall (globals=<optimized out>, nargs=0,
    args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:283
#80 _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:408
#81 0x00005633d2233846 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#82 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#83 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x2b1f3ed2b048, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#84 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#85 0x00005633d217a3c4 in PyEval_EvalCodeEx ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3959
#86 0x00005633d217a3ec in PyEval_EvalCode (co=co@entry=0x2b1f3ed2a030,
    globals=globals@entry=0x2b1f3ed134c8, locals=locals@entry=0x2b1f3ed134c8)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:524
#87 0x00005633d2242f41 in builtin_exec_impl.isra.12 (locals=0x2b1f3ed134c8,
    globals=0x2b1f3ed134c8, source=0x2b1f3ed2a030)
    at /tmp/build/80754af9/python_1553721932202/work/Python/bltinmodule.c:1079
#88 builtin_exec ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/clinic/bltinmodule.c.h:283
#89 0x00005633d21dc569 in _PyMethodDef_RawFastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:651
#90 0x00005633d21dc801 in _PyCFunction_FastCallKeywords (func=0x2b1f34f09d80,args=args@entry=0x5633d40cbf28, nargs=nargs@entry=2, kwnames=kwnames@entry=0x0)
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:730
#91 0x00005633d2239688 in call_function (kwnames=0x0, oparg=2,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4568
#92 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#93 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x5633d40cbd68, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#94 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#95 0x00005633d21db9c5 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#96 0x00005633d2233846 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#97 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#98 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x5633d4002bb8, __pyx_v_exc=<optimized out>)at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#99 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#100 0x00005633d21dba27 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#101 0x00005633d22348fe in call_function (kwnames=0x2b1f35068208, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#102 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3139
#103 0x00002b1f3daf75e0 in __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval (__pyx_v_frame_obj=0x5633d441bc08, __pyx_v_exc=<optimized out>)
    at _pydevd_frame_eval/pydevd_frame_evaluator.c:7206
#104 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#105 0x00005633d21dba27 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#106 0x00005633d22348fe in call_function (kwnames=0x2b1f3de2f0f0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#107 _PyEval_EvalFrameDefault ()at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3139
#108 0x00005633d21db79b in function_code_fastcall (globals=<optimized out>, nargs=0,
    args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:283
#109 _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:408
#110 0x00005633d2233846 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#111 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#112 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#113 0x00005633d21db9c5 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#114 0x00005633d2233846 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#115 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#116 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#117 0x00005633d217a3c4 in PyEval_EvalCodeEx ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3959
#118 0x00005633d217a3ec in PyEval_EvalCode (co=co@entry=0x2b1f3de9c150,
    globals=globals@entry=0x2b1f34f8a480, locals=locals@entry=0x2b1f34f8a480)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:524
#119 0x00005633d224304d in builtin_exec_impl.isra.12 (locals=0x2b1f34f8a480,
    globals=0x2b1f34f8a480, source=0x2b1f3de9c150)
    at /tmp/build/80754af9/python_1553721932202/work/Python/bltinmodule.c:1079
#120 builtin_exec ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/clinic/bltinmodule.c.h:283
#121 0x00005633d21dc569 in _PyMethodDef_RawFastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:651
#122 0x00005633d21dc801 in _PyCFunction_FastCallKeywords (func=0x2b1f34f09d80,
    args=args@entry=0x5633d4061db8, nargs=nargs@entry=2, kwnames=kwnames@entry=0x0)
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:730
#123 0x00005633d2237b85 in call_function (kwnames=0x0, oparg=2,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4568
#124 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#125 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#126 0x00005633d21db9c5 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#127 0x00005633d2233846 in call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#128 _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#129 0x00005633d21794f9 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#130 0x00005633d217a5d5 in _PyFunction_FastCallDict ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#131 0x00005633d21869c4 in PyObject_Call ()
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:226
#132 0x00005633d2285d77 in pymain_run_module ()
    at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:320
#133 0x00005633d229de95 in pymain_run_python (pymain=0x7ffe175a8df0)
    at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:2874
#134 pymain_main () at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:3038
#135 0x00005633d229df7c in _Py_UnixMain ()
at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:3073
#136 0x00002b1f352da495 in __libc_start_main () from /lib64/libc.so.6
#137 0x00005633d2243122 in _start () at ../sysdeps/x86_64/elf/start.S:103

**Comment by karthiknadig** [comment]
@fuzihaofzh Can you try it with ptvsd==4.2.10 ? If it occurs with that version can you provide some repro steps?

**Comment by karthiknadig** [comment]
Please reopen if this happens again. Minimal repro will definitely help address such issues.
