### ISSUE TITLE
Variable check

### ISSUE THREAD

**Issue by hugomartins11** [microsoft/ptvsd#1620]
It'd be nice to check the value of some local vars, without having to use the cursor on top of them. 
I recommend putting it on a tab of the debugger interface and having it being displayed there.

**Comment by int19h** [comment]
You can see all the local variables and their values in the Debug sidebar.

https://code.visualstudio.com/docs/editor/debugging#_debug-view
https://code.visualstudio.com/docs/editor/debugging#_data-inspection

Or did you have something else in mind?

**Comment by hugomartins11** [comment]
Hello!
I did have something else in mind.
Having the ability to check global vars, for example, would be a plus.
This feature is present on pycharm for example

**Comment by int19h** [comment]
Indeed! We have globals on our list of features to implement - #118. Please upvote that issue, so that we can keep track of the user demand for it, and prioritize it accordingly.

**Comment by karthiknadig** [comment]
Closing this as dupe of  #118
