### ISSUE TITLE
Consider coroutines when stepping (check with asyncio and trio).

### ISSUE THREAD

**Issue by andersea** [microsoft/ptvsd#1627]
## Environment data

- VS Code version: 1.36.1
- Extension version: 2019.6.24221
- OS and version: Windows 10 / Version 1903 / Windows_NT x64 10.0.18362 /
- Python version: Python 3.7.3 x64
- Type of virtual environment used: venv
- Relevant/affected Python packages and their versions: trio 0.11.0
- Jedi or Language Server?: Language server (false)

## Expected behaviour

When debugging trio async/await code, continue, stepping over, and out of functions doesn't work.

When stopped on a breakpoint, pressing continue (F5) should continue execution to the next breakpoint.

When stopped on a break point, pressing step over (F10) should proceed to next line of code.

When inside an async function, pressing step out(Shift+F11) should return to the the next line of the calling scope

## Actual behaviour

Behaviour seems erratic. Sometimes I get an error. Sometimes something unexpected happens.

Pressing continue stops on the same line as where you had the breakpoint. Sometimes an error is opened in a new tab, with the following or similar message: "Could not load source '<string>': Source unavailable."

Pressing step over stops on the same line as where you had the breakpoint.

Pressing step out at first doesn't do anything. Pressing it again steps out to the same line as where you stepped in.

## Steps to reproduce:
1.  Use example code:

```
import trio

async def func1():
    await trio.sleep(1)

async def func2():
    await trio.sleep(2)

async def func3():
    await trio.sleep(3)

async def main():
    await func1() # <--- Try putting break point here.
    await func2()
    await func3()

trio.run(main)
```

## Logs

Code started with following parameters

```
(.venv) PS C:\Users\Anders\Documents\python\trio-debugging> cd 'c:\Users\Anders\Documents\python\trio-debugging'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'c:\Users\Anders\Documents\python\trio-debugging\.venv\Scripts\python.exe' 'c:\Users\Anders\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '55265' 'c:\Users\Anders\Documents\python\trio-debugging\debugging.py'
```

**Comment by andersea** [comment]
Here is one error I get in a new tab when using step over from the break point:

    Could not load source '<attrs generated init 8d41ebacfc00edb9f075a656f2e1472dc827095d>': Source unavailable.

**Comment by fabioz** [comment]
I'm investigating this...

**Comment by fabioz** [comment]
There are actually 2 issues here: one is related to tracking `attrs` and the other is that dealing with Python async isn't really ok on `step over` (with just my code turned on it almost appears as it works, but it's very evident with just my code turned off that we end up going to async internals on a step over instead of going to the awaited line).

So, the attrs fix should be straightforward, but properly dealing with await will take more time (I need to investigate better how to handle this internally in the debugger).
