### ISSUE TITLE
Breakpoints not working for Python 3.7.1.

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [microsoft/ptvsd#1629]
VSCode is completely ignoring my breakpoints while trying to debug Flask. 

## launch.json
```
        {
            "name": "Python: Flask (0.11.x or later)",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py",
                "FLASK_ENV": "development",
            },
            "args": [
                "run",
            ],
            "jinja": true
        },
```

## Environment data

- VS Code version: 1.36.1
- Extension version (available under the Extensions sidebar): 2019.6.24221 (9 July 2019)
- OS and version: Win10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv

**Comment by karthiknadig** [comment]
@Karlheinzniebuhr Add `"subProcess": true,` to your launch.json and see if that helps.

**Comment by Karlheinzniebuhr** [comment]
> @Karlheinzniebuhr Add `"subProcess": true,` to your launch.json and see if that helps.

doesn't make a difference, still no breakpoint works

**Comment by karthiknadig** [comment]
Try this, configuration. I see that it is missing "pathMappings" as well.
```js
        {
            "name": "Python: Flask (0.11.x or later)",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py",
                "FLASK_ENV": "development",
            },
            "subProcess": true,
            "args": [
                "run",
            ],
            "jinja": true,
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        }
```

**Comment by karthiknadig** [comment]
If this still does not work. Can you provide details of your project layout (location of your scripts and the location of the virual env). can you also get the logs? You can get the logs by using this env variable:
```js
"env": {
"PTVSD_LOG_DIR": "<path to logs dir>" // make sure this dir exists 
}
```

**Comment by int19h** [comment]
This is a "launch" scenario, so path mappings shouldn't be necessary, I think.

However, the other problem is that Flask has its own mini-debugger that can interfere with ours. This is enabled by default if you use `FLASK_ENV=development`. You can disable it with `FLASK_DEBUG=0` - see if that helps.

If not, then getting those logs would help a lot!

**Comment by karthiknadig** [comment]
"pathMappings" are necessary for the attached sub-processes, since we use the same configuration but in attach mode.

**Comment by Karlheinzniebuhr** [comment]
> Try this, configuration. I see that it is missing "pathMappings" as well.
> 
> ```js
>         {
>             "name": "Python: Flask (0.11.x or later)",
>             "type": "python",
>             "request": "launch",
>             "module": "flask",
>             "env": {
>                 "FLASK_APP": "app.py",
>                 "FLASK_ENV": "development",
>             },
>             "subProcess": true,
>             "args": [
>                 "run",
>             ],
>             "jinja": true,
>             "pathMappings": [
>                 {
>                     "localRoot": "${workspaceFolder}",
>                     "remoteRoot": "."
>                 }
>             ]
>         }
> ```

I can't use pathMappings because it gives me:
`Property pathMappings is not allowed.`

This is my directory structure:
[dirstructure.txt](https://github.com/microsoft/ptvsd/files/3436102/dirstructure.txt)


And here is the log:
[ptvsd-41212.log](https://github.com/microsoft/ptvsd/files/3436117/ptvsd-41212.log)

**Comment by karthiknadig** [comment]
@Karlheinzniebuhr  you will see a squiggle under that . But please try that.
![image](https://user-images.githubusercontent.com/3840081/61969318-1a6c4c80-af8f-11e9-8b45-aa6e3e990b73.png)

**Comment by karthiknadig** [comment]
Note that all of this occurs if you run flask without `--no-reload`. We support running flask with relaod, but it requires the `pathMappings`. If you don't need reload, you can turn it off using `--no-reload`, like this:
```js
"args": [
                "run", "--no-reload",
            ],
```

**Comment by karthiknadig** [comment]
@DonJayamanne Another one of those cases where we need `pathMappings`. Can we make it so that there are no squiggles on `pathMappings`?

**Comment by Karlheinzniebuhr** [comment]
> need rel

Ok so I added pathMappings to my config. But the breakpoints didn't work. Here is the log

[ptvsd-68720.log](https://github.com/microsoft/ptvsd/files/3437228/ptvsd-68720.log)

**Comment by int19h** [comment]
@Karlheinzniebuhr 
Can you try it with `--no-debug` but without `--no-reload`, and see if that works?

If it doesn't, then using both `--no-debug` and `--no-reload` should definitely work.

**Comment by int19h** [comment]
@karthiknadig  Looking at the log, it seems that `"subProcess": true` is not being handled correctly by vscode-python? This is the "launch" request that ptvsd receives:
```json5
{
  "command": "launch",
  ...
  "debugOptions": ["ShowReturnValue", "Jinja", "RedirectOutput", "FixFilePathCase"]
```
Note that there's no `"Multiprocess"` here...

**Comment by karthiknadig** [comment]
You need both `"subProcess": true` and `pathMappings` for this to work.

**Comment by Karlheinzniebuhr** [comment]
> You need both `"subProcess": true` and `pathMappings` for this to work.

Added `"subProcess": true` and voila breakpoints are working. Thank you for your help, would you be so kind to clarify why this happens? I haven't found an explanation in the documentation. 
Here the new log:
[ptvsd-3292.log](https://github.com/microsoft/ptvsd/files/3437774/ptvsd-3292.log)

**Comment by int19h** [comment]
When you run Flask in development mode, by default, it enables auto-reloading. The way that works, the main process that you start immediately spawns a child process, and that child process is what's actually running the web server and your code inside of it. When the main process detects any changes in the filesystem, it restarts the child process to reload those changes.

By default, ptvsd only debugs the process which it started, or which `ptvsd.enable_attach()` was invoked in - not any child processes that it spawns. Thus, it simply wasn't debugging any of your code - only the main Flask process.

When you added `"subProcess": true`, you enabled the (somewhat experimental) feature to automatically detect and attach to any Python child processes. If you look at the debug toolbar or the Stacks pane, you should see those multiple processes in it.

Alternatively, using `--no-reload` disables the Flask auto-reloading feature, and then everything runs in a single process. This is the [recommended way](https://code.visualstudio.com/docs/python/debugging#_flask-debugging) to debug Flask at the moment, because attaching to subprocesses is not 100% reliable on all OSes and Python versions. But your particular configuration - Python 3 on Windows - is the one that should work well in subprocess mode.
