### ISSUE TITLE
stopOnEntry broken when a excluded script loads an included script

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1636]
## Environment data

- PTVSD version: master
- OS and version: Any
- Python version (& distribution if applicable, e.g. Anaconda): Any
- Using VS Code or Visual Studio: VSCode

## Actual behavior

Does not stop on entry into scriptB.py

## Expected  behavior

Should stop on the first line of scriptB.py

## Steps to reproduce:
1. Let scriptA.py load ScriptB.py. Let script A and B be in different locations 

**scriptA.py:**
```py
import scriptB

print("in script A")
```

**scriptB.py:**
```py
print("in script B")
```

In the launch json, exclude the location of script A.
```js
{
    "name": "Terminal",
    "type": "python",
    "request": "launch",
    "pythonPath": "${config:python.pythonPath}",
    "program": "${file}",
    "cwd": "${workspaceFolder}",
    "console": "integratedTerminal",
    "stopOnEntry": true,
    "rules":[
        {"path": "C:\\scriptApath\\**", "include": false}
    ]
},
```

**Comment by fabioz** [comment]
I'm taking a look at this.

**Comment by fabioz** [comment]
I haven't been able to reproduce this. 

I did find some inconsistencies handling filenames in and provided a pull request for that in https://github.com/microsoft/debugpy/pull/67 and I added a test for what's described in this issue, so, although I haven't been able to reproduce this at least there'sa test which checks this use-case.
