### ISSUE TITLE
Bogus file "os.path^M" created during debug sessions

### ISSUE THREAD

**Issue by gatopeich** [microsoft/ptvsd#1645]
Issue Type: <b>Bug</b>

When debugging python tests with pytest, a file named "os.path^M" appears out of the blue in my workspace.

It contains contains a (corrupt) Postscript image created by ImageMagick:

```
%!PS-Adobe-3.0
%%Creator: (ImageMagick)
%%Title: (os.path
)
%%CreationDate: (2019-07-30T17:18:02+01:00)
%%BoundingBox: -0 -0 1148 1025
%%HiResBoundingBox: 0 0 1148 1025
%%DocumentData: Clean7Bit
%%LanguageLevel: 1
%%Orientation: Portrait
%%PageOrder: Ascend
%%Pages: 1
%%EndComments

%%BeginDefaults
%%EndDefaults

%%BeginProlog
%
% Display a color image.  The image is displayed in color on
% Postscript viewers or printers that support color, otherwise
% it is displayed as grayscale.
%
...
```

Since the file name contains a special char, I have searched for it in the complete .vscode folder... It only shows up in `ptvsd` .pyc files:

```
$ grep -r 'os.path\r' ~/.vscode
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/__pycache__/__init__.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydev_bundle/__pycache__/_pydev_imports_tipper.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/__pycache__/pydevd_file_utils.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/__pycache__/pydevd_frame.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/__pycache__/pydevd_resolver.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/__pycache__/pydevd_filtering.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__pycache__/ipcjson.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__pycache__/__main__.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/testing_tools/adapter/pytest/__pycache__/_discovery.cpython-37.pyc matches
Binary file ~/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/testing_tools/adapter/__pycache__/discovery.cpython-37.pyc matches
```

This happens in conjunction with [vscode issue #77807](https://github.com/microsoft/vscode/issues/77807)

Extension version: 2019.6.24221
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3518)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.31GB (3.20GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by karthiknadig** [comment]
This does not looks like a file that the debugger would generate. `os.path` is a standard python library that we use in the debugger, and i am not surprised you could find `os.path\r` in `*.pyc` files. But that seems unrelated to the file being generated here.

**Comment by gatopeich** [comment]
Well, I have many extensions there and only those contain `os.path^M`. Note that the use of ^M is rare on Linux.
Besides, this always happens during debug sessions...
If only I could put a breakpoint on file creation...

**Comment by fabioz** [comment]
Closing issue. Please reopen if you have more info.
