### ISSUE TITLE
Do not deprecate PTVSD_LOG_DIR

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1654]
Currently I'm initializing the env variable `PTVSD_LOG_DIR` for our UI Tests.
Would appreciate it if this is not deprecated in favour of the CLI arg.

Please feel free to close if there's no plan to drop `PTVSD_LOG_DIR`.
FYI - Currently the plan is to ONLY use this in UI Tests (on CI).
For the extension, we'll use the CLI arg (`--log-dir` or which ever is prescribed).

**Comment by int19h** [comment]
There's no plan to drop it anywhere - CLI is just another option, just like the optional argument to `ptvsd.enable_attach()` that we already have.
