### ISSUE TITLE
Programmatic way to launch DA

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1656]
The recommended way to launch the new DA (in Python is as follows):
`python.exe <ptvsd_dir>/adapter` 

Currently in VS Code we have some middleware (`ptvsd_launcher.py`).
This code is being updated to store the logic to determine the version of PTVSD (location, etc) to be used (when using the wheels).
We'd like to keep that around, rather than moving that code into `typescript` (**if possible**)

Hence launching the new DA would have to be done in python code.
Here's the existing [ptvsd_launcher.py](https://github.com/microsoft/vscode-python/blob/master/pythonFiles/ptvsd_launcher.py) file 

Please let us know how this needs to be done (what needs to be invoked) & this would probably need to be an official CLI.
FYI - Today we call `ptvsd.__main__.main(...)`

I guess this is what we'd be expected to do (please confirm):
```python
from ptvsd.adapter.__main__ import main
main(....)
````

**Comment by int19h** [comment]
`ptvsd.adapter.__main__.main(argv)` 

But it's best to use [`runpy`](https://docs.python.org/2/library/runpy.html). If you have a path to ptvsd/adapter/ already, don't even bother setting up PYTHONPATH etc; we can already handle all that. Just set `sys.argv` as needed, and then do:
```py
runpy.run_path(".../ptvsd/adapter")
```
Python itself will load `__main__.py` and invoke `main()` properly.

If you want to keep using the existing import-based logic to locate the right ptvsd package, then set up `sys.path` and `sys.argv`, and then:
```py
runpy.run_module("ptvsd.adapter")
```

**Comment by DonJayamanne** [comment]
Thanks, closing for now.
