### ISSUE TITLE
Attach to process on raspberrypi - Undefined item: "i386".

### ISSUE THREAD

**Issue by andlo** [microsoft/ptvsd#1677]
On a raspberry I am trying to get ptsvd working by attaching to running pid. But it fails.

It works if I start the python module with 
```
python -m ptvsd --host localhost -- port --5678 -m mymodule
```
But if alreddy having the module running and wanting to attach to the process by the --pid parameter it fails.
I cant figure out why or if it is a bug or the fact that this isnt made for arm arcihture.

I am dooing this when it fails:
```
pi@mycroft:~/mycroft-core $python -m ptvsd --host localhost --port 5678 --pid 27613
```
Getting this output:
```
Attaching with arch: i386
Running: gdb --nw --nh --nx --pid 27613 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture i386' --eval-command='call dlopen("/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_linux_x86.so", 2)' --eval-command='call (int)DoAttach(0, "import sys;sys.path.append(\"/home/pi/mycroft-core/.venv/lib/python3.5/site-packages\");sys.path.append(\"/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd\");import attach_script_ptvsd_pid;attach_script_ptvsd_pid.attach(port=5678, host=\"localhost\", client=False, log_dir=\"\");", 0)'
Running gdb in target process.
stdout: b'[New LWP 27642]\n[New LWP 27643]\n[New LWP 27644]\n[New LWP 27645]\n[New LWP 27646]\n[New LWP 27647]\n[New LWP 27648]\n[New LWP 27649]\n[New LWP 27650]\n[New LWP 27651]\n[New LWP 27652]\n[New LWP 27653]\n[New LWP 27654]\n[New LWP 27655]\n[New LWP 27656]\n[New LWP 28020]\n[New LWP 28021]\n[New LWP 28309]\n[New LWP 32685]\n[New LWP 32686]\n[Thread debugging using libthread_db enabled]\nUsing host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".\n0x76d3f674 in select () at ../sysdeps/unix/syscall-template.S:84\n$1 = 0\n'
stderr: b'84\t../sysdeps/unix/syscall-template.S: No such file or directory.\nUndefined item: "i386".\nNo symbol "DoAttach" in current context.\n'
```
where I notised 
```
Undefined item: "i386".
```
wich could pint in direction that it dosnt work on arm ut only i386 architures.

So is that correct it dosnt work, is it a bug/issue or am I simple missing something or dooing something wrong ?

**Comment by int19h** [comment]
Attaching by PID requires injection of a binary module into the running process, and the debugger only comes with them compiled for x86 and x64.

So, this is another item for #1674.

**Comment by int19h** [comment]
Note that if you don't have control over how the app is launched, but you can run your own code inside of it at some point, you can also use `ptvsd.enable_attach()` as a workaround.

**Comment by andlo** [comment]
OK - That makes sense. 

I have been trying to use `ptvsd.enable_attach()` but without any luck. It complaints with
`ValueError: signal only works in main thread `

So my only option for now is to run ptvsd and start the module (which then is loading my stuff I want to debug)

`ptvsd -m --host localhost --port 5678 -m <module>
`
But I were looking for a niser way to start debugging to avoid to stop the module from running and sten start it with debugging.

**Comment by int19h** [comment]
Can you please file a separate bug for that `ValueError`? That's definitely something that we should fix, but it should be tracked separately from ARM support for attach-to-PID.

**Comment by andlo** [comment]
> Can you please file a separate bug for that ValueError? That's definitely something that we should fix, but it should be tracked separately from ARM support for attach-to-PID.

I will file a separate bug for this

**Comment by int19h** [comment]
Closing, as we have separate issues to track ARM support.
