### ISSUE TITLE
Add ptvsd modules to DONT_TRACE

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#169]
pydevd has a list of files that are excluded from tracing in `pydevd_dont_trace_files.py`. It's a dict, so we can add our own entries to it after loading that module.

**Comment by karthiknadig** [comment]
Is this part of Just my code?

**Comment by int19h** [comment]
It would probably have to be done as part of JMC, but it looks like it might have some minor perf benefits outside of that, even if we just add hardcoded list of our .py files there.

**Comment by karthiknadig** [comment]
@int19h Files in that list have `pydevd_` prefix. We may need to put similar prefix `ptvsd_` for that to work correctly, without out accidentally hiding users' files. What do you think?
