### ISSUE TITLE
pydevd produces partial message writes

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1699]
(in dbg_adapter_refactor branch)

This is how it looks in the test:
```
I+01.250: ptvsd-6 stdout> b'end\r\n'

D+01.265: ptvsd-6 --> {
              "seq": 11,
              "type": "event",
              "event": "output",
              "body": {
                  "output": "end",
                  "category": "stdout",
                  "source": {}
              }
          }

D+01.265: ptvsd-6 --> {
              "seq": 12,
              "type": "event",
              "event": "output",
              "body": {
                  "output": "\n",
                  "category": "stdout",
                  "source": {}
              }
          }

E+00001.157: Couldn't read the expected 114 bytes of body:

             server -->
             b'Content-Length: 114'
             b''
             b''
```
Note that the first three log entries are done by the test, while the last one is from the adapter. They all correspond to `print("end")` in the test (`test_run`), immediately before the test code exits.

So, it looks like the server was writing the "exited" event, but dropped the connection before it was actually fully transmitted? I think this might have to do with some kind of buffering (possibly lack of `TCP_NODELAY`?).

This is sporadic in all attach tests.

**Comment by int19h** [comment]
Side note: this is not necessarily a regression from past behavior. The code that used to read messages in `JsonIOStream` previously just treated this as a normal EOF condition on the stream - so it might have been occurring all along, and we just never noticed it. I added detection of this kind of stuff as part of messaging refactoring, so now a partial message read is a hard error.

**Comment by int19h** [comment]
@karthiknadig pointed out that this is unavoidable in general if the server crashes or is force-killed, because that can still happen mid-write. So the adapter has to allow it. I'm going to switch this log it as warning, but otherwise treat it as EOF on the stream.

However, we should see if it's possible to avoid torn message writes in normal conditions - i.e. if it shows up in the log on the adapter side, it should be considered a red flag, not a normal occurrence (unless the test is specifically testing force-killing the server).

**Comment by fabioz** [comment]
Is this still an issue in the current version?
