### ISSUE TITLE
Column number in stackTrace should not be '0'

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#170]
Currently column number in the handler `on_stackTrace` is hardcoded to `0`.
Based on the protocol, if the value is `0`, then its an indication that the column number is to be ignored:
[/** The column within the line. If source is null or doesn't exist, column is 0 and must be ignored. */](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L1223)

Here's the hardcoding:
['line': line, 'column': 0,](https://github.com/Microsoft/ptvsd/blob/master/ptvsd/wrapper.py#L684)

Why does this matter?
* When the value is `0`, the exception widget is not displayed in VS Code
Here's the widget I'm referring to:
<img width="575" alt="screen shot 2018-03-04 at 10 50 14 pm" src="https://user-images.githubusercontent.com/1948812/36961047-6efdbf8a-1ffe-11e8-824c-52be0f95cba1.png">

**Comment by int19h** [comment]
I suppose we can hardcode it to 1 instead - I don't think there's any trivial way to actually map the current statement properly to the range of columns that it was parsed from. But also, why wouldn't VSCode show this when column is not specified? It seems like they only need the line anyway?

**Comment by DonJayamanne** [comment]
> But also, why wouldn't VSCode show this when column 

I guess the rationale is, column number and line number must be valid for a block of code to be defined. Makes sense if that's the logic.
