### ISSUE TITLE
Refactor branch: design changes to support os.fork

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1703]

**Comment by karthiknadig** [comment]
Extension version with support for debug adapter.
[ms-python-insiders.zip](https://github.com/microsoft/ptvsd/files/3522452/ms-python-insiders.zip)

**Comment by int19h** [comment]
Initial research and design is complete, and we are going with the Right Thing approach over the minfix. This requires some pydevd changes, and also changes to the adapter to handle multiple debug servers, and allow multiple connections from the IDE. I'll create separate work items for these.
