### ISSUE TITLE
pydevd: explicit host/port for subprocesses to connect to

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1707]
When pydevd detects a child process spawn and detours it, the child process currently connects to the same socket to which the parent process was connected.

To support #1706 in `enable_attach()` scenarios, the child process needs to be able to connect to a host/port that is explicitly specified, and not assumed to be the same.

The parent process will receive this information via a new property in the "launch" or "attach" request, e.g.:
```json5
"subProcesses": {
  "clientHost": "127.0.0.1",
  "clientPort": 7944,
}
```
(We'll use this property to aggregate all information that needs to be communicated to the parent about how it should handle the children, to avoid proliferation of top-level properties in debug config.)

It should propagate this information to the child process by whatever means are appropriate for the API used to spawn it - that part is considered pydevd implementation detail.

**Comment by fabioz** [comment]
Note: on hold (waiting for e-mail feedback).
