### ISSUE TITLE
pydevd: reconnect listener

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1708]
It should be possible to start pydevd in the mode whereby it opens a listener socket for incoming DAP connections, regardless of the direction of the first connection that it establishes to the client (i.e. even if it's pydevd -> client, and not client -> pydevd). That listener socket should refuse connections for as long as there is one already active, but should accept new connections otherwise.

To enable this mode, we'll use a custom property in the "initialize" request:
```json5
{
  ...
  "command": "initialize",
  "arguments": {
    ...
    "pydevd": {
       "serverHost": ...,   // default "127.0.0.1"
       "serverPort": ...,   // can be 0 to pick an available ephemeral port
    }
  }
}
```
(we'll use the same top-level property for any other custom pydevd-related initialization bits in the future)

The listener socket is enabled if "serverPort" is specified - to pick some available free port, the other side must pass 0.

pydevd must open the listener socket and invoke `listen()` on it _before_ sending the "initialize" response. The response should contain information about the host and the port on which the socket is actually listening, as returned by `getsockname()` (which might be different from inputs in case "0.0.0.0" or :0 are used):
```json5
{
  ...
  "command": "initialize",
  "success": true,
  "body": {
    ...
    "pydevd": {
       "processId": ...,    // pid of the child process
       "serverHost": ...,   // actual host
       "serverPort": ...,   // actual port
    }
  }
}
```

**Comment by int19h** [comment]
It would also be nice to always include "processId" as a property in "initialize", even in non-multiproc scenarios. This will make it a little bit easier to handle this all uniformly in the adapter.

**Comment by fabioz** [comment]
Note: on hold (waiting for e-mail feedback).
