### ISSUE TITLE
"runInTerminal" is broken on non-Windows platforms

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1721]
(dbg_adapter_refactor branch)

On platforms other than Win32, `os.waitpid()` cannot be used to wait on a process that isn't a child process, to obtain its exit code. When the process is launched via "runInTerminal" request, it is a child process of VSCode, not a child process of the adapter. Thus, the adapter cannot track those processes, and cannot detect when they exit in nodebug scenario, since there's no connection.

The launcher needs to keep track of the process instead, and notify the adapter.

**Comment by karthiknadig** [comment]
Done
