### ISSUE TITLE
Output is not captured in "noDebug" with "runInTerminal"

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1722]
Output capture is done by the adapter when it spawns the process. Since "runInTerminal" has the IDE spawn the process instead, there's no way for the adapter to do output redirection.

Instead, launcher should capture the output, and send it over to the adapter.

**Comment by int19h** [comment]
Best combined with #1721 implementation-wise.

**Comment by karthiknadig** [comment]
Done
