### ISSUE TITLE
Error launching 5.0.0a3 debugger

### ISSUE THREAD

**Issue by ygbr** [microsoft/ptvsd#1734]
## Environment data

- PTVSD version: 5.0.0a3
- OS and version: macOS 10.14.6
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.4 (brew)
- Using VS Code or Visual Studio: 1.38.0-insider

## Actual behavior

When launching the pre-release version of ptvsd debugger from VSCode Insiders I get the following error:

```
Traceback (most recent call last):
  File "/Users/yg/.vscode-insiders/extensions/ms-python.python-2019.10.33645-dev/pythonFiles/ptvsd_launcher.py", line 22, in <module>
    from ptvsd.__main__ import main
ImportError: cannot import name 'main' from 'ptvsd.__main__' (/usr/local/lib/python3.7/site-packages/ptvsd/__main__.py)

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

Press Enter to close. . .
```

## Expected  behavior

Debugger should launch normally

## Steps to reproduce:
1. Install ptvsd bleeding edge with pip3 (pip3 install -U ptvsd --pre)
2. Create the launch.json as mentioned below
3. Launch debugger
4. The error pops immediately

## launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Debugger",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/wsgi.py",
            "showReturnValue": true,
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",
            "customDebugger": true,
            "env": {
                "PYTHONPATH": "/usr/local/bin"
            }
        }
    ]
}
```

**Comment by karthiknadig** [comment]
@ygbr the python extension does not support the pre-release version yet (they are working on it). The  5.0.0.a3 is `alpha` and it is limited in functionality. We recommend using 4.* until the `beta` for ptvsd 5 is released.
