### ISSUE TITLE
Failed lookup for key [] in {} Exception in Templates Intermittently

### ISSUE THREAD

**Issue by delizin** [microsoft/ptvsd#1735]
**Describe the bug**
I am getting intermittent exceptions thrown from my django template pages when running my project in debug mode after upgrading to VS 2019. I have disabled all "Break when Thrown" settings and these messages are still popping up. 

It is completely unpredictable when they are going to happen, but they occur very regularly when opening a template. If I stop debugging and relaunch that exact same template, there is a good chance it will work that time. 

Having to constantly restart the debug multiple times to load a page is really killing my productivity.

**Steps to Reproduce**
1. Have a large django project with templates
2. Run Debugger
3. Cycle through different template pages until bug occurs

**Expected behavior**
No exceptions should be thrown in these circumstances. 

**Additional context and screenshots**
![VS-fucking-with-me](https://user-images.githubusercontent.com/6344447/63818127-b1b12080-c8fc-11e9-913e-3af3d6c7bd13.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.2.1
PTVS version: 16.2.19178.1
Python version: 3.7
Debugger Type (if applicable): Default Debugger

**Diagnostics file**
Emailed to ptvshelp@microsoft.com

**Comment by karthiknadig** [comment]
@delizin Add following environment variables to your project:
```
PTVSD_LOG_DIR=C:\logs
PYDEVD_DEBUG=True
PYDEVD_DEBUG_FILE=C:\logs\pydevd.log
```
Ensure that **C:\logs** directory exists. Note that this will generate several `ptvsd-<pid>.log` files. When the issue occurs, stop debugging and share the latest `ptvsd-<pid>.log` and `pydevd.log` files. Remove any personal information from the log files.

**Comment by delizin** [comment]
Here are the requested logs:
[pydevd.log](https://github.com/microsoft/ptvsd/files/3561096/pydevd.log)
[ptvsd-259640.log](https://github.com/microsoft/ptvsd/files/3561097/ptvsd-259640.log)

Just to add to this report a little bit: The exception seems to occur when the requested variable in a django template does not exist, however it does not always fire the false exception. Using variables that might not exist is common practice with django templates and the template engine replaces all non-existent variables with empty strings. Here is the documenation on this behavior: https://docs.djangoproject.com/en/2.2/ref/templates/language/#variables

**Comment by karthiknadig** [comment]
@fabioz Looks like the debugger is not respecting the exceptionOptions.
```js
{
    "command": "setExceptionBreakpoints",
    "arguments": {
        "filters": [],
        "exceptionOptions": [
            {"path": [{"names": ["Python Exceptions"]}], "breakMode": "userUnhandled"},
            {
                "path": [
                    {"names": ["Python Exceptions"]},
                    {
                        "names": [
                            "GeneratorExit",
                            "IndexError",
                            "StopIteration",
                            "AttributeError",
                            "KeyError",
                        ]
                    },
                ],
                "breakMode": "unhandled",
            },
        ],
    },
    "type": "request",
    "seq": 1000000003,
}
```
It seems to treat `VariableDoesNotExist` as on raised (`always`), when it should be `userUnhandled` (which for us is just `unhandled`):
```js
{
    "type": "response",
    "request_seq": 1000000008,
    "success": true,
    "command": "exceptionInfo",
    "body": {
        "exceptionId": "VariableDoesNotExist",
        "breakMode": "always",
        "description": "Failed lookup for key [name] in 'None'",
        "details": {
            "message": "Failed lookup for key [name] in 'None'",
            "typeName": "VariableDoesNotExist",
            "stackTrace": '  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 903, in _resolve_lookup\n    (bit, current))  # missing attribute\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 849, in resolve\n    value = self._resolve_lookup(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 708, in resolve\n    obj = self.var.resolve(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 1040, in render\n    output = self.filter_expression.resolve(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 957, in render_annotated\n    return self.render(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 957, in render_annotated\n    return self.render(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 990, in render\n    bit = node.render_annotated(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 957, in render_annotated\n    return self.render(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 990, in render\n    bit = node.render_annotated(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 957, in render_annotated\n    return self.render(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 990, in render\n    bit = node.render_annotated(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 957, in render_annotated\n    return self.render(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 990, in render\n    bit = node.render_annotated(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py", line 207, in render\n    return self._render(context)\n  File "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\dashboard\\views.py", line 71, in dashboard\n    return render(request, \'dashboard/dashboard.html\', context)\n',
            "source": "C:\\Stuff\\Projects\\DjangoProject\\DjangoProject\\env\\Lib\\site-packages\\django\\template\\base.py",
        },
    },
    "seq": 42,
    "pydevd_cmd_id": 502,
}
```

**Comment by fabioz** [comment]
@karthiknadig this happens because django-related exceptions are "special" -- looking at the code, if the `django debug` mode is turned on (which is needed for breakpoints in templates), then we'll always handle django-related exceptions if either `handled` or `unhandled` is selected -- related code: https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py#L595.

The exception itself seems to be properly handled (it's actually generated inside of django, but it's ignored by the template engine... sometimes the user wants to see it and sometimes he doesn't).

Maybe there should be a separate setting for `django exceptions` (instead of just python-handled / python-unhandled)... ideally we'd just provide that mode when `django debug`  mode is turned on in the settings, but it seems we need to return that on initialize (before those options are sent), so, this may not be feasible.

We may also want to actually split the django exceptions in more parts to give the user a way for deciding which exception should be traced (i.e.: `VariableDoesNotExist` seems something that may be ignored or not, but `TemplateDoesNotExist` or `TemplateSyntaxError` should be shown regardless of that).

@delizin possible workarounds until a fix is done are:

- Disabling the handling for both handled and unhandled exceptions.

- Changing that `if break_raised or break_uncaught` to an `if False` in:
https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py#L595

- Disabling the django debug mode from your settings (although in this case you won't be able to add breakpoints to templates too).

**Comment by int19h** [comment]
https://github.com/microsoft/debugpy/issues/128
