### ISSUE TITLE
refactor branch: pydevd should not close socket connection on disconnect

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1738]
The connection between debug adapter and debug server should not be closed. Disconnect should continue execution as though debugger is not attached. Upon re-attach, debug adapter will not have to re-establish the connection. This is especially handy for multi-proc re-attach.

/cc @int19h

**Comment by fabioz** [comment]
@karthiknadig I thought that `pydevd` never closed the connection on its side on a `disconnect` request (unless the program actually stopped)... so, can you give more details on what's being done exactly that's disconnecting the socket on the `pydevd` side?

**Comment by karthiknadig** [comment]
I see. If this is the case that we can close this item.

**Comment by int19h** [comment]
The important part here is that the connection should recognize an "initialize" request as the start of a new debug session, _as if_ the socket connection was closed and then re-established. Will the existing code handle that?

**Comment by fabioz** [comment]
Yes, it should recognize that already.
