### ISSUE TITLE
enable_attach isn't establishing a connection

### ISSUE THREAD

**Issue by jpenna** [microsoft/ptvsd#1740]
## Environment data

- PTVSD version: 5.0.x
- OS and version: Ubuntu 19
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
- Using VS Code or Visual Studio: VS Code

## Actual behavior

I run `ptvsd.enable_attach(address=('127.0.0.1', 5678))` from my code to allow the debugger to connect, but when I start the debugger there is no connection. 

Just to make sure, I used `ptvsd.wait_for_attach()` and it never started the application, just stood there waiting for the debugger.

## Expected  behavior

Should connect. 

It was working before, so I rolled back to `4.3.2` and now I can use it again.

## Steps to reproduce:

1. Include this at the entrypoint of the application:
```py
import ptvsd
ptvsd.enable_attach(address=('127.0.0.1', 5678))
ptvsd.wait_for_attach()
```

2. Setup `launch.json`.
```
{
      "name": "Python: Remote Attach",
      "type": "python",
      "request": "attach",
      "port": 5678,
      "host": "localhost",
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "."
        }
      ]
    }
```
3. Start the application (I'm using uvicorn: `uvicorn main:app --reload --port 23400`).

4. Start the debugger.

The application will keep waiting forever.

**Comment by jpenna** [comment]
Maybe related to #1712

**Comment by karthiknadig** [comment]
@jpenna ptvsd == 5.0.0a3 is `alpha` version. The python extension currently does not support that version. I recommend waiting till the extension supports it and ptvsd is in `beta` to test it out.

If you really want to try it is what you have to do:
1. start your script
2. Run `python -m ptvsd.adapter --debug-server 8765` or `python <path-to-adapter-dir> --debug-server 8765`
3. Use this in launch.json: Note the **debugServer** below, that by-passes extensions debug adapter implementation.
```js
{
      "name": "Python: Remote Attach",
      "type": "python",
      "request": "attach",
      "debugServer": 8765
      "port": 5678,
      "host": "localhost",
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "."
        }
      ]
    }
```

**Comment by jpenna** [comment]
Thank you @karthiknadig! 

I am fine with the previous version. If if it a known issue for the alpha version, that's ok. Thanks for the quick reply!
