### ISSUE TITLE
No stack trace when exception is thrown from a generator expression (in unhandled exceptions)

### ISSUE THREAD

**Issue by karrtikr** [microsoft/ptvsd#1744]
@fj128 commented on [Fri Aug 30 2019](https://github.com/microsoft/vscode-python/issues/7156)

## Environment data

- VS Code version: 1.37.1
- Extension version (available under the Extensions sidebar): 2019.8.30787
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.4 32bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: XXX
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Jedi

## Steps to reproduce:

    def f():
        # return [1/0 for c in '123']
        return list(1/0 for c in '123')
    f()

## Expected behaviour

Same as when the first line is uncommented:

    Exception has occurred: ZeroDivisionError
    division by zero
      File "C:\test.py", line 2, in <listcomp>
        return [1/0 for c in '123']
      File "C:\test.py", line 2, in f
        return [1/0 for c in '123']
      File "C:\test.py", line 4, in <module>
        f()

## Actual behaviour

No rest of the stack trace in the exception popup or in the stack trace pane:

    Exception has occurred: ZeroDivisionError
    division by zero
      File "C:\test.py", line 3, in <genexpr>
        return list(1/0 for c in '123')

By the way, dictcomp and setcomp work correctly too. When I press F5 again to run the program to the bitter end, python itself prints the stack trace correctly.

**Comment by fabioz** [comment]
Fixed in the refactor branch in:
https://github.com/microsoft/ptvsd/commit/8efec2b3f63747be716d7872e2c44d8183eff9e3
