### ISSUE TITLE
Variable inspector doesn't update for code run via "Debug: Evaluate"

### ISSUE THREAD

**Issue by karrtikr** [microsoft/ptvsd#1745]
@EdwardJB commented on [Sat Aug 31 2019](https://github.com/microsoft/vscode-python/issues/7169)

## Environment data

- VS Code version: 1.37.1
- Extension version (available under the Extensions sidebar): 2019.8.30787
- OS and version: Windows 10 1903 [remote Ubuntu 18.04 via WSL]
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Pyenv

## Expected behaviour

Variable inspector should update to reflect code run via "Debug: Evaluate"

## Actual behaviour

It doesn't update.

## Steps to reproduce:

- Start debugging a file containing just `a=1` with a breakpoint at that line.
- When you hit the breakpoint, select the text, right click and choose "Debug: Evaluate".
- The variable inspector does not update to reflect the new variable assignment `a=1`.
- However entering anything (including an empty line) at the Debug Console input box causes the variable inspector to update.
- Also, simply typing, say, `b=2` at the same box causes the inspector to update with `b=2` immediately, as expected.

**Comment by karthiknadig** [comment]
This was a bug in VSCode itself https://github.com/microsoft/vscode/issues/78299 .
