### ISSUE TITLE
Unexpected behavior when debugging standard library

### ISSUE THREAD

**Issue by geajack** [microsoft/ptvsd#1751]
## Environment data

- VS Code version: 1.37.1
- Extension version (available under the Extensions sidebar): 2019.8.30787
- OS and version: Regolith (Ubuntu 19.04)
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: asyncio
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): true

## Steps to reproduce:
Create a Python module to run `asyncio` code:
```
import asyncio

async def main():
    print("Hello, world!")

if __name__ == "__main__":
    asyncio.run(main())
```
Create the following launch configuration:
```
{
            "name": "Debug",
            "type": "python",
            "request": "launch",
            "module": "main",
            "justMyCode": false
}
```
Place a breakpoint at `/usr/lib/python3.7/asyncio/base_events.py:405`, then launch the debugger with Python 3.7. You will arrive at the line:

```
task = tasks.Task(coro, loop=self)
```

Click the "step in" button.

## Expected behaviour
You arrive at the first line of `tasks.Task.__init__`.

## Actual behaviour
You arrive at `/usr/lib/python3.7/asyncio/base_events.py:1794`, in `BaseEventLoop.get_debug`.

## Logs
No output in Developer console or Output console.

---

I can't see any obvious reason for this. According to the debugger, the symbol `tasks.Task` points to the `Task` class, it hasn't been overwritten or anything. Nobody's overriding `__call__`. Is this a bug in the debugger?

**Comment by fabioz** [comment]
I just checked and the behavior seems correct -- `asyncio.Task` is actually from the native `_asyncio` module, so, we can't really step into it because it's not pure-python code.

If you replace the lines:

`import _asyncio` with `raise ImportError()` in `asyncio/tasks.py`, when stepping in you do get where you expect.

So, closing because things are working as expected here.
