### ISSUE TITLE
Disconnect and reconnect via pid should work when using --client mode

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1760]
Currently you can attach to a process by pid. But detach and re-attach fails. when using --client.

**Comment by fabioz** [comment]
@karthiknadig @int19h I think that the idea is that disconnect/reconnect would keep the socket open, in which case I think this should work without any changes... is that correct or am I missing something?

What we may have to look into is doing attach to pid, closing both and doing another attach to pid (I'm not sure whether that works or not... we probably should have tests for that, but doesn't seem something very usual, so, it's probably not high priority).

**Comment by karthiknadig** [comment]
This is how we currently do attach to pid.
1. User starts the debug session.
2. IDE starts the adapter
3. IDE provides the `pid` via `attach` request.
4. Adapter starts a listener and runs the code injector.
5. Injected code loads and runs the debugger and connects back to adapter.

If the user disconnects at this point then, VSC could terminate the adapter. If we want to have a continued connection with the attached process then it cannot be with the adapter that was launched by the IDE.

**Comment by fabioz** [comment]
> If the user disconnects at this point then, VSC could terminate the adapter. If we want to have a continued connection with the attached process then it cannot be with the adapter that was launched by the IDE.

I was under the impression that if the user just disconnects (without terminating), the adapter would be kept alive... isn't this the case?

**Comment by karthiknadig** [comment]
@int19h Since you have looked at the adapter lifetime part more, you might have more context on this. 

My understanding is this, IDE always launches adapter and terminates it. For most other attach scenarios where we depend on `host` and `port`. The adapter is actually started by user bey either calling `enable_attach` or using command line which starts the adapter indirectly via enable attach. But this case is different. In this particular case, it is like a hybrid of launch and attach. The IDE launches the adapter, which launches the code injector, and the debugger connects back. So the adapter can get terminated as in a `launch` scenario. But the Users should be able to re-attach as in a attach scenario.

This gets even more complicated when we throw in multiproc in to the mix. For now, the bug here is that re-injecting the same debugger startup code should not fail. Currently it fails.

The larger issue of handling multiproc in the scenario is a rare case and we can handle it later.

**Comment by fabioz** [comment]
@karthiknadig is it already possible to use `--client` with vscode (in the refactor branch)?

If it is possible, can you pass me some instructions on how it should be used?

**Comment by int19h** [comment]
It should be possible, but it is completely untested.

You can do this in launch.json:
```json5
"request": "attach",
"host": ...,
"port": ...,
"listen": true,
```

This last bit will make the adapter open a listener socket and wait for incoming connection on spawn, instead of connecting. Then `--client` or `ptvsd.attach()` can be directed to attach to that port.

**Comment by fabioz** [comment]
@int19h Thanks... I couldn't get it to work with that (so, maybe it's not really working or I need to get some insiders version for this to work?)

I did find an issue where disconnecting only in the `pydevd` side stops the debug session (and it can't be restarted), so, I'm taking a look at that, but it'd be nice to also manually test it to make sure I'm covering the same case.
