### ISSUE TITLE
Logpoint messages aren't printed for "launch"

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1769]
For breakpoints with "logMessage", when they're hit, pydevd sends an "output" event with `"category": "stdout"`, but doesn't actually print that message to stdout. Since we're now capturing the output directly from the process for launch scenarios, this means that the event from the server is ignored by the adapter on the assumption that launcher will supply more accurate output. In this case, the assumption doesn't hold, but the IDE ends up never receiving that message.

I can see three options to handle this.

1. Send output with `"category": "console"` instead. This shouldn't make any practical difference in the UI - it will show up in the Debug Console, but not in the terminal, same as it is today - but such events will always be propagated by the adapter, since it only relies on the launcher for stdout/stderr.

2. Add a custom property to "output" events that pydevd can use to mark synthetic ones that do not correspond to any actual output. The adapter would then check that property, and always propagate such events, even if the launcher is capturing actual stdout/err.

3. Don't synthesize the events, but rather just print the message directly to stdout. This will make it show in the terminal. 

It seems that the second option isn't really adding anything useful, and the choice between 1 and 3 depends on whether we want logpoint messages to show up in the terminal, or only in Debug Console.

The DAP spec doesn't say anything about this, but so far we've been doing the equivalent of 1. This feels more reasonable, since it doesn't affect the observable behavior of the app; e.g. imagine if it is debugged with its stdout redirected to be parsed by some other app - logpoints being actually printed would mess that up.

**Comment by int19h** [comment]
`test_log_point` currently fails in the refactor branch due to this bug.

**Comment by karthiknadig** [comment]
I think option 1 is OK.
@fabioz /cc

**Comment by fabioz** [comment]
I think doing this change is ok (so that we have a way to know what's generated from the debugger and what comes from the user output), but, regardless of that, the way I see it, on launch scenarios we should not be redirecting the output at all (i.e.: in which case the adapter would not receive any `output` events for user output anyways).

**Comment by int19h** [comment]
Oh, so basically, just don't propagate "RedirectOutput" debug option to pydevd for "launch"?

**Comment by fabioz** [comment]
> Oh, so basically, just don't propagate "RedirectOutput" debug option to pydevd for "launch"?

Yes

**Comment by int19h** [comment]
Indeed! Doing this, and propagating all remaining (i.e. synthetic) "output" events from the server, fixes the original issue.

We do have a different problem though... since regular output and logpoint output is now captured differently, this means that logpoints get out of sync wrt output. E.g. if you do:
```py
print("foo")
something()  # logpoint here that prints "bar"
print("baz")
```
the end result is sometimes `"foo\nbaz\nbar"`. 

Fixing this properly would be complicated and slow - the logpoint code in pydevd would need to synchronize with the output capture in adapter, basically. One way to do it would be to pause all threads, flush stdout/stderr, report the logpoint as a reverse request, and then wait for response. The adapter would then have to capture whatever is pending in stdout/stderr streams, then finally report logpoint as "output" to the IDE, and respond to pydevd. Only then it can unpause and allow the code to continue running and producing more output. 

I don't think it's worth it, especially if we're going to switch logpoints to a different output category anyway. For now, I'll just change the test so that it doesn't expect logpoint output to have strict ordering relative to regular output.

**Comment by fabioz** [comment]
@int19h @karthiknadig given that the output is no longer redirected, should the change to use "category": "console" for logpoints be done?

**Comment by karthiknadig** [comment]
This is not needed anymore.
