### ISSUE TITLE
Refactor branch: Remove all usage of debug_options

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1770]
We plan on deprecating `debug_options`. It was there to support the old way of VS passing the debug options. Going forward all settings will be read directly as json settings.

@DonJayamanne : I saw the subProcess setting was changed to autoAttachChildProcesses. When such changes occur you may have to proxy the new setting to set the old setting until debugger is updated. i.e., if users set autoAttachChildProcesses then you should pass both autoAttachChildProcesses and subProcess. Feel free to push back on preserving debug_options.

**Comment by int19h** [comment]
All the logic in the adapter now uses properties, with a fallback to "debugOptions" for backwards compatibility. The remaining work is to do the same for pydevd.

**Comment by int19h** [comment]
https://github.com/microsoft/ptvsd/issues/1770
