### ISSUE TITLE
Use setDebuggerProperty and getDebuggerProperty to set states.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1782]
Currently we are overloading the "initialize" request to handle some additional info. We shoudl move that to `setDebuggerProperty` and add `getDebuggerProperty`. Things such as:
1. Access tokens
2. Debuggee process ID
3. Adapter server port, for `enable_attach((host, 0)` case.

/cc @int19h @fabioz

**Comment by int19h** [comment]
With access tokens, we need to think this through. They're not just informational - pydevd actually validates the server access token it receives on "initialize", and this allows it to fail the initialization request and thus effectively reject that session. If it's done via debugger properties, it means that the token will be a special one that always have to be set first, before any other message in the session.

Perhaps it would be better to have a distinct "pydevd_authorize" request here, just for that token exchange, both for the sake of protocol clarity, and ease of implementation on pydevd side? And then PID and port number can be debugger properties.

**Comment by int19h** [comment]
Access tokens are going to be a separate message: #1829 

Debuggee PID and parent PID is already handled by "pydevd_systemInfo".

Adapter port that listens for IDE connection was covered by #1784.
