### ISSUE TITLE
Support completionTriggerCharacters

### ISSUE THREAD

**Issue by brettcannon** [microsoft/ptvsd#1785]
https://code.visualstudio.com/updates/v1_38#_debug-adapter-protocol

**Comment by int19h** [comment]
The default for it is "." - is there any other character that we want to trigger completions on?

**Comment by brettcannon** [comment]
🤷‍♂️

**Comment by int19h** [comment]
@luabud, are there any specific requests to change the current behavior? If we only want the dot to serve as a completion char, we don't need to do anything.

**Comment by luabud** [comment]
I think "." is fine. Anything other than that could be annoying.
