### ISSUE TITLE
Debugger fails on Gunicorn Launched Application

### ISSUE THREAD

**Issue by mikeboulet** [microsoft/ptvsd#1793]
## Environment data

OSX 10.14.6
VSCode 1.38.1
VS Code Python Extension: 2019.9.34911
Python: 3.7.4
ptvsd==4.3.2
gunicorn==19.9.0

## Actual behavior

When attaching to the Gunicorn launched Python application the debugger connects successfully but then fails immediately with the error "Debug adapter process has terminated unexpectedly". The debugger tool bar shows for a second then disappears.

## Expected  behavior

Expected the debugger to show my application code and it stopped on my breakpoint.

## Steps to reproduce:
Insert code following code in the app.py

import ptvsd
print("Waiting for debugger attach")
ptvsd.enable_attach(address=('localhost', 5678), redirect_output=True)
ptvsd.wait_for_attach()
breakpoint()

run the following
gunicorn --reload --timeout 3600 --workers 1 --bind :8080 my.app

VsCode -> Debug -> Start Debugging

launch.json
`
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "My App: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/app"
                }
            ]
        }
    ]
}
`

**Comment by karthiknadig** [comment]
Minor thing, can you add a `print('done')` after `breakpoint()`. The way we have breakpoint hooked up, it always stops at the next line. The assumption there is we want the line that will be executed next to be highlighted in the UI.
```py
import ptvsd
print("Waiting for debugger attach")
ptvsd.enable_attach(address=('localhost', 5678), redirect_output=True)
ptvsd.wait_for_attach()
breakpoint()
print('done')
```

**Comment by mikeboulet** [comment]
Same behavior. Debugger tools show for a second and then disappear. Is
there some kind of log file I can look at that may provide more details?

**Comment by karthiknadig** [comment]
You can enable debugger logging by settings the following environment variables:
```
PTVSD_LOG_DIR=/logs
PYDEVD_DEBUG=True
PYDEVD_DEBUG_FILE=/logs/pydevd.log
```
That should generate a couple of  log files. Please share them, be sure to remove any personal info from the logs. 

I am not able to repro this, so yes logs will definitely be helpful:
![image](https://user-images.githubusercontent.com/3840081/65343739-9ac3be00-db8a-11e9-8d23-a8bc268c1f36.png)

Without the print:
![image](https://user-images.githubusercontent.com/3840081/65343893-09088080-db8b-11e9-9e30-9f8c1c55ac08.png)

**Comment by mikeboulet** [comment]
I just realized that I'm technically not running PTVSD in OSX but under
Linux. Sorry for the confusion.
I'm using something similar to the attached Dockerfile. I'm loading that
image through a docker-compose file with something like the following:

services:
  app:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    env_file: .env

    ports:
      - "127.0.0.1:5678:5678"

**Comment by mikeboulet** [comment]
Sorry the file attachments didn't make it:
[Archive.zip](https://github.com/microsoft/ptvsd/files/3637032/Archive.zip)

**Comment by karthiknadig** [comment]
When running in the container, `enable_attach` you should use `0.0.0.0`. Otherwise the server will not accept connection from outside the container.

**Comment by mikeboulet** [comment]
That was the solution! Works perfectly!

I apologize for wasting your time on that one.

**Comment by jonespm** [comment]
I think I might have had the same issue but I also had --workers 4 which caused the enable_attach to stop with the error
`gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>`
and I didn't notice
`OSError: [Errno 98] Address already in use`

It starts up with 1 worker, which seems fine, I'll try it out with this configuration. Thanks!

**Comment by karthiknadig** [comment]
@jonespm when you use multiple workers. They all try to open the same port 5678. So only one worker wins.
