### ISSUE TITLE
Set Next Statement

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#18]
Need to implement `goto` request.

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/233060/set-next-stament-disabled-in-python-debugging.html

**Comment by karthiknadig** [comment]
This feature is not implemented in the adapter host yet. VSC does not have this feature on their road map either. This is only needed in VS to reach parity.

**Comment by karthiknadig** [comment]
The pending items here are handle `on_goto` and  `on_gotoTargets`

**Comment by huguesv** [comment]
Another request at https://developercommunity.visualstudio.com/content/problem/443064/python-debugger-set-next-statement.html
