### ISSUE TITLE
Adapter doesn't exit if IDE doesn't attach

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1805]
When not using `--wait` or `wait_for_attach()`, if the debuggee exits before the IDE has a chance to connect to the adapter, the adapter hangs around waiting for connection.

**Comment by int19h** [comment]
Basically, when debuggee exits, the adapter needs to also close all the listener sockets (this should abort any pending `accept()` calls with an exception that can be caught).

Once we get to multiproc, it should do this when the _last_ debuggee exits.

**Comment by karthiknadig** [comment]
May be we now have a use for `wait_for_multiple_events` ;) ?

**Comment by int19h** [comment]
Fixed by https://github.com/microsoft/ptvsd/pull/1878 - the adapter no longer waits for IDE at startup in general, exit logic is hinged on existence of IDE and server connections.
