### ISSUE TITLE
"ideOS" is not auto-detected from "pathMappings"

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1812]
In the old implementation, we had this bit:
https://github.com/microsoft/ptvsd/blob/a0e3cbcb3020c53f7df3457517e8a291380b49c2/src/ptvsd/wrapper.py#L1021-L1036
Note the part that tries to figure it out from the slashes and backslashes in mappings. We don't have this in the new adapter:
https://github.com/microsoft/ptvsd/blob/74a85855ad61a206bebcd238e778d2f06c516d2e/src/ptvsd/adapter/ide.py#L163-L168

This breaks `test_client_ide_from_path_mapping_linux_backend`, which expects such auto-detection.

**Comment by karthiknadig** [comment]
The idea was that client OS will be sent via the adapter. There is no need to detect the client OS using paths. Ideally, this should be part of the debug Config. So, VSCode or any IDE should add the `ideOS` field to the debug config.

**Comment by int19h** [comment]
In this case, should we just remove the test? Or is there something else that it's testing aside from this auto-detection?
