### ISSUE TITLE
Use pydevd attach  scripts instead of attach_script_ptvsd_pid

### ISSUE THREAD

**Issue by fabioz** [microsoft/ptvsd#1815]
I had previously submitted this as a comment (in  https://github.com/microsoft/ptvsd/pull/1747/files/6694e70e63a1b49663fa2c7588ed68db89a9e0fa), so making an issue for it (to see whether it should be done or not).

I was thinking about this and this whole code is pretty much a copy of `pydevd_attach_to_process/attach_pydevd.py` and `pydevd_attach_to_process/attach_script.py`... if multiprocessing will work with the plain `pydevd` attach later on, maybe this code shouldn't be needed (we may need to have multiprocessing done first so that this works though).

i.e.: it could use `pydevd_attach_to_process/attach_pydevd.main()` just passing the proper `port` and `pid` to connect to an adapter that'd be waiting for the connection and then do the same handshake that `multiprocessing` will do (right now it doesn't have the mode to wait for an incoming connection, but that should be easy to do).

We don't necessarily need to do this now, but it may be worth doing it in the future so that we don't have to change both places if some change is needed.

**Comment by int19h** [comment]
We do import and reuse a bunch of stuff from `attach_script`, but there are also some debugpy-specific options being handled in there (e.g. logging). Glancing through it, I don't see anything that could be refactored further.
