### ISSUE TITLE
unicode string cannot handle correct in debug console

### ISSUE THREAD

**Issue by A-hoy** [microsoft/ptvsd#1864]
run in Debug Console (python 2.7.16):
```
u'中'
u'\xe4\xb8\xad' # debug console
```

run in Terminal  (python 2.7.16):
```
(py27) D:\OneDrive - danpier\Python\Code>python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:49:40) [MSC v.1500 32 bit (Intel)] on
win32
Type "help", "copyright", "credits" or "license" for more information.
>>> u'中'
u'\u4e2d'
```

As you can see above, the unicode character '中' is handled as three unicode characters in Debug Console.
This could casues some problem like:
```
import re

text = re.sub(u'[中]', 's', u'中')
print(text)

# debug console: sss (unexpected result)
# terminal: s (expected result)
```

## Environment data

- VS Code version: 1.39.2
- Extension version (available under the Extensions sidebar): ms-python.python 2019.10.41019
- OS and version: Windows 7 32-bit (Windows_NT ia32 6.1.7601)
- Python version (Anaconda3-2019.07-Windows-x86): 3.7.3
- Type of virtual environment used: conda 4.7.10 (Python 2.7.16)
- Jedi or Language Server? : False

## Workspace setting:

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        ...
        {
            "name": "Python 2.7: Current File (Debug Console)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "internalConsole",
            "pythonPath": "C:\\Users\\Zerone\\Anaconda3\\envs\\py27\\python.exe"
        },
        ...
    ]
}
```

settings.json

```
{
    "python.pythonPath": "C:\\Users\\Zerone\\Anaconda3\\python.exe",
    "python.terminal.activateEnvironment": true,
    // Lint
    "python.linting.enabled": true,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    // format
    "editor.formatOnSave": true,
    "python.formatting.provider": "yapf",
    //editor
    "workbench.editor.enablePreview": false
}
```

## Expected behaviour

debug console: '中'

## Actual behaviour

debug console: 'ä¸­'

## Steps to reproduce:
1. config env: conda create --name py27 python=2.7
2. config 'launch.json' mentioned above
3. run below code  in Debug Console:
```
print(u'中')
```

## DEBUG CONSOLE

```
Frame skipped from debugging during step-in.
Note: may have been skipped because of "justMyCode" option (default == true).
ä¸­
```

**Comment by fabioz** [comment]
I'll investigate this.

**Comment by fabioz** [comment]
Below is the result of inputs/outputs in the debug console in python 2 and python 3... 

One thing that drew my attention is that printing in Python 2 with `cp1252` gave the proper output (while the `PYTHONIOENCODING` was set to `utf-8`)... I still need to investigate a bit more to understand why we're having these results.

Python 2:
```
>>> import sys;print(sys.stdout.encoding)
UTF-8

>>> u'中'
u'\xe4\xb8\xad'

# Note: the evaluate response message is:
# - Python 2 {"result": "u'\\xe4\\xb8\\xad'" ... }
# - Python 3 {"result": "'\u4e2d'" ... }
# -- note that both are technically correct, the problem is when data is printed.

>>> u'中' == u'\xe4\xb8\xad'
True

>>> print(u'中')
ä¸­

>>> print(u'中'.encode('utf-8'))
ä¸­

>>> print(u'中'.encode('cp1252'))
中

```

Python 3 (printed output seems correct):

```
>>> import sys;print(sys.stdout.encoding)
UTF-8

>>> u'中'
'中'

>>> print(u'中')
中

>>> print(u'中'.encode('utf-8'))
b'\xe4\xb8\xad'

>>> print(u'中'.encode('cp1252'))
UnicodeEncodeError: 'charmap' codec can't encode character '\u4e2d' in position 0: character maps to <undefined>

```

Some notes:

- changing the `PYTHONIOENCODING` to `cp1252` on Python 2 did not fix things (the output is different but not correct).

- this is with the current master version.

- I believe that the out of process adapter is capturing the output right now, so, my current suspect is that the encoding used to capture the bytes does not match the output in which bytes are being printed.

**Comment by fabioz** [comment]
Some more details on the logs (on Python 2 and Python 3):

Python 3:
```
---- print(u'中'): proper output on python 3 ---- 
{"command": "evaluate", "arguments": {"expression": "print(u'\u4e2d')"}}

{"event": "output", "body": {"category": "stdout", "output": "\u4e2d\n"}}


---- print(u'\u4e2d'): proper output on python 3 ---- 
{"command": "evaluate", "arguments": {"expression": "print(u'\\u4e2d')"}}

{"event": "output", "body": {"category": "stdout", "output": "\u4e2d\n"}}


---- print(u'\xe4\xb8\xad'): garbled output on python 3 ---- 
{"command": "evaluate", "arguments": {"expression": "print(u'\\xe4\\xb8\\xad')"}}

{"event": "output", "body": {"category": "stdout", "output": "\u00e4\u00b8\u00ad"}}
```

Python 2: 
```
---- print(u'中'): gave garbled output on python 2 ---- 
{"command": "evaluate", "arguments": {"expression": "print u'\u4e2d'"}}

{"event": "output", "body": {"category": "stdout", "output": "\u00e4\u00b8\u00ad"}}


---- print(u'\u4e2d')': gave proper output on python 2 ---- 
{"command": "evaluate", "arguments": {"expression": "print u'\\u4e2d'"}}

{"event": "output", "body": {"category": "stdout", "output": "\u4e2d\n"}}


---- print(u'\xe4\xb8\xad'): gave garbled output on python 2 ---- 
{"command": "evaluate", "arguments": {"expression": "print u'\\xe4\\xb8\\xad'"}}

{"event": "output", "body": {"category": "stdout", "output": "\u00e4\u00b8\u00ad"}}
```

**Comment by int19h** [comment]
```
---- print(u'\xe4\xb8\xad'): garbled output on python 3 ---- 
{"command": "evaluate", "arguments": {"expression": "print(u'\\xe4\\xb8\\xad')"}}

{"event": "output", "body": {"category": "stdout", "output": "\u00e4\u00b8\u00ad"}}
```
This one looks correct to me. The input is a Unicode string with hex-escaped chars, the output is a Unicode string with the corresponding codepoints (those `\u` escapes are JSON escapes, not Python escapes). Is the Debug Console rendering it wrong?

**Comment by fabioz** [comment]
> This one looks correct to me. The input is a Unicode string with hex-escaped chars, the output is a Unicode string with the corresponding codepoints (those `\u` escapes are JSON escapes, not Python escapes). Is the Debug Console rendering it wrong?

No, that's actually correct... when I said garbled I meant that it gave `ä¸­` as the output in the console (which is expected/correct in this case).
