### ISSUE TITLE
Django static files never finish loading (again)

### ISSUE THREAD

**Issue by ManPython** [microsoft/ptvsd#1866]
This issue is not solved and made for us "matrix"
https://github.com/Microsoft/vscode-python/issues/5521

## Environment data

- VS Code version: 1.38.1
- Extension version (available under the Extensions sidebar): XXX
- OS and version: w7x63ps1
- Python version (& distribution if applicable, e.g. Anaconda): p36
 - Relevant/affected Python packages and their versions: django 2.2.6
 
## Expected behaviour
 I speend weekd before I discover that VSC in debug mode not loading static in case that normal procedure in cmd as python manage.py runserver 127.0.0.1:8000 not showing any problems!

These args ot other not helping
`"args": ["runserver", "127.0.0.1:8000", "--insecure", "--nothreading"],`

And this same problem
https://github.com/microsoft/ptvsd/issues/1473

**Sounds like the args with -- not working?**
Just try with ports as "--port" "8000"

**Comment by karthiknadig** [comment]
@int19h @fabioz Looks like this is a new manifestation of the static files issue. I don't think we changed anything in particular around this. It might be that the latest django release broke this somehow.

**Comment by ManPython** [comment]
BTW `manage.py runserver: error: unrecognized arguments: --traceback 
The clicking errors from debug console not moving to the code part or files what I expecting.

**Comment by fabioz** [comment]
@karthiknadig I've checked with `master` and it seems to work for me (with Python 3.6 and Django 2.2.6)... provided that `--nothreading` is **NOT** added to the parameters.

**Comment by ManPython** [comment]
I'm confused little here near of this issue and DJango..
So.. on 
VSC - not working static on debug
WIN - on cmd static working on debug
LNX - by wsgi static not workig on debug

The difference betwen WIN and LNX that WIN `200` status, LNX `404` error (The requested resource was not found on this server.).

How this impacting by VSC and LNX? Eg. files in `static` dir located in this way:
1. home/user/app/static/ - no any file is not available by browser due to wsgi doing forward/routing for domain by port of the app
vs
2. home/user/domains/example.com/app/static/ - files can be available probably more easy in security aspects
```
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    #os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, 'static'),
)
```
Should we put `static` like in example in point 2 and this is normaly available where static files are "forwarded/routed" in some way or should we put like in point 1 (And whole app in low level of domains/example.com/ ) where static files are normaly available by browser in any way? 
This is related with the remote computer debuging in configuration described on link (point. 4) https://code.visualstudio.com/docs/python/debugging

More confusions are coz there is many ways and variables in django to set static and double this settings without knowelede where are priors or wich methods are higer recomended for some reasons.

Is this example 1 still static in case of "forwarded/routed"?

**Comment by ManPython** [comment]
Looks that the best is to use [uwsgi] as file loaded with many vars and add  line `check-static = home/user/app/`
https://uwsgi-docs.readthedocs.io/en/latest/StaticFiles.html

**Comment by danvisko** [comment]
you should check out the documentation [https://www.djangoproject.com/](url)
[https://www.danvisko.com/](url)

**Comment by fabioz** [comment]
It seems this is working given the latest comments, so, closing this issue (please reopen if that's not the case).
