### ISSUE TITLE
Subprocesses should inherit PydevdCustomization

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1874]
The crucial one is `DEFAULT_PROTOCOL`. At the moment, pydevd in subprocesses tries to connect to the adapter using the hardcoded default, which is not JSON.

**Comment by int19h** [comment]
This one should be considered a priority, because it's blocking adapter-based multiproc (I worked around it in my branch by changing the hardcoded value directly in pydevd, but I don't want to commit that, obviously).

**Comment by fabioz** [comment]
Sure... it'll be the first thing I'll tackle on Monday ;)
