### ISSUE TITLE
Subprocesses need "pathMappings" in "launch" scenario

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1876]
The "ptvsd_attach" event for subprocesses is generated by the adapter from the request that started the parent debug session. If that request was "attach", then it contains "pathMappings" (or not), and that is propagated accordingly. But if it was "launch", it never contains "pathMappings" - and thus subprocesses don't get any, either. And not having "pathMappings" for "attach" generally breaks things that rely on file paths, such as breakpoints.

Thus, when the parent debug session is "launch", any "ptvsd_attach" event in it should include auto-generated "pathMappings" that properly map local files to themselves via "cwd".

**Comment by int19h** [comment]
After some investigation, it is not clear to me why this is necessary.

If path mappings are explicitly defined for the launch config as follows:
```json5
            "pathMappings": [
                {
                    "localRoot": "",
                    "remoteRoot": "",
                }
            ]
```
then everything works fine. However, from pydevd perspective, this arrangement effectively *disables* path mappings, because it specifically checks for empty strings:
https://github.com/microsoft/ptvsd/blob/f51c96450c99f97bd5f53b93ad049ccf2084e085/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py#L337-L346

(which is exactly what we want, since there's no need for path mapping at all for local scenarios - all paths are already valid, and they're all absolute due to normalization!)

The reason why it makes a difference is because the *extension* doesn't try to inject its path mapping defaults into the "attach" request, if it sees any existing entries there - even if those entries are effectively no-op, as in this case:

https://github.com/DonJayamanne/pythonVSCode/blob/967f7b1a63dc3211569a6dafbd9be4d0cac95095/src/client/debugger/extension/configuration/resolvers/attach.ts#L111-L116

Note that this specifically injects those entries for localhost, which is exactly where they should *not* be used!

I believe that this is a legacy of the old implementation in ptvsd 4, which handled "pathMappings" itself, and translated it to pre-DAP pydevd path mappings. In that one, we special-cased "launch" to disable "sourceReference" altogether, but for "attach", we returned "sourceReference" unless the path was mapped:
https://github.com/microsoft/ptvsd/blob/14982d90bae7a5f83e8ecbde15c77187e235e83c/ptvsd/wrapper.py#L1554-L1563
Thus, local attach would cause documents to open in new tabs because VSCode would always try to fetch them via "source" requests"; the injected "pathMappings" then took care of that.

However, the current implementation of "pathMappings" in pydevd is different: it doesn't care whether it's "launch" or "attach", it just looks at presence of "pathMappings" themselves. If they're present, then they're applied, and anything that couldn't be mapped gets a "sourceReference". But if they're *not* present, then path mapping is disabled entirely, and then *nothing* gets a "sourceReference":
https://github.com/microsoft/ptvsd/blob/f51c96450c99f97bd5f53b93ad049ccf2084e085/src/ptvsd/_vendored/pydevd/pydevd_file_utils.py#L577-L581

This behavior is exactly what we need for local attach, including subprocess auto-attach.

Thus, the fix for this issue is to completely remove the localhost fixup in `AttachConfigurationResolver` in the extension. It does not serve any useful purpose at this point - just breaks things.

**Comment by int19h** [comment]
@fabioz, can you confirm the above analysis - i.e. that pydevd does *not* need "pathMappings" to be specified for local "attach" scenarios to prevent source files from being reported with "sourceReference" != 0 (which causes VSCode to use source fetching, even for local paths)?

**Comment by fabioz** [comment]
@int19h I can confirm that... `pydevd` does not need `pathMappings` when running locally (as you investigated, it'll provide a `sourceReference` to any file which does NOT have some `pathMapping` applied to it but only if there is a `pathMappings` set).

As a note, it just occurred to me that when we are in a remote scenario with sub processes, it's possible that the `sourceReference` to a given file is not the same among 2 different processes (but that's probably a different issue).

**Comment by int19h** [comment]
That shouldn't be an issue, because to the IDE, they will be two completely different sessions, so it'll keep track of source references separately for each. But we'll need to check what happens when both processes end up in the same file in this manner. So long as the UI matches their paths and merges the editor tabs, it should work... but I'm not entirely sure.
