### ISSUE TITLE
"pydevdSystemInfo" does not report "ppid" on Python 2.7 on Windows

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1877]
`os.getppid()` was not available on Windows until Python 3.2. Pydevd catches any exceptions from that call, and omits the property from JSON, so this doesn't crash the debugger. But because the adapter doesn't receive "ppid" for the incoming server connection, it doesn't know which of the existing debug sessions is the parent, and doesn't send the subprocess notification to any of them. This effectively breaks multiproc debugging on 2.7.

**Comment by int19h** [comment]
Pydevd might have to propagate the parent PID via command line when spawning the child process to ensure that it's always available. Or perhaps there's a way to re-implement `os.getppid()` in 2.7 in a way similar to how it's done in 3.2.

**Comment by int19h** [comment]
The fix doesn't seem to be working reliably. This is from a test run for `test_flask_breakpoint_multiproc[launch(integratedTerminal)]`:
```
D+00001.268: Server[?] <-- {
                 "seq": 1, 
                 "type": "request", 
                 "command": "pydevdSystemInfo"
             }

D+00001.277: Server[?] --> {
                 "pydevd_cmd_id": 502, 
                 "seq": 2, 
                 "type": "response", 
                 "request_seq": 1, 
                 "success": true, 
                 "command": "pydevdSystemInfo", 
                 "body": {
                     "process": {
                         "pid": 128364, 
                         "bitness": 64, 
                         "executable": "c:\\git\\ptvsd\\.tox\\py27\\scripts\\python.exe"
                     }, 
                     "python": {
                         "version": "2.7.16final0", 
                         "implementation": {
                             "description": "CPython", 
                             "version": "", 
                             "name": ""
                         }
                     }, 
                     "platform": {
                         "name": "win32"
                     }
                 }
             }
```
Note the missing "ppid". Looking at pydevd log for the process reporting, it has this entry in it, but no further details:
```
Process32First failed (getting process from CreateToolhelp32Snapshot).
```

**Comment by fabioz** [comment]
I'm investigating.
