### ISSUE TITLE
test_multiprocessing broken on Linux with set_start_method("spawn")

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1887]
It looks like this creates an extra helper process on Linux:
```
Patching args: ['/home/int19h/src/ptvsd/.tox/py37/bin/python', '-c', 'from multiprocessing.semaphore_tracker import main;main(8)']
Patching args: ['/home/int19h/src/ptvsd/.tox/py37/bin/python', '-c', 'from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=9, pipe_handle=14)', '--multiprocessing-fork']
```
This is duly detoured by pydevd, and reported via "ptvsd_attach" to the adapter. But the test itself expects to see only one subprocess, and so it attaches to the first one it sees (which is the wrong one). The other process just sits there waiting for a client to connect to the adapter and claim it.

**Comment by int19h** [comment]
This is more complicated than originally anticipated, because the number of helper processes depends on Python version (some spawn them for each subprocess, some only for the main process), and the order is non-deterministic - the second process may get spawned before the first one gets a chance to notify the adapter. So the test can't just attach to subprocesses in a predetermined sequence - it has to attach to processes with specific PIDs only, but also allow for other arbitrary subprocesses, and attach/detach to them to unblock them.

**Comment by fabioz** [comment]
I believe this was fixed by not having `pydevd` report about it 2 times (i.e.: https://github.com/microsoft/ptvsd/commit/3e29307d65318362b2cf2f3b84ebd88840f8b0c0).
