### ISSUE TITLE
Stopping debugger when paused on breakpoint does not kill python process

### ISSUE THREAD

**Issue by damufo** [microsoft/ptvsd#1899]
## Environment data

- VS Code version: 1.39.2
- OS and version: debian 9.10 XFCE
- Python version (& distribution if applicable, e.g. Anaconda): 3.5.3 64 bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.0-0.bpo.5-amd64

I think it's the same problem as
https://github.com/microsoft/vscode-python/issues/6304

When stop debugging a app, vscode  should kill the python process.

I have zombie processes that when logging out and logging in (xfce session)  are still running.

![Captura de pantalla_2019-11-06_10-55-18](https://user-images.githubusercontent.com/4057369/68288568-eec82a80-0084-11ea-9f2d-298841135792.png)

**Comment by karthiknadig** [comment]
We have a newer version of the debugger that is in `alpha`, that should address this issue. In this particular case the node debug adapter is being left behind for some reason after the old python debugger exits. In the newer version, the adapter itself will be a python process and the lifetime of that process is managed more aggressively.

I am closing this issue in favor of waiting for the extension to roll out the new debugger.
