### ISSUE TITLE
Python Debugger Leaks Processes on Restart

### ISSUE THREAD

**Issue by OutOfFocus4** [microsoft/ptvsd#1905]
## Environment data

- VS Code version: 1.40.0
- Extension version (available under the Extensions sidebar): 2019.10.44104
- OS and version: Ubuntu 18.04.3
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.6.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Jedi

This is a duplicate of microsoft/vscode-python#3217, but that issue is locked.

When restarting the Python Debug Adapter (as opposed to stopping it), a new debugger process is started, but the old one is not killed.

I have replicated the issue on both MacOS Mojave and Ubuntu 18.04, using version 1.39 and 1.40 of Visual Studio Code. I am unable to replicate the issue using Visual Studio Code for Windows.

If I add `"logToFile": true` to the launch configuration, restarting the debugger kills the process correctly.

*Redacted log file from Mac*:
[debug34201.log](https://github.com/microsoft/vscode-python/files/3827307/debug34201.log)

*Redacted log file from Ubuntu*:
[debug19070.log](https://github.com/microsoft/vscode-python/files/3827308/debug19070.log)

**Comment by int19h** [comment]
By "restart" and "stop", do you mean the corresponding buttons on the Debug toolbar?

**Comment by OutOfFocus4** [comment]
Yes, If I restart the debugger using the debug toolbar (or related keyboard shortcuts), a new process is started, but the original debugger process isn't stopped, even if I later close Visual Studio Code.

After quitting Visual Studio Code on a Mac, this is the output of `pgrep -lf delete`. I have replaced my username with `*********`:

```
1183 /System/Library/PrivateFrameworks/CacheDelete.framework/deleted
40019 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e delete process.env.ELECTRON_RUN_AS_NODE;require(process.argv[1]) /Users/*********/vscode/extensions/ms-python.python-2019.10.44104/out/client/debugger/debugAdapter/main.js
```

**Comment by OutOfFocus4** [comment]
I am now encountering instances where clicking the Restart button will stop the debugger, but not start a new one. This also occurs when I use the keyboard shortcut.

Like before, the debugger process isn't killed automatically unless I have `logToFile: true` in `launch.json`.

Also, here is my `launch.json`:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python: Django",
			"type": "python",
			"request": "launch",
			"program": "${workspaceFolder}/manage.py",
			"console": "integratedTerminal",
			"args": [
				"runserver",
				"--noreload"
			],
			"django": true
		},
	]
}
```

**Comment by OutOfFocus4** [comment]
I just installed version 2019.11.49689 of the extension on my Mac, and the issue still exists.

**Comment by int19h** [comment]
We have completely rewritten the component that you see becoming a zombie in the upcoming ptvsd 5 release. These bits are already checked in, and pre-releases on PyPI have them, but we haven't shipped a version of VSCode with them - this is coming soon, however. Better lifetime management has been a specific focus in this rewrite, so it's likely to resolve this issue.

**Comment by int19h** [comment]
You can try the new debugger by following the instructions in https://github.com/microsoft/ptvsd/issues/1706#issuecomment-572287267. Please re-open the issue if you can reproduce it with the new bits.

**Comment by OutOfFocus4** [comment]
I followed the instructions in the comment. When I try to restart the debugger, using either the debug toolbar buttons or a keyboard shortcut, the debugger just stops entirely.

**Comment by karthiknadig** [comment]
@OutOfFocus4 you need to reload VSCode for the extension to pickup the new settings. Once it is reloaded check to see if the Python output logs show that you are in the two experiment groups (`DebugAdapterFactory - experiment`, `PtvsdWheels37 - experiment`):
![image](https://user-images.githubusercontent.com/3840081/72833594-fa66ce80-3c3b-11ea-92d8-4af439442b08.png)

**Comment by OutOfFocus4** [comment]
Here is the Python output:
```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - control'
User belongs to experiment group 'PtvsdWheels37 - experiment'
```

And this is the output when I launch a Django project (I have removed personal information):
```
env PTVSD_LAUNCHER_PORT=55237 /Users/******/bin/python /Users/******/.vscode/extensions/ms-python.python-2020.2.59126-dev/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher /Users/******/manage.py runserver --noreload 
Performing system checks...

System check identified no issues (0 silenced).
January 22, 2020 - 09:21:48
Django version 3.0.2, using settings '******.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

It launches fine, but when I try to restart it, it stops.

**Comment by OutOfFocus4** [comment]
After upgrading to the latest version of the Python extension and opting into `new_ptvsd` experiment, the issue appears to be resolved.
