### ISSUE TITLE
Fork/exec creates two connections from pydevd to adapter

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1909]
This is causing `test_subprocess` to fail on Python 2.7, and is also the root cause of Flask test failures.

The problem is that on 2.7, `subprocess.Popen` uses fork+exec - and pydevd detours both. So first `fork()` creates a child process, and pydevd is spun up in that process and connects to the adapter. Then the child process does `exec()`, pydevd patches command line to ensure that it gets loaded first, and as it does so, it connects to the adapter again. Since both connections come from a process with the same PID, the adapter rejects the second one.

There is a bug in the adapter here as well (#1908), but the fundamental problem is that it really is the _same_ process trying to connect twice. The adapter can handle it by forcibly closing any existing connection with the same PID when a new one comes in; but I wonder if it might be better to prevent this on pydevd side, e.g. by having the code detouring `exec()` close the socket before replacing the process. Per `man execve`, the OS itself will keep the socket fd open unless it's explicitly closed, so the adapter can't just wait for it to go away.

**Comment by int19h** [comment]
@fabioz, what do you think? Is there any downside to explicitly closing the socket in pydevd?

**Comment by int19h** [comment]
Another interesting side effect of this: because we use PID to generate distinct log file names, they end up clashing in this case. This made it harder to diagnose this issue, because the pydevd log created after `exec` was overwriting the older log created after `fork`. The same issue would apply to `ptvsd.server` log, if it got far enough to create one.

Perhaps we should include a timestamp in the filename?

**Comment by fabioz** [comment]
I think closing the socket is ok and makes sense. I'll create a pull request for that.

I was thinking a bit more about it and maybe we should handle that specific case from subprocess and don't even create a connection for the fork in that case (note that we still need to handle the fork/exec case in case some user specifically does it, but it won't be common as it is now -- in this case it may be ok to just leave the log as it is without adding a timestamp just for this corner case).

What do you think?

**Comment by int19h** [comment]
Makes sense, if it can be detoured reliably. Attaching to that intermediate process doesn't do anything useful, but the user ends up paying the penalty of loading the debugger in it and waiting for IDE to attach to it.
