### ISSUE TITLE
attach_to_pid tests fail on Travis CI

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1915]
I+00001.303: Injector[PID=6125] output:
             b'stderr: b\'Could not attach to process.  If your uid matches the uid of the target\\nprocess, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try\\nagain as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf\\nptrace: Operation not permitted.\\nTarget \\\'None\\\' cannot support this command.\\nNo symbol table is loaded.  Use the "file" command.\\nNo symbol table is loaded.  Use the "file" command.\\n\''

**Comment by int19h** [comment]
@fabioz Is there some requirement that attach-to-PID needs that we're missing in our Travis setup?

**Comment by fabioz** [comment]
Yes... the ptrace scope needs some tweaking:

See: https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/.travis.yml#L89
