### ISSUE TITLE
Capture usage of the experimental debugger

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#193]
This can be done via an `OutputEvent` with a category of `telemetry` .
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json#L278

This is something that would be useful to both PTVS as well as VS Code.

**Comment by int19h** [comment]
@DonJayamanne, can you figure out what's the most convenient way to report this info from VSC adapter perspective (since it's the primary beneficiary, let's implement it in a way that keeps it simple), and what info needs to be in the event aside from debugger ID.

**Comment by DonJayamanne** [comment]
> @DonJayamanne, can you figure out what's the most convenient way to report this info from VSC 

Apologies for the late response, we dont need to do anything in VSC. If you send the event using the code you have today, that'll be sufficient. VSC will handle the rest for us.
