### ISSUE TITLE
Debugging on some WiFi causes localhost to be not found

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/ptvsd#1931]
This is the same issue as microsoft/vscode-python#715 which is closed as resolved. Adding this issue to provide more detail on reproduction.

## Environment data

- VS Code version: 1.40.1
- Extension version (available under the Extensions sidebar): 2019.10.44104
- OS and version: macOS 10.15.1
- Python version (& distribution if applicable, e.g. Anaconda): 3.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language server

## Expected behaviour

Open a python file and click debug to debug the file.
Code runs and can be debugged

## Actual behaviour

An error occurs:

Failed to start the socket server. (Error: getaddrinfo ENOTFOUND localhost)

## Steps to reproduce:

This happens with any Python file on certain WiFi. Debugging works on my work and home wifi, but this error was seen at the New York Institute of Technology and on a flight using GoGo WiFi. It looks like certain WiFi connections do something weird with `localhost`.

Following the instructions in microsoft/vscode-python#715 fixes the issue, but ideally it should just work and not need a change to a hosts file. One set of students at a hackathon were using VS Code and had this issue, so they switched to another IDE.

**Comment by karthiknadig** [comment]
@int19h is it feasible to get better error messages here?

**Comment by int19h** [comment]
We receive this as a generic `socket.error` from Python, and propagate the included error message. On some platforms this works better than others, but it's a fairly common pattern for dev tooling, and it does have the benefit that the error message is unique enough that it's easy to search for - try googling "getaddrinfo ENOTFOUND localhost".

We could check for `ENOTFOUND` error code specifically, and replace the error message. Or perhaps check for "localhost" and macOS specifically, and add a platform-specific note?

**Comment by karthiknadig** [comment]
@int19h +1 for the platform specific note idea. I don't think we should modify the error. Just provide a note.

**Comment by int19h** [comment]
This shouldn't be an issue in debugpy anymore, as it uses 127.0.0.1 consistently instead of localhost.
