### ISSUE TITLE
Feature request: allow changing variable value during debugging

### ISSUE THREAD

**Issue by dxkaufman** [microsoft/ptvsd#1932]
I did a couple of searches and don't see anything that is a duplicate, though I'm not going to be surprised if you find one!

I would like to be able to use the Watch window to change the value of a variable during debugging.

**Comment by int19h** [comment]
We do implement the requisite bit in the protocol specification ("setExpression"), and this already lights up the corresponding feature in Visual Studio. But it appears that Visual Studio Code itself just doesn't support editing values in the Watch window, only in Variables, so there isn't much we can do here until that changes (and when it does, it should "just work" from our end).

**Comment by dxkaufman** [comment]
@int19h clearly I should have searched the VS code documentation; I'm used to being able to set it in the watch screen in other IDEs I've used, and I didn't even think of trying in the variables section.  Sorry to waste your time, but thank you for getting back to me!
