### ISSUE TITLE
Monkey-patch os.posix_spawn

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1934]
But succeeds on Python 3.6 and 3.7. Looking at pydevd logs for the parent process, the difference is that there's no "Patching args" in case of 3.8. However, there *is* a pydevd logfile for the child process, which only contains the "Using Cython speedups" line.

**Comment by int19h** [comment]
Initial investigation:

I believe that this is due to https://bugs.python.org/issue35537 - Python 3.8 now uses `posix_spawn` instead of `fork`+`exec` to implement a "fast path" for `subprocess.Popen()`. Note that this doesn't always apply - e.g. on Linux it only kicks in above a certain version of glibc, and on all platforms it only applies if certain arguments to `Popen()` have specific values. Here's how that conditional looks in the source:
```py
            if (_USE_POSIX_SPAWN
                    and os.path.dirname(executable)
                    and preexec_fn is None
                    and not close_fds
                    and not pass_fds
                    and cwd is None
                    and (p2cread == -1 or p2cread > 2)
                    and (c2pwrite == -1 or c2pwrite > 2)
                    and (errwrite == -1 or errwrite > 2)
                    and not start_new_session):
                self._posix_spawn(args, executable, env, restore_signals,
                                  p2cread, p2cwrite,
                                  c2pread, c2pwrite,
                                  errread, errwrite)
                return
```
That's why `test_subprocess` works fine - it redirects the output of the child process (not sure why), and thus skips `posix_spawn`.

On Linux, `posix_spawn` is itself implemented as vfork + exec inside glibc, and it seems that pydevd can handle that correctly? But on macOS, it's a syscall, and I guess that breaks something.

@fabioz, looks like this is another thing that needs to go into `pydev_monkey.py`.

**Comment by int19h** [comment]
Same thing applies to `test_django_breakpoint_multiproc`.

**Comment by fabioz** [comment]
Yes, it seems that `os.posix_spawn` isn't monkey-patched. I'll provide a patch shortly.
