### ISSUE TITLE
python venv debugger session timed out

### ISSUE THREAD

**Issue by sharondescalo** [microsoft/ptvsd#1937]
## Environment data

- VS Code version: 1.40.1
- Extension version (available under the Extensions sidebar): 2019.11.49689 
- OS and version: Windows_NT x64 10.0.17763
- Python version (& distribution if applicable, e.g. Anaconda): pyenv python 3.7.2-amd  & python 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: XXX
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): XXX

## Expected behaviour

Start a Debug Session on visual code

## Actual behaviour

![image](https://user-images.githubusercontent.com/1915885/69317761-5618d980-0c44-11ea-9060-8ae1535ec8f0.png)

## Steps to reproduce:
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. py -3 -m venv .venv
2 .venv\scripts\activate
3. start debug any file on visual code

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
[python.log](https://github.com/microsoft/vscode-python/files/3873445/python.log)

```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
[console.log](https://github.com/microsoft/vscode-python/files/3873443/console.log)

```

**Comment by karthiknadig** [comment]
Thanks for reporting. We are aware of this issue, and we plan on addressing it soon. See #1930
