### ISSUE TITLE
Better display for the variable in the debug console

### ISSUE THREAD

**Issue by 520Chris** [microsoft/ptvsd#1939]
When I want to check the variable in the debug console, I get long variable information like the image shows.
![image](https://user-images.githubusercontent.com/39628662/69239716-d5bb8f80-0bd5-11ea-9820-8ed57e2a24f9.png)
The multiline information is chaos, and unreadable!

**Describe the feature you'd like**
Change **multiline** information of a variable to **one line**.
When the user wants to check the detail of a variable, the character shows in the following image is a better choice.
![image](https://user-images.githubusercontent.com/39628662/69239944-5d090300-0bd6-11ea-941f-72fd08e4c9f9.png)

**Comment by int19h** [comment]
We're aware of this issue, and are tracking it in #1432

**Comment by 520Chris** [comment]
Thank you very much.
