### ISSUE TITLE
Just My Code

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#194]
An option that allows the user to:

- Avoid stepping into the standard library
- Avoid breaking on handled exceptions that happen inside the standard library

For the purposes of this item, "standard library" is defined as every package installed into the current Python environment (i.e. including site-packages).

**Comment by int19h** [comment]
Depends on https://github.com/Microsoft/ptvsd/issues/169

**Comment by karthiknadig** [comment]
This should be enabled using `supportsDebuggerProperties` which supports `JustMyCodeStepping`.
https://github.com/Microsoft/VSDebugAdapterHost/wiki/Debugger-Properties

**Comment by int19h** [comment]
The first approximation is what the old ptvsd did, which is: all files installed anywhere in lib or site-packages (including user-global and virtualenv) are non-user code, which is the same as "stdlib". If the latter is confusing, I propose that we change that.

Once we have feature parity, that definition can certainly be extended. There have been user asks to treat Python built-in modules separate from site-packages, mostly for the purposes of debugging self-authored packages in a "natural environment", without the overhead of disabling JMC entirely (@zooba, is that right?). But all that stuff is post-VS-stable.

**Comment by int19h** [comment]
BTW, this issue only tracks the feature parity version. There's a separate item for fine-grained JMC: https://github.com/Microsoft/ptvsd/issues/207

**Comment by qubitron** [comment]
Let's focus on feature parity per @int19h and focus on fine-grained control later.

**Comment by int19h** [comment]
Yep. They're already assigned to milestones accordingly - this one is in VSC milestone, and fine-grained isn't in any milestone at all (i.e. post-stable).

**Comment by karthiknadig** [comment]
Completed via https://github.com/Microsoft/ptvsd/pull/467
