### ISSUE TITLE
print Chinese to be  mess code 

### ISSUE THREAD

**Issue by liyanan24** [microsoft/ptvsd#1947]
![image](https://user-images.githubusercontent.com/42564665/69397363-ca28af80-0d20-11ea-9a80-e09d756a1a02.png)
It worked fine before, today the output becomes mess suddenly. Reinstallation did not solve the problem.

**Comment by karthiknadig** [comment]
This is same as #1938. See comment here for a possible workaround: https://github.com/microsoft/ptvsd/issues/1938#issuecomment-557343123
