### ISSUE TITLE
Wait on exit

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#195]
When debuggee exits, there should be an option to:
- wait ("Press any key to continue...") if it terminated normally
- wait if it terminated with an error

**Comment by DonJayamanne** [comment]
Fyi, this isn't necessary for vs code, hence this needs to be a configurable behavior.

**Comment by int19h** [comment]
It is a configurable behavior for VS as well for both of these options. And it only applies to F5 scenarios, not attach, so we're just going to reuse the existing debug option for it (passed as command line argument).

**Comment by karthiknadig** [comment]
Should we do this via InitializeRequest? The adapter host allows us to add custom attributes to Initialize request. Let me know if we should do this approach vs send this via command line.

**Comment by int19h** [comment]
VS already does it via command line on its side (when it invokes ptvsd_launcher.py), so the easiest thing is to just enable support for those two flags (`WaitOnNormalExit` and `WaitOnAbnormalExit`) on ptvsd side.
