### ISSUE TITLE
 Popen('python') in VS Code crashes the debugger, with Python 2

### ISSUE THREAD

**Issue by markonius** [microsoft/ptvsd#1966]
## Environment data

PTVSD version: 4.3.
Extension version: 2019.11.50794
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.3.13-200.fc30.x86_64

Running the following code from the teminal works fine:

```py
import subprocess
print 'hello'
subprocess.Popen('python')
```
Running it from VS Code (using 'Current file' debug configuration) crashes the process with:
```
E-0000.090: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/me/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              ...
              File "/home/me/vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
```

**Comment by markonius** [comment]
Related to [this](https://github.com/microsoft/vscode-python/issues/8897)

**Comment by int19h** [comment]
Sounds like #943 - we already have the fix for that in ptvsd 5.
