### ISSUE TITLE
debugging doesn't hit "pass" line

### ISSUE THREAD

**Issue by kzhui125** [microsoft/ptvsd#1977]
```py
a = 0

if a == 0:
    pass
```

Sometimes I want to do conditional debugging, and I don't want to use  conditional breakpoint (not convenient to change condition).

So  I use "if" and add a breakpoint at the pass line. But my breakpoint won't hit. 
I have to change the "pass" line (which is auto completion) to print('') or others.

**Comment by kzhui125** [comment]
[how-to-break-on-pass-in-pycharm](https://stackoverflow.com/questions/47625526/how-to-break-on-pass-in-pycharm)

After reading this thread, I think it's not easy to break at the pass line.

According to this thread, there are three methods:

1. writing if statement, change pass to [breakpoint()](https://docs.python.org/3/library/functions.html#breakpoint), press F5 to debug
2. writing if statement, change pass to ... or bare integer or variable, make a breakpoint, press F5 to debug
3. writing if statement, change pass to print('') or other statements, make a breakpoint, press F5 to debug

convenience: 1 > 2 > 3

but ptvsd doesn't at 1 and 2

**Comment by int19h** [comment]
Yep, the problem with `pass` is that it literally "doesn't even run", much like an empty line.

For option 2, `()` - i.e. empty tuple constructor - is a handy one that works on any version of Python.

However, all the options listed above should work. If they don't, it's a bug - @kzhui125, can you please file it separately, and provide more details? i.e. versions of Python, ptvsd itself, and the code snippet and the location of the breakpoint in it.

**Comment by kzhui125** [comment]
```py
for i in range(1000):
    if i == 500:
        ...
        0
        # breakpoint()
```

@int19h  yes, 1 and 2 works too.

but if I make a breakpoint at "..." or 0, or uncomment "breakpoint()" line, the code will break at the "for i in range(1000):" line, this looks strance. Is this expected?


<img width="346" alt="1" src="https://user-images.githubusercontent.com/11925432/70686559-aa652580-1ce7-11ea-8bad-14ebfec94908.png">
