### ISSUE TITLE
Conditional breakpoint - Log Message does not work.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/ptvsd#1980]
## Environment data
- VS Code version: 1.41.0-insider
- Extension version : 2019.12.53195-dev

## Reproduced step:
1.Move the cursor to the line you want to set breakpoint
2.Add conditional breakpoint using "Debug > New Breakpoint > Conditional Breakpoint…"
3.Click dropdown list and select "Log Message", Type the message in the dialog and press enter
![image](https://user-images.githubusercontent.com/39871640/70683274-b5ff1f00-1cdc-11ea-8439-89d44cb9efcd.png)
4.Start to debugging, ensure:

## Expected behavior
The corresponding log message will be printed after each print (i)

## Actual behavior
python2.7 : ![image](https://user-images.githubusercontent.com/39871640/70683523-9caaa280-1cdd-11ea-9ad8-ad0a8e1ed20a.png)
python3.7: ![image](https://user-images.githubusercontent.com/39871640/70683928-2870fe80-1cdf-11ea-9574-544ba459f8a8.png)

**Comment by int19h** [comment]
This behavior has changed considerably in ptvsd 5: log points now log messages to Debug Console only, not to the terminal. If regular output is redirected to Debug Console using `"redirectOutput": true`, then it is ordered properly with respect to log points.
