### ISSUE TITLE
The breakpoint could not be hit in attach debugging.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/ptvsd#1981]
## Environment data

- VS Code version: 1.41.0-insider
- Extension version (python extension): 2019.12.53195-dev

## Expected behaviour
The breakpoint can be hit in attach debugging

## Actual behaviour
The breakpoint could not be in attach debugging.

## Steps to reproduce:
1. Install ptvsd via below command:
    python -m pip install --upgrade ptvsd
2.Add new python file named test.py, enter some code like below:
```python
import ptvsd
ptvsd.enable_attach()
ptvsd.wait_for_attach()
for i in range(1, 10, 2):
    print (i)
print('demo done.')
```
3.Run attach_test.py and wait for attaching
python test.py
4.Select debugging configuration "Python: Attach"
5.Press F5 to start debugging

## launch.json
![image](https://user-images.githubusercontent.com/39871640/70691622-7e9c6c80-1cf4-11ea-9df1-1e71862853c0.png)

## video
[attach.zip](https://github.com/microsoft/vscode-python/files/3954419/attach.zip)

## Note
This issue also exist in remote debugging.

**Comment by fabioz** [comment]
I tested this in `ptvsd 5.x` and it seems to be working for me.

It'd be nice to have the logs to know what may be wrong here (`log_dir` may be passed to `enable_attach` to get them).

Also, at least on `ptvsd 5.x`, the `pathMappings` are not required on the launch.

**Comment by int19h** [comment]
Presumed fixed in ptvsd 5.
