### ISSUE TITLE
Cannot reach finally block after sending keyboard interrupt

### ISSUE THREAD

**Issue by pt12lol** [microsoft/ptvsd#1984]
## Environment data

- PTVSD version: 5.0.0a7
- OS and version: Ubuntu 18.04
- Python version: 3.6.8
- Using VS Code

## Steps to reproduce:
1. Create a `main.py` file with the following Python source code:
```python
import time

try:
    print('waiting for ctrl+C hit...')
    while True:
        time.sleep(1)
finally:
    time.sleep(1)
    print('cleanup')
```
2. Add a basic Python file debugging configuration, such as:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
    ]
}
```
3. Open `main.py` in VSCode file editor.
4. Hit `F5`.
5. Press `ctrl+C` in terminal.

## Actual behavior

Cannot reach `finally` block after sending keyboard interrupt - neither execute code inside finally nor reach breakpoint set up in VSCode.

In the test case described above, `cleanup` string is not printed to the terminal. Breakpoint set in the `finally` block cannot be reached.

## Expected  behavior

Can reach `finally` block after sending keyboard interrupt.

In the test case described above, `cleanup` string is printed to the terminal. Breakpoint set in the `finally` block can be reached.

**Comment by int19h** [comment]
This is the same problem as #1896.
