### ISSUE TITLE
Hide internal debugger machinery

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#199]
Do not show:

- debugger helper threads in the thread list
- debugger modules in the module list
- debugger frames on the stack

(for both pydevd and ptvsd)

**Comment by int19h** [comment]
Note that currently, we don't list modules at all (#21), so that part is "done" - but will need to be revisited once modules are properly listed.

**Comment by karthiknadig** [comment]
Also error propagation.

Test.py:
```
raise ValueError
```
Set `ValueError` to notify when raised in Exception settings. When exception is raised , hit continue. VS will break inside `ptvsd`.

**Comment by karthiknadig** [comment]
This is done.
