### ISSUE TITLE
Session-1 timed out waiting for debuggee to spawn with PySide2 in venv

### ISSUE THREAD

**Issue by theperelomov** [microsoft/ptvsd#1994]
## Environment data

- VS Code version: 1.41.0
- Extension version (available under the Extensions sidebar): 2019.11.49689 or 2019.11.50794
- OS and version: Windows 10 LTSC 1809 Build 17763.914
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: PySide2 5.13.2
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): N/A

## Expected behaviour

Start debugger

## Actual behaviour

Error
![image](https://user-images.githubusercontent.com/35110565/70844452-5460c100-1e52-11ea-854b-ce883584a609.png)

## Steps to reproduce:
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1.Open VS Code
2.Add test.py - without code
3.Choose Python 3.7.5
![vscode](https://user-images.githubusercontent.com/35110565/70844681-b8d14f80-1e55-11ea-85e3-011ea438d6cd.png)
4. Write commands
```
python -m venv venv
venv/Scripts/activate
pip install pyside2
```
![vscode_term](https://user-images.githubusercontent.com/35110565/70844769-cc30ea80-1e56-11ea-8746-82bad0dbd1ee.png)
5. Choose venv
![image](https://user-images.githubusercontent.com/35110565/70844795-1d40de80-1e57-11ea-842a-0f2f357578bf.png)
6. Press F5
![image](https://user-images.githubusercontent.com/35110565/70844819-9ccead80-1e57-11ea-9146-126e4c7be776.png)
7. ERROR!
Start debugger, and after 5-10 seconds, i have that error(
![image](https://user-images.githubusercontent.com/35110565/70844828-c556a780-1e57-11ea-9cbc-f45b664fac1f.png)

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

Nothing in OUTPUT
```
User belongs to experiment group 'AlwaysDisplayTestExplorer - control'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'Reload - control'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> py -3.7 -c "import sys;print(sys.executable)"
> py -3.6 -c "import sys;print(sys.executable)"
> py -3 -c "import sys;print(sys.executable)"
> py -2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> conda info --json
Starting Jedi Python language engine.
> conda --version
> ~\AppData\Local\Programs\Python\Python38\python.exe -c "import sys;print(sys.prefix)"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -c "import sys;print(sys.prefix)"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -c "import sys;print(sys.executable)"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -c "import sys;print(sys.executable)"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -m site --user-site
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -m site --user-site
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -m pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\Perelomov\Desktop\repr\test.py
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe -m pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\Perelomov\Desktop\repr\test.py
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python38\python.exe completion.py
cwd: c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles
> ~\AppData\Local\Programs\Python\Python38\python.exe completion.py
cwd: c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles
##########Linting Output - pylint##########
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Programs\Python\Python37\python.exe -m pip --version
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "import sys;print(sys.prefix)"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "import sys;print(sys.prefix)"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "import sys;print(sys.executable)"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "import sys;print(sys.executable)"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -m site --user-site
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -m site --user-site
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -m pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\Perelomov\Desktop\repr\test.py
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe -m pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\Perelomov\Desktop\repr\test.py
cwd: c:\Users\Perelomov\Desktop\repr
> ~\AppData\Local\Programs\Python\Python37\python.exe completion.py
cwd: c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles
> ~\AppData\Local\Programs\Python\Python37\python.exe completion.py
cwd: c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles
##########Linting Output - pylint##########
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -m pip --version
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "import sys;print(sys.prefix)"
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "import sys;print(sys.prefix)"
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "import sys;print(sys.executable)"
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "import sys;print(sys.executable)"
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -m site --user-site
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -m site --user-site
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -m pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\Perelomov\Desktop\repr\test.py
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -m pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\Perelomov\Desktop\repr\test.py
cwd: c:\Users\Perelomov\Desktop\repr
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe completion.py
cwd: c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe completion.py
cwd: c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "import pylint"
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "import pylint"
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "import pylint"
> c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe -c "import pylint"

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

Just debugger launch command
```
PS C:\Users\Perelomov\Desktop\repr> ${env:PTVSD_SESSION_ID}='1'; ${env:PTVSD_LAUNCHER_PORT}='50445'; & 'c:\Users\Perelomov\Desktop\repr\venv\Scripts\python.exe' 'c:\Users\Perelomov\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\new_ptvsd\wheels\ptvsd\launcher' 'c:\Users\Perelomov\Desktop\repr\test.py'
```

## workaround until bug fix
Python extension for Vs Code versions 2019.10.44104 or lower, work for me.

**Comment by int19h** [comment]
This is a dup of #1930. We already have a fix for this, but the version of ptvsd with the fix hasn't shipped yet.

In the meantime, you can work around this by copying python.exe from your global Python installation into the venv Scripts folder, replacing the stub that is already there.

Alternatively, you can opt out of ptvsd 5 by disabling Python -> Experiments: Enabled in VSCode settings.

**Comment by lzdawer** [comment]
ms-python.python
"timed out waiting for debuggee to spawn"
This error has not been fixed and is repeated throughout 2020.
The latest working version is 2019.10.44104.
And even then it has Python 3.7.5 problems with Russian encoding.
However, in Python 3.8.2, this problem disappears.
By the way, in Visual Studio, the error is "timed out waiting for debuggee to spawn"
also present.

**Comment by int19h** [comment]
@lzdawer, this issue was specifically about venv (i.e. the same code would work fine if selecting a global interpreter). If you're seeing the same error message, but in a different scenario, can you please file a separate bug, and give more detailed repro steps?

**Comment by lzdawer** [comment]
I do not know how to file separate error messages.
I have this error reproduced without venv.
Even if it works without error, then the next time, it will definitely happen.
The ratio is about 1: 1000.
I don’t have any special code, and the output provided in this thread is exactly right for my case.
Also, interestingly, in WSL2, it is played less often.
I think that by comparing the codes from version 2020.3.69010 and 2019.10.44104, you can try to figure it out, but I'm not an expert on this.
  
>Понедельник, 23 марта 2020, 3:47 +03:00 от Pavel Minaev <notifications@github.com>:
> 
> 
>@lzdawer , this issue was specifically about venv (i.e. the same code would work fine if selecting a global interpreter). If you're seeing the same error message, but in a different scenario, can you please file a separate bug, and give more detailed repro steps?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 

------------------------------------------------
Мне привычней тучи!
Я из той породы...
Что может быть лучше,
Плохой погоды!
                          (c) Богомил Райнов.

**Comment by lefig** [comment]
I have the same error. Latest version of version 2019 with updates.

 1> ERROR: One or more errors occurred.

Failed to launch debug adapter.  Additional information may be available in the output window.

Session-1 timed out waiting for debuggee to spawn
 1> ERROR: Debug adapter error output: E+00014.141: /handling #2 request "launch" from IDE[1]/
 1> ERROR: Debug adapter error output:              Handler 'IDE._start_message_handler.<locals>.handle' (file 'c:\\program files (x86)\\microsoft visual studio\\2019\\community\\common7\\ide\\extensions\\microsoft\\python\\core\\debugpy\\adapter/../..\\debugpy\\adapter\\components.py', line 170)
 1> ERROR: Debug adapter error output:              couldn't handle #2 request "launch" from IDE[1]:
 1> ERROR: Debug adapter error output:              
 1> ERROR: Debug adapter error output:              Traceback (most recent call last):
 1> ERROR: Debug adapter error output:                File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\common\messaging.py", line 769, in _handle
 1> ERROR: Debug adapter error output:                  self.describe(),
 1> ERROR: Debug adapter error output:              AssertionError: Handler 'IDE._start_message_handler.<locals>.handle' (file 'c:\\program files (x86)\\microsoft visual studio\\2019\\community\\common7\\ide\\extensions\\microsoft\\python\\core\\debugpy\\adapter/../..\\debugpy\\adapter\\components.py', line 170) for #2 request "launch" from IDE[1] must not return a response body if it has already invoked request.respond().
 1> ERROR: Debug adapter error output:              
 1> ERROR: Debug adapter error output:              Stack where logged:
 1> ERROR: Debug adapter error output:                File "C:\work\python\3.6.7\python-3.6.7.amd64\lib\threading.py", line 884, in _bootstrap
 1> ERROR: Debug adapter error output:                  self._bootstrap_inner()
 1> ERROR: Debug adapter error output:                File "C:\work\python\3.6.7\python-3.6.7.amd64\lib\threading.py", line 916, in _bootstrap_inner
 1> ERROR: Debug adapter error output:                  self.run()
 1> ERROR: Debug adapter error output:                File "C:\work\python\3.6.7\python-3.6.7.amd64\lib\threading.py", line 864, in run
 1> ERROR: Debug adapter error output:                  self._target(*self._args, **self._kwargs)
 1> ERROR: Debug adapter error output:                File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\common\messaging.py", line 1502, in _run_handlers
 1> ERROR: Debug adapter error output:                  handler()
 1> ERROR: Debug adapter error output:                File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\common\messaging.py", line 791, in _handle
 1> ERROR: Debug adapter error output:                  self.describe(),
 1> ERROR: Debug adapter error output:              
 1> Debug adapter process exited.

**Comment by int19h** [comment]
@lefig Please file a new issue in https://github.com/microsoft/debugpy, with more specific repro steps - e.g. does it happen for any program you're trying to run, and if not, then what specifically is being run? Are you running in a virtual environment? Are you trying to use some specific Python library?
