### ISSUE TITLE
PTVSD 5.* debugger Flags are not working

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/ptvsd#2001]
I'm setting the debugger flags in the launch json, but they are being ignored by the debugger. For instance, the show return value and break on system exit 0 are not working. 

Launch JSON: 
![image](https://user-images.githubusercontent.com/3315992/71121455-5c429d00-2193-11ea-88d6-7db65c4774c0.png)

DebugAdapterLogs for PTVSD 5.*
[DebugAdapterHost5.txt](https://github.com/microsoft/ptvsd/files/3980429/DebugAdapterHost5.txt)

DebugAdapterLogs for PTVSD 4.0 (for comparison)
[DebugAdapterHost4.txt](https://github.com/microsoft/ptvsd/files/3980432/DebugAdapterHost4.txt)

**Comment by int19h** [comment]
We didn't fully transition to new-style properties for all the debug options yet. We need to do so.

For some of the properties, the extension or the adapter automatically generate the corresponding option to pass to pydevd, but not all. However, it would be better for pydevd itself to handle these directly in one place.

The required behavior is straightforward: for every debug option named "Foo", we should have a corresponding Boolean property named "foo", with the same semantics. Eventually we'll retire the debug options, and keep the properties.

**Comment by fabioz** [comment]
I'll take a look at it.
