### ISSUE TITLE
atexit isn't called when debugging is stopped

### ISSUE THREAD

**Issue by lanzkron** [microsoft/ptvsd#2009]
Issue Type: <b>Bug</b>

Create a python file with the following contents:

    import atexit
    import time

    atexit.register(print, "at exit called")
    time.sleep(1000)

Debug the file and then stop debugging during the sleep.
==> At exit isn't called

Extension version: 2019.11.50794
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (16.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment]
This is by design - if you do "Stop Debugging" rather than allowing the program to run to completion, it is equivalent to force-killing the process; so atexit handlers, finally blocks etc are not executed. "Stop" is meant to be 100% reliable, ending the session in any circumstances.

**Comment by lanzkron** [comment]
Is there a way to exit the process from the debugger similar to pressing Ctrl-C in the CLI? I tried `quit()` from a breakpoint but it didn't terminate the whole process tree.
