### ISSUE TITLE
Debug interactive (REPL)

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#201]
The following features must be supported:
- Evaluate code in current frame or any module
- List all processes, threads, frames and get/set current
- IntelliSense: member completions
- IntelliSense: signature info
- Synchronize with processes/threads/frame active selection in VS UI

**Comment by int19h** [comment]
Need to investigate the requirements from VS and VSC - depending on implementation there, it might just need support for arbitrary expression implementation on pydevd side, or we might need some custom protocol messages.

**Comment by edurenye** [comment]
Why has been closed if not fixed?

Should probably have to be moved to https://github.com/microsoft/debugpy

**Comment by int19h** [comment]
This was a ZenHub Epic that combined several issues together. All of those issues were fixed.
