### ISSUE TITLE
urllib.request.urlopen cannot open url

### ISSUE THREAD

**Issue by pjuangph** [microsoft/ptvsd#2010]
Referencing this bug report https://github.com/microsoft/vscode/issues/87384#issuecomment-567497177

I tried it in visual studio, pycharm, and vs code. 
The problem only exists in vscode. I've included a link to the github. you can run main.py in v1.0

**Comment by fabioz** [comment]
@pjuangph It seems you have many working directory based references in your code, so, maybe the working directory is not ok?

Also, can you say which is the actual url you're trying to grab? (the exception you have says that the url is not valid)

I've tried it with the code below and it seems it works for me...

```
from urllib.request import urlopen
import urllib

if __name__ == '__main__':

    page_url = 'http://google.com'
    response = urlopen(urllib.parse.urlparse(page_url).geturl())
    if 'text/html' in response.getheader('Content-Type'):
        html_bytes = response.read()
        html_string = html_bytes.decode("utf-8", "replace")
        print(html_string)
```

**Comment by pjuangph** [comment]
seems to be working for me as well. Maybe it is a problem of my environment. Thanks
