### ISSUE TITLE
Unable to use the VSCode Debugger

### ISSUE THREAD

**Issue by saltgen** [microsoft/ptvsd#2013]
## Environment data

- PTVSD version: 0.2.0
- OS and version: Manjaro Budgie Juhraya 18.1.4
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.0 from venv
- Using VS Code or Visual Studio: VSCode

## Actual behaviour

Trying to use debugger to capture/watch variable values
Error: Unable to find thread for evaluation.

## Expected  behaviour

Once debugger is up an running, should be able to watch and check variable values

## Steps to reproduce:
1. Start a virtual environment using venv
2. Install Django 2.1 and then create dummy project
3. Open project folder with VSCode(editor should pick up the venv's interpreter)
4. Head over to the Debugger tile and select Django as the debugger config
5. Start the Debug session
6. Try getting the output of any variable from the file getting debugged

Error: Unable to find thread for evaluation.

**Comment by karthiknadig** [comment]
@saltgen Can you confirm you are using the right extension ? check the version number it should match the screenshot below.
![image](https://user-images.githubusercontent.com/3840081/71472093-978e2e80-2786-11ea-95f7-b665764c060d.png)

In any case the current debugger version is `>=4.3.2` can you check if you are using the right version of the debugger? you can do this by running the following code.
```py
import ptvsd
print(ptvsd.__version__)
```

Lastly can you share the contents of the `python` pane in the output. It should have something like the screenshot below. I am particularly interested in the lines that start with "User belongs to experiment group ..."
![image](https://user-images.githubusercontent.com/3840081/71472295-4fbbd700-2787-11ea-9dc2-817026a90279.png)

**Comment by saltgen** [comment]
Hello @karthiknadig 

Thanks for looking into this, should I be printing the debugger version on the Debug Console?

I believe I'm uisng the correct extension, here is output from python pane.

![Selection_001](https://user-images.githubusercontent.com/6542058/71515521-a4676b00-28c9-11ea-8ff6-6e7888e19ee5.png)

User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'AA_testing - control'

**Comment by saltgen** [comment]
This is my bad, I have found the issue. 

Please consider adding the live reload feature, for instance after I start the Django debugger I need to reload the local site once more for the debugger to catch the variables, etc.

Thank you for the prompt response though.
