### ISSUE TITLE
Error running debug on Windows

### ISSUE THREAD

**Issue by dmorris0** [microsoft/ptvsd#2020]
I updated VSCode on my Windows computer after not using it for a while, and now I get an error running the debugger:

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
![SharedScreenshot](https://user-images.githubusercontent.com/7038009/71557674-3204a100-2a17-11ea-830b-f3b0cf41ce5c.jpg)

What I noticed was if I restarted VSCode, then I could run my code one time, but the subsequent times I would get this error.

Here is my json file:
``{``
``    "configurations": [``
``        {``
``            "name": "Python: Current File",``
``            "type": "python",``
``            "request": "launch",``
``            "program": "${file}",``
``            "envFile": "${workspaceFolder}/.vscode/.env",``
``            "console": "integratedTerminal"``
``        }``
``    ]``
``}``

Any help would be appreciated.  I see that others have had this problem in the past, but I have not found a solution.

**Comment by int19h** [comment]
Please try this with the new debugger: https://github.com/microsoft/ptvsd/issues/1706#issuecomment-572287267
