### ISSUE TITLE
enable_attach error 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ReonLion** [microsoft/ptvsd#2022]
## Environment data

- PTVSD version: 5.0.0a10
- OS and version: win10-Chinese
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VSCode 1.41.1

## Actual behavior
call enable_attach(address=('127.0.0.1', 5678))
and debug with QGIS
Error: 'str' object has no attribute 'decode'

## Expected  behavior
enable_attach() work fine

## Steps to reproduce:
1. call enable_attach(address=('127.0.0.1', 5678))

Analysis:
error is caused by force_str() defined in common/compat.py. On top of the file,  "unicode = builtins.unicode; bytes = builtins.str" would succeed, so the force_str() would call force_bytes() and execute the code in the 'else' segment. Now, s=bytes(s), due to the 'bytes = builtins.str' above, this may means s=str(s)? so  'str' object has no attribute 'decode' happend.

**Comment by ReonLion** [comment]
I figure it out! For some reson, when call Python console in QGIS, builtins.unicode and  builtins.bytes are all 'str'.

**Comment by int19h** [comment]
It might be a dup of #1978
