### ISSUE TITLE
Debugger soesn't stop at breakpoints - 5.0.0a10

### ISSUE THREAD

**Issue by andlo** [microsoft/ptvsd#2024]
## Environment data
RaspberryPi3 Raspban Bustner

- PTVSD version: 5.0.0a10
- OS and version: Raspban Bustner - Linux 4.19.75-v7+
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3
- Using VS Code or Visual Studio: Theia IDE

## Actual behavior

If my module uses ptvsd.enable_attach() I can attach frm the IDE. But it never stops at breakpoints. 
I did see it work but now it dosnt and I cant figure out why :(

Attached is the logs. If someonecould point in direction for why and how I could fix this I be suer happy.

[ptvsd.adapter-869.log](https://github.com/microsoft/ptvsd/files/4027935/ptvsd.adapter-869.log)
[ptvsd.server-32560.log](https://github.com/microsoft/ptvsd/files/4027936/ptvsd.server-32560.log)

## Expected  behavior
That it stoped at breakpoints....

**Comment by int19h** [comment]
Are you doing `wait_for_attach()` after `enable_attach()`? Looking at the logs, it seems like the code is already running while some of the breakpoints are being set, in which case it might have already run past them.

**Comment by andlo** [comment]
I did try both.....
The code is running and enable_attach() is made from one file in one module. The code where brekpoints are are run everytime something happens, but it still misses breakpoints.

**Comment by andlo** [comment]
Yah it seems that that is a problem - I enable_attach on a wrong place.

I try figure out when to do it.

closing as it isnt a bug.
