### ISSUE TITLE
inject_dll_x86.exe being quarantined by virus scanners

### ISSUE THREAD

**Issue by gregfergusonvizio** [microsoft/ptvsd#2028]
Hi,

Would like to raise the issue that the file inject_dll_x86.exe is being quarantined by virus scanners. According to the available data, this file appears to be reaching out to an IP address in Japan.

https://www.virustotal.com/gui/file/ffcb4aa810425c60fa8be30c6109b35085354dc36dfe959707a9436318b5ac5a/detection

**Comment by fabioz** [comment]
That's really weird... the source code definitely doesn't have anything which access the net, although it injects a dll into another process though, so, I'm not surprised virus scanners tag it.

As a note, it's built locally by:

https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/pydevd_attach_to_process/windows/compile_windows.bat

**Comment by karthiknadig** [comment]
This should be fixed in v5.0.0a11

**Comment by fabioz** [comment]
Note: discussion in: https://github.com/microsoft/vscode-python/issues/9474
