### ISSUE TITLE
Debugger quits when pressing restart on breakpoint (ctrl-shift-f5)

### ISSUE THREAD

**Issue by andersea** [microsoft/ptvsd#2029]
## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.57377-dev
- OS and version: Windows 10 Version 1909
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3 amd64
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): false (Language Server)

I am using the internal preview of the extension.

## Expected behaviour

Pressing restart restarts the program.

## Actual behaviour

Pressing restart quits the debugger.

## Steps to reproduce:

1. Example code:

```
import time

def main_sync():
    print('Hello')
    # Set breakpoint on next line
    time.sleep(10)
    print('World')
    time.sleep(5)
    print('Bye')


if __name__ == '__main__':
    main_sync()
```
2. Set breakpoint on the `time.sleep(10)` line and run the script in the debugger. The debugger stops on the line.

![Screenshot of debugger stopped on breakpoint](https://user-images.githubusercontent.com/10992982/72022289-5ad73280-3270-11ea-90d9-03db724d4676.png)

3. Press the green restart icon in the debugger toolbar, or press ctrl-shift-f5.

## Logs
Terminal output:

```
(stream-trio-test-gbo-I5e8-py3.7) PS C:\Users\Anders\Documents\python\stream-trio-test> ${env:PTVSD_LAUNCHER_PORT}='55226'; & 'C:\Users\Anders\AppData\Local\pypoetry\Cache\virtualenvs\stream-trio-test-gbo-I5e8-py3.7\Scripts\python.exe' 'c:\Users\Anders\.vscode\extensions\ms-python.python-2020.1.57377-dev\pythonFiles\lib\python\new_ptvsd\wheels\ptvsd\launcher' 'c:\Users\Anders\Documents\python\stream-trio-test\trio_restart_on_breakpoint.py' 
Hello
(stream-trio-test-gbo-I5e8-py3.7) PS C:\Users\Anders\Documents\python\stream-trio-test> 
```

**Comment by karthiknadig** [comment]
This issue is addressed in `ptvsd` version `5.0.0a12`. It should be available in the insiders version of the extension soon.

**Comment by kzhui125** [comment]
When will this be fixed in stable version of the extension?

**Comment by karthiknadig** [comment]
@kzhui125  This is fixed in the stable version of the extension. Make sure you get the extension version `2020.3.*`.
