### ISSUE TITLE
Debug restart session does not work

### ISSUE THREAD

**Issue by schperplata** [microsoft/ptvsd#2034]
Issue Type: <b>Bug</b>

With the latest release, debug restart action does not work. 
It only stop current debug session.

Very simple to reproduce, run any py file with default python launch configuration and try to restart debug session.

Extension version: 2020.1.57204
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by karthiknadig** [comment]
Likely related #2029

**Comment by andersea** [comment]
Sounds like a duplicate of #2029

**Comment by schperplata** [comment]
Exactly as #2029. I don't know why I coun't find yesterday, but I sure searched for.
Sorry for duplicating already reported issue.
