### ISSUE TITLE
debugging pytest_subprocess causes a usage error

### ISSUE THREAD

**Issue by dvirtz** [microsoft/ptvsd#2037]
## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.57204
- OS and version: MacOS Mojave
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: pytest 5.3.2
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Jedi

## Expected behaviour

able to debug tests with `testdir.runpytest_subprocess()`

## Actual behaviour

I see the following in `result.errlines`:
```
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --port 62985 --client 127.0.0.1 --multiprocess --json-dap-http --file
  inifile: None
  rootdir: /Users/dyitzchaki/.vscode/extensions/ms-python.python-2020.1.57204/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/_vendored/pydevd
```

Seems like the debugger is adding command line options to pytest
## Steps to reproduce:
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

put a breakpoint on `result.assert_outcomes()` in the following test:
```
def test_subprocess(testdir):
  result = testdir.runpytest_subprocess()
  result.assert_outcomes()
```

debug configuration:
```
    {
      "name": "PyTest",
      "type": "python",
      "request": "launch",
      "module": "pytest",
      "console": "integratedTerminal",
      "justMyCode": false,
      "subProcess": true,
      "args": [
        "${workspaceFolder}/tests/pytest/test_bug.py"
      ]
    }
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

None

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
workbench.desktop.main.js:sourcemap:254 [Extension Host] Info Python Extension: 2020-01-11 20:37:06: Cached data exists getEnvironmentVariables, /Users/dyitzchaki/projects/falcon
workbench.desktop.main.js:sourcemap:254 [Extension Host] Info Python Extension: 2020-01-11 20:37:06: Cached data exists KeyPrefix=Cache_Method_Output_b.getCondaVersion-Args=
workbench.desktop.main.js:sourcemap:1572   ERR timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2819:336)
    at async R.terminate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5113:637)
workbench.desktop.main.js:sourcemap:254 [Extension Host] Info Python Extension: 2020-01-11 20:37:33: Cached data exists getEnvironmentVariables, /Users/dyitzchaki/projects/falcon
2workbench.desktop.main.js:sourcemap:254 [Extension Host] Info Python Extension: 2020-01-11 20:37:33: Cached data exists getEnvironmentVariables, <No Resource>
workbench.desktop.main.js:sourcemap:254 [Extension Host] Info Python Extension: 2020-01-11 20:37:33: > conda info --json
workbench.desktop.main.js:sourcemap:254 [Extension Host] Info Python Extension: 2020-01-11 20:37:33: > conda --version
```

**Comment by int19h** [comment]
You can disable subprocess debugging with `"subProcess": false` in your launch.json - this should allow the test to run, although it would prevent debugging of any code in the subprocess.

It does add command line arguments to the Python binary - it has to, in order to debug the subprocess. Those arguments shouldn't be visible in `sys.argv`, though, because they're removed before the user code starts running.But if the app accesses the command line directly via OS APIs, it can still see the original command line - we've seen it with Flask on 2.7. Perhaps pytest is doing something like this here, as well?

**Comment by dvirtz** [comment]
I still see the same error with `"subProcess": false` and it seems that it does read the arguments from `sys.argv`: https://github.com/pytest-dev/pytest/blob/7ff91d81277f92a9fa0910133b61f9eb80a0a8c0/src/_pytest/config/__init__.py#L206

**Comment by fabioz** [comment]
The problem is that `pytest` does something as `python -mpytest`, which was not expected when patching the args (it would only handle something as `python -m pytest`).

I'm working on a fix.
