### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by hiddenslave** [microsoft/ptvsd#2047]
Issue Type: <b>Bug</b>

File "/root/.vscode-server-insiders/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/__main__.py", line 78, in <module>
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Extension version: 2020.1.58038
VS Code version: Code - Insiders 1.42.0-insider (960cddb992cc96d47f56b633b361909f1b5b3353, 2020-01-10T06:48:04.971Z)
OS version: Linux x64 5.3.0-26-generic
Remote OS version: Linux x64 5.3.0-26-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (4 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 1, 1|
|Memory (System)|17.24GB (11.74GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Docker Compose …|
|OS|Linux x64 5.3.0-26-generic|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (4 x 2112)|
|Memory (System)|17.24GB (11.74GB free)|
|VM|0%|
</details>

**Comment by int19h** [comment]
It sounds like your container has `LANG` or some of the `LC_*` environment variables set to a specific locale, but that locale isn't actually supported by the OS running inside the container. 

If you expect the locale to be set, make sure that it's generated - `sudo locale-gen` should do the trick. If you deliberately removed the locales to save space, you need to ensure that environment variables reflect that.
