### ISSUE TITLE
Unable to execute command in command prompt for remote debugger.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/ptvsd#2053]
""Describe this issue**
This issue appears in all three versions of ptvsd installed using the following three methods:
pip ptvsd==3.2.1 for legacy debugger
pip install ptvsd and pip install ptvsd==5.0.0a11 for debug debugger

*Legacy debugger is a failure caused after the debugger fails. If you run legacy debugger first, it will work

**Steps to Reproduce**
1.Create python application named Testing in VS
2.using "pip install ptvsd" to install ptvsd in python 3.7(64-bit) environment
3.In command prompt(right-click the python environment and select "Open Command Prompt Here…"), execute:
python -m ptvsd --host 127.0.0.1 --port 4022 C:\Users\vwazho\source\repos\Testing\Testing\Testing.py

**Expected behavior**
no any error in command prompt wondow

**Additional context and screenshots**
execute command failed with errors
![image](https://user-images.githubusercontent.com/39871640/72875020-590c7500-3d2e-11ea-81b2-831f8c81a231.png)

**VS version**
![image](https://user-images.githubusercontent.com/39871640/72875062-72152600-3d2e-11ea-8bcd-23aa884708f2.png)

**Repro video**
[remote debugging.zip](https://github.com/microsoft/PTVS/files/4095833/remote.debugging.zip)

**Comment by int19h** [comment]
The adapter is supposed to exit as soon as all debuggees exit. It's a bug if it does not.
