### ISSUE TITLE
Validate breakpoint targets

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#206]
It is currently possible to set breakpoints on lines where valid breakpoints aren't possible (e.g. blank lines, or lines in the middle of a multi-line statement). When that happens, there's no error or warning, and the breakpoint doesn't get hit.

We should either automatically move the breakpoint to the nearest valid line, or display an error message in that case.

**Comment by int19h** [comment]
https://github.com/Microsoft/PTVS/issues/207

**Comment by int19h** [comment]
First, the general problem. In CPython, breakpoints don't work on lines of code which don't map to any bytecode range at runtime, since the bytecode interpreter uses those ranges to keep track of the current source line for debugger purposes. This can happen for various reasons: blank lines, obviously, but also `pass` statements (although not in all contexts). 

In addition, on Python 2 especially, all bytecode for multiline statements usually gets mapped to the last line of that statement. E.g. for something like this:
```py
print(1,
      2, 3,
      4, 5, 6)
```
all the bytecode is recorded as corresponding to line 3, so that's the only line where you can set the breakpoint.

Since this all is already dependent on Python version, and likely to do so in the future, we can't rely on parsing the source code ourselves - we need to look at the bytecode at runtime, and extract valid line numbers from there. But when setting the breakpoint, the target file might not even be loaded by Python at all, so there's no corresponding code object; and even if there is, Python doesn't provide any way to enumerate existing code objects, or to find one by filename.

However, the file can be separately loaded, parsed and compiled (without executing it) to produce a code object. This code object only covers the top level of the module, but it contains references to other code objects generated for nested classes, functions etc. Thus, it is possible to walk that entire tree and extract line information from all code objects that get produced from the file. Here's some straightforward recursive code that does that for any file given to it:
```py
import dis
import sys
import types

def get_valid_lines(code):
    for _, lineno in dis.findlinestarts(code):
        yield lineno
    for const in code.co_consts:
        if isinstance(const, types.CodeType) and const.co_filename == code.co_filename:
            for lineno in get_valid_lines(const):
                yield lineno

filename = sys.argv[1] 
with open(filename) as f:
    source = f.read()
code = compile(source, filename, 'exec')
lines = set(get_valid_lines(code))
print(lines)
```
The debugger can do something similar every time a breakpoint is set. I don't even think we'll need caching, because setting a breakpoint is a one-off operation, so the overhead of parsing the file won't be noticeable (but parsing it every time would accommodate e.g. exotic scenarios where the file changes).

If the line on which a breakpoint is being set is not in the list of valid lines, we can report the breakpoint as invalid (like C#), or we can adjust it to the next valid line (like C++). It's hard to say whether one or the other is preferable in general - for a multiline statement in Python 2, the user would probably expect it to adjust, but for all other scenarios like `pass`, moving BP might actually place it in an undesirable location - supposing something like this:
```py
while foo():
    pass
print('done')
```
The breakpoint on `pass` would be invalid, but moving it to `print` makes no sense either. If we only look at Python 3, where individual lines of multiline statements are properly mapped to bytecode, all remaining scenarios are like this, so rejecting the breakpoint is probably a better idea.

**Comment by karthiknadig** [comment]
/cc @qubitron 
Let us know your opinion on how to handle invalid breakpoints.

**Comment by DonJayamanne** [comment]
Can we also add the same for django/flask templates?
Or should that be tracked as a separate issue?

**Comment by int19h** [comment]
It needs to be investigated first. I don't think this approach will work there.

**Comment by qubitron** [comment]
For invalid breakpoints I'd prefer to move to the next valid line, though I'm not sure if the VS Code UI/DAP supports that @DonJayamanne.

If that is too difficult, then we can start by at least showing that it's not valid.

**Comment by int19h** [comment]
Even if the next valid line is semantically unrelated? (as in the loop example... I'd expect that if the breakpoint is adjusted there, it's one line up, not one line down).

Implementation-wise it's all very similar - the only real difference is setting the invalid flag vs setting the line number in response message.

**Comment by qubitron** [comment]
I would like to optimize for minimizing wasted time. If the breakpoint is invalid, I won't find that out until run-time, and it's annoying when the breakpoint gets skipped/missed and I have to restart my program to hit the breakpoint again. If we push it down one line past the point of execution, then again I might need to restart my program to hit the point that I wanted to hit.

So always going up one line means I never miss the point of execution I'm trying to stop on, so that sounds like a good approach to me, even though it is inconsistent with how C++. 

Breaking in the wrong spot doesn't really ever "do harm", but not breaking when I wanted to can waste time.

**Comment by int19h** [comment]
Thinking about it, adjusting to the previous seems to work well in general - in most scenarios it's reasonable. One case where it can be confusing with multiline, e.g.:

```py
print(1,
      2, 3,
      4, 5, 6)
```
In Python 2, this will only break on the last line of three. Suppose the user sets a breakpoint at print, where it's more natural. If we adjust upwards, they will end up on a different statement. If we adjust downwards, it'll do exactly what they wanted, breaking right before print.

However, this is specific to Python 2.

**Comment by qubitron** [comment]
The case I hit this was:
```
a = [
  1,
  2,
  3]
```

I set the breakpoint on the first line but would expect it to hit on the second instead.

**Comment by int19h** [comment]
Interesting - that one happens on Python 3 as well.

Either way, we can implement one thing and then try it out. It's an easy change later to adjust in a different direction or invalidate the breakpoints instead.

**Comment by qubitron** [comment]
Let's go with the adjust to previous line rule, so that we never run past where the user wanted us to execute.
