### ISSUE TITLE
Two processes started by Python debugger (usecase mixed Python/C++ debugging)

### ISSUE THREAD

**Issue by D-Roberts** [microsoft/ptvsd#2064]
## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.58038
- OS and version: macOS Catalina 10.15.2
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.6.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: NA
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): python.jediEnabled=true by default.

## Expected behaviour

Python debugger should start one process. Then the lldb debugger should be able to attach to this one process. Should be able to thus debug and step through breakpoints in both the Python code and the C++ code.

## Actual behaviour

The Python debugger starts 2 processes (2 PIDs). It is unclear which one to pick to attach the lldb debugger to. Then lldb does not attach successfully. If one of the PIDs is killed, both of them seem to be killed. (attached image of the 2 processes that show up when trying to attach the lldb debugger)

## Steps to reproduce:
1. Add the Extension to VSCode and enable.

2. Create settings.json with Pythonpath:
{ "python.pythonPath": "/Users/denisaroberts/anaconda3/bin/python" }

3. Create launch.json for mixed debugging :

> {
"version": "0.2.0",
"configurations": [
{
"name": "Python launch",
"type": "python",
"request": "launch",
"stopOnEntry": false,
"pythonPath": "/Users/denisaroberts/anaconda3/bin/python3",
"program":"${file}",
"cwd":"${workspaceFolder}",
"console": "internalConsole",
"env": {},
"envFile": "${workspaceRoot}/.env",
"justMyCode": false},
{
"name": "lldb attach Debug",
"request": "attach",
"program": "/Users/denisaroberts/anaconda3/bin/python3",
"stopOnEntry": false,
"pid": "${command:pickProcess}",
"type": "lldb"
}
]
}

4. Example code (similar for other code examples):

Python code: eg.py:

`import ctypes import numpy import glob libfile = glob.glob('libProject.so')[0] mylib = ctypes.CDLL(libfile) mylib.mysum.restype = ctypes.c_longlong mylib.mysum.argtypes = [ctypes.c_int, numpy.ctypeslib.ndpointer(dtype=numpy.int32)] array = numpy.arange(0, 100000000, 1, numpy.int32) array_sum = mylib.mysum(len(array), array print('sum of array: {}'.format(array_sum))`

C++ code mysum.cpp (included for completeness):

`extern "C" long long mysum(int n, int* array) { // return type is 64 bit integer long long res = 0; for (int i = 0; i < n; ++i) { res += array[i]; } return res; }`

5. Add breakpoints in code (both Python and C++).

6. Launch Python debugger.

7. Two Python debugging processes seen (two different PIDS), pick one to attach lldb debugger.
 
<img width="933" alt="Screenshot 2020-01-28 18 23 04" src="https://user-images.githubusercontent.com/4791217/73314694-72b12f00-41fc-11ea-9de6-9168bdc6a87d.png">
).

**Comment by fabioz** [comment]
Hi @D-Roberts, this is actually correct/expected... one process is launched to be the debug adapter (some debuggers use node.js to do that, but `ptvsd` does it through a python process) and the other one is the python running your own code.

So, the problem I see there is that the select process dialog isn't very helpful because it's doesn't show which one is the debugger process and which one is the adapter (but that's something to be solved on the project that does the attach through gdb, not in ptvsd).

As a workaround you should be able use `ps` in a shell to find the target process command line/pid and then in the attach filter through the target pid.

**Comment by D-Roberts** [comment]
@fabioz This is helpful, thanks.
