### ISSUE TITLE
Invalid message: Session is not initialized yet

### ISSUE THREAD

**Issue by haniamr** [microsoft/ptvsd#2067]
## Environment data

- PTVSD version: **latest master**
- OS and version: **Windows 10 host + Alpine Linux container**
- Python version (& distribution if applicable, e.g. Anaconda): **3.8.1**
- Using VS Code or Visual Studio: **VS Code**
- VS Code Python extension: **2020.2.60336-dev**

## Actual behavior
At random times, I get the error "_Invalid message: Session is not initialized yet_" when trying to debug a Django app running in a Linux container. I made sure to have the opt-in properties in the user settings:
```
    "python.experiments.optInto": [
        "DebugAdapterFactory - experiment",
        "PtvsdWheels37 - experiment"
    ]
```
It might go away after a couple of trials, and it might after restarting VS Code, it's totally random. Not sure what's wrong here, however I'm using the [Extension Development Host] if that would be of any relevance.

Looks like it's the same symptoms as #2044, but I updated to the latest Insider extension and it didn't resolve it for me.

## Expected  behavior
Debugger to attach successfully.

## Steps to reproduce:
1. Create an empty Django project
2. Add Dockerfile:
```
FROM python:alpine
RUN apk add python3-dev build-base linux-headers pcre-dev
ADD requirements.txt .
RUN python3 -m pip install -r requirements.txt
LABEL Name=django_demo Version=0.0.1
EXPOSE 8000
WORKDIR /app
ADD . /app
CMD ["uwsgi", "-http", ":8000", "--module", "django_demo.wsgi"]
```
3. Add requirements.txt:
```
asgiref==3.2.3
Django==3.0.2
pytz==2019.3
sqlparse==0.3.0
uWSGI==2.0.18
```
4. Build image and run the container (ensure to update the paths in the volume mappings):
```
& docker build --rm -f 'C:\temp\django_demo/Dockerfile' -t 'djangodemo:latest' 'C:\temp\django_demo'
& docker run -dt -P -e 'PTVSD_ADAPTER_ENDPOINTS=/pydbg/ptvsd/dbg.json' -e 'PTVSD_LOG_DIR=/app' -v 'C:\temp\ptvsd-master\ptvsd-master\src:/pydbg:rw' -p '5678:5678' --entrypoint 'python' 'djangodemo:latest' /pydbg/ptvsd --host 0.0.0.0 --port 5678 --wait manage.py runserver --noreload --nothreading 0.0.0.0:8000
```

5. Add a "Python: attach" configuration that points to localhost:5678
6. F5

Logs from the container:
[ptvsd.server-1.log](https://github.com/microsoft/ptvsd/files/4131820/ptvsd.server-1.log)
[ptvsd.adapter-11.log](https://github.com/microsoft/ptvsd/files/4131821/ptvsd.adapter-11.log)

**Comment by int19h** [comment]
This looks like it's the old debugAdapter.ts code on the extension side talking - it sends the "attach" request immediately without going through the full DAP initialization sequence.

Can you try a simple local launch for a hello world type app, and see what that gives you in the terminal? If "old_ptvsd" shows up there, we'll know that it's an issue with the opt-in logic.

**Comment by karthiknadig** [comment]
Can you share the contents of Output > Python panel? Specifically lines that star with “user belongs to experiment”.

**Comment by fabioz** [comment]
As a note, in my case (in https://github.com/microsoft/ptvsd/issues/2044) I changed the settings to `Python: Insiders Channel` to `daily` and when it got the latest version it worked (@haniamr can you check if you still have the same issue if you use the `daily` channel?)

i.e.: the setting is `"python.insidersChannel": "daily"`

**Comment by haniamr** [comment]
@int19h I've tried that and it's using the "new_ptvsd" debugger.
@karthiknadig Here's the output:
```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - control'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'LS - control'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - enabled'
```
@fabioz I've add the setting and it then installed the new extension, I restarted VS Code and now I'm unable to repro the issue.

It was kind of random so I'm not sure if it's fixed or not, so will keep playing around with it today and close the issue if it no longer repros. Thanks everyone for the help!

**Comment by haniamr** [comment]
Alright, it seems there's a weird issue in my VS Code instance where it insists on using a particular version of the extension (latest stable) even though I explicitly uninstalled it. Once I do this (possibly every session) and install the insiders, it works fine, so I'll close this issue for now.
