### ISSUE TITLE
Questions: What are these executable files?

### ISSUE THREAD

**Issue by xmha97** [microsoft/ptvsd#2069]
Hello, What are these executable files?
![image](https://user-images.githubusercontent.com/23485114/73536350-8fa35900-43da-11ea-9487-62134276a95a.png)
Can I delete them?

**Comment by fabioz** [comment]
They are helpers to do an attach to pid (they inject a dll that will run code on your target process in order to attach the debugger to it). 

You can delete them if you won't use the attach to pid feature.
