### ISSUE TITLE
Just My Code fine grained control

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#207]
Like #194, but with the ability for the user to specify whether they want to treat site-packages as part of the standard library, or as their code.

**Comment by karthiknadig** [comment]
See https://github.com/Microsoft/vscode-python/issues/2087#issuecomment-425528613 for more details.

**Comment by karthiknadig** [comment]
@int19h #997 covers this scenario right? so i think we can close this.

**Comment by int19h** [comment]
Not quite. This one is specifically about site-packages. You can manually write a rule for them with #997, but this issue is about automatically doing that for site-packages of the active Python interpreter, essentially.

**Comment by karthiknadig** [comment]
This can be achieved with `rules` so closing this item.
