### ISSUE TITLE
Debugging pytest with multiprocessing does not work

### ISSUE THREAD

**Issue by gandroz** [microsoft/ptvsd#2074]
## Environment data

- VS Code version: 1.38.1
- Extension version (available under the Extensions sidebar): 2019.10.41019
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7

## Expected behaviour

Setting a breakpoint inside subprocess or after a sub-process starts should be possible

## Actual behaviour

I am aware of microsoft/vscode-python#4525 but it does not work for me. Whereas I am able to break before a sub-process is launched, the debuger stops as soon as a sub-process starts.

**Comment by int19h** [comment]
See https://github.com/microsoft/ptvsd/issues/1706#issuecomment-572287267
