### ISSUE TITLE
VSCode debug console: print expressions no longer have output

### ISSUE THREAD

**Issue by kzhui125** [microsoft/ptvsd#2075]
previously:

<img width="512" alt="1" src="https://user-images.githubusercontent.com/11925432/74089135-062a1000-4ad9-11ea-8254-f54ebdeb1561.png">

now:

<img width="439" alt="2" src="https://user-images.githubusercontent.com/11925432/74089158-3ec9e980-4ad9-11ea-926a-f5c81e3bdb7a.png">

I see the output goes to terminal, it's very inconvenient.

Especially when I want to see pandas dataframe values (pretty print).

**Comment by karthiknadig** [comment]
This is same as https://github.com/microsoft/ptvsd/issues/2036.
