### ISSUE TITLE
Python debug restart fails

### ISSUE THREAD

**Issue by naschidaniel** [microsoft/ptvsd#2078]
The restart Button fails to start the debug modus for my django enviroment.

## Environment data
- VS Code version: 1.42.0
- OS and version: OS: Linux x64 5.4.17-200.fc31
- Python version (& distribution if applicable, e.g. Anaconda): python 3.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: django 3.0.2

## Expected behaviour

If i press the restart button, the debugmodus and the server should restart

## Actual behaviour

Since 1.42.0 the restartbutton fails to restart

## Steps to reproduce:
Install conda
Install django

launch.jsong
     {
      "name": "Python: Django",
      "type": "python",
      "request": "launch",
      "program": "${workspaceFolder}/manage.py",
      "args": [
          "runserver",
          "--noreload"
      ],
      "django": true
    }

Thanks for your support

**Comment by karthiknadig** [comment]
This has been addressed. The fixed verison should be available in the next release https://github.com/microsoft/ptvsd/issues/2029
