### ISSUE TITLE
'Invalid variable attributes' shows instead of variables

### ISSUE THREAD

**Issue by luabud** [microsoft/ptvsd#2080]
Filed originally here https://github.com/microsoft/vscode/issues/90238#issue-561702431

VSCode Version: 1.42.0
OS Version: Windows_NT x64 10.0.18362
Steps to Reproduce:
Have Python and Gauge loaded

Build Gauge .spec file, step_implement Python file with variables present.
Set debug start point in Python file.
Run 'debug scenario' to begin spec.
Local variables show up as ': Invalid variable attributes'; watches show up as 'NameError("name '(watched item)' is not defined")'
Does this issue occur when all extensions are disabled?: No, debug option disabled when Gauge unloaded, Python will not run with Python unloaded.

Python version 3.7.6 32-bit
Gauge version 0.0.11

**Comment by Flintols** [comment]
What issue do I look at to get updates?

**Comment by int19h** [comment]
Can you try adding `"logToFile": true` in launch.json, and see if that helps with the logs? It should write them to the directory where the extension is installed.

**Comment by Flintols** [comment]
ok, its on, but still have issue present

**Comment by luabud** [comment]
@int19h because the session is started through the Gauge extension, it doesn't seem to pick up the launch.json file in the workspace (it seems to create a configuration under the hood, but I could be wrong). I was able to produce the log files by setting PTVSD_LOG_DIR in the python.properties file under the env\default folder in the workspace, which is used by the Gauge extension. 

@Flintols without looking into the logs it's going to be hard to diagnose what's going on, as we can't reproduce the issue 😟. They should be saved in the folder you defined through the PTVSD_LOG_DIR in the python.properties file. The only other thing I can think of is that there may be some experiments that may be interfering with it.  Do you mind pasting here the contents from the Python Output channel?

![image](https://user-images.githubusercontent.com/45497113/74563324-6548b400-4f21-11ea-92eb-666c4ffac62f.png)

**Comment by Flintols** [comment]
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'Reload - control'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'WebHostNotebook - control'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> py -3.7 -c "import sys;print(sys.executable)"
> py -3.6 -c "import sys;print(sys.executable)"
> py -3 -c "import sys;print(sys.executable)"
> py -2 -c "import sys;print(sys.executable)"
> C:\Program Files (x86)\Python37-32\python.exe -c "import sys;print(sys.executable)"
> conda info --json
Starting Jedi Python language engine.
> C:\Program Files (x86)\Python37-32\python.exe -c "import jupyter"
> C:\Program Files (x86)\Python37-32\python.exe -c "import jupyter"
> C:\Program Files (x86)\Python37-32\python.exe -c "import notebook"
> C:\Program Files (x86)\Python37-32\python.exe -c "import notebook"
> conda --version

**Comment by int19h** [comment]
Can you try setting it as global environment variable temporarily, just to get the logs? Also note that the directory should already exist.

**Comment by Flintols** [comment]
logs file still empty... where is the default to?

**Comment by luabud** [comment]
It doesn't default to any location, it tries to find the path to the directory you set in the setting, and if it doesn't exist I think it simply doesn't save the logs (and ofc, correct me if I'm wrong @int19h).

**Comment by int19h** [comment]
What does `import ptvsd; print(ptvsd.__version__)` output for you if you do it from the script being debugged?

**Comment by Flintols** [comment]
4.1.4

**Comment by int19h** [comment]
That is surprisingly old! Even for the stable debugger (4.x), the most recent version that we have is 4.3.2, and that was from August last year.

It's very strange that you're getting this in the recent version of the extension. There must be some issue with the install that kept the old bits around. What does it show if you do `print(ptvsd.__file__)`?

**Comment by Flintols** [comment]
C:\Users\myself\AppData\Roaming\Python\Python37\site-packages\ptvsd\__init__.py

**Comment by Flintols** [comment]
trying to install, it tells me that getgauge 0.3.5 has the requirement of ptvsd 4.1.4

**Comment by Flintols** [comment]
upgraded to getgauge 0.3.8, and ptvsd 4.3.2

**Comment by Flintols** [comment]
it is still showing 4.1.4 with print(ptvsd.__version__). How do I fix this?

**Comment by Flintols** [comment]
it will show as changed, but next time I start VSCode, it returns to previous version

**Comment by int19h** [comment]
I think you might have different versions installed globally (where it got 4.1.4 from), and in the virtual env. Perhaps the Gauge extension is re-creating the virtual env every time?

By the way, the Python extension will be moving to https://github.com/microsoft/debugpy (previously known as ptvsd 5.x) shortly. It should still be able to attach to ptvsd 4 debug servers, but we won't be actively testing that scenario once debugpy is stable - so other extensions that wrap ptvsd will need to be updated eventually.

**Comment by Flintols** [comment]
have updated to python 3.8.2, besides it not supporting pythonnet, the ptvsd works.

**Comment by Flintols** [comment]
also had to install getgauge with --no-deps
