### ISSUE TITLE
"justMyCode" setting doesn't work

### ISSUE THREAD

**Issue by ftrofin** [microsoft/ptvsd#2084]
## Environment data

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Also happens in the latest version January 2020 (1.42)

## Expected behaviour

Setting "justMyCode" flag in the launch.json should be honored by the debugger.

## Actual behaviour

I can't step in library code no matter what I do. This happens in both the November 2019 and January 2020 editions.

## Steps to reproduce:
First of all, there are three places where "justMyCode" can be set: in the launch.json, user prefs and worspace prefs. I set it to "false" in all three places. I still get this error message:
```Frame skipped from debugging during step-in.
Note: may have been skipped because of "justMyCode" option (default == true). Try setting "justMyCode": false in the debug configuration (e.g., launch.json).```

**Comment by int19h** [comment]
Can you share the complete debug configuration JSON that you're using?

**Comment by int19h** [comment]
No follow-up - closing for now. Please re-open if you are still seeing the issue with the most recent version.
