### ISSUE TITLE
Print-function prints only None in Debug Console Despite Setting "redirectoutput" as true

### ISSUE THREAD

**Issue by ruizhuanguw** [microsoft/ptvsd#2086]
Issue Type: <b>Bug</b>

I edited the lanch.json and explicitly specify "redirectOutput": true. However, print-function still prints None in Debug Console and no print output in terminal either. 

Extension version: 2020.2.63072
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (21.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment]
Can you share your entire debug configuration from launch.json, and ptvsd version number? (`import ptvsd; print(ptvsd.__version__)`)

**Comment by int19h** [comment]
Closing due to lack of follow-up.
