### ISSUE TITLE
CPython 2.6 compatibility

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#209]
Ensure that it works, and add it to the list of supported targets (i.e. make sure we run our tests against it, build wheels etc).

**Comment by int19h** [comment]
Wheels for 2.6 and 3.3 are optional.

**Comment by zooba** [comment]
We should consider 2.5 support, as we've had requests for it. It may be as simple as:

```python
try:
    import json
except ImportError:
    import simplejson as json
```

**Comment by karthiknadig** [comment]
2.6 compatibility issues: I will add more as I discover them
1. Requires a substitute for importlib used to import vendored modules
2. str.format() requires numbered placeholders

**Comment by huguesv** [comment]
3.3 compatibility:
![image](https://user-images.githubusercontent.com/1696845/41735481-ac070900-753e-11e8-85dd-03e054134d5b.png)

3.4 appears to be working fine (our VS UI tests all pass)

**Comment by karthiknadig** [comment]
We decided not to support python 2.6.
