### ISSUE TITLE
"?" Is displayed incorrectly in debug console when debug flask.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/ptvsd#2090]
## Repro steps:
Pre-requesites:
Clone repro and run the setup script:
	git clone  https://github.com/qubitron/pydemo
	cd pydemo
	py -3 setup.py
	
In user settings add:
"python.jediEnabled": false
1. Open stackoverflow-flask folder
2. Select "Debug"
3. Select "Add Configuration…" in "DEBUG" dropdown menu
4. Customize the path in launch.json:
![image](https://user-images.githubusercontent.com/59192491/74519597-fd11c680-4f50-11ea-8e89-7f789021a48d.png)
5. Set "DEBUG" to "Python:Flask"
![image](https://user-images.githubusercontent.com/59192491/74519614-0438d480-4f51-11ea-8049-0a08f5b18a46.png)
6.Start to debug and observe app starts in terminal, ctrl+click to open the app in the browser
7. Set breakpoint on line6 of main.py and then start to debug and refresh the browser page
8. Make sure breakpoint is hit and main.py works
9. Click "F10/F11/Shift+F11/stop" to verify debug works

## Expected behaviour
The debug console display correct without incorrect symbol.

## Actual behavior
"?" Is displayed incorrectly in debug console.
![image](https://user-images.githubusercontent.com/59192491/74519866-7c06ff00-4f51-11ea-99be-a44ade0d0318.png)

## Test Environment
![image](https://user-images.githubusercontent.com/59192491/74519937-9e008180-4f51-11ea-9afd-ab22f1759e5c.png)

**Comment by int19h** [comment]
This is ptvsd 4 - can you please try the same with ptvsd 5, by following [these instructions](https://github.com/microsoft/ptvsd/issues/1706#issuecomment-572287267)?
