### ISSUE TITLE
"Stop debugging" does not stop multiprocessing processes anymore

### ISSUE THREAD

**Issue by pfaion** [microsoft/ptvsd#2091]
Issue Type: <b>Bug</b>

Hi, I'm working on a larger Python project that spawns multiple processes with `multiprocessing.Process(...).start()`. At the end of the main process we `.join()` on all `multiprocessing.active_children()`, so the main process only ends when all child processes have finished.

Previously this worked well together with the built-in Python debugging from vscode. Hitting "Stop debugging" would quit the child processes, resulting in the main process to exit gracefully after all children were finished. With the latest version of vscode I do not get this behavior anymore. Instead, hitting "Stop debugging" results in the main process quitting and the Child processes continuing to run.

I'm not sure if this description is sufficient for making sense out of it. I just hope that someone goes "ah, yes, obviously!" and it's clear what the problem is. Otherwise I can try to provide a minimal example, but this might take some time.

Extension version: 2020.2.63072
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (22.80GB free)|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment]
Which version of ptvsd are you running? You can do:
```py
import ptvsd
print(ptvsd.__version___)
```
in your app to get that info.

**Comment by pfaion** [comment]
ptvsd version 5.0.0a12

Since this is a pre-release I double checked and I did not subscribe to any insiders version of the python extension on this machine.

**Comment by int19h** [comment]
This is https://github.com/microsoft/debugpy/issues/3 - we have a fix already, it just hasn't shipped in the extension yet.

**Comment by pfaion** [comment]
Awesome, thanks for the quick response!

**Comment by kenmillar253** [comment]
Oh! Do you mean it will be released soon?
