### ISSUE TITLE
CPython 3.1-3.3 compatibility

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#210]
Ensure that it works, and add it to the list of supported targets (i.e. make sure we run our tests against it, build wheels etc).

**Comment by IgorNovozhilov** [comment]
Hi! Are there any deadlines to support this functionality?

**Comment by karthiknadig** [comment]
@IgorNovozhilov No, this is not planned for the near future. Sorry.

**Comment by gramster** [comment]
Not planning this.
