### ISSUE TITLE
Exception in thread ptvsd.stopping (most likely raised during interpreter shutdown

### ISSUE THREAD

**Issue by vega1207** [microsoft/ptvsd#2102]
Python2.7 scripts executed in the vs code, which will display  "Exception in thread ptvsd.stopping (most likely raised during interpreter shutdown)", but I run the console window, which is good, what's the problem about it, thanks!

**Comment by int19h** [comment]
Can you please [try it with the new debugger](https://github.com/microsoft/ptvsd/issues/1706#issuecomment-572287267), and see if that helps?
