### ISSUE TITLE
Disabling "justMyCode" does not allow me to step into stdlib functions

### ISSUE THREAD

**Issue by calebho** [microsoft/ptvsd#2103]
## Environment data

- VS Code version: 1.42.1
- Extension version (available under the Extensions sidebar): 2020.2.64397
- OS and version: Darwin x64 19.3.0
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions:
- Relevant/affected Python-related VS Code extensions and their versions:
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Jedi
- Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Debugger steps into standard library function

## Actual behaviour

Debugger steps over standard library function

## Steps to reproduce:
I think this is similar to microsoft/vscode-python#7347 so I'm copying the repro steps except for `launch.json`
1. `launch.json` (note that I tried with and without `"console": "integratedTerminal"`):
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Tests",
      "type": "python",
      "request": "test",
      // "console": "integratedTerminal",
      "justMyCode": false
    }
  ]
}
```
2. `test_main.py`:
```python
import subprocess


def test_main():
    a = subprocess.call(["ls"])  # set breakpoint here
    print(a)
```
3. Configure `pytest` as the testing framework
4. Click the "Debug Test" lens prompt over `test_main`
5. At the breakpoint, click step into
6. Observe that instead the debugger steps over the `subprocess.call` call

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
n/a
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
[Extension Host] Info Python Extension: 2020-02-26 15:28:03: Cached data exists getEnvironmentVariables, extension-output-#4
```

**Comment by calebho** [comment]
> @calebho Can you share the lines from the Python Output panel?

Yeah sure @karthiknadig:
```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - control'
User belongs to experiment group 'WebHostNotebook - control'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> ~/miniconda3/bin/python -c "import sys;print(sys.executable)"
> conda info --json
> ~/miniconda3/bin/python -c "import notebook"
> ~/miniconda3/bin/python -c "import jupyter"
> ~/miniconda3/bin/python -m jupyter kernelspec --version
> ~/miniconda3/bin/python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/scratch/vscode-test/test_main.py
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/scratch/vscode-test/test_main.py
cwd: ~/scratch/vscode-test
Starting Jedi Python language engine.
##########Linting Output - flake8##########
> conda env list
> ~/miniconda3/bin/python -c "import sys;print(sys.prefix)"
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -c "import sys;print(sys.prefix)"
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -c "import sys;print(sys.executable)"
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -c "import sys;print(sys.executable)"
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -m site --user-site
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -m site --user-site
cwd: ~/scratch/vscode-test
> conda env list
> ~/miniconda3/bin/python completion.py
cwd: ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles
> ~/miniconda3/bin/python completion.py
cwd: ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles
> ~/miniconda3/bin/python ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir ~/scratch/vscode-test -s --cache-clear .
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/scratch/vscode-test/main.py
cwd: ~/scratch/vscode-test
> ~/miniconda3/bin/python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/scratch/vscode-test/main.py
cwd: ~/scratch/vscode-test
##########Linting Output - flake8##########
```

**Comment by calebho** [comment]
> @calebho try the same thing after adding this to your user settings:
> 
> ```
>     "python.experiments.optInto": [
>         "PtvsdWheels37 - experiment"
>     ],
> ```
> 
> This should use the newer version of the debugger that should handle `subprocess` better.

I don't think `subprocess` is relevant here. The same thing happens if I use an `os` function for instance, i.e.
```python
import os

def test_main():
    os.listdir()  # set breakpoint here
```

**Comment by kvdveer** [comment]
I have found a workaround: Adding `"debugStdLib": true,` to the `launch.json`, allows me to debug outside of my code. (tested with django, not actual stdlib).

`launch.json` editor told me that it's not a valid property, but it does actually have an effect.

**Comment by fabioz** [comment]
This should be fixed by https://github.com/microsoft/debugpy/commit/6b335f19e65ed35cde9aa963ff2f74264efad957

**Comment by fabioz** [comment]
As noted, until a new release is done, the workaround is using `"debugStdLib": true`.

**Comment by ashleybartlett** [comment]
This workaround worked for me.
