### ISSUE TITLE
Using latest version of the debugger.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#2104]
Download and install insiders build of the python extension: https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix

![image](https://user-images.githubusercontent.com/3840081/75914276-54e17600-5e09-11ea-8ace-da227fd241fb.png)

To use the new debugger please add the following to your user settings:
![image](https://user-images.githubusercontent.com/3840081/75913463-d7693600-5e07-11ea-80aa-fb16481b4449.png)

```js
    "python.experiments.optInto": [
        "DebugAdapterFactory - experiment",
        "PtvsdWheels37 - experiment"
    ],
```
Reload VSCode. if you look at `Output` tab > `Python` panel, you should see these lines:
![image](https://user-images.githubusercontent.com/3840081/75914150-1c419c80-5e09-11ea-8ccc-913995d22da7.png)

This should get you the new debugger.

**Comment by karthiknadig** [comment]
Note: We are moving to use `debugpy` package as the debugger, so you may see that instead of `ptvsd`

**Comment by memco** [comment]
Is there anything else not included in the instructions we need to do in order to test this? I downloaded the insiders extension and added those configs, but I don't see that output in the Python output. Attempting this on 1.43 stable on Mac OSX 10.15.3.

**Comment by karthiknadig** [comment]
@memco Enable these two settings:
![image](https://user-images.githubusercontent.com/3840081/76374852-8d012100-6301-11ea-8f17-e41c6f8864ec.png)

Experiments are disabled when telemetry is disabled.
