### ISSUE TITLE
Python-Extension: Debugger not running with Python 2.7

### ISSUE THREAD

**Issue by dpalmetzvbg** [microsoft/ptvsd#2112]
When trying to make a python-program with VSCode (Python 2.7.14) and run the debugger, an exception occurse. The program is very small:

Everything works perfectly well with python-3 environments.

```
import os
pass
```

Running without debugger is possible.

## Environment data

- VS Code version: 1.43.0
- Extension version (available under the Extensions sidebar): Python-Extension 2020.2.64397
- OS and version: Windows 10 64 Bit (German)
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.14 (shipps with ArcGis)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: none
- Relevant/affected Python-related VS Code extensions and their versions: Python-Extension
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): XXX
- Value of the `python.languageServer` setting: XXX

## Expected behaviour
The debugger should start.

## Actual behaviour
Exception is thrown.

## Steps to reproduce:
Create a pyhton-file, save it and start the debugger.

## Logs

```
 XXX
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
 cd 'c:\Entwicklung\Python\Django_Test_P3_6'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Python27\ArcGIS10.4\python.exe' 'c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '52684' 'd:\Entwicklung\Django_Test_36\test1.py'
Traceback (most recent call last):
  File "c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 283, in _on_run
    self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
  File "c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 164, in process_net_command_json
    cmd = on_request(py_db, request)
  File "c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 490, in on_setbreakpoints_request
    py_db, filename, btype, breakpoint_id, line, condition, func_name, expression, suspend_policy, hit_condition, is_logpoint, adjust_line=True)
  File "c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 424, in add_breakpoint
    py_db.apply_files_filter(self._DummyFrame(filename), filename, False)
  File "c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 964, in apply_files_filter
    if (self._is_libraries_filter_enabled or force_check_project_scope) and not self.in_project_scope(frame):
  File "c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 866, in in_project_scope
    file_type = self.get_file_type(frame, abs_real_path_and_basename)
  File "c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 705, in get_file_type
    if self.dont_trace_external_files(abs_real_path_and_basename[0]):
  File "c:\Users\<userdir>\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 758, in custom_dont_trace_external_files
    return abs_path.startswith(start_patterns) or abs_path.endswith(end_patterns)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 72: ordinal not in range(128)
```

**Comment by karthiknadig** [comment]
Can you try with the new debugger? Instructions here on how to turn it on.
https://github.com/microsoft/ptvsd/issues/2104

**Comment by dpalmetzvbg** [comment]
No, still the same result (installed and reloaded the extension and the editor).

cd 'd:\temp\test2'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Python27\ArcGIS10.4\python.exe' 'c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '52565' 'd:\temp\Testöaäpui\test2.py'
Traceback (most recent call last):
  File "c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 283, in _on_run
    self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
  File "c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 164, in process_net_command_json
    cmd = on_request(py_db, request)
  File "c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 490, in on_setbreakpoints_request
    py_db, filename, btype, breakpoint_id, line, condition, func_name, expression, suspend_policy, hit_condition, is_logpoint, adjust_line=True)
  File "c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 424, in add_breakpoint
    py_db.apply_files_filter(self._DummyFrame(filename), filename, False)
  File "c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 964, in apply_files_filter
    if (self._is_libraries_filter_enabled or force_check_project_scope) and not self.in_project_scope(frame):
  File "c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 866, in in_project_scope
    file_type = self.get_file_type(frame, abs_real_path_and_basename)
  File "c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 705, in get_file_type
    if self.dont_trace_external_files(abs_real_path_and_basename[0]):
  File "c:\Users\bkor\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 758, in custom_dont_trace_external_files
    return abs_path.startswith(start_patterns) or abs_path.endswith(end_patterns)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 12: ordinal not in range(128)

Greetings,
Didi

Von: Karthik Nadig <notifications@github.com>
Gesendet: Donnerstag, 12. März 2020 18:31
An: microsoft/ptvsd <ptvsd@noreply.github.com>
Cc: Palmetzhofer Dietmar <Dietmar.Palmetzhofer@vorarlberg.at>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/ptvsd] Python-Extension: Debugger not running with Python 2.7 (#2112)


Can you try with the new debugger? Instructions here on how to turn it on.
#2104<https://github.com/microsoft/ptvsd/issues/2104>

**Comment by dpalmetzvbg** [comment]
I followed the install-instructions, but it seems that the experimental debugger is not used, I do not get these messages mentioned in the link you sent me.
Greetings,
Didi

Von: Karthik Nadig <notifications@github.com>
Gesendet: Donnerstag, 12. März 2020 18:31
An: microsoft/ptvsd <ptvsd@noreply.github.com>
Cc: Palmetzhofer Dietmar <Dietmar.Palmetzhofer@vorarlberg.at>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/ptvsd] Python-Extension: Debugger not running with Python 2.7 (#2112)


Can you try with the new debugger? Instructions here on how to turn it on.
#2104<https://github.com/microsoft/ptvsd/issues/2104>

**Comment by karthiknadig** [comment]
@dpalmetzvbg Check these settings, they should both be checked:
https://github.com/microsoft/ptvsd/issues/2104#issuecomment-597405499

If that do not fix then  check the extension folder to see if multiple version of python extension are installed?
If so, then delete them all and follow instructions again https://github.com/microsoft/ptvsd/issues/2104

If that does not work, please share your settings.json (redact any personal information)

**Comment by dpalmetzvbg** [comment]
I reinstalled the python extension, and there is only one extension, and also reinstalled the experimental extension, but it still does not work.
Here are my settings:

{
    "python.pythonPath": "C:\\Python27\\ArcGIS10.4\\python.exe",
    "python.venvFolders": [
        "C:\\Program Files\\ArcGIS\\Pro\\bin\\Python",
        "C:\\<somefolder>\\Python\\VirtualEnv\\Django"
    ],
    "python.linting.mypyCategorySeverity.error": "Information",
    "telemetry.enableTelemetry": false,
    "http.proxy": <proxy-settings>",
    "http.proxyStrictSSL": false,
    "http.proxySupport": "on",
    "http.systemCertificates": false,
    "sqltools.useNodeRuntime": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "python.experiments.optInto": [
        "DebugAdapterFactory - experiment",
        "PtvsdWheels37 - experiment",
    ],
}


Von: Karthik Nadig <notifications@github.com>
Gesendet: Montag, 16. März 2020 17:49
An: microsoft/ptvsd <ptvsd@noreply.github.com>
Cc: Palmetzhofer Dietmar <Dietmar.Palmetzhofer@vorarlberg.at>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/ptvsd] Python-Extension: Debugger not running with Python 2.7 (#2112)


@dpalmetzvbg<https://github.com/dpalmetzvbg> Check these settings, they should both be checked:
#2104 (comment)<https://github.com/microsoft/ptvsd/issues/2104#issuecomment-597405499>

If that do not fix then check the extension folder to see if multiple version of python extension are installed?
If so, then delete them all and follow instructions again #2104<https://github.com/microsoft/ptvsd/issues/2104>

If that does not work, please share your settings.json (redact any personal information)

**Comment by dpalmetzvbg** [comment]
Now the experimental debugger is running, had to enable the telmetry-setting (the world belongs to those who read ‘till the end).
But still no success:

${env:DEBUGPY_LAUNCHER_PORT}='63681'; & 'C:\Python27\ArcGIS10.4\python.exe' 'c:\Users\<user>\.vscode\extensions\ms-python.python-2020.4.68094-dev\pythonFiles\lib\python\debugpy\no_wheels\debugpy\launcher' 'd:\temp\Testöaäpui\test2.py'
debugpy 1.0.0b3
See https://aka.ms/debugpy for documentation.

Usage: debugpy [--listen | --connect] [<address>:]<port>
               [--wait-for-client]
               [--configure-<name> <value>]...
               [--log-to <path>] [--log-to-stderr]
               <filename> | -m <module> | -c <code> | --pid <pid>
               [<arg>]...

Error: 'ascii' codec can't decode byte 0xf6 in position 12: ordinal not in range(128)

Von: Karthik Nadig <notifications@github.com>
Gesendet: Montag, 16. März 2020 17:49
An: microsoft/ptvsd <ptvsd@noreply.github.com>
Cc: Palmetzhofer Dietmar <Dietmar.Palmetzhofer@vorarlberg.at>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/ptvsd] Python-Extension: Debugger not running with Python 2.7 (#2112)


@dpalmetzvbg<https://github.com/dpalmetzvbg> Check these settings, they should both be checked:
#2104 (comment)<https://github.com/microsoft/ptvsd/issues/2104#issuecomment-597405499>

If that do not fix then check the extension folder to see if multiple version of python extension are installed?
If so, then delete them all and follow instructions again #2104<https://github.com/microsoft/ptvsd/issues/2104>

If that does not work, please share your settings.json (redact any personal information)

**Comment by int19h** [comment]
You're hitting https://github.com/microsoft/debugpy/issues/69 now. We already have a fix, but until it gets into a new release, the workaround is to not use paths with non-ASCII characters on Python 2.7.

**Comment by dpalmetzvbg** [comment]
Yes, seems to be the same problem. Waiting for the fix.


Von: Pavel Minaev <notifications@github.com>
Gesendet: Dienstag, 17. März 2020 09:03
An: microsoft/ptvsd <ptvsd@noreply.github.com>
Cc: Palmetzhofer Dietmar <Dietmar.Palmetzhofer@vorarlberg.at>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/ptvsd] Python-Extension: Debugger not running with Python 2.7 (#2112)


You're hitting microsoft/debugpy#69<https://github.com/microsoft/debugpy/issues/69> now. We already have a fix, but until it gets into a new release, the workaround is to not use paths with non-ASCII characters on Python 2.7.

**Comment by int19h** [comment]
Thank you for confirming! I'm going to close this issue as a duplicate.
