### ISSUE TITLE
Easy way to find debugger version number (How does one get the version number of the VS Code debugger?)

### ISSUE THREAD

**Issue by brando90** [microsoft/ptvsd#2123]
# How does one get the version number of the VS Code debugger ptvsd?

I've been trying to google how to get the debugger number for ptvsd. Perhaps a feature where it makes it easy to find it? An individual setting for it?

At the very least I hope this feature request makes it googleable/searchable:

https://www.quora.com/unanswered/How-does-one-get-the-version-number-of-the-VS-Code-debugger

https://www.reddit.com/r/vscode/comments/g9os91/how_does_one_get_the_version_number_of_the_vs/?

**Comment by int19h** [comment]
The only supported way is to import it and then access `__version__`. Ditto for debugpy, which is the more interesting one at the moment (ptvsd won't see any further changes).
