### ISSUE TITLE
Hide internals when evaluating invalid expressions (or other errors from the debugger)

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#219]
* Debug a program
* Add a breakpoint
* Enter an invalid variable (such as `x`) in the debug console of VSC
* Problem: Error message (`NameError("name 'x' is ...`) is displayed twice

The same problem (but worse, very large stacktrace is printed out) exists when evaluating an invalid expression such as `x=y`.

See below:
<img width="373" alt="screen shot 2018-03-16 at 10 13 52 pm" src="https://user-images.githubusercontent.com/1948812/37551926-b61b2976-2967-11e8-91e5-112c4df49192.png">

**Comment by fabioz** [comment]
I just tried this with the latest master and was not able to reproduce (see image below).

So, I think this was fixed during the upgrade to the latest pydevd. @DonJayamanne can you check if this is still an issue for you?

![ptvsd_name_error](https://user-images.githubusercontent.com/117621/41368747-348124b8-6f19-11e8-92e8-9064680a39da.png)
