### ISSUE TITLE
Debug REPL evaluate code in any frame

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#224]
Currently the code is evaluated on the topmost frame.

**Comment by int19h** [comment]
Worst case - if pydevd doesn't have this - we can take the original expression, and add a bunch of `sys._getframe()` etc around it.

**Comment by karthiknadig** [comment]
This should work after we hook up the threads and frames with debug REPL. Currently it is hard coded to look at the top frame only.

**Comment by karthiknadig** [comment]
This can be done directly from VS, there is some work that needs to be done on VS side.
