### ISSUE TITLE
Ability to stop on the first line of user code

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#231]
This is VSC specific

**Comment by zooba** [comment]
It’s also necessary for VS – if you start with the Step In or Over commands then we should break on the first line.

**Comment by fabioz** [comment]
Will start to take a look at this.

The idea is creating a `CMD_STOP_ON_START` command for `pydevd` which has to be issued before the `CMD_RUN`.

**Comment by fabioz** [comment]
Already done in `pydevd` (waiting for https://github.com/Microsoft/ptvsd/pull/692 to be merged before providing a pull request as changes were done on top of the contents in that pull request).

**Comment by karthiknadig** [comment]
With PR #700 pydevd part of this is done. Following items remain:
- [ ] In ptvsd we need to handle the `StopOnEntry` debug option. (I have this ready and will send a PR after pydevd part is merged)
- [ ] VSC should covert the `stopOnEntry` launch json option to debug option for Launch.
