### ISSUE TITLE
Handle debug options for attach

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#248]
- [x] Handle debug options for attach in VSC (#276)
- [ ] Handle debug options for attach in VS

**Comment by DonJayamanne** [comment]
@karthiknadig @int19h I've started this work (PR ready for review #277).
The changes will work for VSC, but for VS it depends on how settings will be passed into debug adapter (whether they're passed along with `attach` request or else where).
I've tried to keep it simple and generic (identical to the way `launch` request was being hanled).

**Comment by int19h** [comment]
For VS, the existing UX for attach doesn't provide an opportunity to set those debug options - so you always get the default. Hence, this is also the baseline for the new debugger wrt VS.

We'll want to revisit this eventually (for Flask attach scenarios etc), but it might require some accommodation from VS to enable a good end-to-end user experience.

**Comment by karthiknadig** [comment]
This item was for VS. Vs has moved the debug adapter launcher to allow passing settings. An Alternate way to handle this is no longer needed.

**Comment by kyselejsyrecek** [comment]
@karthiknadig: Sorry for asking you directly but there does not seem to be a documentation available on how to do that. I am particularly interested in setting localRoot and remoteRoot as described in issue #753. This can be done in VSCode using a launch.json file stored in a .vscode directory inside the project. How can such a setting be passed to ptvsd in Visual Studio (2017)? When attaching to remote machine, VS fails to even set a breakpoint if source paths differ on the machines. Thank you for clarification.

**Comment by karthiknadig** [comment]
Since mapping is not available in VS yet, you may have to call `ptvsd.break_into_debugger()`. This will allow VS to load the file from remote source. You should be able to set breakpoints after the file is loaded from remote. Unfortunately, breakpoints are not persistent in this method. 

/cc @huguesv
