### ISSUE TITLE
Debugging broken in VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#249]
* Create a program with a `print("Hello World")` statement
* Select the checkboxes `Raised Exceptions`
* Start debugging
* Looks like debugger is stuck

Looking at the logs we can tell that ptvsd doesn't reply back to a request from vsc (the last message is a request from VSC).

Here's a screenshot & the logs
<img width="1001" alt="screen shot 2018-03-23 at 9 45 18 pm" src="https://user-images.githubusercontent.com/1948812/37860505-d2f3a4ca-2ee3-11e8-9787-0c7c92d71ef5.png">

**Logs:**
<section>
<details>
9:45:14 PM, 3/23/2018
Started @ Fri Mar 23 2018 21:45:14 GMT-0700 (PDT)
From Client:
Content-Length: 336

{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code - Insiders","adapterID":"pythonExperimental","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
To Client:
Content-Length: 425

{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsExceptionInfoRequest":true,"supportsConfigurationDoneRequest":true,"supportsConditionalBreakpoints":true,"supportsSetVariable":true,"supportsExceptionOptions":true,"exceptionBreakpointFilters":[{"filter":"raised","label":"Raised Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":true}]}}
From Client:
Content-Length: 815

From Client:
{"command":"launch","arguments":{"name":"Python Experimental: Terminal (integrated)","type":"pythonExperimental","request":"launch","logToFile":true,"env":{"PYTHONPATH":"/Users/donjayamanne/Desktop/Development/vscode/my_forked_ptvsd"},"program":"/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo/one.py","console":"integratedTerminal","pythonPath":"/Users/donjayamanne/anaconda3/envs/myenv3/bin/python","cwd":"/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo","envFile":"/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo/.env","stopOnEntry":false,"internalConsoleOptions":"neverOpen","debugOptions":["RedirectOutput"],"options":"REDIRECT_OUTPUT=True","__sessionId":"b4b62b8c-9a74-426a-8a06-75e74e7a1b13"},"type":"request","seq":2}
To Client:
Content-Length: 847

{"command":"runInTerminal","arguments":{"kind":"integrated","title":"Python Debug Console","cwd":"/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo","args":["/Users/donjayamanne/anaconda3/envs/myenv3/bin/python","/Users/donjayamanne/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd_launcher.py","/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo","50604","34806ad9-833a-4524-8cd6-18ca4aa74f14","RedirectOutput,RedirectOutput","/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo/one.py"],"env":{"PYTHONPATH":"/Users/donjayamanne/Desktop/Development/vscode/my_forked_ptvsd:/Users/donjayamanne/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd","PYTHONIOENCODING":"UTF-8","PYTHONUNBUFFERED":"1"}},"type":"request","seq":2}
From Client:
Content-Length: 84

From Client:
{"type":"response","seq":3,"command":"runInTerminal","request_seq":2,"success":true}
To Client:
Content-Length: 77

{"seq":3,"type":"response","request_seq":2,"command":"launch","success":true}
To Client:
Content-Length: 815

To Client:
{"command":"launch","arguments":{"name":"Python Experimental: Terminal (integrated)","type":"pythonExperimental","request":"launch","logToFile":true,"env":{"PYTHONPATH":"/Users/donjayamanne/Desktop/Development/vscode/my_forked_ptvsd"},"program":"/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo/one.py","console":"integratedTerminal","pythonPath":"/Users/donjayamanne/anaconda3/envs/myenv3/bin/python","cwd":"/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo","envFile":"/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo/.env","stopOnEntry":false,"internalConsoleOptions":"neverOpen","debugOptions":["RedirectOutput"],"options":"REDIRECT_OUTPUT=True","__sessionId":"b4b62b8c-9a74-426a-8a06-75e74e7a1b13"},"type":"request","seq":2}
To Client:
Content-Length: 336

To Client:
{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code - Insiders","adapterID":"pythonExperimental","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
To Client:
Content-Length: 56

To Client:
{"event":"initialized","type":"event","seq":2,"body":{}}
From Client:
Content-Length: 97

From Client:
{"command":"setExceptionBreakpoints","arguments":{"filters":["raised"]},"type":"request","seq":4}
To Client:
Content-Length: 130

To Client:
{"success": true, "seq": 3, "body": {}, "message": "", "type": "response", "request_seq": 4, "command": "setExceptionBreakpoints"}
From Client:
Content-Length: 56

{"command":"configurationDone","type":"request","seq":5}
From Client:
Content-Length: 46

{"command":"threads","type":"request","seq":6}
To Client:
Content-Length: 124

To Client:
{"success": true, "seq": 4, "body": {}, "message": "", "type": "response", "request_seq": 5, "command": "configurationDone"}
To Client:
Content-Length: 92

To Client:
{"event": "thread", "type": "event", "seq": 5, "body": {"reason": "started", "threadId": 1}}Content-Length: 158

{"success": true, "seq": 6, "body": {"threads": [{"name": "MainThread", "id": 1}]}, "message": "", "type": "response", "request_seq": 6, "command": "threads"}
To Client:
Content-Length: 228

{"event": "process", "type": "event", "seq": 7, "body": {"name": "/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/aThrowAwayRepo/one.py", "systemProcessId": 74608, "isLocalProcess": true, "startMethod": "launch"}}
From Client:
Content-Length: 46

From Client:
{"command":"threads","type":"request","seq":7}

</details>
</section>

**Comment by int19h** [comment]
Did it have anything to do with that default exception settings issue, by chance? I can't repro with the most recent bits.

**Comment by DonJayamanne** [comment]
@int19h Apologies, didn't see your response. will try today.

**Comment by DonJayamanne** [comment]
Closing as I can no longer replicate this in master nor pre-release version of PTVSD.
