### ISSUE TITLE
Secure remote debug requests using `secret` phrase

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#254]
Secure remote debugging using `secret` phrase as already supported in older version of PTVSD.

**Comment by int19h** [comment]
We'll probably want to use something more standardized than what we had before.

**Comment by DonJayamanne** [comment]
Do you mean this version of PTVSD will not be backwards compatible?

**Comment by int19h** [comment]
It's already not backwards compatible, since we're not using the same protocol for remoting. So we'll probably want a different URI scheme etc.

**Comment by karthiknadig** [comment]
It was decided to not support this feature in v4.0+
