### ISSUE TITLE
Add compatibility check of PTVSD for remote debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#267]
We'll need the ability for ptvsd to validate the compatibility of client and server ptvsd packages. 
@karthiknadig do you do something similar with the local attach today.

**Comment by int19h** [comment]
I'm not sure I follow - there's no client ptvsd package in a remote scenario. It's the IDE directly connecting to ptvsd on the server. So the only thing that should matter is how much of the VSC protocol ptvsd implements, no?

**Comment by DonJayamanne** [comment]
Yes, but what happens when someone tries to connect to an older version of otvsd running remotely?
Currently ptvsd handles this scenario. Should we do the same?

**Comment by DonJayamanne** [comment]
I'm closing this issue simply because we haven't got one yet. I'm just hypothesising one. Will reopen (if necessary) when looking into remote debugging with VSC.

**Comment by int19h** [comment]
I think we might get into that situation once we start adding more custom messages. But so long as we stick to the spec, we should be good for backwards-compat - much better than with the old debugger, where we required a hard version match.

**Comment by karthiknadig** [comment]
Even if we add custom messages, if we follow the pattern of using `supportsFeatureBlah`. Compatibility should not be a issue.
