### ISSUE TITLE
Support Jinja template debugging when using bottle or pyramid

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#268]
Currently Jinja template debugging works only when debugging flask.
We might want to create a separate setting that enables Jinja template debugging instead of using FLASK_DEBUG. (Or perhaps rename FLASK_DEBUG to JINJA_DEBUG)

@karthiknadig cc

**Comment by DonJayamanne** [comment]
Jnja template debugging with bottle in vs could possibly benefit from this as well.

**Comment by karthiknadig** [comment]
We can add `JINJA_DEBUG` in addition to `FLASK_DEBUG` to support uncommon parings.

**Comment by DonJayamanne** [comment]
What is template engine used in ptvs bottle template?

**Comment by int19h** [comment]
It's the default Bottle templating engine that comes in the box with it (I'm not sure if it even has a name).

**Comment by karthiknadig** [comment]
Bottle supports 4 templates: SimpleTemplate (default), Jinja2, Mako, Cheetah

**Comment by karthiknadig** [comment]
@DonJayamanne This is done right?

**Comment by DonJayamanne** [comment]
I added a setting for vscode named `Jinja`, that will in turn initialize the FLASK_DEBUG flag. So it is done for VSC, not for VS.

**Comment by int19h** [comment]
At this point, it sounds like all the remaining work is on VS side of things? Or do we still need something to do in ptvsd to enable that?
