### ISSUE TITLE
Question, does ptvsd work with embedded interpreters?

### ISSUE THREAD

**Issue by pauldotknopf** [Microsoft/ptvsd#269]
I am using [PyOtherSide](https://github.com/thp/pyotherside) with Qt, on an embedded device.

PyOtherSide has it's own embedded Python thread/interpreters. Will ptvsd worth with it?

```python
import ptvsd
ptvsd.enable_attach("my_secret", address = ('0.0.0.0', 3000))
ptvsd.wait_for_attach()
```

Normally, in python, you load files from the file system. PyOtheSide projects typically embedded the python file in the executable, and there is a custom loader that will load it into the interpreter when needed. I imagine ptvsd wouldn't work with that, since it wouldn't know how to map that file loaded on the target file the local file source on my dev machine. I will probably have to configure my source files to be loaded by the Qt/PyOtherSide application by the actual local file system, which isn't an issue.

My main question is about an embedded interpreter. Do you expect it to work?

**Comment by int19h** [comment]
Yes, Python embedding is a supported scenario for both local and remote attach.

With respect to file system, that might be a problem, but it depends on how exactly it is implemented. For breakpoints, ptvsd looks at `f_code.co_filename` of the frame object. That can be set to something meaningful even if the code isn't loaded directly from the file, so it depends on whether PyOtherSide is doing that, or not. The easiest way to check is probably to "Break All", and then look at the call stack and see if there are module names in there, or not.

**Comment by pauldotknopf** [comment]
I verified it works when my embedded python files reference local files. I can attach a debugger to my local file and it works as expected, embedded and all!

[Here](https://github.com/thp/pyotherside/blob/77738b5a760b5f534fb1dbee2d8d2b7f4fd6ff90/src/qrc_importer.py#L23) is the import code that loads source files from Qt's resource compiler.

Any ideas?

**Comment by int19h** [comment]
I'm not super familiar with import machinery, but looking at it, it looks like the modules loaded in this manner will have `__file__` set (and it will be applied to code objects produced from them). If you can somehow print `__file__` from inside one of your own modules, what does it say?

**Comment by pauldotknopf** [comment]
```__file__``` is ```"qrc:/Python//initializer_service.py"```

I'm going to see if I can modify PyOtherSide to change this value without effecting the guts of it.
