### ISSUE TITLE
Debugger stop at breakpoint in main thread but not in callback function 

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/ptvsd#288]
Previously, I think it is an issue in VSCode Python extension. After some investiagation, I find the same issue happen in VS IDE.

Repro steps:

1. Download and open file in VS or VS Code:  https://github.com/VSChina/iot-edge-python-docker/blob/master/debug/SimulatedDevice.py
2. Run `pip install azure-iothub-device-client` 
3. Follow https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-getstarted#create-an-iot-hub to create an IoT Hub and a device to get a **device connection string**. Update `CONNECTION_STRING` in https://github.com/VSChina/iot-edge-python-docker/blob/2e4452be2f4b09074f0eebfca61fbf4e78fdb863/debug/SimulatedDevice.py#L9
3. Press `F5` to start debuging

Results:

  * I could stop at breakpoint in the main thread
  * However, I could not stop at any breakpoint within the **send_confirmation_callback()** function: https://github.com/VSChina/iot-edge-python-docker/blob/2e4452be2f4b09074f0eebfca61fbf4e78fdb863/debug/SimulatedDevice.py#L18

**Comment by karthiknadig** [comment]
I was able to repro this issue both in the current and experimental debugger. One thing to note though, we do seem to hit the breakpoint in `send_confirmation_callback` when the `result` is `BECAUSE_DESTROY`.
![image](https://user-images.githubusercontent.com/3840081/38206651-1341676e-3660-11e8-93a2-aa44439bfc82.png)

Looking at the logs (for experimental) I don't see the thread stopped event being for any of the callback calls before the result changes to `BECAUSE_DESTROY`

**Comment by formulahendry** [comment]
Hi @karthiknadig , thanks a lot for your investigation! I want to add more info. Actually, In our use case. we want to debug the python code running in Docker with VS Code. For remote debugging, it seems that the required version of ptvsd is 3.0.0, right? So could we have fix based on ptvsd 3.0.0 since the VS Code remote debugging relies on this version. Thank you!

**Comment by int19h** [comment]
Is the root cause here what #305 is about?

Hooking up new threads that weren't actually started from Python is a major new feature. We're in the process of migrating both VS and VSC to the new (4.x.x) ptvsd at the moment, so all the major fixes and feature work are happening in that codebase - which is this repo.

**Comment by formulahendry** [comment]
Thanks @int19h for the info!

> Hooking up new threads that weren't actually started from Python

The python code is using `install azure-iothub-device-client` pip which wrap on top of C code. So this would be the root cause?

> We're in the process of migrating both VS and VSC to the new (4.x.x) ptvsd at the moment

Could I know the rough timeline of this?

**Comment by karthiknadig** [comment]
There is a workaround for this. You can use `ptvsd.break_into_debugger` in the callback. This will always break. The current `master` branch has a version of  `ptvsd.break_into_debugger` that works for both launch and attach scenarios.
