### ISSUE TITLE
"disconnect" request not handled properly when running "attached".

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/ptvsd#289]
When a "disconnect" request is sent, it is handled differently if the debug adapter was "launched" or "attached".  The handling for "attached" debuggers feels incomplete.  For instance, in tests/highlevel/test_lifecycle.py the LifecycleTests.test_attach() test reports that it timed out waiting for a "disconnect" request, even though one was sent.  This is because the test closes the debug adapter and that operation expects a "disconnect" request, which "on_disconnect()" (in ptvsd/wrapper.py) doesn't record in the "attach" case.

Could be related to #285.

**Comment by int19h** [comment]
IIRC this is done that way to stop the debuggee on detach. But the right way to do it is to fix #136, then the client can request what it wants exactly.

**Comment by int19h** [comment]
Actually, let's just close this one as a dupe?
