### ISSUE TITLE
on_invalid_request should not exit

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#294]
As the comment there suggests, `on_invalid_request` should respond back with
`self.send_response(request, success=False, message='Unknown command')` . It should not exit.

**Comment by DonJayamanne** [comment]
Agreed, I'd say we should add this before the final release.
We can't have the debugger falling over just because there's a new message sent by the debugger.

**Comment by karthiknadig** [comment]
I will send a PR for this. I need to test a few things from VS side since we make use of the custom messages.
