### ISSUE TITLE
Create unit tests to test launching of debugger using ptvsd.debug 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#298]
We need unit tests to account for regression issue #292

**Comment by DonJayamanne** [comment]
This test was necessary as VSC was making use of the `debugger` module in PTVSD. However VSC no longer uses this, and I do not believe anyone else does.
Hence we could remove the file (tracked in https://github.com/Microsoft/ptvsd/issues/524).

**Comment by karthiknadig** [comment]
Running via ptvsd.debug is deprecated.
