### ISSUE TITLE
Debugging of modules using -m is broken in VSC

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#299]
Regression issue https://github.com/Microsoft/ptvsd/issues/257

**Comment by ericsnowcurrently** [comment]
Do you have an example of what the debugger.debug() args looks like (as well as sys.argv).  Or is this doing "attach" (such that ptvsd.__main__ is used)?

**Comment by ericsnowcurrently** [comment]
@DonJayamanne Please verify that this is fixed now that #306 has been merged.

**Comment by DonJayamanne** [comment]
Fixed
