### ISSUE TITLE
Add ability to break into the debugger using break_into_debugger

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#324]
@int19h older version of PTVSD has this, I'm assuming we'll need this same functionality in the new debugger (name can change).

How is this supposed to work?:
* Are we supposed to break immediately into the next operation 
* Or do we break into the next possible operation

I've implemented this in PTVSD by invoking the command CMD_THREAD_SUSPEND, however the results are immediate. I.e. debugger breaks into code around 2-3 lines of code after the `break_into_debugger` instruction.

**Comment by int19h** [comment]
Alternatively, we can just send the pause message from the implementation of that function, and don't return from it until we get a continue from the IDE. Then other threads can be suspended asynchronously (there's no guarantee for them being at a specific point either way), and the thread on which it was called has a well-defined order.

**Comment by DonJayamanne** [comment]
> Alternatively, we can just send the pause message from the implementation of that function

I did try that, but it froze. Then just gave up, I guess I did something wrong.

**Comment by DonJayamanne** [comment]
@ericsnowcurrently 
In order to make this (functionality) possible, we'll need a way to get hold of the instance of `VSCodeMessageProcessor` (pydev has a function to do this `get_global_debugger`). I think we'll need a similar function that can be used form outside the message processor to send messages to the debug client and similar.

**Comment by DonJayamanne** [comment]
Completed as part of https://github.com/Microsoft/ptvsd/issues/251
