### ISSUE TITLE
Debuggee no longer terminates

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#325]
* Python program
![image](https://user-images.githubusercontent.com/11925432/38463040-5f8fec72-3b23-11e8-90e7-b7137748045f.png)
* Add a break point at line 4
* Debug the above code
* Stop debugging
* You'll notice that the 4th and 5th lines are executed.

Here's the original issue https://github.com/Microsoft/vscode-python/issues/1345

**This used to work in PTVSD**. 
**Here's a commit that it used to work in 608ca082dad71b4394fdb2e5d0615a78970c0f0f**

Note:
* The above commit in PTVSD works with VSC. I.e. its a PTVSD bug. 
* Seems like we're continuing the code

**Comment by int19h** [comment]
Is this for launch, or for attach?

**Comment by DonJayamanne** [comment]
Launch

**Comment by karthiknadig** [comment]
@DonJayamanne looks like the request does not contain `terminateDebuggee=true`. So this is the right behavior? Interestingly the request contains `restart`, could not find that in the DAP. https://github.com/Microsoft/ptvsd/blob/master/debugger_protocol/schema/debugProtocol.json#L782
```
{"command":"disconnect","arguments":{"restart":false},"type":"request","seq":13}
```

**Comment by DonJayamanne** [comment]
Please remember, this used to work. It's broken now.

**Comment by MikhailArkhipov** [comment]
@int19 - ping since it is P0
