### ISSUE TITLE
Path mappings case-sensitive in windows

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#328]
Path mappings should be case insensitive for windows.

The issue is in `pydevd_file_utils.py` in `_norm_file_to_server`. The `startswith` check there should be case-insensitive in windows.

**Comment by int19h** [comment]
Per comments in that file, you're supposed to call `normcase` on the paths added to the mappings, if it's on Windows. Can we just do that when we provide the list of files?

**Comment by karthiknadig** [comment]
@DonJayamanne Since you know this area better. Can you provide the reason why `normcase` cannot be used here? I know you mentioned that this affects how VSC opens tabs.

Note: This bus is an issue for remote launch scenario. We can take this up later after we have figured out remote launch.

**Comment by DonJayamanne** [comment]
> Since you know this area better. Can you provide the reason why normcase cannot be used here

The list of files added as breakpoints are sent by VSC. We need to preserve the file cases, else VSC will open duplicate editor windows (VSC is case sensitive with file paths).

**Comment by DonJayamanne** [comment]
@karthiknadig What was the underlying issue.
Today I was diagnosing another issue related to `launch` debugging with `pathMappings` and found this was not working at all (as expected) on Windows. And part of the problem was the code that @karthiknadig identified. However, that alone didn't resolve that. I'll create a separate issue for that.

**Comment by DonJayamanne** [comment]
@karthiknadig is this still an issue?

**Comment by karthiknadig** [comment]
This was affecting remote launch in a container.  I am closing this for now. Will reop if I see this again, when we get to remote launch scenario.
