### ISSUE TITLE
Wrong path separator in source path when working cross platform

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#333]
Client is VS connecting to ptvsd running in linux:
Actual:
```
{"id": 2, "name": "\\usr\\local\\lib\\python3.5\\dist-packages\\django\\template\\base.render : 991", "source": {"path": "\\usr\\local\\lib\\python3.5\\dist-packages\\django\\template\\base.py", "sourceReference": 0}, "line": 991, "column": 1}
```

Expected:
```
{"id": 2, "name": "/usr/local/lib/python3.5/dist-packages/django/template/base.render : 991", "source": {"path": "/usr/local/lib/python3.5/dist-packages/django/template/base.py", "sourceReference": 0}, "line": 991, "column": 1}
```

**Comment by DonJayamanne** [comment]
This may have something to do with the options WindowsClient=True.
Here PyDev is replacing all path separators with the windows path seprator `\` (pydevd_fileutils).

**Comment by DonJayamanne** [comment]
I think its important to mention the scenario under which you're getting this issue (i.e. this is a `launch` scenario isn't it)

**Comment by karthiknadig** [comment]
I don't see how launch or attach should have a difference in the stack trace source path.

**Comment by DonJayamanne** [comment]
You might want to test attach, cuz I can't replicate this in VSC.

**Comment by karthiknadig** [comment]
Tested with attach. When using path mappings the path separator for linux files is wrong. The issue occurs in both launch and attach.

**Comment by int19h** [comment]
Looking at pydevd_file_utils.py, it seems that it tries to derive the path separator for the client (i.e. the IDE) from path mappings:

https://github.com/fabioz/PyDev.Debugger/blob/62b77e45ac173ec16d42130d6bde293e316bda56/pydevd_file_utils.py#L303

**Comment by MikhailArkhipov** [comment]
@int19h  - link to pydevd?

**Comment by fabioz** [comment]
Note: I'll start to take a look at this issue on Monday.

**Comment by fabioz** [comment]
@karthiknadig I'm taking a look here and as @int19h mentioned, this is really expected right now.

I.e.: it's expected that the path translation fixes paths to what the client expects and there are translations which convert to the debugger when it receives a filename and it converts back when it sends the filename (this is in `pydevd_file_utils.norm_file_to_client` and `pydevd_file_utils.norm_file_to_server`).

So, I'd like to understand why this is a problem... I've taken a look at the source code and found one instance where the translation wasn't taking place properly (i.e.: loading the contents from a file from CMD_LOAD_SOURCE, which I've already fixed locally), but aside from that specific place, I couldn't find any other instance where this was a problem, so, can you enlighten me a bit more on why changing the path separator to be compatible with the client is a problem?

**Comment by karthiknadig** [comment]
I don't think this is entirely a `pydevd` issue. If the path translations on the pydevd side are correct, then ptvsd has to do the work to provide the right translations back to the IDE depending on the scenario. After your PR is in I will remove the upstream-pydevd and continue this as a ptvsd issue.

**Comment by fabioz** [comment]
@karthiknadig ok, I've provided a patch which fixes some inconsistencies on the translations, but it's still expected that the path sent to the client is compatible with the path separator found in the client.
