### ISSUE TITLE
Run python code without debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#336]
In VSC the debug adapter is responsible for running code without debugging (Ctrl+F5).
The way this work is simple, when the launch message is sent by VSC, a flag is used to indicate whether debugging necessary or not.

In the current version of VSC we use the old PTVSD debugger to run python code.
Here's part of the code responsible for running python code without debugging:
```typescript
    try:
        if run_as == 'module':
            _vspu.exec_module(file, globals_obj)
        elif run_as == 'code':
            _vspu.exec_code(file, '<string>', globals_obj)
        else:
            _vspu.exec_file(file, globals_obj)
    except:
        exc_type, exc_value, exc_tb = sys.exc_info()
        handle_exception(exc_type, exc_value, exc_tb)
```

This works well (has worked well). I've hooked up some basic protocol (old PTVSD protocol) messages [in that file](https://github.com/Microsoft/vscode-python/blob/master/pythonFiles/PythonTools/visualstudio_py_launcher_nodebug.py). I can use it to run a module or a file.

**Now with the new version of PTVSD I'll need something similar.**
We have a couple of options:
1. Keep using the old version of PTVSD for launch python code (without debugging).
Doesn't feel right to use older (unsupported code).
See the file [visualstudio_py_launcher_nodebug.py](https://github.com/Microsoft/vscode-python/blob/master/pythonFiles/PythonTools/visualstudio_py_launcher_nodebug.py)
2. VSC Python extension could create an instance of `PyDb` class and invoke the `run` method.
Doesn't feel right to use internals of pydevd. I.e. VSC should be using PTVSD (that's the public api).
3. Create a wrapper for PyDb in PTVSD so we can invoke code without debugging.
E.g. create a method named `run` similar to `debug method found in debugger.py`.
And wire up the protocol messages, **but disable the debugging functionality.**

@int19h @ericsnowcurrently cc
I feel that 3 is the best option, and the most expensive as this might require additional work (i.e. **ensuring debugging is disabled**).

I'd like to go with this approach. Including you two, as we're creating some public API that will be used only by VSC.

**Why can't I just spawn the python process instead of launching via PTVSD?**
* VSC requires the code to be launched via debug adapter 
* The debug adapter expects the protocol messages (the flag to run without debugging comes in via the `launch` request).
* When the process stops, DA needs to send VSC the `exited`, `terminated` and `disconnect` events/messages (these cannot be sent if the python program is launched via the terminal, unless we launch the program via PTVSD, i.e. PTVSD handles the messages as done today).
* Similarly, the VSC needs the ability to kill the process via the `disconnect` request (again, this cannot be done if the python program is launched in a terminal, the extension has no access to this process - we don't know what it is).

**Comment by DonJayamanne** [comment]
Not sure whether this is an enhancement or bug. Either way, this is a feature that we must have in VSC. But a change that needs to be made in PTVSD (something that didn't exist in the older versions, but something I managed to get working via a [separate file visualstudio_py_launcher_nodebug.py](https://github.com/Microsoft/vscode-python/blob/master/pythonFiles/PythonTools/visualstudio_py_launcher_nodebug.py)).

**Comment by DonJayamanne** [comment]
@brettcannon the (quick 'n dirty) solution we discussed won't work (see above).

**Comment by int19h** [comment]
It sounds to me that what we really want here is a *separate* debug adapter, that basically just handles initialize/launch/exited/terminated/disconnect, and can launch scripts and modules? Since there are no attach scenarios here, it doesn't even need to use the socket - it can just be a conventional VSC adapter that works directly with stdin/out.

I suspect this would end up being a lot simpler than trying to split the code flow in ptvsd into "debug" and "no debug" branches as needed, given how much it's driven by messages from pydevd.

**Comment by DonJayamanne** [comment]
> Since there are no attach scenarios here, it doesn't even need to use the socket - it can just be a conventional VSC adapter that works directly with stdin/out.

Agreed. However I'll still have to let the VSC adapter handle all requests until `launch`. That's when I'll know whether we need to debug or run without debugging.

> I suspect this would end up being a lot simpler than trying to split the code?  

Agreed

Do you see any problems in us directly using the `run` method of the `pydevd.PyDB` class to perform the execution of python code?
E.g. `pydevd.PyDB().run(.....)`

**Comment by int19h** [comment]
I think this would work, but do we need pydevd in the picture at all? It feels like it's just one `exec` or `import`, ultimately. Well, and the "Press any key" stuff maybe, but we already implement it ourselves in a way that should work equally well without pydevd.

**Comment by DonJayamanne** [comment]
>  It feels like it's just one exec or import

Easy, I'll proceed with that.
