### ISSUE TITLE
Breakpoints not hitting when used in conjunction with exceptions

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#347]
* Here's the program
```python
1. for i in range(10):
2.     print("one")
3.     try:
4.         raise AttributeError()
5.     except:
6.         pass
```
* Add a breakpoint to line 2 and line 4
* Start debugging
* First loop, both break points are hit
* Second loop, only the fist breakpoint is hit

![breakpoint_not_working](https://user-images.githubusercontent.com/1948812/38763875-9f848196-3f59-11e8-981f-ec9f7d2f100e.gif)

**Comment by DonJayamanne** [comment]
Setting a milestone of VSC Stable, as this could be an edge case and might not be crucial for VSC Preview (@brettcannon @int19h please feel free to change).
However this should be fixed for VSC Stable, as this could be a symptom of a more serious issue (won't know until we check this out).

**Comment by karthiknadig** [comment]
This is the fix that is needed : https://github.com/fabioz/Pydev/commit/f29d29f257a382e1da3af107865fcda1eb656662
