### ISSUE TITLE
Clicking Pause should pause all threads

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#349]
This has been discussed a number of times with @karthiknadig and @huguesv 
Currently clicking Pause doesn't seem to pause all threads.
Note: The requirement to pause all threads is something that comes from VS. (in VSC we'd like to implement the same functionality as we'd need to be consistent).

@karthiknadig I couldn't find an issue that tracks this. Please feel free to close this if there is one.

**Comment by karthiknadig** [comment]
The difference here is VS passes `threadid = 0` and we use that:
https://github.com/Microsoft/ptvsd/blob/master/ptvsd/wrapper.py#L1568

**Comment by DonJayamanne** [comment]
Note: Going forward we should get rid of this condition as the decision is to ensure both VS and VSC suspend all threads when hitting `Pause`.
