### ISSUE TITLE
Better way of excluding ptvsd threads

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#354]
Currently we identify ptvsd threads that need to be hidden from the client debugger based on a prefix `ptvsd.` in the thread name.
Ideally we should hide these custom threads based on some additional attribute or they should inherit a custom Thread class.

This is closely related to #353 (We'd hide those threads based on the fact that they inherit from `threading._Dummy`, I'd go about implementing the same approach to hide our (PTVSD) thread as well.

**Comment by int19h** [comment]
Can we reliably obtain a `Thread` object for those to query?

**Comment by karthiknadig** [comment]
@fabioz Should `pydev_do_not_trace = True` cause the thread to be hidden from being reported? from commands like CMD_LIST_THREADS.

**Comment by fabioz** [comment]
It doesn't right now, but it probably should (as a note, there are 2 flags: `is_pydev_daemon_thread` and `pydev_do_not_trace` -- in this case, if a thread is marked with `is_pydev_daemon_thread` I don't think it needs to be included (right now the client filters it, but it makes sense that the server itself uses that information to decide that a thread should not be shown).

I've already marked ptvsd threads in https://github.com/Microsoft/ptvsd/pull/430, so, after it's merged, it should be a matter of not filtering it properly in _pydevd_bundle.pydevd_comm.NetCommandFactory.make_list_threads_message.

**Comment by fabioz** [comment]
This one can be closed (this is already done).
