### ISSUE TITLE
Run CI tests on Windows OS

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#363]
* Issue #361 would have been picked up in the live tests if run on Windows OS

**Comment by d3r3kk** [comment]
Yes, all tests are represented in Windows OS across many Python versions.

Once the tests run clear of failures we can turn the CI in VSTS on full-time.

**Comment by d3r3kk** [comment]
@MikhailArkhipov I would be ill-prepared to fix the issues, but I can certainly open issues. Please stand by... ;)
