### ISSUE TITLE
Errors in Pydevd are not propagated back to PTVSD

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#368]
Found an error in pydevd code https://github.com/Microsoft/ptvsd/issues/367 
This error wasn't propagated to PTVSD, the debugger was hanging.

**Comment by MikhailArkhipov** [comment]
@DonJayamanne - What is the user scenario?

**Comment by DonJayamanne** [comment]
Issue #367, there was a bug in pydevd code, the error there was not being propagated over to ptvsd.

**Comment by karthiknadig** [comment]
I am not able to repro this. Attempting to recreate the same situation, this is what gets printed, for every breakpoint we try to set.
```
Traceback (most recent call last):
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command.py", line 307, in process_net_command
    if  len(condition) <= 0 or condition == "None" or condition is not None:
TypeError: object of type 'NoneType' has no len()
```
re-open if this appears again.
