### ISSUE TITLE
Provide a reliable mechanism to detect whether a debugger is attached/detached

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#375]
Currently user's have a way of checking (form within their code) whether a debugger is attached via the [ptvsd.is_attached()](https://github.com/Microsoft/ptvsd/blob/master/ptvsd/attach_server.py#L77)

This works, 
* When a debugger is not attached
* When a debugger is attached

However once a debugger detaches from the program, this condition no longer works.

@ericsnowcurrently cc

**Comment by karthiknadig** [comment]
The current version of `is_attached` fixes this. https://github.com/Microsoft/ptvsd/commit/f726968304b97e20e6262d5ef80f28e202e43843
