### ISSUE TITLE
Master version older than version used in VS

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#384]
version used in VS: `4.1.1a1`
Not a critical issue but creates annoyance, due to version check in VS: `4.1.0a0+29.g9dc790c.dirty`

**Comment by int19h** [comment]
It's because I had to create a branch for this release (to cherry-pick one change that fixed one versioning issue). So the version tag is also in that branch, and builds from masters don't see it.

I just added another tag in master; try it now.

**Comment by MikhailArkhipov** [comment]
@karthiknadig - is it resolved?

**Comment by karthiknadig** [comment]
Yes
