### ISSUE TITLE
Pydevd removes first entry from sys.path when sys.path[0] = ''

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#388]
VSC launches the PTVSD debugger using `-m`, this adds an entry into `sys.path` for the current directory. Subsequently pydevd removes this:
```python
            if m.__file__.startswith(sys.path[0]):
                # print >> sys.stderr, 'Deleting: ', sys.path[0]
                del sys.path[0]
```

As a result of this debugging modules in ptvsd fails (at least in VSC).

**Comment by karthiknadig** [comment]
This is fixed?
