### ISSUE TITLE
Getting a UserWarning when running a short script

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#398]
When running:
```python
x = 1
y = 2
x = 3
print("Hello, Douglas Adams!")
```

I'm getting this at the end:
```
C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\wrapper.py:757: UserWarning: timed out waiting for disconnect request
  warnings.warn('timed out waiting for disconnect request')
```

**Comment by karthiknadig** [comment]
I have not seen this. Re-open if this occurs again

**Comment by karthiknadig** [comment]
Reopening .Attaching and disconnecting seems to repro this consistently.

**Comment by DonJayamanne** [comment]
@brettcannon @karthiknadig 
Please could you test this again with the latest version of PTVSD. Should be fixed.
