### ISSUE TITLE
Error in debugging in flask (in VS Code)

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#399]
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/Users/donjayamanne/.vscode/extensions/ms-python.python-2018.4.0-rc/pythonFiles/experimental/ptvsd/ptvsd/pydevd/pydevd.py", line 387, in check_output
    v = out.getvalue()
  File "/Users/donjayamanne/.vscode/extensions/ms-python.python-2018.4.0-rc/pythonFiles/experimental/ptvsd/ptvsd/pydevd/_pydevd_bundle/pydevd_io.py", line 46, in getvalue
    return ''.join(b)
TypeError: sequence item 0: expected str instance, bytes found

**Comment by karthiknadig** [comment]
May be something like:
```py
''.join((bytes.decode(e) if isinstance(e, bytes) else e for e in b))
```

**Comment by DonJayamanne** [comment]
Is this something you want me to try? Either way, its an issue in pydevd.
Note, when decoding you'd need to specify the encoding.

**Comment by karthiknadig** [comment]
I was wondering if this is a solution. I have tried it, but I was not able to repro the original issue.

**Comment by karthiknadig** [comment]
This is what we get back from flask. First few lines are written as bytes.
```
[<class 'bytes'>]: b''
[<class 'bytes'>]: b' * Serving Flask app "runserver.py"\r\n'
[<class 'bytes'>]: b' * Environment: production\r\n'
[<class 'bytes'>]: b'   WARNING: Do not use the development server in a production environment.\r\n'
[<class 'bytes'>]: b'   Use a production WSGI server instead.\r\n'
[<class 'bytes'>]: b' * Debug mode: off\r\n'
[<class 'str'>]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[<class 'str'>]: 

[<class 'str'>]: Traceback (most recent call last):

[<class 'str'>]: 
[<class 'str'>]:   File "C:\git\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 387, in check_output
    v = out.getvalue()

[<class 'str'>]: 
[<class 'str'>]:   File "C:\git\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_io.py", line 50, in getvalue
    return ''.join(b)

[<class 'str'>]: 
[<class 'str'>]: TypeError: sequence item 0: expected str instance, bytes found

[<class 'str'>]: 

```
