### ISSUE TITLE
Random newlines in output

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#400]
Use the code below and set breakpoint in the loop at `sleep`:
```
import time
import sys
print("Hello")

for i in range(100):
    time.sleep(0.1)
    print(i)
```

You may see random newlines. This does not always happen:
```
 1> [DebugAdapter] <--   E (output): {"type": "event", "seq": 193, "event": "output", "body": {"category": "stdout", "output": "25"}}
 1> [DebugAdapter] <--   E (output): {"type": "event", "seq": 194, "event": "output", "body": {"category": "stdout", "output": "\n"}}
```

**Comment by DonJayamanne** [comment]
This is correct. The print statement send the text and a new line. In this case you are setting both coming through separately. Hence I do not believe this is an issue.
I.e. instead of two separate items you should see '25\n'

**Comment by karthiknadig** [comment]
Then there is a bug in the output event handler in VS.

**Comment by karthiknadig** [comment]
In the VS output window:
![image](https://user-images.githubusercontent.com/3840081/39539896-ec13d642-4df5-11e8-81d5-480b71d95267.png)

**Comment by int19h** [comment]
For the lines that were printed normally, was it just a single `output` message with `"24\n"` etc?

**Comment by DonJayamanne** [comment]
@karthiknadig 
**This feels like a bug in VS. VS Code seems to work properly without any issues.**
Can you try the following:

* Use `sys.stdout.write`
* Add a delay of around 0.5ms, **then try another test with 0.1** (back to old time)

```
import time
import sys
print("Hello")

for i in range(100):
    time.sleep(0.5)
    sys.stdout.write(i)
```

**Comment by karthiknadig** [comment]
Closing this. Since it is a VS issue.

**Comment by DonJayamanne** [comment]
👍
