### ISSUE TITLE
Move `ptvsd_launcher.py` into this repo

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#41]
VS Code would like to use the `ptvsd_launcher.py` file (found in VS) to launch the debugger.

This allows VS Code to share the logic found in the above script.

Based on conversation with Pavel here https://github.com/Microsoft/ptvsd/issues/40#issuecomment-363261515

@karthiknadig Once this is done you'll need to update VS accordingly.

**Comment by brettcannon** [comment]
Been told by @DonJayamanne this has been done.

**Comment by DonJayamanne** [comment]
Fixed with https://github.com/Microsoft/vscode-python/pull/1373
