### ISSUE TITLE
Enable pydevd tests in CI

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#410]
https://travis-ci.org/fabioz/PyDev.Debugger

**Comment by karthiknadig** [comment]
@d3r3kk Since you are already looking into CI. This in another item in that area.

**Comment by d3r3kk** [comment]
Once I get the automation up and running I can take a look. ETA will be late May/early June perhaps?

**Comment by d3r3kk** [comment]
@karthiknadig  I think I may have some time to work on this in the next few weeks. I'll start out putting it into the existing ptvsd VSTS instance and we can add it someplace else if necessary later.

**Comment by karthiknadig** [comment]
Re-open if we decide to do this.
