### ISSUE TITLE
Debugging with module `itk` fails

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#414]
* OS = Mac
* Create a python file with the following code:
```python
import itk
print("Hello")
itk_vector = itk.vector[itk.SpatialObjectPoint[2]]()
print("Goodbye")
```
* Pip install `pip install itk==4.12.0.post1`
* Add a breakpoint to the first print statement
* Debug in VS Code
* Debugger hits the print statement
* Hit step to next statement, it will stop at line with`itk_vector`
* Hit step to next statement, and it hangs.

Following error is printed out in the terminal:
```
Hello
libc++abi.dylib: terminating with uncaught exception of type swig::stop_iteration
Abort trap: 6
```

I believe the problem lies when retrieving a list of the variables.
For instance if you stop at the first print statement and then hit continue, then the program runs to completion. I.e. stopping at the second print statement is what causes the issue.

**Comment by karthiknadig** [comment]
FYI, Does not occur on window:
![image](https://user-images.githubusercontent.com/3840081/39774547-09a0f9ba-52b0-11e8-922b-18d36f3917a9.png)

**Comment by DonJayamanne** [comment]
Hmm, please updated to indicate the fact that this was reproduced on a mac.

**Comment by karthiknadig** [comment]
@DonJayamanne Can you test this with PR #443 ? and see if this fixes the issue?

**Comment by DonJayamanne** [comment]
Confirmed, is has been fixed.
