### ISSUE TITLE
Debuggers breaks into PTVSD code

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#416]
* Create a python file with the following code:
```pyhton
if True:
```
* Enable the setting `[x] Uncaught Exceptions`
* Debug using the experimental debugger
* Debugger breaks into pydevd code

I've been told in the past this is related to #194, however I disagree.
This is related to #169, i.e. we shouldn't be stepping/breaking into the debugger code.
Note: This is not standard lib code, its pydevd (debugger code).

<img width="1073" alt="screen shot 2018-05-10 at 11 56 17 am" src="https://user-images.githubusercontent.com/1948812/39879688-889d9de6-5449-11e8-8663-36c0e29a0609.png">

**Comment by DonJayamanne** [comment]
@int19h @karthiknadig cc

**Comment by karthiknadig** [comment]
That is breaking into `runpy.py`, That is standard library file, give that it is located in the python install directory.

**Comment by DonJayamanne** [comment]
Oops, yes, for some reason I thought I saw pydevd. Sorry.
