### ISSUE TITLE
Python Immediate Window "type()" returning unhelpful "<type>"

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#419]
`type('!')`

Prints `<type>` in immediate, locals, debug interactive.
Prints `<class 'str'>` in interactive window / console

 
![image](https://user-images.githubusercontent.com/1696845/39935642-92dfc256-54fe-11e8-87b4-40593ec30b38.png)

Reported on Developer Community: https://developercommunity.visualstudio.com/content/problem/246168/python-immediate-window-type-returning-unhelpful.html

**Comment by MikhailArkhipov** [comment]
Did it ever work?

**Comment by huguesv** [comment]
No

**Comment by int19h** [comment]
This doesn't repro in VSC - can you recheck in VS?

**Comment by huguesv** [comment]
Tested with latest ptvsd, it works now!
