### ISSUE TITLE
Show return values

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#420]
Pydevd allows us to show the return values of functions. It can be useful to see the return value without adding a explicit print.

![image](https://user-images.githubusercontent.com/3840081/39943998-bf884f7e-5519-11e8-9961-3bd015632798.png)

Stepping over a function will display its return value in the locals window.

**Comment by DonJayamanne** [comment]
it should not be `MyClass.do_something`, the name in `locals` read `c.do_something`?

**Comment by karthiknadig** [comment]
The name comes from pydevd, it looks like they use qualified function names in this case.

**Comment by karthiknadig** [comment]
This is a fairly straight forward change. Calling the following pydevd command from debug options handler should be enough. We may want to add option to show/hide return values in settings.
```
self.pydevd_request(pydevd_comm.CMD_SHOW_RETURN_VALUES, '')
```
