### ISSUE TITLE
Execution when debugging is incorrect

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#423]
From developer community
https://developercommunity.visualstudio.com/content/problem/254447/python-execute-problem.html?childToView=255082#comment-255082

```
import pymysql
db = pymysql.connect(host="localhost",user="root",password="",database="zhidao",charset='utf8')
cursor_select = db.cursor()
sql_select = "select question_id from zhidao"
size_select = cursor_select.execute(sql_select)
for i in range(size_select):
	data = cursor_select.fetchone()
	print(data[0])
db.close()
```

Table zhidao is a small one, which has about 1400 rows, it works fine if you execute the code directly, but if you set a breakpoint and execute "size_select = cursor_select.execute(sql_select)" using F10, data will become NoneType somehow, if you check this problem deeper, you can find execution using F10 will somehow change cursor_select.rownumber to nonzero, related code of pymysql is here: https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/cursors.py
I hope this is helpful.
Version:
Win10 1803
VS Community 2017 - 15.7.1
Python - 15.7.18116.1
Python 3.6(64-bit)

**Comment by karthiknadig** [comment]
This happens because as a part of repr we do enumeration to determine the length of the repr. This causes __iter__ to be executed. Which seems to change the `rownumber`, in `Cursor`. This should be fixed by #443
