### ISSUE TITLE
Re-enable connection tests.

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/ptvsd#434]
(this is relatively low priority)

In #381 I added a number of tests.  One of them was failing most of the time on Travis (but I could not repro locally).  We disabled that one test to land the PR.  However, the test should be re-enabled after getting the test working on travis.

[tests/system_tests/test_connection.py:RawConnectionTests.test_repeated](https://github.com/Microsoft/ptvsd/blob/master/tests/system_tests/test_connection.py#L85)

**Comment by karthiknadig** [comment]
Closing this as this refers to the older tests.
