### ISSUE TITLE
Debugger may miss a breakpoint in a line where a raise happens

### ISSUE THREAD

**Issue by fabioz** [Microsoft/ptvsd#441]
I've already done the fix in pydev in https://github.com/fabioz/Pydev/commit/f29d29f257a382e1da3af107865fcda1eb656662 will add tests and port to pydev.debugger/ptvsd tomorrow.

**Comment by karthiknadig** [comment]
Looks like the cause for #347

**Comment by fabioz** [comment]
Definitely (checked that the case didn't work without the fix and works with it). 

Will close this one in favor of https://github.com/Microsoft/ptvsd/issues/347 then.
