### ISSUE TITLE
Fix CI Tests on VSTS

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ptvsd#442]
CI Tests are now available on VSTS across macOS, Linux, and Windows. Also, there are multiple versions of Python being used to run the tests in as well. 

Because the coverage has expanded so greatly, there are many failures to correct. Once the tests are cleanly running we can turn on PR verification and CI using the VSTS build system.

Please see the following grid of failing tests for the current state (as of this writing).

## Currently Failing Tests

 TestName | Module | OS | Python Version | Status 
----------|--------|----|----------------|-------
test_path_names_lowercase_disabled |tests.ptvsd.test_pathutils.PathUtilTests | Win | 2.7 | FAIL 
test_path_names_uppercase_enabled |tests.ptvsd.test_pathutils.PathUtilTests | Win | 2.7 | ERROR 
test_path_names_normcased |tests.ptvsd.test_pathutils.PathUtilTests | Win | 2.7 | ERROR 
test_path_names_lowercase_enabled |tests.ptvsd.test_pathutils.PathUtilTests | Win | 2.7 | ERROR 
test_basic |tests.highlevel.test_live_pydevd.LogpointTests | Win | 3.4 | FAIL 
test_active_exception |tests.highlevel.test_messages.ExceptionInfoTests | Win | 3.4 | FAIL 
test_all |tests.test_setup.IterVendoredFilesTests | Win | 3.4 | FAIL 
test_default_args |tests.debugger_protocol.schema.test___main__.HandleCheckTests | Win | 3.4 | ERROR 
test_default_args |tests.debugger_protocol.schema.test___main__.HandleDownloadTests | Win | 3.4 | ERROR 
test_default_args |tests.debugger_protocol.schema.test___main__.CLITests | Win | 3.4 | ERROR 
test_run_to_completion |tests.system_tests.test_main.CLITests | Win | 3.4 | ERROR 
test_script_args |tests.system_tests.test_main.CLITests | Win | 3.4 | ERROR 
test_attach_embedded |tests.system_tests.test_main.LifecycleTests | Win | 3.4 | ERROR 
test_attach_started_separately |tests.system_tests.test_main.LifecycleTests | Win | 3.4 | ERROR 
test_launch_ptvsd_server |tests.system_tests.test_main.LifecycleTests | Win | 3.4 | ERROR 
test_pre_init |tests.system_tests.test_main.LifecycleTests | Win | 3.4 | ERROR 
test_reattach |tests.system_tests.test_main.LifecycleTests | Win | 3.4 | ERROR 
test_match |tests.system_tests.test_schema.CheckCommandTests | Win | 3.4 | ERROR 
test_metadata_mismatch |tests.system_tests.test_schema.CheckCommandTests | Win | 3.4 | ERROR 
test_metadata_missing |tests.system_tests.test_schema.CheckCommandTests | Win | 3.4 | ERROR 
test_schema_missing |tests.system_tests.test_schema.CheckCommandTests | Win | 3.4 | ERROR 
test_upstream_mismatch |tests.system_tests.test_schema.CheckCommandTests | Win | 3.4 | ERROR 
test_upstream_not_found |tests.system_tests.test_schema.CheckCommandTests | Win | 3.4 | ERROR 
test_custom_source |tests.system_tests.test_schema.DownloadCommandTests | Win | 3.4 | ERROR 
test_basic |tests.highlevel.test_live_pydevd.LogpointTests | Win | 3.5 | FAIL 
test_all |tests.test_setup.IterVendoredFilesTests | Win | 3.5 | FAIL 
test_failure |tests.system_tests.test_main.CLITests | Win | 3.5 | ERROR 
test_run_to_completion |tests.system_tests.test_main.CLITests | Win | 3.5 | ERROR 
test_script_args |tests.system_tests.test_main.CLITests | Win | 3.5 | ERROR 
test_attach_embedded |tests.system_tests.test_main.LifecycleTests | Win | 3.5 | ERROR 
test_attach_started_separately |tests.system_tests.test_main.LifecycleTests | Win | 3.5 | ERROR 
test_launch_ptvsd_server |tests.system_tests.test_main.LifecycleTests | Win | 3.5 | ERROR 
test_pre_init |tests.system_tests.test_main.LifecycleTests | Win | 3.5 | ERROR 
test_reattach |tests.system_tests.test_main.LifecycleTests | Win | 3.5 | ERROR 
test_basic |tests.highlevel.test_live_pydevd.LogpointTests | Win | 3.6 | FAIL 
test_all |tests.test_setup.IterVendoredFilesTests | Win | 3.6 | FAIL 
test_failure |tests.system_tests.test_main.CLITests | Win | 3.6 | ERROR 
test_run_to_completion |tests.system_tests.test_main.CLITests | Win | 3.6 | ERROR 
test_script_args |tests.system_tests.test_main.CLITests | Win | 3.6 | ERROR 
test_attach_embedded |tests.system_tests.test_main.LifecycleTests | Win | 3.6 | ERROR 
test_attach_started_separately |tests.system_tests.test_main.LifecycleTests | Win | 3.6 | ERROR 
test_launch_ptvsd_server |tests.system_tests.test_main.LifecycleTests | Win | 3.6 | ERROR 
test_pre_init |tests.system_tests.test_main.LifecycleTests | Win | 3.6 | ERROR 
test_reattach |tests.system_tests.test_main.LifecycleTests | Win | 3.6 | ERROR 
test_basic |tests.highlevel.test_live_pydevd.LogpointTests | Win | 3.7.0-b2 | FAIL 
test_all |tests.test_setup.IterVendoredFilesTests | Win | 3.7.0-b2 | FAIL 
test_active_exception |tests.highlevel.test_messages.ExceptionInfoTests | Win | 3.7.0-b2 | ERROR 
test_failure |tests.system_tests.test_main.CLITests | Win | 3.7.0-b2 | ERROR 
test_run_to_completion |tests.system_tests.test_main.CLITests | Win | 3.7.0-b2 | ERROR 
test_script_args |tests.system_tests.test_main.CLITests | Win | 3.7.0-b2 | ERROR 
test_attach_embedded |tests.system_tests.test_main.LifecycleTests | Win | 3.7.0-b2 | ERROR 
test_attach_started_separately |tests.system_tests.test_main.LifecycleTests | Win | 3.7.0-b2 | ERROR 
test_launch_ptvsd_server |tests.system_tests.test_main.LifecycleTests | Win | 3.7.0-b2 | ERROR 
test_pre_init |tests.system_tests.test_main.LifecycleTests | Win | 3.7.0-b2 | ERROR 
test_reattach |tests.system_tests.test_main.LifecycleTests | Win | 3.7.0-b2 | ERROR 
test_active_exception |tests.highlevel.test_messages.ExceptionInfoTests | Linux | 3.4 | FAIL 
test_default_args |tests.debugger_protocol.schema.test___main__.HandleCheckTests | Linux | 3.4 | ERROR 
test_default_args |tests.debugger_protocol.schema.test___main__.HandleDownloadTests | Linux | 3.4 | ERROR 
test_match |tests.system_tests.test_schema.CheckCommandTests | Linux | 3.4 | ERROR 
test_metadata_mismatch |tests.system_tests.test_schema.CheckCommandTests | Linux | 3.4 | ERROR 
test_metadata_missing |tests.system_tests.test_schema.CheckCommandTests | Linux | 3.4 | ERROR 
test_schema_missing |tests.system_tests.test_schema.CheckCommandTests | Linux | 3.4 | ERROR 
test_upstream_mismatch |tests.system_tests.test_schema.CheckCommandTests | Linux | 3.4 | ERROR 
test_upstream_not_found |tests.system_tests.test_schema.CheckCommandTests | Linux | 3.4 | ERROR 
test_custom_source |tests.system_tests.test_schema.DownloadCommandTests | Linux | 3.4 | ERROR 
test_active_exception |tests.highlevel.test_messages.ExceptionInfoTests | Linux | 3.7.0-b2 | FAIL 
test_failure |tests.system_tests.test_main.CLITests | macOS | 3.6 | ERROR 
test_run_to_completion |tests.system_tests.test_main.CLITests | macOS | 3.6 | ERROR 
test_script_args |tests.system_tests.test_main.CLITests | macOS | 3.6 | ERROR 
test_attach_embedded |tests.system_tests.test_main.LifecycleTests | macOS | 3.6 | ERROR 
test_attach_started_separately |tests.system_tests.test_main.LifecycleTests | macOS | 3.6 | ERROR 
test_launch_ptvsd_server |tests.system_tests.test_main.LifecycleTests | macOS | 3.6 | ERROR 
test_pre_init |tests.system_tests.test_main.LifecycleTests | macOS | 3.6 | ERROR 
test_reattach |tests.system_tests.test_main.LifecycleTests | macOS | 3.6 | ERROR 

> Attached: ptvsd-failing.csv file so you can sort/arrange as you wish...

[ptvsd-failing-tests.zip](https://github.com/Microsoft/ptvsd/files/2049718/ptvsd-failing-tests.zip)

**Comment by ericsnowcurrently** [comment]
A number of these should be resolved now, after #455.

**Comment by karthiknadig** [comment]
@d3r3kk Is this fixed?

**Comment by d3r3kk** [comment]
@karthiknadig, does not appear to be (see for yourself, check the latest output on the VSTS CI build here)[https://ptvsd.visualstudio.com/ptvsd/ptvsd%20Team/_build/results?buildId=137&view=ms.vss-test-web.test-result-details].

Or, for brevity here's the current status of unit tests across the various OS's and Python versions we have specified today:

![image](https://user-images.githubusercontent.com/11466735/41867227-5695da4c-7867-11e8-880a-e1e9f53fb3d2.png)

**Comment by karthiknadig** [comment]
Some of the issues in Py3.4 should be improved with #519
