### ISSUE TITLE
Stepping through Python C Extension

### ISSUE THREAD

**Issue by saulshanabrook** [Microsoft/ptvsd#446]
First off, thank you for a wonderful experience stepping through Python code.

I am debugging a Python library that has some parts written in C (Numba). I notice that if I am in the debugger, I am not able to step through the parts written in C.

I would like to be able to do this, because these are often the most confusing parts, where having a debugger would be the most helpful.

I imagine this would be difficult to do, but I is it possible? I see there is some documentation for debugging C++ code in VS Code, so I wonder if that could somehow be combined with the Python debugger. 

I wasn't sure if I should open this here or https://github.com/Microsoft/vscode-python. If it's better suited there I can open a new issue.

**Comment by ericsnowcurrently** [comment]
@zooba, know anything about this relative to VS Code?

**Comment by int19h** [comment]
This requires a debugger that can handle both simultaneously. We do have such a thing for VS, but not for VSCode (it requires a native debugger that is mixed-mode-capable for us to hook into, and so far only VS has one).

https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio

**Comment by fabioz** [comment]
As a note, sometimes an easier setup is starting the debugger on python and then use the 'attach to' from the C++ debugger. 

Although if you're using the numba jit and want to debug that, I think you'll have a hard time debugging that in the C++ debugger too (may be easier to remove the `jit` declaration temporarily and debug in pure Python and then put the `jit` declaration back).

**Comment by saulshanabrook** [comment]
> Although if you're using the numba jit and want to debug that, I think you'll have a hard time debugging that in the C++ debugger too

I am actually debugging numba's source code, not a jitted function.

> As a note, sometimes an easier setup is starting the debugger on python and then use the 'attach to' from the C++ debugger.

OK I will try that, thank you!
