### ISSUE TITLE
Something wrong in debugging file contains FileStorage

### ISSUE THREAD

**Issue by rosekc** [Microsoft/ptvsd#451]
when I debugging this  code
```py
from flask import Flask, Request, request
import unittest
import io

class TestFile(unittest.TestCase):
    def test_1(self):
        app = Flask(__name__)
        app.debug = True

        @app.route("/upload", methods=['POST'])
        def upload():
            f = request.files['file']
            s = f.read()
            print(s)
            f.close()
            return s

        client = app.test_client()
        msg = b'hello world'
        resp = client.post(
            '/upload',
            data = {
                'file': (io.BytesIO(msg), 'hello world.txt'),
            }
        )
        self.assertEqual(
            msg,
            resp.get_data(),
        )

if __name__ == '__main__':
    unittest.main()
```
I add a breakpoint like this:
![image](https://user-images.githubusercontent.com/17542574/40793144-3aa86210-652e-11e8-9ebd-0d1bb903e71c.png)
It can't work and print `b''`.

If I delete the breakpoint at line 13 and add breakpoint at line 12, then just keep resuming it, it works properly and print `b'hello world'`.

But I check the variable `request.files['file']` when it hit the breakpoint, it can't work and print `b''`.

It seem something wrong in debugging file contains `FileStorage`.

**Comment by DonJayamanne** [comment]
Fixed with #443
