### ISSUE TITLE
Breakpoint only hit once on for loop

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#456]
Python 3.6
From VS
```
from math import cos, radians
	
# Create a string with spaces proportional to a cosine of x in degrees
from math import *
def make_dot_string(x):
	rad = radians(x)                             # cos works with radians
	numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	return st
	
def main():
	for i in range(0, 1800, 12):
	    s = make_dot_string(i)
	    print(s)
	
main()
```

Put breakpoint on the `for` line in `main`.
Start debugging.
Press F5 to continue.

Result: You won't hit that breakpoint on the `for` line anymore.

If you do the same with the old debugger, it will stop at that breakpoint on each iteration.

Since it's a change in behavior, I figured I'd ask.

**Comment by karthiknadig** [comment]
This is fixed in master.
