### ISSUE TITLE
Break on normal exit is not respected

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#459]
Using Visual Studio
Enable Break on normal exit option

Result: Console does not wait for input at end of program

**Comment by karthiknadig** [comment]
Looks like we don't get to Line 274 in launch scenario.
![image](https://user-images.githubusercontent.com/3840081/40863624-63a13f9e-65a5-11e8-88e0-3adb94f12c8e.png)

**Comment by ericsnowcurrently** [comment]
@huguesv, I've made a PR with a fix (#463).  Could you give it a try?

**Comment by karthiknadig** [comment]
This is not fixed yet. The merge was partial solution.

**Comment by huguesv** [comment]
Now it's pausing for a bit (2 secs) and then the console goes away.

**Comment by ericsnowcurrently** [comment]
Hmm, apparently the prompt goes away after a couple of seconds. :/
