### ISSUE TITLE
Cannot edit collection elements

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#46]

**Comment by karthiknadig** [comment]
I tried changing code in `pydevd` to generate `lines[0]`. Instead of updating the first item in the `lines` collection. It actually added a new item to the `FRAME` named `lines[0]`.

**Comment by int19h** [comment]
I think it's because for `CMD_CHANGE_VARIABLE`, you need to specify the children in the same way as you do for `CMD_GET_VARIABLE` (i.e. tab-separated like `foo\tbar\t1` for `foo.bar[1]`).

It looks like we'll just have to fix it on pydevd side of things, by accounting for indices in the handling of `CMD_CHANGE_VARIABLE`.

**Comment by int19h** [comment]
Actually, to clarify - when you changed that code, did you change it to generate just a single `lines[0]`, or tab-separated `lines` and `[0]`?

**Comment by karthiknadig** [comment]
The command args looked like this: `<tid>\t<fid>\tFRAME\tlines[0]\t1234`. The issue is actually in `pydevd_vars.py`. Get variable code uses the type resolver to get to the actual value. Where as set variable does not use type resolver, instead it directly attempts to change the value.

**Comment by karthiknadig** [comment]
This is the result of setVariable with following inputs:
`['pid_26312_id_1588235631248', '1588252057672', 'EXPRESSION', 'lines[0]', '22']`

Result:
![image](https://user-images.githubusercontent.com/3840081/37312620-ffa6f6ae-2608-11e8-8c03-64b94292a7b1.png)

Instead of updating, it created a new variable.

And for this case:
`['pid_3364_id_2123742022344', '2123757001656', 'EXPRESSION', 'lines', '[0]', '22']`

you will get this error:
```
Traceback (most recent call last):
  File "G:\git\ptvsd\ptvsd\pydevd\_pydevd_bundle\pydevd_vars.py", line 396, in change_attr_expression
    Exec('%s=%s' % (attr, expression), frame.f_globals, frame.f_locals)
  File "G:\git\ptvsd\ptvsd\pydevd\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 1
    lines.[0]=22
          ^
```
