### ISSUE TITLE
ptvsd.break_into_debugger not working

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#461]
**Steps to reproduce**
* Launch remote program (`python one.py`)
* Attach
* Nothing happens

```python
import time
import ptvsd
print(ptvsd.__version__)
print(ptvsd.__file__)
ptvsd.enable_attach(('localhost', 3000))
for i in range(100):
    ptvsd.break_into_debugger()
    time.sleep(1)
    print(i)
```

**Comment by karthiknadig** [comment]
This seems to be working on Windows:
![image](https://user-images.githubusercontent.com/3840081/41173940-7faca1f2-6b0d-11e8-83f6-c0f0495b95f1.png)

Can you verify if this is broken with the latest master?

**Comment by DonJayamanne** [comment]
No longer reproduceable.
