### ISSUE TITLE
pydevd ignores user code raised exception when ignoring library exceptions

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#466]
User code raised exceptions work only if `ignore_library` option in `CMD_ADD_EXCEPTION_BREAK` is set to `0`. Setting this field to `1`, ignores user-code exceptions.

**Comment by fabioz** [comment]
This was really a problem on pydevd. I've fixed it in https://github.com/fabioz/PyDev.Debugger/commit/163fdeb0d7dbcd693a5f49e1357b13ed61cb72bb but I'm waiting on https://github.com/Microsoft/ptvsd/pull/426 to actually provide a pull request.
