### ISSUE TITLE
Inappropriate ioctl for device when remote debug with fabric

### ISSUE THREAD

**Issue by bingkxu** [Microsoft/ptvsd#470]
python version: 2.7.13
ptvsd version: 3.0.0
vscode version: 1.23.1
fabric version: 1.14

when using remote debug, call fabric function run('find / -name xx.sh 2>/dev/null'), an error occurs:
    out = run('find / -name xx.sh 2>/dev/null')
  File "./fabric/network.py", line 687, in host_prompting_wrapper
  File "./fabric/operations.py", line 1090, in run
  File "./fabric/operations.py", line 933, in _run_command
  File "./fabric/operations.py", line 770, in _execute
  File "./fabric/utils.py", line 306, in _pty_size
IOError: [Errno 25] Inappropriate ioctl for device

then delete debug code below, everything goes fine:
import ptvsd
ptvsd.enable_attach("my_secret", address=('0.0.0.0', 3000))

ptvsd.wait_for_attach()
ptvsd.break_into_debugger()

it seems that fabric and ptvsd have conflicts

**Comment by karthiknadig** [comment]
@bingkxu This repository tracks the newer version of the ptvsd debugger (ie. v4.0+), which is still in experimental state.

If you want to try the newer version, here are some things you can do:
* Install the pre-release version of ptvsd: `pip install --upgrade --pre ptvsd`
* Change the `enable_attach` to `ptvsd.enable_attach('0.0.0.0', 3000)`
* There is currently a issue when using and `break_into_debugger` with  `wait_for_attach` (see #462). So you can either just use `break_into_debugger` or use `wait_for_attach` with breakpoint.
* When connecting with VSC use the `Python Experimental: Attach` configuration.

@zooba, @huguesv Any idea on this issue (considering the legacy debugger)?

**Comment by bingkxu** [comment]
version above 4.0+ most use with python3 and windows
is there any version is compatible with python 2.7.12 and linux?

**Comment by karthiknadig** [comment]
`ptvsd` v4.0+ that is shipped with VSC supports python 2.7, 3.5-3.7, and following platforms: windows, linux, and macOS.

**Comment by bingkxu** [comment]
[https://pypi.org/project/ptvsd/4.1.1a9/#files](url)
In pypi page, only support py3 and windows. so, do you mean that if I download ptvsd-4.1.1a9-py3-none-win_amd64.whl and upzip to linux folder, it can work fine?

Filename, size & hash SHA256 hash help | File type | Python version | Upload date
-- | -- | -- | --
ptvsd-4.1.1a9-py3-none-win32.whl (1.6 MB)  Copy SHA256 hashSHA256 | Wheel | py3 | Jun 21, 2018
ptvsd-4.1.1a9-py3-none-win_amd64.whl (1.6 MB)  Copy SHA256 hashSHA256 | Wheel | py3 | Jun 21, 2018
ptvsd-4.1.1a9.zip (1.3 MB)  Copy SHA256 hashSHA256 | Source | None | Jun 21, 2018

**Comment by zooba** [comment]
@bingkxu Those are just the versions that have precompiled binaries. If you `pip install --pre ptvsd` then you will get the source distribution and it will (try to) build the compiled modules. If you don't have a compiler available, it will still work, but will run slower.

**Comment by karthiknadig** [comment]
```console
kanadig:~$ python -m pip install --user --pre ptvsd
Collecting ptvsd
  Using cached https://files.pythonhosted.org/packages/88/59/84205b428f4b08b93f65e1055eae171c202bfa94139f6d18ba3bd4255a9c/ptvsd-4.1.1a9.zip
Building wheels for collected packages: ptvsd
  Running setup.py bdist_wheel for ptvsd ... done
  Stored in directory: /home/kanadig/.cache/pip/wheels/02/83/eb/cb2d8f448dbaf88a4ce68120de78df34e9c0980bfd7e33d49f
Successfully built ptvsd
Installing collected packages: ptvsd
Successfully installed ptvsd-4.1.1a9
kanadig:~$ python -m pip show ptvsd
Name: ptvsd
Version: 4.1.1a9
Summary: Remote debugging server for Python support in Visual Studio and Visual Studio Code
Home-page: https://aka.ms/ptvs
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT
Location: /home/kanadig/.local/lib/python2.7/site-packages
Requires: 
Required-by: 

```

**Comment by bingkxu** [comment]
thanks for reply. But my linux can not connect to internet, any way to install from the source code?
will it work by simply unzipping source ptvsd-4.1.1a9.zip to linux folder? I see some .pyd in zip file

**Comment by karthiknadig** [comment]
Yes you can install from a zip file:
```console
kanadig:~$ python -m pip install --user ptvsd-4.1.1a9.zip
Processing ./ptvsd-4.1.1a9.zip
Building wheels for collected packages: ptvsd
  Running setup.py bdist_wheel for ptvsd ... done
  Stored in directory: /home/kanadig/.cache/pip/wheels/6a/42/5d/ff3ecc6a49a592faccb3eea027a4899b4bc5aaada9c46d73b0
Successfully built ptvsd
Installing collected packages: ptvsd
Successfully installed ptvsd-4.1.1a9

```

**Comment by bingkxu** [comment]
@zooba is right. I use pip installed zip file, and compare the source and installed files, all the same except for pyc files. So it can work by simply unzipping zip archive.

**Comment by bingkxu** [comment]
there are some differences between pythonExperimental and python
secret localRoot remoteRoot are in python, but not in pythonExperimental. How can I add these information in pythonExperimental? Manually added it says: Property is not allowed
![ptvsd](https://user-images.githubusercontent.com/40077975/42122858-c0551df0-7c7a-11e8-9c83-aa1ac225242d.JPG)

**Comment by karthiknadig** [comment]
Not sure if you got the answer for this but you can use this:
```
"pathMappings": [{
                "localRoot": "${workspaceFolder}",
                "remoteRoot": "/home/" 
            }]
```
