### ISSUE TITLE
Unit tests in VSC for path translation for remote debugging fails on Linux

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#473]
https://github.com/Microsoft/vscode-python/issues/1939

I'll try to identify the root cause soon, but want to create this issue in PTVSD first.
This impacts remote debugging between linux and Windows OS.

**Comment by DonJayamanne** [comment]
Narrowed down the issue further, seems to be a problem with Pydevd.
Looks like path translations are not taking place in pydevd.
Note: version of pydevd in 4.1.1a1 works, where as pydevd in master of PVTSD doesn't.

**Comment by DonJayamanne** [comment]
@fabioz this started failing after we merged upstream PyDevD changes.
I.e. some change in PyDevD broke this, looks like path translations for remote debugging isn't working as expected.

**Comment by fabioz** [comment]
@DonJayamanne I'm currently working in path translations as a part of https://github.com/Microsoft/ptvsd/issues/333, so, hopefully that'll fix this too.

**Comment by fabioz** [comment]
@DonJayamanne can you check if https://github.com/Microsoft/ptvsd/pull/533 fixes it? If it doesn't, it'd be nice if you could print the paths received in `pydevd_file_utils.setup_client_server_paths` and also provide the output gotten by setting `pydevd_file_utils.DEBUG_CLIENT_SERVER_TRANSLATION` to `True` to help checking where the error may be on `pydevd`.

**Comment by karthiknadig** [comment]
@DonJayamanne Did you get a chance to look at this?

**Comment by DonJayamanne** [comment]
Will check this out and get back some time later today or first thing tomorrow.

**Comment by DonJayamanne** [comment]
Cannot test as remote debugging is broken.
