### ISSUE TITLE
pydevd: Step  over and step return should support just-my-code

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#477]

**Comment by karthiknadig** [comment]
@fabioz Can you give an estimate for this item?

**Comment by fabioz** [comment]
Estimate: 4 days.

**Comment by fabioz** [comment]
Note: started to take a look at this, but I won't be able to finish today, so, will resume working on it when I'm back (Nov 27th) -- unless something else becomes a priority in the meanwhile ;)
