### ISSUE TITLE
Pausing (break) not working anymore in VSC

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#479]
We have unit tests that have caught this error. 

Been ignoring failing Debugger tests in VSC as we have had a number of failing debugger tests for over a month, hence I have no idea when this issue cropped up. Either way this is something that used to work (still works in the preview version of PTVSD on pypi).

<img width="771" alt="screen shot 2018-06-13 at 5 42 57 pm" src="https://user-images.githubusercontent.com/1948812/41385618-9e751bdc-6f31-11e8-9461-a32149d5b201.png">

**Steps to reproduce:**
* Create a python file with the following code:
```python
import time

for i in range(1000):
    time.sleep(1)
    print(i)
```
* Start debugging without any breakpoints
* Once started printing to console window, hit the `Pause` button.
* **Nothing happens**

**Comment by DonJayamanne** [comment]
Looks like d635e22d3396f1cf3ab2fe9bc6fc9f5395b38232 has introduced this issue.

/cc @karthiknadig @fabioz

**Comment by fabioz** [comment]
Pull request https://github.com/Microsoft/ptvsd/pull/508 should fix this too.

**Comment by karthiknadig** [comment]
This is fixed. Tested on windows with VSC.
