### ISSUE TITLE
JustMyCode debugging not working in VS Code when virtualenv is inside workspace

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#481]
* Environment:
* OS - MAC
* VS Code Version - Stable Version

* Go into vs code Python extension (go into command palette `Open Extensions Folder`)
* Delete the following directory: `pythonFiles/experimental/ptvsd`
* Open a workspace in VS Code and create a virtual environment
* Install PTVSD master into virtual env `pip install git+https://github.com/Microsoft/ptvsd`
* Create a python file with the following code:
```python
import os

print(os.getenv('ONE', 'BL'))
```
* Start debugging using the experimental debugger
* Keep using `Step In`, and you'll be taken into `os.getenv` function.

**Comment by karthiknadig** [comment]
This does not repro on  Windows. @DonJayamanne Reproed this on mac. 

Note: Make sure that `debugStdLib` is `false` when trying.

**Comment by DonJayamanne** [comment]
Assigned to me to ensure I can replicate this.

**Comment by DonJayamanne** [comment]
@karthiknadig 
I can replicate it on Mac and Windows, and the problem arises from the fact that i have a virtual env in my workspace folder.
* Create a virtual environment in your workspace folder.
* Start debugging

**Comment by cjolivier01** [comment]
I have this same problem
