### ISSUE TITLE
Debugger does not end in VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#483]
* Env:
OS - Mac
PTVSD Version - Master

**Not working video:**
![dbg2](https://user-images.githubusercontent.com/1948812/41437045-6c905792-6fd8-11e8-92a1-880f3341a22e.gif)

**Working (`with older version PTVSD 4.1.1a1`)**
![dbg1](https://user-images.githubusercontent.com/1948812/41437056-70915562-6fd8-11e8-82b9-3a5d99ca9e8f.gif)

**Comment by fabioz** [comment]
This usually means some spawned thread did not finish. I'm pasting below the code I have around to help diagnose this:

```
import sys
import threading
import time
import traceback

class DumpThreads(threading.Thread):
    def run(self):
        time.sleep(2)

        thread_id_to_name = {}
        try:
            for t in threading.enumerate():
                if not t.daemon:
                    thread_id_to_name[t.ident] = '%s  (daemon: %s)' % (t.name, t.daemon)
        except:
            pass

        stack_trace = [
            '===============================================================================',
            'Threads still running',
            '================================= Thread Dump =================================']

        for thread_id, stack in sys._current_frames().items():
            stack_trace.append('\n-------------------------------------------------------------------------------')
            stack_trace.append(" Thread %s" % thread_id_to_name.get(thread_id, thread_id))
            stack_trace.append('')

            if 'self' in stack.f_locals:
                sys.stderr.write(str(stack.f_locals['self']) + '\n')

            for filename, lineno, name, line in traceback.extract_stack(stack):
                stack_trace.append(' File "%s", line %d, in %s' % (filename, lineno, name))
                if line:
                    stack_trace.append("   %s" % (line.strip()))
        stack_trace.append('\n=============================== END Thread Dump ===============================')
        sys.stderr.write('\n'.join(stack_trace))


dump_current_frames_thread = DumpThreads()
dump_current_frames_thread.start()
```

**Comment by brettcannon** [comment]
I can replicate on Windows.

This is now blocking the VS Code release.

**Comment by fabioz** [comment]
I tried running this locally with ptvsd master and couldn't replicate this.

-- Note: locally I'm using release 2018.5.0 just changing ptvsd to the master version (tried on Windows and Linux).

Since you're having the error there, can you run the sample code I posted to print which threads are still running?

**Comment by brettcannon** [comment]
It turns out to be special to either the insiders build and/or the development version of the Python extension. Working on narrowing it down now.

**Comment by brettcannon** [comment]
It's an issue with VS Code Insiders.

**Comment by DonJayamanne** [comment]
I can replicate consistently on:
* Mac
* VS Code Stable
* PTVSD latest preview release
* Python Extension (from source) as well as from Marketplace

**Comment by DonJayamanne** [comment]
The latest PR https://github.com/Microsoft/ptvsd/pull/499 has resolved this issue for me on the Mac

**Comment by brettcannon** [comment]
I can verify Don's fix takes care of the issue.
