### ISSUE TITLE
What is supportsDebuggerProperties in Capabilities returned by the Debugger

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#494]
In VSC we have some unit tests failing due to the addition of a new capability `supportsDebuggerProperties` in PTVSD.
However I cannot fund this documented in the [Protocol Spec](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json#L2164)

**Comment by karthiknadig** [comment]
This is a VS Specific protocol extension to support Just-my-code in VS. See https://github.com/Microsoft/VSDebugAdapterHost/wiki/Debugger-Properties
