### ISSUE TITLE
Unable to debug odoo with latest version of ptvsd

### ISSUE THREAD

**Issue by abokerba** [Microsoft/ptvsd#497]
the ptvsd version 4.1.1a5  bundled with the latest version of that extension causes odoo to be stuck and not responsive after beginning to listen on 0.0.0.0:8069.

so I want to use older version that uses ptvsd==3.2.1.

I'm using Windows 10 with the latest updates.
the problem is with these versions of programs:
visual studio 15.7.3
visual studio code insiders version (latest)
visual studio code latest version

every thing is updated to the latest version except visual studio 2017  and the problem started when I updated to the latest versions.

this is the debugger configuration on both vs code and vs code insiders.

-----------------------
{
            "name": "Odoo 10e windows exp",
            "type": "pythonExperimental",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "python",
            //"program": "${file}", use this to debug opened file.
            "program": "D:\\Projects\\odoo-bin",
            "args": [
              "-cD:\\Projects\\odoo\\odoo.conf",
              "-rabokerba",
              "-wadmin"
            ],
            // "cwd": "${workspaceRoot}",
            "console": "integratedTerminal"
        }

-----------------------

It works well with the non-experimental python.

this is the output of the console:

---------------------------------------------
 cd 'd:\Projects\sean\medi_meadows\additional_modules'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; ${env:PYTHONPATH}='c:\Users\abokerba\.vscode-insiders\extensions\ms-python.python-2018.5.0\pythonFiles\experimental\ptvsd'; & 'python' '-m' 'ptvsd' '--host' 'localhost' '--port' '57300' 'D:\Projects\odoo-bin' '-cD:\Projects\odoo\odoo.conf' '-rabokerba' '-wadmin'
pydev debugger: starting

2018-06-19 11:31:32,516 15828 INFO ? odoo: Odoo version 10.0+e-20170327
2018-06-19 11:31:32,519 15828 INFO ? odoo: Using configuration file at D:\Projects\odoo\odoo.conf
2018-06-19 11:31:32,519 15828 INFO ? odoo: addons paths: [u'C:\\Users\\abokerba\\AppData\\Local\\OpenERP S.A.\\Odoo\\addons\\10.0', u'D:\\Projects\\odoo\\addons', u'D:\\Projects\\dvit-odoo', u'D:\\Projects\\sean\\medi_meadows\\additional_modules', 'd:\\projects\\odoo\\addons', 'c:\\python27\\lib\\site-packages\\odoo\\addons']
2018-06-19 11:31:32,520 15828 INFO ? odoo: database: abokerba@default:default
2018-06-19 11:31:32,556 15828 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069

---------------------------------------------

and the browser keeps waiting for the response.

the "Analyze wait chain." in Task manager tell me that one or more threads of python.exe are waiting for network I/O .

I'll make a video to inform you about the bug.

Thanks!

**Comment by fabioz** [comment]
I vaguely remember an issue with odoo with pydevd related to gevent support... can you try to set an environment variable:

`GEVENT_SUPPORT` with a value of `True` and see if it makes it work for you?

**Comment by DonJayamanne** [comment]
@fabioz Is there any reason not to always enable GEVENT_SUPPORT in the debugger?
I.e. what's the implication of setting this flag to True, even when not using `gevents`?

**Comment by fabioz** [comment]
Another suggestion if the above one doesn't work would be not using odoo with gevent (if that's possible for you).

If it's ok, try commenting out the following lines at the top of openerp/__init__.py. 

```
if sys.modules.get("gevent") is not None:
    evented = True 
```

**Comment by fabioz** [comment]
Note: I'm just posting the suggestions from: https://brainwy.com/tracker/PyDev/658 (may be outdated though as it's been a while and `ptvsd` has its own threads running inside the process, so, there may be more work to make `ptvsd` work with `odoo` here).

**Comment by abokerba** [comment]
I've tried both solutions and nothing changed. (I can't even pause the debugger to know what's happening)
please note that odoo was working well with python experimental older versions but once I update visual studio 2017 it didn't work (the same for vscode and vscode insiders version)

If there's a way to install older version the python extension with ptvsd==3.2.1 , it'll be good.

**Comment by DonJayamanne** [comment]
> f there's a way to install older version the python extension with ptvsd==3.2.1 , it'll be goo

If you want to use the old debugger, then all you need to do is change `type` in `launch.json` from `"type": "pythonExperimental",` to `"type": "python",`

**Comment by abokerba** [comment]
this is a workaround.

I've remove the folders from "C:\Users\username\.vscode\extensions\ms-python.python-2018.5.0\pythonFiles\experimental\ptvsd" to force VSCode to use the ptvsd installed by pip.
I've found that these versions of ptvsd (installed by pip):

4.1.1a1 -> works without problems.
4.1.1a5 -> the problem described in this issue.
4.1.1a6 -> installation failed (IOError: [Errno 2] No such file or directory: 'DESCRIPTION.md').
4.1.1a7 -> same as 4.1.1a5
4.1.1a8 -> same as 4.1.1a5

**Comment by DonJayamanne** [comment]
Please could you send a sample code we could use to replicate this issue.

**Comment by abokerba** [comment]
my code is an odoo module that the execution process in the debugger down't reach.
Odoo can't even load its modules or mine.
so, you can debug odoo without my code.
I'm using odoo 10.0
you can get it from here: https://github.com/odoo/odoo/tree/10.0
or here: https://www.odoo.com/documentation/10.0/setup/install.html#source-install

**Comment by DonJayamanne** [comment]
@abokerba
Thanks, but would it be possible to provide some sample code. I have not used odoo, hence haven't got a clue where to start from. If you're able to provide a sample code for us that would greatly reduce the time taken to diagnose this issue at our end.

**Comment by abokerba** [comment]
sorry! but I don't have code that will help you.
just start debugging odoo from the source code and you'll face the same problem (I've tested it without my modules)
I don't know another way to detect this problem.

**Comment by DonJayamanne** [comment]
> you'll face the same problem

Ok, but are you able to provide some instructions to replicate the issue you are experiencing.

**Comment by abokerba** [comment]
I've found that odoo 10 community edition work well with all versions of ptvsd.
but the problem is with odoo 10 Enterprise. So i'll attach for you.
[odoo10e.zip](http://www.mediafire.com/file/ew3q4vdsevwbmqf/odoo10e.zip/file)

here's a good guide: [How to install odoo 10 on Ubuntu 16.04](https://www.linode.com/docs/websites/cms/install-odoo-10-on-ubuntu-16-04/#install-postgresql-database-and-server-dependencies)

and in "launch.json" insert the following config:

>      {
>            "name": "Odoo 10e",
>            "type": "pythonExperimental",
>            "request": "launch",
>            "stopOnEntry": false,
>            "pythonPath": "python",
>            "program": "(odoo-bin path)",
>            "args": [
>              "-c(odoo config file path)"
>            ]
>            "console": "integratedTerminal"
>        }

**Comment by abokerba** [comment]
The problem has been solved once I updated to the latest version of vs code and ptvsd==4.1.1a10.
I'm still working with the same version of odoo 10e.

**Comment by abokerba** [comment]
I've noticed that ptvsd==4.1.1a10 is slower. So I've downgraded it to ptvsd==4.1.1a1 again.

**Comment by fabioz** [comment]
@abokerba can you give details on what exactly is slower? 

I ran the benchmarks I have available and found no particular regressions... 

Also, can you give details on your Python version and if the cython speedups are available in your case? 

If you don't know whether the speedups are available, please set an environment variable named:

`PYDEVD_USE_CYTHON` to `YES` -- that way the debugger won't even start if the cython modules are not available (so, if you are able to run with that environment variable turned on, you're using the cython modules, otherwise you aren't).

Also, are you able to provide a sample code to reproduce the issue you have?

**Comment by karthiknadig** [comment]
Reopen if this continues to be a issue.
