### ISSUE TITLE
KeyError in thread suspended handler in attach scenario.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#506]
This line raises an error if the thread is seen only at suspend.
https://github.com/Microsoft/ptvsd/blob/master/ptvsd/wrapper.py#L2184

Previously we were not reporting the thread  state leaving the thread suspended. In a later change we removed it since thread created or found were reported via created handler or threads request handler. For attach scenario, it is possible that we see the thread for the first time in the suspended handler. So, only for the attach case we should allow the thread to be added to the thread map (may be send a created event as well?) and report thread suspension.

**Comment by ericsnowcurrently** [comment]
FWIW, there is code precedent in `on_thread()` for adding a previously unseen thread.
