### ISSUE TITLE
Attach does not support tracing of existing threads

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#509]
This drawback impacts remote debugging (attaching to a running program) and local attach.

@fabioz

https://github.com/Microsoft/ptvsd/pull/508#discussion_r196907476

> -- note: currently, because of the way that Python works, it will only set the tracing for future threads -- there's no API to set the tracing for a running thread from a different thread... not that it's impossible to do: the attach to running process has some utilities to do it, but it's currently not supported in the used APIs and that part from the attach to process needs a better API to handle this).

/cc @karthiknadig

**Comment by DonJayamanne** [comment]
Solution https://github.com/Microsoft/ptvsd/issues/200#issuecomment-399408021

**Comment by ericsnowcurrently** [comment]
FYI, #545 is related.

**Comment by fabioz** [comment]
Note: created issue on CPython (https://bugs.python.org/issue35370) so that this could be better supported by Python itself in the future.
