### ISSUE TITLE
Debugging PyQT apps might not work in VS

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#526]
@karthiknadig 
Based on your comments in https://github.com/Microsoft/ptvsd/issues/435#issuecomment-398487058. I don't think debugging of PyQT apps will work in VS.

To my knowledge VS doesn't use `python -m ptvsd...` approach of launching the debugger. It uses `debugger` module.
And that doesn't have the defaults.

I.e. defaults defined in `__main__` are not used when launching debugger from `debugger` module. As that bypasses `__main__`.

@karthiknadig  Please confirm this.

**Comment by DonJayamanne** [comment]
@karthiknadig Once confirmed, we can close this issue, as #525 should fix this (provided the solution is acceptable)

**Comment by karthiknadig** [comment]
VS will require debug to have the defualts for launch. #525 will fix the issue in attach case but not launch for VS.

**Comment by DonJayamanne** [comment]
> will fix the issue in attach case but not launch for VS.

Why not. If we add defaults in `_launch. it'll work, I don't see why not.

I don't think we should be adding defaults in VS as well. Feels wrong to duplicate stuff around. Tomorrow if we add another default, then VS would have to be modified, i.e. a whole new release of VS!!

**Comment by karthiknadig** [comment]
Fixing it in _local.py will fix it for all cases.

**Comment by karthiknadig** [comment]
Fix for #525  will fix this as well.
