### ISSUE TITLE
PTVSD needs to wait for a little while before closing the socket after sending the last message

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#530]
## Environment data

- PTVSD version: Master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio: VSC

Related to VSC issue https://github.com/Microsoft/vscode-python/issues/2064

## Actual behavior

* PTVSD shuts down even before VSC receives the entire packet

## Expected  behavior

PTVSD Should wait for some random time waiting for VSC to receive the message before terminating the socket.

## Possible solutions
Note: VSC has a slight delay of 100ms for such situations (e.g. if PTVSD dies, or user kills the PTVSD process manually, etc). In such cases VSC sends the terminated event.

**Solution 1:** We could do the same here, if disconnect request is received with a `restart` flag, PTVSD can wait for 100ms before killing the socket.
**Solution2:** 
* First send the response, then invoke `notify_disconnecting`
* This seems to work. Would prefer to still add the delay based on the `restart` flag in the disconnect request. A delay of 100ms.
```python
        self.send_response(request)
        self._notify_disconnecting()
        self._set_disconnected()
```
/c @ericsnowcurrently 

## Steps to reproduce:
1. Start debugging
1. Add a breakpoint
1. Click the `Restart` button in VSC
1. PTVSD receives the `disconnect` request
1. PTVSD sends the response and immediately disconnects

**Comment by DonJayamanne** [comment]
@karthiknadig @ericsnowcurrently 
This is yet another reason to work on https://github.com/Microsoft/vscode-python/issues/1367

**Comment by karthiknadig** [comment]
For solution 2 is it a custom message? If so then this won't work for VS.

**Comment by DonJayamanne** [comment]
> For solution 2 is it a custom message? If so then this won't work for VS.

Does VS support `restart`?

**Comment by karthiknadig** [comment]
No. It does not. I have to check with the Adapter Host folks about this. 
```
1> [DebugAdapter] --> C (disconnect-19): {"command":"disconnect","arguments":{"terminateDebuggee":true},"seq":19,"type":"request"}
```
On restart, they terminate the debuggee (see above message) and start another session.

**Comment by ericsnowcurrently** [comment]
FWIW, I've landed a few PRs that improve the situation.  Apparently they do not quite solve the problem yet, though.  Per Don, the sys.exit() call blocks indefinitely.  I have not seen this issue in our tests, but who knows.

**Comment by DonJayamanne** [comment]
@ericsnowcurrently I've created some tests for this in https://github.com/Microsoft/ptvsd/pull/539 (currently disabled and incomplete).

**Comment by DonJayamanne** [comment]
@ericsnowcurrently 
Once fixed, please enable the following test:
```python
tests/system_tests/test_launch.py

    @unittest.skip('To be fixed in #530')
    def test_terminating_program(self):
```

**Comment by DonJayamanne** [comment]
@ericsnowcurrently Please do not look into this next week.
We have decided to implement a work around in VSC for now, please look at other [P0 issues](https://github.com/Microsoft/ptvsd/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apriority%3AP0).

/cc @MikhailArkhipov @karthiknadig

**Comment by ericsnowcurrently** [comment]
FYI, #475 is related.

**Comment by DonJayamanne** [comment]
I found the cause and a managed to hack a work around, we can discuss once we have resolved other issues

**Comment by DonJayamanne** [comment]
> I found the cause and a managed to hack a work around

Time to clean up the hack.

**Comment by karthiknadig** [comment]
The out-of-proc debug adapter handles cleanly shutting down debuggee process and issues the relevant messages in case the debuggee is killed by user.
