### ISSUE TITLE
Occasional test failure in CI:  tests.system_tests.test_main.LifecycleTests.test_attach_embedded

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/ptvsd#534]
Occasionally we see the following test failure in CI.    It indicates that there's a race somewhere along the line.

    FAIL: test_attach_embedded (tests.system_tests.test_main.LifecycleTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/Microsoft/ptvsd/tests/system_tests/test_main.py", line 506, in test_attach_embedded
        self.assertIn('success!', out)
    AssertionError: 'success!' not found in ''

    ----------------------------------------------------------------------
    Ran 578 tests in 113.185s

    FAILED (failures=1, skipped=50)

**Comment by fabioz** [comment]
I've provided a fix for this one at https://github.com/Microsoft/ptvsd/pull/529/commits/cb74656296e5de5dd02cebfda1e07361b2b4cafc

**Comment by fabioz** [comment]
(in open pull request: https://github.com/Microsoft/ptvsd/pull/529/)
