### ISSUE TITLE
Occasional test failure in CI:  tests.highlevel.test_live_pydevd.LogpointTests.test_basic

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/ptvsd#535]
Occasionally we see the following test failure in CI.    It indicates that there's a race somewhere along the line.

(may be related to #534)

    FAIL: test_basic (tests.highlevel.test_live_pydevd.LogpointTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/Microsoft/ptvsd/tests/highlevel/test_live_pydevd.py", line 478, in test_basic
        'logMessage': '{a}+{b}=3'
      File "/home/travis/build/Microsoft/ptvsd/tests/highlevel/__init__.py", line 901, in assert_vsc_received
        assert_messages_equal(received, expected)
      File "/home/travis/build/Microsoft/ptvsd/tests/helpers/message.py", line 62, in assert_messages_equal
        raise AssertionError('\n'.join(msg))
    AssertionError: 
    Received:
    Event(seq=0, event='output', body={'category': 'telemetry', 'output': 'ptvsd', 'data': {'version': '4.1.1a9+13.g59106e1'}})
    Response(seq=1, request_seq=0, command='initialize', success=True, message='', body={'supportsEvaluateForHovers': True, 'supportsValueFormattingOptions': True, 'supportsExceptionInfoRequest': True, 'supportsExceptionOptions': True, 'supportTerminateDebuggee': True, 'supportsConfigurationDoneRequest': True, 'exceptionBreakpointFilters': [{'label': 'Raised Exceptions', 'filter': 'raised', 'default': False}, {'label': 'Uncaught Exceptions', 'filter': 'uncaught', 'default': True}], 'supportsDebuggerProperties': True, 'supportsModulesRequest': True, 'supportsLogPoints': True, 'supportsSetExpression': True, 'supportsConditionalBreakpoints': True, 'supportsSetVariable': True, 'supportsHitConditionalBreakpoints': True})
    Event(seq=2, event='initialized', body={})
    Response(seq=3, request_seq=1, command='attach', success=True, message='', body={})
    Response(seq=4, request_seq=2, command='setBreakpoints', success=True, message='', body={'breakpoints': [{'verified': True, 'line': '4', 'id': 1}]})
    Response(seq=5, request_seq=3, command='configurationDone', success=True, message='', body={})
    Event(seq=6, event='process', body={'name': '/tmp/workspace-8s678cri/spam.py', 'startMethod': 'attach', 'isLocalProcess': True, 'systemProcessId': 2631})
    Event(seq=7, event='thread', body={'threadId': 1, 'reason': 'started'})
    Event(seq=8, event='output', body={'category': 'stdout', 'output': '1+2=3\n'})
    Event(seq=9, event='output', body={'category': 'stdout', 'output': 'bye'})

    Expected:
    Event(seq=0, event='output', body={'category': 'telemetry', 'data': {'version': '4.1.1a9+13.g59106e1'}, 'output': 'ptvsd'})
    Response(seq=1, request_seq=0, command='initialize', success=True, message='', body={'supportsEvaluateForHovers': True, 'supportsValueFormattingOptions': True, 'supportsExceptionInfoRequest': True, 'supportsExceptionOptions': True, 'supportsConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsSetVariable': True, 'supportsDebuggerProperties': True, 'supportsModulesRequest': True, 'supportsLogPoints': True, 'supportsSetExpression': True, 'supportTerminateDebuggee': True, 'exceptionBreakpointFilters': [{'label': 'Raised Exceptions', 'filter': 'raised', 'default': False}, {'label': 'Uncaught Exceptions', 'filter': 'uncaught', 'default': True}], 'supportsHitConditionalBreakpoints': True})
    Event(seq=2, event='initialized', body={})
    Response(seq=3, request_seq=1, command='attach', success=True, message='', body={})
    Response(seq=4, request_seq=2, command='setBreakpoints', success=True, message='', body={'breakpoints': [{'verified': True, 'line': '4', 'id': 1}]})
    Response(seq=5, request_seq=3, command='configurationDone', success=True, message='', body={})
    Event(seq=6, event='process', body={'name': '/tmp/workspace-8s678cri/spam.py', 'isLocalProcess': True, 'startMethod': 'attach', 'systemProcessId': 2631})
    Event(seq=7, event='thread', body={'threadId': 1, 'reason': 'started'})
    Event(seq=8, event='output', body={'category': 'stdout', 'output': '1+2=3\n'})
    Event(seq=9, event='output', body={'category': 'stdout', 'output': 'bye'})
    Event(seq=10, event='output', body={'category': 'stdout', 'output': '\n'})

    Diff by line
      0:  Event(seq=0, event='output', body={'category': 'telemetry', 'output': 'ptvsd', 'data': {'version': '4.1.1a9+13.g59106e1'}})
      1:  Response(seq=1, request_seq=0, command='initialize', success=True, message='', body={'supportsEvaluateForHovers': True, 'supportsValueFormattingOptions': True, 'supportsExceptionInfoRequest': True, 'supportsExceptionOptions': True, 'supportTerminateDebuggee': True, 'supportsConfigurationDoneRequest': True, 'exceptionBreakpointFilters': [{'label': 'Raised Exceptions', 'filter': 'raised', 'default': False}, {'label': 'Uncaught Exceptions', 'filter': 'uncaught', 'default': True}], 'supportsDebuggerProperties': True, 'supportsModulesRequest': True, 'supportsLogPoints': True, 'supportsSetExpression': True, 'supportsConditionalBreakpoints': True, 'supportsSetVariable': True, 'supportsHitConditionalBreakpoints': True})
      2:  Event(seq=2, event='initialized', body={})
      3:  Response(seq=3, request_seq=1, command='attach', success=True, message='', body={})
      4:  Response(seq=4, request_seq=2, command='setBreakpoints', success=True, message='', body={'breakpoints': [{'verified': True, 'line': '4', 'id': 1}]})
      5:  Response(seq=5, request_seq=3, command='configurationDone', success=True, message='', body={})
      6:  Event(seq=6, event='process', body={'name': '/tmp/workspace-8s678cri/spam.py', 'startMethod': 'attach', 'isLocalProcess': True, 'systemProcessId': 2631})
      7:  Event(seq=7, event='thread', body={'threadId': 1, 'reason': 'started'})
      8:  Event(seq=8, event='output', body={'category': 'stdout', 'output': '1+2=3\n'})
      9:  Event(seq=9, event='output', body={'category': 'stdout', 'output': 'bye'})
    !10: None != Event(seq=10, event='output', body={'category': 'stdout', 'output': '\n'})

    ----------------------------------------------------------------------
    Ran 578 tests in 113.185s

    FAILED (failures=1, skipped=50)

**Comment by DonJayamanne** [comment]
Investigate whether this is still occuring

**Comment by DonJayamanne** [comment]
No longer an issue
