### ISSUE TITLE
Debugger doesn't break at the first line when it has a breakpoint

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#536]
## Environment data

- PTVSD version: Master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: N/A

## Actual behavior

Debugger doesn't stop at the first line when there's a breakpoint.

## Expected  behavior

Debugger should stop

## Steps to reproduce:
1. Python code:
```python
a = 1
b = 2
c = 3
```
* Add a breakpoint to the first line
* Unit tests fail for testing of breakpoints
* Add a breakpoint to the third line, and it works!

I'm in the process of writing some tests, will create a test specifically for this and mark it as skipped (for now).

**Comment by karthiknadig** [comment]
Does not repro on Windows.
![image](https://user-images.githubusercontent.com/3840081/41998656-1b58d934-7a10-11e8-89f7-b2d50d5aa2a8.png)

**Comment by DonJayamanne** [comment]
Closing, as I'm unable to replicate this.
