### ISSUE TITLE
Args passed to user script on 'start without debugging' contains ptvsd args

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#540]
## Environment data

- PTVSD version: Master
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Any
- Using VS Code or Visual Studio: VSC

## Actual behavior

```
['c:\\Users\\kanadig\\.vscode\\extensions\\ms-python.python-2018.6.0\\pythonFiles\\experimental\\ptvsd\\ptvsd\\__main__.py', '--nodebug', '--host', 'localhost', '--port', '51225', 'c:\\scratch\\test.py', '--one', '--two', '--three']
```

## Expected  behavior

```
['c:\\scratch\\test.py', '--one', '--two', '--three']
```

## Steps to reproduce:
1. Create a script file with this content:
```python
import sys
print(sys.argv)
```
2. Add `args` to python experimental launch configuration:
```json
{
    "name": "PyExp: Current File",
    "type": "pythonExperimental",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "args": ["--one", "--two", "--three"]
}
```
2. Run using **F5** and **Ctrl+F5**, the output should be same.

**Comment by DonJayamanne** [comment]
@karthiknadig  I'll be creating tests for this, or you too could do the same.

**Comment by karthiknadig** [comment]
I will do it when i fix the issue.
