### ISSUE TITLE
Enable unicode tests 

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#548]
Unit tests for debugging of files with unicode characters in file paths have been disabled.
The tests fail when running with code coverage (added in https://github.com/Microsoft/ptvsd/pull/514)

**Comment by karthiknadig** [comment]
Looks like the LANG is not set to utf-8. That is what is causing this issue.
```
test_breakpoints_single_file (tests.highlevel.test_live_pydevd.UnicodeBreakpointTests) ... LANG: none
LC_ALL: none
LANG: none
enc: ascii
ERROR
test_exception_breakpoints (tests.highlevel.test_live_pydevd.UnicodeBreakpointTests) ... LANG: none
LC_ALL: none
LANG: none
enc: ascii
ERROR
test_no_breakpoints (tests.highlevel.test_live_pydevd.UnicodeBreakpointTests) ... LANG: none
LC_ALL: none
LANG: none
enc: ascii
ERROR
```
@int19h how do we set this? i tried doing it in the `travis.yml` does not seem to propagate to the tests.

**Comment by int19h** [comment]
I don't know if there's a Travis-specific thing to do this. But it looks like Travis will ultimately just invoke Makefile. And that should be able to do this at the top (where it sets $PYTHON):
```
export LANG=en_US.UTF-8
```

**Comment by karthiknadig** [comment]
I made the changes needed to add export LANG to the make file. That does not seem to help:
https://github.com/Microsoft/ptvsd/compare/master...karthiknadig:issue548

```
======================================================================
ERROR: test_breakpoints_single_file (tests.highlevel.test_live_pydevd.UnicodeBreakpointTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/karthiknadig/ptvsd/tests/highlevel/test_live_pydevd.py", line 61, in setUp
    self.set_source_file(self.FILENAME, self.SOURCE)
  File "/home/travis/build/karthiknadig/ptvsd/tests/highlevel/test_live_pydevd.py", line 92, in set_source_file
    filename = self.pathentry.write(filename, content=content)
  File "/home/travis/build/karthiknadig/ptvsd/tests/helpers/workspace.py", line 106, in write
    return self._write(path, **kwargs)
  File "/home/travis/build/karthiknadig/ptvsd/tests/helpers/workspace.py", line 129, in _write
    with open(filename, 'w') as outfile:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-25: ordinal not in range(128)
```

/cc @d3r3kk

**Comment by d3r3kk** [comment]
Have you set PYTHONENCODING?

We use `export PYTHONENCODING='utf-8'` in a few places... but perhaps that's not what you are looking for here.

Is there a build that has the failure that I can have a look at?

What version of Python is this failing in? What OS (I assume Linux because of Travis! But making sure all the cables are plugged in...)

**Comment by karthiknadig** [comment]
This is fixed in pytest based tests
