### ISSUE TITLE
Create files in PTVSD repo for testing purposes instead of creating them on the fly

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#556]
Currently we have code used to create files on the fly for the system/integration tests.
Suggestion is to create files in the PTVSD repo instead.
I believe this:
* Saves time in writing tests
* Reduces the amount of code in tests
* Improves readability (reduction in lines of unnecessary code).

Here's some sample code used to create files for testing:
```python
        source = dedent("""
            def do_something():
                # <Token>
                print("inside bar")
            """)
        bar_filepath = self.create_source_file("bar.py", source)
        bp_line = self.find_line(bar_filepath, 'Token')

        source_module = dedent("""
            from . import bar
            def foo():
                # <Token>
                bar.do_something()
            foo()
            """)
        source_file = dedent("""
            import bar
            def foo():
                # <Token>
                bar.do_something()
            foo()
            """)
        (filename, filepath, env, expected_module, argv,
         cwd) = self.get_test_info(source_module if self.IS_MODULE else source_file) # noqa
        foo_line = self.find_line(filepath, 'Token')
```

/cc @ericsnowcurrently @karthiknadig @int19h

**Comment by DonJayamanne** [comment]
My suggestion is to create the files under `tests/resources` directory.
Create separate directories for different tests.

**Comment by DonJayamanne** [comment]
I'll be creating physical files in the repo (test directories) for testing purposes.
I've come across problems with a number of tests where paths are not predictable.
E.g. file is created in `/var/folders/xxx`, but ptvsd/pydevd **sometimes** returns paths prefixed with `/private`. 

Yes both paths point to the same directory, but that doesn't help testing.
Also, its too messy having to implement work arounds (I've tried supplying paths with `/private/var/folders` that doesn't work either (as mentioned **sometimes** ptvsd/pydev resolves path to contain `private` - guess this is some OS thing).

Anways, long story short, there are number of issues and some tests must have reliable paths (e.g. identifying just my code relies on this)

**Comment by karthiknadig** [comment]
Agree with this.
