### ISSUE TITLE
Update VSTS to use released 3.7

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#558]

**Comment by d3r3kk** [comment]
Will take a look today and see if it's on there yet...

**Comment by d3r3kk** [comment]
3.7.0b2 is the latest version of Python supported on Windows & Linux machines. (Actually, I had trouble determining the latest version on Windows!). 3.6 is the last version available on Mac as well.

We need to either wait until Python tool support is advanced on the VSTS agent, or switch to a PyEnv solution as we've done on the vscode-python extension.

**Comment by DonJayamanne** [comment]
@d3r3kk
> 3.6 is the last version available on Mac as well.

Do you mean to say 3.6 is the latest on Windows, Mac and Linux?

> We need to either wait until Python tool support is advanced on the VSTS agent

Can we ping the team responsible for this task, or get an ETA for this.

**Comment by d3r3kk** [comment]
Sorry for not being super clear...
- 3.6 is the latest on Mac. 
- 3.7.0b2 is the latest on Windows and Linux.

> Can we ping the team responsible...
Certainly! Who is that team? Perhaps I can reach out the the generic VSTS mailing list and ask for some dates, but I've not got an immediate contact into that team at this time.
