### ISSUE TITLE
Breakpoints not working with remote debugging with handled exceptions

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#581]
## Environment data

- PTVSD version: Master
- OS and version: N/A (but tested on Windows)
- Python version (& distribution if applicable, e.g. Anaconda): XXX
- Using VS Code or Visual Studio: VSC
- Though this is remote debugging, everything is local, both debugger and program

## Actual behavior
Debugger does not break at breakpoints when there's a handled exception.
 
## Expected  behavior

Debugger should break at breakpoints.

This used to work in `4.1.1a5`

## Steps to reproduce:
* Start the following code for remote debugging:
```python
import time

import ptvsd
ptvsd.enable_attach()

for i in range(1000):
    time.sleep(1)
	print(i)
	try:
		raise ArithmeticError()
	except Exception:
		pass
```
* Go into VSC
* Ensure the settings in `Breakpoints` of VSC are as follows (default):
[ ] Raised Exceptions
[x] Uncaught Exceptions
* Attach the debugger (for remote debugging)
* Observe how debugger breaks on the exception (issue reported #580)
* Add a breakpoint to the line `time.sleep(1)`
* Hit continue button
* Breakpoint is not hit

**Comment by karthiknadig** [comment]
Does not repro on Windows or Linux.

**Comment by DonJayamanne** [comment]
Please confirm that you can replicate it on Windows

**Comment by fabioz** [comment]
This is the same thing as #580 (that exception is considered unhandled even though it's handled because it's in the topmost frame during a remote attach), which is also probably why @karthiknadig is not being able to reproduce (it depends on whether it was started with the `-m` switch or not).

You can confirm that by putting the code inside a method:

```
import time

import ptvsd
ptvsd.enable_attach()

def main():
    for i in range(1000):
        time.sleep(1)
        print(i)
        try:
            raise ArithmeticError()
        except Exception:
            pass

main()
```
