### ISSUE TITLE
Retry Tests

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#597]
Over the past few days I've been fixing some issues in the tests.
One issue that I have managed to fix to a great degree is `connection timeouts`.

Here are some of the issues that have been resolved:
* Attempting to connect to socket server even before socket server has started
    * Solution - Wait for socket server to start (check if port is used)
* Attempting to start socket server when port is still in use
    * Solution - Wait for port to be free
* Socket server was not killed if tests fail. This results in cascading effect of other tests failing due to connectivity issues.

Now, in-spite of the numerous fixes, I've found that we're still getting some connection timeout errors. 
Restarting the tests (closing PR and opening it again) fixes it.

**Solution (actually a work around):**
* Add a `retry` decorator for some tests.
* This only applies to the system tests.

I know this is a work around, but I don't want to spend too much more time on this. I know @ericsnowcurrently too spent a lot of time in the past trying to resolve similar issues on Travis.

/cc @ericsnowcurrently @karthiknadig @int19h

**Comment by karthiknadig** [comment]
This was with regard to how we ran tests earlier. This is not seen anymore.
