### ISSUE TITLE
Debugger not terminating when terminal is closed

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#602]
## Environment data

- PTVSD version: Master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio: VSC

## Actual behavior

Close the terminal does not end debugger session in VSC

## Expected  behavior

Debugger should terminate when closing the terminal

## Steps to reproduce:
1. Start a python program
1. Close the terminal (I believe this is the SIGHUP signal)
1. Watch out the debug toolbar is still visible in VSC

Kind of a regression of https://github.com/Microsoft/ptvsd/issues/128
The problem is PTVSD dies before being able to receive the `disconnect` request.
Related to https://github.com/Microsoft/ptvsd/issues/530 (same commit introduced these two issues)

**Comment by karthiknadig** [comment]
@DonJayamanne This looks platform specific. Did not repo on windows. Does this still occur?

**Comment by DonJayamanne** [comment]
No longer an issue
