### ISSUE TITLE
Stopping debugger in VSC does not terminate python program

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#607]
## Environment data

- PTVSD version: Master
- OS and version: N/A
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio:VSC

## Actual behavior

Stopping debugger does not stop python program
(currently there's a dead lock in PTVSD, see #530)

## Expected  behavior

Python program should terminate

## Steps to reproduce:
* This will have to be tested in PTVSD itself.
* Currently we have a work around in VSC that will kill the python process if it doesn't die in a timely manner

Related to https://github.com/Microsoft/ptvsd/issues/530

## Note, currently we have a work around in VSC, however the underlying bug in PTVSD must be fixed.

**Comment by gramster** [comment]
Fixed in new adapter.
