### ISSUE TITLE
Source references not working

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#610]
## Environment data

- PTVSD version: master
- OS and version: windows to windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VSC

## Actual behavior

Pausing while using remote only file (no path mapping) will bring up:
![image](https://user-images.githubusercontent.com/3840081/42406222-d3f69c9e-8157-11e8-97b1-844c82ea57e8.png)

## Expected  behavior

Should use source reference to pull the remote file

### On remote machine:
1. Create this file `remote_test.py`:
```python
import time
import ptvsd

ptvsd.enable_attach()

i = 0
while True:
    print(i)
    time.sleep(1)
    i += 1
```
2. Ensure port `5678` has access for inbound connections.
3. run `py -3.7 remote_test.py`

### On dev machine:
1.  Use following launch config:
```json
        {
            "name": "PyExp: Attach (Remote)",
            "type": "pythonExperimental",
            "request": "attach",
            "port": 5678,
            "host": "<remote-pc-name>",
            "logToFile": true
        },
```
2. Select `PyExp: Attach (Remote)` to attach.
3. Hit pause after attaching.

**Comment by DonJayamanne** [comment]
@karthiknadig 
This is the PR i was referring to https://github.com/Microsoft/ptvsd/pull/533
See comment here https://github.com/Microsoft/ptvsd/issues/473#issuecomment-401464260

**Comment by DonJayamanne** [comment]
@karthiknadig 
As suspected, #533 broke this. In hindsight we shouldn't have merged the PR without testing this.

**Comment by DonJayamanne** [comment]
@ericsnowcurrently @karthiknadig 
There are a number of problems that are contributing to this issue.
I'll address the first item.

* `WINDOWS_CLIENT` is being set incorrectly
In `wrapper.py` we initialize a `debugOption` named `WINDOWS_CLIENT`.
Based on the original code, the default value of `WINDOWS_CLIENT` was `False`. The existence of the item `WindowsClient` would turn on the value for `WINDOWS_CLIENT`.
https://github.com/Microsoft/ptvsd/blob/master/ptvsd/wrapper.py#L730

Now, VSC is NOT sending this value, hence the value is expected to be false.

However, this is not the case, changes have been subsequently introduced to change this behavior. https://github.com/Microsoft/ptvsd/blob/master/ptvsd/wrapper.py#L797 

@ericsnowcurrently, I'm not sure why this was done, please could you try to cast your mind back to this change. I'm more than happy to revert this bug, but I have no idea why this was done?

**Comment by fabioz** [comment]
One thing from a quick look at the code is that CMD_LOAD_SOURCE was fixed on `pydevd` to convert the path to the server properly, but inside `ptvsd.wrapper.VSCodeMessageProcessor.on_source` it already used the private API to do a translation -- although it's probably not the culprit here it's an inconsistency added after #533 was merged.

**Comment by DonJayamanne** [comment]
@fabioz	I can see that #533 addresses a few issues we had in the past.
I think I've figured out what's going on, two fold, a bug at our end and we need to account for upstream pydevd changes (#533).

**Comment by fabioz** [comment]
@DonJayamanne great, if you want me to take a look at something on my end, please let me know... 

Right now I'm taking a look at #72, but I guess it's not that critical for a release and will still need more work on ptvsd to make it work, so, if you want to assign me some bug to take a look (even if it's on ptvsd and not pydevd), please let me know (as a note, it's actually already EOD for me today, so, I'll check it at Wednesday)

**Comment by karthiknadig** [comment]
Note path mapping also has an issue:
This works:
```json
"pathMappings": [
{"localRoot": "C:\\GIT\\pyscratch", "remoteRoot": "~/GIT"}
],
```

But this does not:
```json
"pathMappings": [
{"localRoot": "${workspaceFolder}", "remoteRoot": "~/GIT"}
],
```
This is the error i see:
![image](https://user-images.githubusercontent.com/3840081/42475757-725d8a62-8380-11e8-803a-8e6ed26bd0f6.png)
