### ISSUE TITLE
Break on Thrown Exception displays Unhandled Exception dialog

### ISSUE THREAD

**Issue by zooba** [Microsoft/ptvsd#62]
Screen:
![image](https://user-images.githubusercontent.com/1693688/36126064-af4af268-100b-11e8-8c61-606448975f2e.png)
![image](https://user-images.githubusercontent.com/1693688/36126071-bb753fda-100b-11e8-88a7-1718a38740f7.png)

This popup is the one that should appear when the checkbox is _not_ selected (currently there is no popup in that case). There's different language and options on the correct popup for this case.

**Comment by karthiknadig** [comment]
This is fixed via #149
![image](https://user-images.githubusercontent.com/3840081/37062112-5cd2f62a-214a-11e8-8a18-d28682f5c3d1.png)
