### ISSUE TITLE
Remote debugging crashes program when output is redirected

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#623]
## Environment data

- PTVSD version: Master
- OS and version: Client - Mac, Remote - Windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio:VSC

## Actual behavior

User program crashes and terminates.

## Steps to reproduce:
1. On widows start the following program:
```python
import time
import ptvsd

ptvsd.enable_attach()

i = 0
while True:
    print(i)
    time.sleep(0.1)
    i += 1
```
2. On a Mac, attach to the above remote debug session from VSC
3. Once attached watch the output being printed out to the console window
4. Eventually it will crash

## Output from console
```
0
1
2
3
4
5
6
7
8
9
10
11
12
Traceback (most recent call last):
  File "remote_dbg.py", line 10, in <module>
    print(i)
  File "C:\Development\VSCode\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_io.py", line 30, in write
    r.write(s)
IOError: [Errno 0] Error
```

I believe this is caused by the commit 8427816

/cc @karthiknadig @fabioz

**Comment by karthiknadig** [comment]
I tried this several times from Windows (VSC) to Linux (remote), Did not repro.

**Comment by karthiknadig** [comment]
Tried this the other way around Linux (VSC) to Windows (remote), Did not repro.

**Comment by DonJayamanne** [comment]
Interestingly, I'm no longer able to replicate this issue.
Closing for now.
