### ISSUE TITLE
Presence of signal handlers in user code interfers with debugger

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#629]
## Lets not work on this for now.
To be done after all P* issues are resolved.

In python we can only have one handler for a signal.
Currently we have signal handlers getting registered in PTVSD.

If the user code has a signal handler, then that will overwrite the signal handler in PTVSD.

This causes all sorts of other issues with graceful termination of the debugger.

**Comment by ericsnowcurrently** [comment]
FYI, solving this will probably involve monkey-patching signal.signal with a wrapper func that preserves our signal handler, while somehow also respecting the provided one.

**Comment by karthiknadig** [comment]
In the `dbg_adapter_refactor` branch `ptvsd` no longer registers signal handlers. `pydevd` uses signal handlers for PyQT support, but it has always done that. Closing this since this particular issue was specific to ptvsd singnal handlers.
