### ISSUE TITLE
Failing test on Windows Agent on VSTS

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#630]
/cc @karthiknadig 

<img width="784" alt="screen shot 2018-07-10 at 3 33 39 pm" src="https://user-images.githubusercontent.com/1948812/42541300-a9629a30-8456-11e8-8a50-81f93f99f915.png">

**Comment by karthiknadig** [comment]
@DonJayamanne Any idea why the path is relative and not absolute?

**Comment by DonJayamanne** [comment]
Hope you have noticed that in both cases (expected value and actual value) we're dealing with relative paths.
