### ISSUE TITLE
Create test plan for every release of PTVSD

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#635]
Prior to every release of PTVSD, we'll need to ensure certain tests have been run manually, and tests that cannot be automated in CI.

* Debugging and running file to completion in VSC in a **Terminal**  
    * Testing issues #633 #618, #656, #657  
    * Create a python file with a simple `print("Hello World")`  
    * Debug in VSC without any breakpoints  
    * Confirm:
    * [ ] Program runs to completion without any errors
    * [ ] The only message displayed in terminal is `Hello World`
    * [ ] The message `Terminated 15` is not displayed in the terminal
    * [ ] Works on Mac (3.6 is mandatory)
    * [ ] Works on Linux
    * [ ] Works on Windows (2.7 is mandatory)
* Remote debugging
    * [ ] Testing issue #611
    * [ ] Run a python program on a remote machine with remote debugging enabled using `ptvsd.enable_attach`
    * [ ] Confirm we are able to attach from another machine

**Comment by DonJayamanne** [comment]
@karthiknadig 
I'll update this with mandatory items, and we'll need to create a PRE_RELEASE_INSTRUCTIONS.md or similar file that will be part of PTVSD repo.
This way we'll never forget it, or that's the plan.
This list only contains tests that cannot be automated.

**Comment by asouini** [comment]
can i add to "remote debugging" section : to confirm that breakpoints are set

**Comment by gramster** [comment]
Subsumed by better unit tests.
