### ISSUE TITLE
Local variables not shown when in async function running in trio event loop

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#638]
## Environment data

- PTVSD version: Master
- OS and version: N/A
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio:N/A

## Actual behavior

Local variables not shown when in async function running in trio event loop

## Actual behavior

When running an async function on the Trio event loop, and when stopping on a breakpoint inside the async function, local variables are not shown.

![billede](https://user-images.githubusercontent.com/10992982/42292252-6d8e5212-7fd1-11e8-9bc7-4e85aed0a7ab.png)

## Expected  behavior

In the example, local variables should show sleep_time: 5

## Steps to reproduce:

    import trio

    async def main():
        sleep_time = 5
        # set breakpoint below
        print('Going to sleep')
        await trio.sleep(sleep_time)
        print('Woke up')

    some_text = 'Hi!'

    trio.run(main)

    print(some_text)

## Logs
Output of Terminal pane:
```
andersa@Kubuntu-N73JF:~/python/async_debugging_experimental$ cd /home/andersa/python/async_debugging_experimental ; env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" "PYTHONPATH=/home/andersa/.vscode/extensions/ms-python.python-2018.6.0/pythonFiles/experimental/ptvsd" /home/andersa/.local/share/virtualenvs/async_debugging_experimental-zTVpGFmI/bin/python -m ptvsd --host localhost --port 38433 /home/andersa/python/async_debugging_experimental/test.py
```

## Notes:
* I can replicate this on my Mac (Python 3.6)
* Reported upstream in VS Code https://github.com/Microsoft/vscode-python/issues/2093

**Comment by fabioz** [comment]
I'll investigate this (pydev itself doesn't show it, so, should be `upstream-pydevd`).

**Comment by DonJayamanne** [comment]
@fabioz lets leave this until we've resolved other critical issues. 
I'm not too concerned about this just yet.

**Comment by fabioz** [comment]
@DonJayamanne seems go to me... right now, this means I'll go back to #72 (note that it's already close to EOD for me, so, I'll probably only work on it next Monday).

Still, if #580/#581 is deemed important enough to have a fix (even if it means parsing python code or analysing bytecode), or there's some other critical I missed, please let me know.

**Comment by karthiknadig** [comment]
Does not repro in master.
![image](https://user-images.githubusercontent.com/3840081/52099547-8776ca80-2588-11e9-975a-14fa356953b5.png)
