### ISSUE TITLE
Using os.kill() means the atexit handler is not triggered, which means disconnect won't work right (since it is triggered via at exit)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#642]
#538 may have resolved this issue, however we didn't have any tests to prove this.
#538 introduced two new bugs (#633, #618), and @Donjayamanne reverted it in #634

If we are to address this issue then:
* Prove there's a bug that needs to be address
* Introduce tests to validate such a change (and these tests must fail if the fix is reverted)

/cc @ericsnowcurrently @karthiknadig

**Comment by DonJayamanne** [comment]
Need to identify whether this is a regression.

**Comment by karthiknadig** [comment]
This should get addressed by #1452
