### ISSUE TITLE
Importing ptvsd is slow, and this slows down tests

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#648]
## Environment data

- PTVSD version: Master
- OS and version: N/A
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio:N/A

## Actual behavior

* Importing PTVSD is slow
* Side effects:
    * Spinning up debugger is slow
    * Tests are slow

## Expected  behavior

* Importing PTVSD should be quick

## Steps to reproduce:
1. Open terminal
2. `python`
3. `>>> import ptvsd`

Note:
The delay is in `ptvsd/_vendored/force_pydevd.py` (importing all of pydevd modules takes over 0.5 secs)

Not sure whether this is the source of delays when debugging in Conda environments in VS.

/cc @karthiknadig @huguesv

**Comment by fabioz** [comment]
As a note, `pydevd` itself needs to import things when it starts up and lazy loading is not ideal for the debugger (there are some places where lazy loading cannot happen inside the debugger and there's always the chance that the user removes the debugger from `sys.path`).

Still, what I recently did to speed up the `pydevd` test cases is using `pytest-xdist` to run tests in parallel and it gives nice benefits -- in my machine, a sequential run takes almost 3 minutes, running with 8 workers -- which is the number of cores with hyperthreading -- takes 40 seconds -- although this is quite dependent on the number of cores available on CI).

`pytest` itself does support running `unittest` test cases, so, initially it could be used to just run the tests (albeit if the pytest runner is used, I'd see benefits on using some of its features later on too).

**Comment by karthiknadig** [comment]
We have added some mitigation via xdist. Closing this for now. Please reopen if this continues to problem.
