### ISSUE TITLE
Tool tips try to evaluate invalid expressions

### ISSUE THREAD

**Issue by zooba** [Microsoft/ptvsd#65]
![image](https://user-images.githubusercontent.com/1693688/36126945-c3813694-100f-11e8-910a-f731eb366601.png)
![image](https://user-images.githubusercontent.com/1693688/36126951-d16d9da6-100f-11e8-8c1f-0cfa1443d4e6.png)

We should probably not return anything when a `SyntaxError` is raised while evaluating, and also do the extra effort to make sure that we don't evaluate function calls here.

**Comment by karthiknadig** [comment]
fixed by #168
