### ISSUE TITLE
Debugger breaks into exception more than once

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#653]
## Environment data

- PTVSD version: Master
- OS and version: N/A
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio:VSC

## Actual behavior

Debugger breaks at exceptions more than once

## Expected  behavior

Should break on exceptions once.

## Steps to reproduce:
**Scenario 1**
1. Open VSC ensure breakpoint settings are as follows:
* [ ] Raised Exceptions
* [x] Uncaught Exceptions
2. Debug following python code:
```python
raise AttributeError('1234')
```
3. Debugger breaks at exception
4. Click continue
5. Debugger breaks at exception, when it shouldn't
4. Click continue, and program completes
6. Debugger breaks at exception twice, instead of once

**Scenario 2**
1. Open VSC ensure breakpoint settings are as follows:
* [x] Raised Exceptions
* [x] Uncaught Exceptions
2. Debug following python code:
```python
raise AttributeError('1234')
```
3. Debugger breaks at exception
4. Click continue
5. Debugger breaks at exception, when it shouldn't
4. Click continue
5. Debugger breaks at exception, when it shouldn't
4. Click continue, and program completes
6. Debugger breaks at exception three times, instead of once

Issue introduced in 8c4dfdc526ffe2dade3a420db8c632a01527a775, [Fix issue where additional info could be None (#529)](https://github.com/Microsoft/ptvsd/pull/529)

/cc @karthiknadig @fabioz

**Comment by fabioz** [comment]
For the `unhandled` case, this is happening because `pydevd` is not accounting that it may be embedded with a different runner, so, it stops on the proper place at `pydevd` but then proceeds going up the stack and stops once more where `ptvsd` is calling `pydevd` and there's no back frame.

Investigating how to deal with that.

**Comment by fabioz** [comment]
Note: I've created a pull request for the case where unhandled exceptions were reported twice (https://github.com/Microsoft/ptvsd/pull/671)

Still, there's still an issue where the debugger may handle the same exception once considering that it's unhandled and another when it's considered handled (so, in the scenarios above, it should hit the exception breakpoint once in the first scenario and twice in the second).

I'm not sure how much of this is a bug or a feature given that the user did ask to report on handled and unhandled exceptions (so, it's reporting the first time when it's caught and a second time on postmortem mode).

**Comment by karthiknadig** [comment]
I agree with @fabio.
* If **only** `Raised Exceptions` is selected, it should hit once (where it was raised, and not during postmortem)
* If **only** `Uncaught Exceptions` is selected, it should hit once (only in postmortem)
* if **both**  `Raised Exceptions` and `Uncaught Exceptions` are selected, it should hit twice (where it was raised and during postmortem)

This is the behavior as seen after merging #671.

**Comment by DonJayamanne** [comment]
> if both Raised Exceptions and Uncaught Exceptions are selected, it should hit twice (where it was raised and during postmortem)

I disagree, this is not how it should behave. If it is, then we need to all be on the same page why this decision is being made - i.e. due to technical challenges. Else its the wrong behavior. As a user i would not want to break on the same exception twice, it makes no sense.

**Comment by DonJayamanne** [comment]
Then again, that makes sense. So, I agree. Its fine. Thanks
