### ISSUE TITLE
New version for Tuesday 17th

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#658]
@karthiknadig can we get a new version published on PyPi for the next version of VSC.
I'd like a new version of the debugger to go with the next version of VSC Extension.
Note: The debugger will still be labeled `experimental`.

We plan on publishing a new version on Wednesday, so having a new version on Tuesday 17th would be great.

**Comment by karthiknadig** [comment]
I will prepare a release after taking #660

**Comment by karthiknadig** [comment]
Done. https://pypi.org/project/ptvsd/4.1.1a10/
