### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by johnygomez** [Microsoft/ptvsd#659]
## Environment data

- PTVSD version: 3.0.0
- OS and version: MacOS 10.13.5 (Local), Ubuntu 16.04 LTS (Remote)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.3-local, 3.6.5-remote
- Using VS Code or Visual Studio: VSCODE

## Actual behavior

Remote debugger exits with: `Debug adapter process has terminated unexpectedly`
Error trace:
```
Error: Uncaught, unspecified "error" event. (Unhandled command 'cg')
    at PythonProcessCallbackHandler.emit (events.js:166:17)
    at PythonProcessCallbackHandler.HandleIncomingData (/Users/gomez/.vscode/extensions/ms-python.python-2018.6.0/out/client/debugger/PythonProcessCallbackHandler.js:87:22)
    at PythonProcess.HandleIncomingData (/Users/gomez/.vscode/extensions/ms-python.python-2018.6.0/out/client/debugger/PythonProcess.js:156:30)
    at Socket.socket.on (/Users/gomez/.vscode/extensions/ms-python.python-2018.6.0/out/client/debugger/DebugServers/RemoteDebugServer.js:50:40)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
Error: Uncaught, unspecified "error" event. (Unhandled command 'cg')
```

## Expected  behavior

Debugger should stop on breakpoint

## Steps to reproduce:
1. Setup python remote debugging according to tutorial.
2. Used `runpy` to run my module from debug script

**Comment by DonJayamanne** [comment]
> Setup python remote debugging according to tutorial.

* What tutorial?

* Are you using the Experimental debugger?

* Please provide the contents of your `launch.json`

**Comment by johnygomez** [comment]
> What tutorial?

https://code.visualstudio.com/docs/python/debugging#_remote-debugging

> Are you using the Experimental debugger?

Is it on by default? I don't remember setting anything like that

> Please provide the contents of your launch.json
```
"configurations": [
    {
      "name": "Attach (Remote Debug)",
      "type": "python",
      "request": "attach",
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/data/",
      "port": 3000,
      "secret": "secret",
      "host": "192.168.59.204",
    },
```

**Comment by karthiknadig** [comment]
Can you try this using 4.1.1a11? This repo is for `ptvsd>=4.*`. Reopen this if you run into the same issue with the experimental debugger:
```json
        {
            "name": "Attach (Remote Debug)",
            "type": "pythonExperimental",
            "request": "attach",
            "port": 3000,
            "host": "192.168.59.204",
            "pathMappings": [{
                "localRoot": "${workspaceFolder}",
                "remoteRoot": "/data/"
            }]
        },
```

**Comment by johnygomez** [comment]
@karthikananth experimental debugger seems to be working, but it seems it's not breaking on breakpoints out of main thread. Actually it seems that execution stops, but debugger just doesn't jump into breakpoint. Do you have any clue what's wrong? I think this was working for me on 3.0.0

**Comment by karthiknadig** [comment]
@johnygomez  Can you create a new bug with code to reproduce this issue?
