### ISSUE TITLE
Cannot see dunder members in Watch window

### ISSUE THREAD

**Issue by zooba** [microsoft/ptvsd#66]
![image](https://user-images.githubusercontent.com/1693688/36127060-4d492878-1010-11e8-8763-cf80acfb1390.png)

Actual members:
![image](https://user-images.githubusercontent.com/1693688/36127090-7ac004f2-1010-11e8-922e-ed5694e18124.png)

**Comment by DonJayamanne** [comment]
@donjayamanne to investigate whether this is an issue in VSC as well.

**Comment by DonJayamanne** [comment]
In VSC dunder members are not displayed in the old nor new debugger.
Hence I wouldn't consider this an issue in VSC, this change would be considered an enhancement for VSC.

**Comment by gramster** [comment]
Closing; no upvotes and old.
