### ISSUE TITLE
Incorrect number of threads displayed when debugging in VSC

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#661]
## Environment data

- PTVSD version: Master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio:VSC

## Actual behavior

Two threads displayed in call stack.

## Expected  behavior

Single thread to be displayed

## Steps to reproduce:
1. Debug a simple python hello world
2. Optionally add a breakpoint
3. Notice there are two threads displayed in the stack trace window

@karthiknadig Please confirm you are able to replicate this as well.
Regression as I'm certain we fixed this at some point in the past.

<img width="525" alt="screen shot 2018-07-16 at 8 45 02 am" src="https://user-images.githubusercontent.com/1948812/42768577-c13ef892-88d4-11e8-841f-9eebe6bd3f21.png">

**Comment by karthiknadig** [comment]
No. Does not repro on Windows or Linux.

**Comment by fabioz** [comment]
@DonJayamanne since you can reproduce it there, can you do print the live/threads and stack traces (in that program)?

You should be able to declare it in the module and call it in the interactive console while stopped in the breakpoint.

Code to dump threads below:

```
def dump_threads():
    import threading
    import sys
    import traceback
    thread_id_to_name = {}
    try:
        for t in threading.enumerate():
            thread_id_to_name[t.ident] = '%s  (daemon: %s)' % (t.name, t.daemon)
    except:
        pass
    
    stack_trace = [
        '===============================================================================',
        'Threads running',
        '================================= Thread Dump =================================']
    
    for thread_id, stack in sys._current_frames().items():
        stack_trace.append('\n-------------------------------------------------------------------------------')
        stack_trace.append(" Thread %s" % thread_id_to_name.get(thread_id, thread_id))
        stack_trace.append('')
    
        if 'self' in stack.f_locals:
            sys.stderr.write(str(stack.f_locals['self']) + '\n')
    
        for filename, lineno, name, line in traceback.extract_stack(stack):
            stack_trace.append(' File "%s", line %d, in %s' % (filename, lineno, name))
            if line:
                stack_trace.append("   %s" % (line.strip()))
    stack_trace.append('\n=============================== END Thread Dump ===============================')
    sys.stderr.write('\n'.join(stack_trace))
```

**Comment by DonJayamanne** [comment]
Lol, unable to replicate now.
Will leave this open for a while.
