### ISSUE TITLE
Revert PR #475 and find a different solution for Issue #459

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#672]
PR #475
Issue #459

**Comment by karthiknadig** [comment]
I have an alternate implementation for wait-on-exit (see here https://github.com/karthiknadig/ptvsd/commit/93ec1f99b54e073b5906691d9989ff49400b5aae). Let me know what you think.

**Comment by karthiknadig** [comment]
Do we still need this?

**Comment by DonJayamanne** [comment]
No we don't
