### ISSUE TITLE
Multi threaded debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#688]
@karthiknadig 
What's the status of multi threaded debugging.
I remember there were some issues related to multi threaded debugging.
E.g. suspending all threads, etc.

We might want to solve that before looking at multi process debugging.

**Comment by karthiknadig** [comment]
Suspend policy feature was checked in yesterday. With that I think we have all of the pieces we need to do this. Some work is pending on `ptvsd` side, like, enabling the suspend-all policy, updating pause and continue commands to always suspend all threads, etc/

**Comment by DonJayamanne** [comment]
> Some work is pending on ptvsd side, like, 

Do we have an issue to track this?
If yes, then please close this issue.

**Comment by karthiknadig** [comment]
#72 tracks the works for this item.
