### ISSUE TITLE
Auto-detect root if remote root is not provided

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#691]
Auto-detect root when using `pathmappings` with no remote root. `ptvsd` v3 detects root folder for path mappings.

**Comment by DonJayamanne** [comment]
@karthiknadig Why is this in the icebox.
We need this for VS Code (https://github.com/Microsoft/vscode-python/issues/2493)

**Comment by karthiknadig** [comment]
We had discussed offline that this by itself is not a good solution. 
* First, there is no fallback mechanism, i.e, we either use `pathMappings` or use source reference. There is no middle ground. So we need to a spec for this.
* Second, If we want to use auto detection we may have to spec it another way. The original idea was to go up the directory chain till we find a dir with no `__init__.py`, and treadt that dir as the root. But with name spaces packages that approach won't work.

**Comment by karthiknadig** [comment]
A thing that we could do is treat remote current directory as the root. For this VSC would always pass `pathMappings` on attach with `"localRoot": ${workspacefolder}, "remoteRoot": "."'`. On the debugger side we convert '.' to absolute path and set the mappings in `pydevd`. This should work for for common cases. It is simpler to implement.

Downsides: No fallback (no different than current situation).

**Comment by DonJayamanne** [comment]
@karthiknadig @int19h  
Please can we bump up the priority for this issue.
I've done the same at our end, to ensure this gets into the next release.

**Comment by gramster** [comment]
We cover common cases and allow for path mapping so there are solutions.
