### ISSUE TITLE
When remote debugging VS Code will spawn a second read-only copy of the file in which I have set breakpoints. The debugger interacts with that file.

### ISSUE THREAD

**Issue by JeffHanna** [Microsoft/ptvsd#693]
## Environment data

- PTVSD version: 4.1.1a10
- OS and version: 1703 (OS Build 15063.909)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.5.2 (default, Dec  1 2016, 18:54:08) [MSC v.1900 64 bit (AMD64)] on win32
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When a remote debug session to a local .exe with Python script support hits a breakpoint VS Code will load a second read-only copy of the file with the breakpoint and highlight the line in that file.  No breakpoints are visible in the newly loaded read-only file This behavior only occurs when debugging by remote attach.

## Expected  behavior

The original file would be used by the debugger

## Steps to reproduce:
1. Set a breakpoint in a file that is used within a program you can remote-attach to.
2. Run that program and attach VS Code for remote debugging.
3. Exercise that program such that the line with the breakpoint is executed.

**Comment by JeffHanna** [comment]
We didn't, as we run our Python tools directly out of the local P4 depot on the user's machine (this is all for an in-house developed world editor for game development). A colleague just tried putting ${workspaceFolder} in for both the localRoot and remoteRoot  entries and the problem went away.

Thanks!

**Comment by jkassismz** [comment]
This is happening for me using a local configuration...
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PyBot Local",
            "type": "python",
            "request": "launch",
            "console": "internalConsole" ,
            "cwd": "/projects/pybot",
            "program": "/projects/pybot/src/mz/bot/__main__.py",
            "gevent": true,
            "justMyCode": false
        },
    ]
}```

**Comment by int19h** [comment]
Likely another manifestation of https://github.com/microsoft/ptvsd/issues/1480#issuecomment-497392812

@jkassismz, can you try adding:
```json5
"pathMappings": [],
```

and see if that helps?
