### ISSUE TITLE
Experimental debugger, step into seems to just continue

### ISSUE THREAD

**Issue by bob-white** [Microsoft/ptvsd#699]
## Environment data

- PTVSD version: 4.1.1a10
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Embedded Python 3.5 
- Using VS Code or Visual Studio: VSCode

## Actual behavior
When using the experimental debugger, attaching to a local process, I can't seem to use the step into command.
Trying to step into code (F11) seems to behave just like continue (F5).
This does not happen when running code in the integrated terminal.

## Expected  behavior

I would be able to step into code properly.

## Steps to reproduce:
1. Attach to a python process
2. Hit a breakpoint
3. Use step into

**Comment by karthiknadig** [comment]
There were few issues with just-my-code,( i.e., "debugStdlib": false in launch config). Try this with ptvsd **v4.1.1**. If this continues to occur, please reopen and provide code to repro.
