### ISSUE TITLE
Create a whole suite of tests for enable_attach without using wait_for_attach

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#718]
Currently almost all system tests use `wait_for_attach` due to a bug in `enable_attach` the simulated the same behavior of `wait_for_attach`.

**Comment by karthiknadig** [comment]
#740 adds couple cases for using `enable_attach` without `wait_for_attach`

- `enable_attach` with `is_attached` and `break_into_debugger`
- `enable_attach` and `break_into_debugger`

**Comment by karthiknadig** [comment]
`break_into_debugger` tests and `disconnect` system tests cover this
