### ISSUE TITLE
Overall VSTS CI Status is green even when tests fail

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#720]
/cc @karthiknadig I thought this was fixed.

**Comment by karthiknadig** [comment]
Do we want to block on DAP json schema changes as well?

**Comment by karthiknadig** [comment]
@d3r3kk Can we enable fail on non zero exit code?

**Comment by d3r3kk** [comment]
We can do whatever you like.
Once all the tests run successfully I can turn the fail-on-test-failure stuff. I've been waiting for them to all run green before turning that on.
Here's what is still allowed to fail:

- [ ] DAP verification. This was an initial requirement, that it not fail the build but just notify. We can change this anytime you like.
- [ ] All **macOS Test Run** tests.
- [ ] All **Windows Test Run** tests.
- [ ] All ** Linux Test Run** tests.

From the history, I'm not seeing a lot of green `master` builds yet:
![image](https://user-images.githubusercontent.com/11466735/43789453-dac72d28-9a24-11e8-8d6c-2c9117524b59.png)


So I don't think we are ready to turn on warnings as failures across the board quite yet.

Looking at the last 6 master builds I don't see consistent green builds for any OS either. Perhaps we concentrate on one at a time, and turn each on as they get green?

**Comment by d3r3kk** [comment]
That is, unless you fine folks are ready to just turn the failures on across the board and halt any development until they are all running successfully? It's a bold move, but if your team is behind it I am all for it as well.

**Comment by DonJayamanne** [comment]
> ard and halt any development until they are all running successfully? It's a bold move, 

I vote for this. @karthoknadig will want this too. That's two out of two PTVSD devs!! 😁.
This way nothing slips, and we can use our judgement to merge PRs, rather than always ignoring items. Also an incentive to fix breaking/flaky tests.

**Comment by karthiknadig** [comment]
Yes. Please go ahead block on failing tests.

**Comment by d3r3kk** [comment]
Done.
