### ISSUE TITLE
Connect, launch, and debug

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#730]
This is a feature request from feed back:

> Always I think, why start debugging can't run script on remote server? Now to start remote debug I must:
> 1) Run script in my Docker from attached Bash
> 2) Script wait to attach debugger
> 3) Run debugger in VS Code locally
> 4) Repeat when any changes made in script
> Why when I run debugger locally I can't via SSH (or any service) automatically run my Python script like when I debug my Python scripts locally without ptvsd library?

**Comment by DonJayamanne** [comment]
I don't understand the work flow (requirement)

**Comment by karthiknadig** [comment]
Not a `ptvsd` issue. Not enough info.
