### ISSUE TITLE
Suspend/resume all user threads command in pydevd

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#732]
@fabioz Would it be possible to provide suspend all and resume all commands Or just extend the existing commands if no thread id is provided then it means suspend all or resume all?

**Comment by fabioz** [comment]
Yes, that should be possible.

**Comment by fabioz** [comment]
Just as a note, I already have a fix for this, but it has conflicts with other pull requests I have open:

https://github.com/Microsoft/ptvsd/pull/765
https://github.com/Microsoft/ptvsd/pull/767

So, when those are merged I'll provide a pull request for this one.
