### ISSUE TITLE
Debugger unusably slow

### ISSUE THREAD

**Issue by Lobotomik** [Microsoft/ptvsd#741]
## Environment data

- PTVSD version: 3.2.1
- OS and version: Windows 10 Pro
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 2.7.13 (64b)
- Using VS Code or Visual Studio: VS Code

## Actual behavior
I step through my program and feels sluggish compared to debugging the same code in Pycharm or Pydev. In some cases, a step that takes less than a second in Pycharm takes over 15 seconds in VSCode. and spins the fans into overdrive. Looping that statement a few times becomes a chore, when it is not an issue with Pycharm or Pydev.

## Expected  behavior
Stepping along my program with Visual Studio should be comparably fast to other debuggers. Some sluggishness is tolerable, but this is unusable.

## Steps to reproduce:
My program uses Numpy, Traits, Traitsui, wxPython.

I have the suspicion the debugger gets bogged down when a large(ish) array is passed as a parameter and the debugger struggles to produce a representation, whether I need it or not.

**Comment by DonJayamanne** [comment]
This repo is used to manage versions 4 and later.
Please create your issue against the vscode python repo.
https://github.com/Microsoft/vscode-python

Please ensure you have tried using the Experimental debugger, before filling the issue against the pythin extension repo.
