### ISSUE TITLE
Launching module with --nodebug breaks imports

### ISSUE THREAD

**Issue by ajpower** [Microsoft/ptvsd#745]
My project structure is 
```
demo/
  foo/
    __main__.py
    bar.py
```
`bar.py` is an empty file. `__main__.py` contains the single statement `import bar`. My `launch.json` configuration is
```
{
    "name": "Demo",
    "type": "pythonExperimental",
    "request": "launch",
    "program": "${workspaceFolder}/foo",
    "console": "integratedTerminal"
}
```

Running in debug mode causes the program to immediately terminate successfully, as expected. With `--nodebug` the program crashes with a `ModuleNotFoundError` exception complaining that there is no module named bar.

I am running `ptvsd` in VSCode with Python3.6 on Ubuntu 18.04.

**Comment by ajpower** [comment]
Fails with the same error.

**Comment by karthiknadig** [comment]
Can you try with an empty `__init__.py` file?

**Comment by ajpower** [comment]
I did, same issue.

**Comment by karthiknadig** [comment]
Can you tell me the version of `ptvsd`? I am not seeing this in master. But I want to make sure we have addressed this.

**Comment by ajpower** [comment]
I'm using 4.1.1a10, which ships with the current version of vscode.

Actually I'd like to clarify that the configuration you gave above (which `module` set instead of `program`) actually fails with and without `--nodebug`. Presumably this happens since it's trying to run something like `python -m ptvsd -m foo` which _should_ fail since bar needs to be a relative import. But with the original configurations vscode runs something like `python -m ptvsd /path/to/foo` which works fine, but `python -m ptvsd --nodebug /path/to/foo` fails with the error mention in the OP.

**Comment by fabioz** [comment]
This is not a bug -- things are working as expected.

i.e.: if you have a structure such as the one below where `demo` is the folder in the `PYTHONPATH`, you should write an import on `__main__.py` as `from foo import bar` or `from . import bar` (a single `import bar` expects the `bar` module to be on the root -- which is not the case).

```
demo/
  foo/
    __main__.py
    bar.py
```

**Comment by ajpower** [comment]
Regardless of how you feel imports should be done, the fact remains that `python foo` will execute the code without throwing an exception, as will `python -m ptvsd foo`. Passing the `--nodebug` option should break this behaviour.

Incidentally, I agree that `import bar` is a poor way to perform the import. However, projects like Django will perform imports this way e.g. when setting `DJANGO_SETTINGS_MODULE`, so this bug will break programs that ought to work.

**Comment by fabioz** [comment]
Note that it'll fail in the command line if `python -m foo` is used in plain Python, so, ideally you wouldn't write imports that way, but I agree with your point that `ptvsd` should replicate what Python does even if it means shooting yourself in the foot ;) 

-- Python itself appears to be executing `foo/__main__.py` directly (so, it'll find `bar` as a root module -- and if you do in another place an `from foo import bar` you'll have another version of the same module).
