### ISSUE TITLE
$attach command unavailable in Standard REPL/immediate

### ISSUE THREAD

**Issue by syagev** [Microsoft/ptvsd#747]
## Environment data

- PTVSD version: 15.7.18156.1-15.0
- OS and version: Windows 10 (v1803 build 17134.167)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.6
- Using VS Code or Visual Studio: Visual Studio 2017

## Actual behavior

In the interactive window the `$attach` command is not available:
![image](https://user-images.githubusercontent.com/5247438/44061254-4990751c-9f60-11e8-942c-bbee9ace33c8.png)

## Expected  behavior

The `$attach` command should be available and attach the debugger

## Steps to reproduce:
1. Create a new project from existing code
2. Create Python 3.6 env
3. Open a REPL window
4. Type `$attach`

Maybe I'm doing something wrong?

**Comment by karthiknadig** [comment]
This is a PTVS issue. Please file it here: https://github.com/Microsoft/PTVS
@huguesv FYI

**Comment by syagev** [comment]
Done. See https://github.com/Microsoft/PTVS/issues/4636
Thanks.
