### ISSUE TITLE
Namespace packages fail to import

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#748]
## Environment data

- PTVSD version: master
- OS and version: Any
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VSC

## Actual behavior

No module named foo

## Expected  behavior

Should import the package

## Steps to reproduce:
1. Create a package with this structure:
```
foo
|_ __main__.py
|_ bar.py
```
2. Use the following configuration:
```
        {
            "name": "foo",
            "type": "pythonExperimental",
            "request": "launch",
            "console": "integratedTerminal",
            "module": "foo",
            "cwd": "${workspaceFolder}",
            "env": {"PYTHONPATH": "${workspaceFolder}"}
        },
```
this is very similar to #745, however, this occurs both in debug and no debug mode.
reference: https://docs.python.org/3/reference/import.html#namespace-packages

**Comment by karthiknadig** [comment]
Namespace packages don't have `__init__.py`. `No module named foo` error is not seen when `__init__.py` is available.

**Comment by fabioz** [comment]
If this is the exact same case as #745, this isn't really a bug (the import is just not written correctly -- see: https://github.com/Microsoft/ptvsd/issues/745#issuecomment-414700314).

**Comment by fabioz** [comment]
Note that for this issue, this is what Python expects (so, it fails even without `ptvsd`) and is not a bug, unlike the case in #745, where the user is executing the file (which works on Python -- note: taking a look at that one).
