### ISSUE TITLE
Remote dbg: adding breakpoint to file that does not exist

### ISSUE THREAD

**Issue by polakovicp** [Microsoft/ptvsd#753]
## Environment data

- PTVSD version: '4.1.1a11'
- OS and version: Win 10
- remote OS: Debian GNU/Linux 8 (jessie)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.4.2
- Using VS Code or Visual Studio: VS2017 Pro, Version 15.7.5

## Actual behavior

Hi, after attaching to remote process with PTVSD, no breakpoint is hit. But in the output I see the message:
_pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/polakovic/d:\work\repositories\Forensic\ppforensics\main.py (will have no effect)_

As can be seen, win path and linux path is mixed, causing invalid BP target.
Previously I used PTVSD version 3.2 without any problems.
Thanks for the help/fix.

**Comment by karthiknadig** [comment]
Try adding `pathMappings` to your attach configuration.
```json
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/home/polakovic"
                },
            ]
```

**Comment by polakovicp** [comment]
Well, I am not using any configuration while attaching with VS2017. I read about some _launch.json_ but everything I read was applicable only for VS Code. How can I create such configuration for VS2017?

**Comment by karthiknadig** [comment]
Sorry, I read it wrong. While doing remote attaches with the new debugger VS2017 does not support path mappings yet. This feature is still a open item https://github.com/Microsoft/ptvsd/issues/248.
There are two ways you can deal with this:
**Option 1**: Use `ptvsd.wait_for_attach`, and `ptvsd.break_into_debugger` combination. This will cause VS download the source and open it up for you as a read only document. You could set the breakpoints in that file then.
```python
import ptvsd
ptvsd.enable_attach(('0.0.0.0',5678))
ptvsd_wait_for_attach()
ptvsd.break_into_debugger()

# your code
```
The down side here is that the breakpoints are not persisted.

**Option 2**: Use 'ptvsd.break_into_debugger` where ever you would want to put breakpoints. VS will download the source file like in Option 1, but you don't have to set breakpoints each time.
```python
import ptvsd
ptvsd.enable_attach(('0.0.0.0',5678))
# You could you this as well.
# ptvsd_wait_for_attach()
ptvsd.break_into_debugger()

def myfunc():
    ptvsd.break_into_debugger()
    # do something

myfunc()
```
The down side here is the debugger will break wherever `break_into_debugger` is used as long as you are connected.

**Comment by polakovicp** [comment]
Seems like break_into_debugger doesn't work. After debugger attach program continues it's execution.
`
import ptvsd
ptvsd.enable_attach()
ptvsd.wait_for_attach()
ptvsd.break_into_debugger()`

**Comment by karthiknadig** [comment]
Try Option 2 (with `wait_for_attach`). If that does not work, would it be possible to share your code or minimal repro?

**Comment by polakovicp** [comment]
Sorry I can't provide original source. But I added new file to the project called _remote_dbg.py_.

```
import ptvsd

ptvsd.enable_attach()
ptvsd.wait_for_attach()

def breakpoint():
    ptvsd.break_into_debugger()

    print("Stuff")

breakpoint()

print("More stuff")
```

Copied it to the home folder on remote server and executed:
> $ python3 ~/remote_dbg.py

After attaching to the process, Visual Studio crashes immediately.
More things:
- interpreter on remote is Python3.4 64b, local is Python3.5 64b
- connection string used is _tcp://secret@xxxxxx:5678/_, notice the "secret", but no secret phrase is passed to the _enable_attach_ method (ptvsd 4.1.1a11) (?)
- if I launch _remote_dbg.py_ locally, I get the message
![capture](https://user-images.githubusercontent.com/522894/44201125-c3d47c80-a148-11e8-8974-2ec63d41b90c.PNG)

**Comment by karthiknadig** [comment]
@fabioz even if `PATHS_FROM_ECLIPSE_TO_PYTHON` is set, from ptvsd point of view the mappings are not set. So, ptvsd will use source reference see https://github.com/Microsoft/ptvsd/blob/master/ptvsd/wrapper.py#L1549

We need to figure out why  `break_into_debugger` is not working here. 1) `break_into_debugger` is not getting to the settrace part, or 2) settrace is not working as intended.

@polakovicp I will look it why this is not working. For your local environment (to remove the version warning), check if you have  `ptvsd` installed and upgrade it. From version 4.x onwards `enable_attach` no longer uses **secret**.

**Comment by karthiknadig** [comment]
Both option 1 and 2 work for me.
![image](https://user-images.githubusercontent.com/3840081/44225112-65f06680-a141-11e8-86ac-29afc88724fa.png)

![image](https://user-images.githubusercontent.com/3840081/44225062-36415e80-a141-11e8-93ac-864dea3c9fc1.png)

Is there anything particularly different from the vanilla python 3.4 environment?

**Comment by polakovicp** [comment]
Maybe my environment is somehow screwed up...
**Can you help me how to update local ptvsd package?**

1) Right click on Python interpreter and select "Open Interactive Window"
![image](https://user-images.githubusercontent.com/522894/44250909-acec6380-a1f6-11e8-8dc4-49a8d2ac9721.png)

2) Get exe path & ptvsd version (notice 3.2.1 !!!)
![image](https://user-images.githubusercontent.com/522894/44250958-e58c3d00-a1f6-11e8-94fb-3f8abf8a8e7b.png)

3) Copy exe path and past & run in windows cmdline - not ptvsd installed
![image](https://user-images.githubusercontent.com/522894/44250991-0d7ba080-a1f7-11e8-8c5e-09b2d40cbbb3.png)

**Comment by polakovicp** [comment]
More info
```
>>> ptvsd.__file__
'c:\\program files (x86)\\microsoft visual studio\\2017\\professional\\common7\\ide\\extensions\\microsoft\\python\\core\\ptvsd\\__init__.py'
```
But there is also another ptvsd package in VS installation folder:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd`

```
C:\>Python35\python.exe
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append(r"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages")
>>> import ptvsd
>>> ptvsd.__version__
'4.1.1a9'
```
So how to force VS to load the 4.1.1a9 package instead of old version?

**Comment by karthiknadig** [comment]
@polakovicp in VS2017 15.7* go to **Tools > Options > Python > Experimental** and enable the experimental debugger. That will enable the new debugger `4.1.1a9` for Launch (i.e, when you hit F5) and Attach (i.e., from Debug > Attach to process). `4.1.1a9` is the latest that is available with VS.

For the interactive window. By default VS will load the old debugger (3.2.1), we have not moved the `repl` part to the new debugger yet. To get the new debugger features you can do this in the interactive window (similar to what you did in the above comment):
```python
>>> import sys
>>> del sys.modules['ptvsd']
sys.path.append(r"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages")
>>> import ptvsd
```

To test the remote feature locally, I recommend creating a virtual environment and pip install `ptvsd==4.1.1.a11`. Then activate and run the test code you had provided in that environment.
If that works then we can try and figure out what is different about the environment in the Linux machine that prevents this for working.

**Comment by polakovicp** [comment]
I don't have _experimental debugger_ in my VS 15.8.0 :\
![image](https://user-images.githubusercontent.com/522894/44323796-c4745800-a453-11e8-8a04-7208afb4d8c6.png)

**Comment by karthiknadig** [comment]
In VS 2017 15.8.* the ptvsd>=4.1.* is the default debugger. This is the debugger that will be used when you start debugging with F5. But, when you start an interactive window we still use ptvsd==3.2.1 for that. If you want to test attach locally with the latest version of ptvsd, you should do it from the windows command prompt.

**Comment by polakovicp** [comment]
With your help it's finally working with the _break_into_debugger_ method. Many thanks

**Comment by karthiknadig** [comment]
Awesome. Glad, I could help.

**Comment by Tahirhan** [comment]
In my case removing "pathMappings" from launch.json solved the issue.

**Comment by ZERO20** [comment]
hi can you help me please I am running odoo with docker-compose, is there a way to add the commands in the yml file? I am currently installing pip3 install debugpy with docker exec and then run the command `python3 -m debugpy --listen 0.0.0.0:3001 /usr/bin/odoo  -w odoo -r odoo --db_host db -p 5432` 

when executing it in vsc it is marked in orange and it tells me that the points are on a file that does not exist, please if you can help me I would greatly appreciate it since the debug is something that helps a lot
![Captura de pantalla_2020-05-11_12-50-45](https://user-images.githubusercontent.com/8439796/81594163-18407680-9386-11ea-8873-26112b5dd8cd.png)
![code](https://user-images.githubusercontent.com/8439796/81594173-1b3b6700-9386-11ea-8db9-03ed00933fc1.png)

**Comment by Tahirhan** [comment]
Hi,

You are using port 5432 in command line but port in launch.json is 8879, it
doesn't match. After fixing that remove 'pathMappings' from launch.json and
try again.

Sincerely,
Tahirhan

Edgar de la Cruz <notifications@github.com>, 11 May 2020 Pzt, 20:51
tarihinde şunu yazdı:
