### ISSUE TITLE
Tooltip/watch missing module members

### ISSUE THREAD

**Issue by zooba** [microsoft/ptvsd#763]
When expanding a module via a tooltip, not all its members are shown.

Even when expanding a module via the Watch window, it shows more members, but not all of them.

`dir(sys)` has more than either of them. Ideally, all the same members would appear (even `__dunder__` and `_internal` members - debugging is not the time where it's useful to hide information).

![image](https://user-images.githubusercontent.com/1693688/44365477-cf90ad80-a47e-11e8-9f56-56f5e337619b.png)

**Comment by karthiknadig** [comment]
This feels like the same issue as #66

**Comment by zooba** [comment]
Similar, but worse. Most of the missing items do not have underscores at all - they seems to be mostly functions (often builtin functions) or special types. #66 should also be fixed, of course, but this is much more impactful.
