### ISSUE TITLE
Re-enable frame eval mode in debugger

### ISSUE THREAD

**Issue by fabioz** [Microsoft/ptvsd#768]
In a previous fix, the debugger frame eval mode was disabled, but it should be re-enabled later on.

-- see: https://github.com/Microsoft/ptvsd/issues/358#issuecomment-390966462 for more info on when the frame eval mode can be used and its limitations.

-- in the scenario where it works well as it has a very good performance (so, its use is limited but under the proper circumstances its overhead can be near zero -- i.e.: when entering a function call, the overhead to determine tracing is comparable to the tracing debugger, but afterwards, when inside of a function with a breakpoint, the regular mode needs to actually trace the function whereas the frame eval has zero overhead and acts as a programmatic breakpoint).

Note that to re-enable it, the root cause of the performance degradation when both the frame eval mode and the regular mode needs to be fixed (so, there should be a performance test to make sure there are no performance regressions after breakpoints are changed).

**Comment by fabioz** [comment]
Will start taking a look at this one again (@karthiknadig, can you assign to me?)

**Comment by karthiknadig** [comment]
Via #989
