### ISSUE TITLE
Intersection with project's module names: module 'queue'

### ISSUE THREAD

**Issue by dmyger** [Microsoft/ptvsd#773]
## Environment data
- PTVSD version: ptvsd-4.1.1+6.gdf9c8fd
- OS and version: OpenSuse Linux
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.5
- Using VS Code or Visual Studio: VS Code 1.26.1

## Actual behavior
Edit `.vscode/launch.json` to select **pythonExperimental** instead old python debugger. Then run my project for debugging and got following error:
```
Could not connect to localhost: 41589
Traceback (most recent call last):
  File "/home/dmitriy/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1699, in main
    debugger.connect(host, port)
  File "/home/dmitriy/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 326, in connect
    self.initialize_network(s)
  File "/home/dmitriy/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 313, in initialize_network
    self.writer = WriterThread(sock)
  File "/home/dmitriy/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 418, in __init__
    self.cmdQueue = _queue.Queue()
AttributeError: module 'queue' has no attribute 'Queue'
```
After investigation I found that issue is in crossing of names of modules. My project has '**queue**' module, too! So debugger tries import 'Queue' from my module not out his own. 
If I change a name of the folder with my module, then debugger will run without specified error.
Also, I have `.env` file with `PYTHONPATH` set to my work space folder, but it does not affect on issue.

## Expected  behavior
I expect that debugger should not depend on project hierarchy and should uses only own modules.
At least old debugger works correctly with this project.

## Steps to reproduce:
1. Create project with module 'queue':
```
    ${workspaceFolder}/
        .env
        src/
            main_app.py
            queue/
                __init__.py
                myqueue.py
```
2. Select `pythonExperimental` debugger in `launch.json`:
```
{
    "name": "My App",
    "request": "launch",
    "type": "pythonExperimental",
    "console": "integratedTerminal",
    "debugStdLib": true,
    "program": "${workspaceFolder}/main_app.py",
    "cwd": "${workspaceFolder}",
    "args": [ ........ ]
}
```
3. Try run the project for debugging

**Comment by fabioz** [comment]
`queue` is a standard library module and you should not shadow it in your own project (if you do it, it's common to break many other dependencies -- in this case it's the debugger, but many other projects may depend on the `queue` module from the standard library being available).

My suggestion is creating your own top-level package and then putting your `queue` package inside it.

i.e.:
```
    ${workspaceFolder}/
        .env
        src/
            main_app.py
            my_app/
                queue/
                    __init__.py
                    myqueue.py
```
Then importing it `from my_app import queue`.

-- sidenote: for Python 3 the `__init__.py` is not actually needed (if it's not there, the folder becomes a namespace package by default -- although you can still add the `__init__.py` to have it behave like it used to on Python 2).

**Comment by karthiknadig** [comment]
Re-open if the above resolution doesn't work for you.
