### ISSUE TITLE
Stepping takes long time when variables have large amounts of data

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#788]
## Environment data

- PTVSD version: master
- OS and version: Any
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Using VS Code or Visual Studio: Any

**Comment by fabioz** [comment]
I think one of the culprits may be that all locals are gotten in a single step whereas it'd be better to get it in parts (I saw that the debug adapter protocol provides a way to get partial results, so, implementing the debug adapter protocol and making it possible to load variables in steps could improve the situation here -- also, the current protocol which uses `xml` and `urllib.quote` is probably not ideal in this case).

 -- as I was already planning to use the debug adapter protocol to fix https://github.com/Microsoft/ptvsd/issues/45, this may be fixed along that one (it'd be nice to have a sample case with the problem to check before/after).

**Comment by fabioz** [comment]
Starting to tackle porting the variable requests to pydevd (when that's finished, this issue should also be fixed).

**Comment by gramster** [comment]
Need to support paged requests.

**Comment by fabioz** [comment]
Note: I wasn't able to get paged requests working for named variables (which is the case for locals -- see: https://github.com/microsoft/vscode/issues/87718 for more details).

**Comment by fabioz** [comment]
@karthiknadig do you have the real-world use case for this? (does it happen with named variables or indexed variables?)
