### ISSUE TITLE
How often will/should PTVSD be released

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#789]
* Should we consider releasing PTVSD every time we release a new version of the Python Extension?
    * I Say yes.
    * Note: This is only necessary if there are any new changes/fixes in PTVSD that can be integrated into the python extension.

The reason I bring this up is https://github.com/Microsoft/vscode-python/issues/2498#issuecomment-419589205
* Here an issue was reported in the Python Extension
* However it was fixed over a week ago.
* The issue was resolved before VS Code was released.
* In such cases, it makes perfect sense to release a new version of PTVSD, to ensure we have all of the latest fixes. 

I.e. release PTVSD (if there are changes) just before the release of the Python Extension.

cc @Microsoft/pvsc-team @gramster

**Comment by brettcannon** [comment]
I suspect that having staggered sprints will mean ptvsd can release the week prior to the end of our last sprint before a release.

**Comment by MikhailArkhipov** [comment]
POR is to have release branches with numbered releases. Release branch forks week before the extension release. Fixes are accepted on a case by cases basis into the release branch and then integrated into the master. Master is always open. Same applies to LS.
