### ISSUE TITLE
Can not set IDE-breakpoints in remote Python debugging session

### ISSUE THREAD

**Issue by SteveGuidi** [Microsoft/ptvsd#792]
## Environment data

- PTVSD version: 4.1.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.14 (amd64) via Visual Studio Python Tools
- Using VS Code or Visual Studio: Visual Studio 2017 15.8.3

## Actual behavior

I'm trying to debug a remote Python application using the Visual Studio 2017 IDE and the PTVSD debugger.  I am connecting to a Linux server via an OpenSSH tunnel initiated from Powershell.  In order to attach the debugger, I've followed the steps documented in [issue #753](https://github.com/Microsoft/ptvsd/issues/753#issuecomment-413440162).

My issues arise when starting to set breakpoints via the IDE.  For the time being, I've used the technique to set an in-code breakpoint using `ptvsd.break_into_debugger()`.  This causes the debugger to retrieve the source file locally and allow stepping and inspection of variables.  However, when I try to set an IDE breakpoint, the following error and stack trace is produced.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ptvsd/wrapper.py", line 1254, in done
    fut.result()
  File "/usr/local/lib/python2.7/site-packages/ptvsd/futures.py", line 40, in result
    reraise(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/ptvsd/futures.py", line 149, in callback
    x = next(it)
  File "/usr/local/lib/python2.7/site-packages/ptvsd/wrapper.py", line 2059, in on_setBreakpoints
    path = args['source']['path']
KeyError: 'path'
```

Alternatively, if I follow the documentation on [this page](https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines?view=vs-2017) and try to set the IDE breakpoint in the local copy of the remote file, then I get the following error message.

```
pydev debugger: warning: trying to add breakpoint to file that does not exist: /media/steve/src/project/e:\path\src\project\main.py (will have no effect)
```

Note that the above is for a copy of the remote file on my local machine -- not the temp file that is created when the debugger downloads the remote file.  This issue is also described in #753 and #248, but it is odd as the above documentation was updated 8 days ago on Sept. 2, 2018.

Unfortunately, this means that I am relegated to editting the remote files and using `ptvsd.break_into_debugger()` each time I need to set a breakpoint, which is _totally unusable_ for large projects.  Is there another workaround for this issue?  Perhaps my use of the OpenSSH tunnel is causing the file paths to get messed up?

**Comment by karthiknadig** [comment]
Visual Studio 2017 currently does not support the `pathMappings` argument that is needed by `ptvsd`, to map remote and local files. Unfortunately, for VS the best option is to use `ptvsd.break_into_debugger()`.

/cc @huguesv
