### ISSUE TITLE
Out-of-proc debug adapter

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#800]
This assumes that as a part of doing the multi-process debugging support we will be switching the communication between `ptvsd` and `pydevd` to a real socket.

## Old implementation (no multi-process support) : v4.1.4
![image](https://user-images.githubusercontent.com/3840081/45507001-c2957000-b745-11e8-9386-f579df90f2b6.png)

## Current Implementation for Multi-process debugging: v4.2.0
![image](https://user-images.githubusercontent.com/3840081/48870199-bad0f800-ed94-11e8-9155-f6412e332c91.png)

## Stage 2: `ptvsd` runs Out-of-process
![image](https://user-images.githubusercontent.com/3840081/45507202-46e7f300-b746-11e8-9c5f-c8a4ba5dcd6d.png)

## Final: Remove DA written in TS
![image](https://user-images.githubusercontent.com/3840081/45507361-bf4eb400-b746-11e8-9f18-7f8a1e9119f3.png)

/cc @DonJayamanne @int19h

**Comment by DonJayamanne** [comment]
Related issue https://github.com/Microsoft/ptvsd/issues/801

**Comment by karthiknadig** [comment]
Done in `dbg_adapter_refactor` branch. Alpha version is available on pypi. Closing this, since we are currently tracking individual issues that occur with switching to python debug adapter.
