### ISSUE TITLE
Create debug adapter in Python

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#801]
_From @DonJayamanne on April 11, 2018 5:5_

Currently the debug adapter is written in typescript, and in the `launch` handler we start the python process that's running PTVSD, after this we connect the VSC streams to the python process streams.
From then on the Typescript DA doesn't play any role.

VS Code have some changes in the pipeline that'll make it possible to write the debug adapter in Python. I.e. just before the debug is launched we have the ability to provide the path to the selected (workspace) python interpreter, along with any custom arguments.
https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L384

However this seems to be in preview (no idea when they'll release this).

Either way, what's good about this is the fact that we can build the debug adapter completely in python (as part of PTVSD).

@brettcannon @ericsnowcurrently @karthiknadig @int19h cc

_Copied from original issue: Microsoft/vscode-python#1367_

**Comment by DonJayamanne** [comment]
@karthiknadig would it be possible to write the DA in python for VS? Please could you check with the VS DA team.

**Comment by DonJayamanne** [comment]
_From @int19h on April 11, 2018 5:19_

VS implementation doesn't have a debug adapter in that sense - they provide us with an extensibility point for stuff like launch and attach, that works via .NET interfaces, which are implemented by code in the same process as VS itself. Turning it into an out-of-proc Python implementation would be a substantial change, and I'm not sure it's even feasible for all the VS features that we need.

**Comment by DonJayamanne** [comment]
_From @ericsnowcurrently on April 11, 2018 17:5_

I'm definitely on board with writing the adapter in Python.  TBH, I still think that ptvsd should be a fully compatible implementation of the protocol.  Then we could use it directly in VSC, with no need for a second adapter.  For VS (or any other non-protocol needs), we'd have shims on top as necessary.

Of course, taking this approach is not practical in the short term, so having a shim to use in VSC would be fine for now.  Keeping it in the ptvsd repo makes sense since it's not specific to our extension (or is it?).

**Comment by DonJayamanne** [comment]
_From @ericsnowcurrently on April 11, 2018 17:7_

@int19h As to an out-of-proc Python implementation, I'd like to understand better about:

* what the "adapter" for VS would look like (what it looks like now in C#?)
* what the different challenges are to using a Python implementation in-proc would be
* what's this restriction about out-of-proc execution (i.e. subprocesses)

Are there quick answers (or perhaps it would be better to talk about it in the debugger meeting)?

**Comment by DonJayamanne** [comment]
_From @int19h on April 11, 2018 17:22_

Take a look at the code here, ignoring the "Debugger" subfolder.

https://github.com/Microsoft/PTVS/tree/master/Python/Product/Debugger

**Comment by DonJayamanne** [comment]
_From @int19h on April 11, 2018 17:24_

I don't see how we can avoid a second adapter in VSC though. By its very nature, ptvsd has to run in the debuggee process. For remote scenarios, this means that it's talking to something over a socket; and VSC cannot talk debugger protocol over a socket (remotely and in a supported way). And for local scenarios, it can't talk over stdin/out, because the user code will be using it for its own purposes - so, again, we need a socket.

**Comment by DonJayamanne** [comment]
_From @karthiknadig on April 11, 2018 17:28_

If we move the socket connection from VSC-ptvsd to ptvsd-pydevd. Then we can have a out-of-proc python only adapter. I see it like the broker-RAU-RHost that we have in RTVS.

**Comment by DonJayamanne** [comment]
_From @fabioz on June 27, 2018 17:20_

As a note, I've actually started creating a debug adapter with pydevd in pure python some time ago (before starting to work along ptvsd, so, that's paused for some time already) with a debug adapter on python (I've made a couple of blog posts related to it: http://pydev.blogspot.com/2018/05/howto-launch-and-debug-in-vscode-using.html / http://pydev.blogspot.com/2018/05/howto-launch-and-debug-in-vscode-using_12.html) and in the process I made pydevd itself talk through the debug adapter protocol... (although that support is definitely still not complete, I only got it to the point of adding a simple breakpoint and then disconnecting).

One thing to note is that to handle the multiprocessing capabilities of pydevd either a new connection to a new process must be made or the adapter needs to handle talking to multiple processes and translating those to the client as if it was a single process composed on threads from the multiple processes (I started to go that path in my case as I think it's a better approach -- also, it's not clear to me how it'd work to ask vscode to handle a connection to an incoming process transparently from an existing debug adapter)... I'm mentioning this because I think that the debug adapter itself (being `node` or `python`) needs to do that communication in order for things to work properly and I think doing it `python` is better ;)

`ptvsd` could still do any needed customization using the mechanism that pydevd provides for other extensions (creating a `pydevd_plugins.extensions` package and using existing pydevd hooks for the customization and handling the launching parameters), so, I think that it could be a reasonable approach (although this is something that still requires a good amount of work to get done).

**Comment by karthiknadig** [comment]
Done in `dbg_adapter_refactor` branch. Alpha version is available on pypi. Closing this, since we are currently tracking individual issues that occur with switching to python debug adapter.
