### ISSUE TITLE
Python debugger not working with breakpoints in Visual Studio Code

### ISSUE THREAD

**Issue by SueMcMetzger** [Microsoft/ptvsd#815]
I have very simple code. Can run Debug in both integrated and external terminal with expected results. However, the minute I set a breakpoint, I get an error indicating an IndexError that begins with this:
Traceback (most recent call last):
File "c:\Users\smcfarla.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\wrapper.py", line 1254, in done
fut.result()
File "c:\Users\smcfarla.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\futures.py", line 40, in result
reraise(self._exc_info)

If I choose Step In, the program runs but seems to ignores the breakpoint and does not display values for the variable listed in the Watch panel.

This was working just fine prior to the Aug 2018 update and also prior to recent Windows udpates.

Suggestions?
Thanks,
Sue

VS Code version: Code 1.27.2 (f46c4c4, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.14393

System Info
Item	Value
CPUs	Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz (4 x 2594)
GPU Status	2d_canvas: enabled
checker_imaging: disabled_off
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
rasterization: enabled
video_decode: enabled
video_encode: enabled
webgl: enabled
webgl2: enabled
Memory (System)	7.91GB (2.29GB free)
Process Argv	C:\Program Files\Microsoft VS Code\Code.exe
Screen Reader	no
VM	0%
Extensions (3)
Extension	Author (truncated)	Version
anaconda-extension-pack	ms-	1.0.0
python	ms-	2018.8.0
vscode-yaml	red	0.0.16

**Comment by SueMcMetzger** [comment]
I realize this problem only happens when working on a networked drive. Is there a fix?

**Comment by karthiknadig** [comment]
@SueMcMetzger This is the fix, https://github.com/Microsoft/ptvsd/commit/80dec2a423417d32a39294697fc368ac838edf41 it is in master.
