### ISSUE TITLE
Verify remote debugging with multiple path mappings

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#819]
## Environment data

- VS Code version: Latest
- Extension version (available under the Extensions sidebar): Latest
- OS and version: Windows + Docker
- Python version (& distribution if applicable, e.g. Anaconda): XXX
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A

## Actual behavior

![image](https://user-images.githubusercontent.com/1948812/45733619-4d3afc80-bb96-11e8-922f-92544beb8028.png)

## Expected  behavior

No errors

**Comment by karthiknadig** [comment]
Verified that this works.
