### ISSUE TITLE
Sub-process: Do not reuse port in child process

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#820]
Currently we allow re-use of ports in ptvsd by default. we should add a switch that turns off this feature.

**Comment by int19h** [comment]
We will still need to use the option to avoid crashing processes hogging up the port. But it looks like it's all more complicated than just allowing reuse, and also varies by platform.

https://docs.microsoft.com/en-us/windows/desktop/winsock/using-so-reuseaddr-and-so-exclusiveaddruse

https://stackoverflow.com/a/14388707/111335

**Comment by karthiknadig** [comment]
Let us use this work item to add the option to fail on address reuse. I will create another work item to refactor and properly set reuse for all supported platforms.

**Comment by karthiknadig** [comment]
This was a issue specific to windows. We decided to use SO_EXCLUSIVEADDRUSE on windows to fix this.
