### ISSUE TITLE
Refactor: Reuse socket as per requirements of various supported platform

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#821]
References:
https://docs.microsoft.com/en-us/windows/desktop/winsock/using-so-reuseaddr-and-so-exclusiveaddruse
https://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t/14388707#14388707

**Comment by avirlrma** [comment]
Hey @karthiknadig, Can I take a shot at this one?  P.S. I am new here and would require a bit of mentoring.
Thanks

**Comment by karthiknadig** [comment]
@avirlrma I would not recommend this one. There are several issues in the 'icebox' pipeline that you could try. You have to install 'ZenHub for GitHub' extension to see them.

**Comment by avirlrma** [comment]
will do and  thanks for the info

**Comment by karthiknadig** [comment]
This is done in refactor branch
