### ISSUE TITLE
Variables not listed when debugging with pypy

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#825]
## Environment data

- PTVSD version: Latest
- OS and version: Tested and reported on Mac (**not verified on other OS**)
- Python version (& distribution if applicable, e.g. Anaconda): pypy
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Variables & Watch window not working.
Evaluation of variables not working.

## Expected  behavior

Variables, watch window, debug console should be able to list and evaluate variables.

## Steps to reproduce:
1. Debug with pypy
2. View variables window

Note: Looking at the json output, I can see that the `variables` request has failed.
`{"type": "response", "seq": 14, "request_seq": 10, "success": false, "command": "variables", "message": "", "body": {}}`

However no error messages are returned.

**Comment by fabioz** [comment]
Right now `pydevd` itself is not tested with `pypy`, so, I think that the first step here would be adding `pypy` as a new target in `pydevd` tests (should a new ticket be created for that?)

**Comment by karthiknadig** [comment]
Created  https://github.com/microsoft/ptvsd/issues/835 to track test target work item.

Additional info about this bug:
Looks like Get frame fails with `Frame not found: 56715728 from thread: pid_18684_id_46712688`

**Comment by karthiknadig** [comment]
This seems to be behaving better with the latest version of ptvsd (at least on windows):
![image](https://user-images.githubusercontent.com/3840081/53155200-64c94780-3571-11e9-9284-d08c2cf25c47.png)

**Comment by karthiknadig** [comment]
Verified, that the latest bits work on linux pypy as well.
