### ISSUE TITLE
VS code, appengine gusetbook app, debug hits sometimes depending on restart vs code

### ISSUE THREAD

**Issue by moguzalp** [microsoft/ptvsd#830]
## Environment data

- PTVSD version: 4.1.2
- OS and version: Windows 10
- Python version: 2.7
- Using VS Code

## Actual behavior

When I debug proj, google appengine sample project: guestbook, in terminal window in C:\Python27\Lib\site-packages\ptvsd at below method:

    def async_handler(m):
        """Converts a generator method into a fire-and-forget async one."""
        m = futures.wrap_async(m)

        def f(self, *args, **kwargs):
            fut = m(self, self.loop, *args, **kwargs)

            def done(fut):
                try:
                    fut.result()
                except BaseException:
                    traceback.print_exc(file=sys.__stderr__)

            fut.add_done_callback(done)

        return f

this error occurs:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\ptvsd\wrapper.py", line 1275, in done
    fut.result()
  File "C:\Python27\lib\site-packages\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "C:\Python27\lib\site-packages\ptvsd\futures.py", line 149, in callback
    x = next(it)
  File "C:\Python27\lib\site-packages\ptvsd\wrapper.py", line 1458, in _handle_attach
    yield self._send_cmd_version_command()
  File "C:\Python27\lib\site-packages\ptvsd\wrapper.py", line 1454, in _send_cmd_version_command
    return self.pydevd_request(cmd, msg)
  File "C:\Python27\lib\site-packages\ptvsd\wrapper.py", line 1300, in pydevd_request
    return self._pydevd_request(self.loop, cmd_id, args)
  File "C:\Python27\lib\site-packages\ptvsd\wrapper.py", line 441, in pydevd_request
    os.write(self.pipe_w, s.encode('utf8'))
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\python\runtime\stubs.py", line 42, in os_error_not_implemented
    raise OSError(errno.ENOSYS, 'Function not implemented')
OSError: [Errno 40] Function not implemented
errnoerrno

<module 'errno' (built-in)><module 'errno' (built-in)>

this screenshot enlighten the proj I think

![image](https://user-images.githubusercontent.com/8073348/45867184-89837e00-bd8b-11e8-82b1-1fe19cd20e3b.png)

Thus this occurs sometimes, I mean break point hits sometimes and sometimes not when I restart project of course

The isssue is depicted at this [SO thread](https://stackoverflow.com/q/52249076/492258) as well

**Comment by nvictor** [comment]
I have the same issue. The solutions on SO are unlikely. It looks like ptvsd needs some OS functionalities that GAE disables at runtime... because on the production server you won't have access to them either. 

A real catch-22 scenario here. You are on the development server and want to debug. But you can't debug because GAE wants the dev environment to look like production.

The solution for ptvsd to work with GAE is likely to do without access to "os.write". I am no expert in debugger implementation but I know PyCharm does not run into that issue. So technically it is possible...

**Comment by karthiknadig** [comment]
This should be addressed by #1052

**Comment by gramster** [comment]
This is old appengine w/Python 2; we aren't going to fix it.
