### ISSUE TITLE
Refactoring: IPC-JSON

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#831]
The product itself and the test suite use two completely different implementations of IPC JSON protocol underlying DAP. This is partly because the product implementation is server-side-only, and the test implementation is client-side-only. Even so, it is mostly the same functionality, and there's no reason to implement it twice in such a radically different way. Furthermore, neither of those implementations has proper test coverage.

This item captures the work necessary to converge on a single implementation that is used throughout the product and the high-level test suite, with proper tests of its own.

**Comment by karthiknadig** [comment]
I say this is priority. since we will need this for multi-proc IPC to send back pid/port etc...
