### ISSUE TITLE
Test refactoring: high-level test framework

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#832]
We currently have several different micro-frameworks across the test suite, which share some code and duplicate the other. There needs to be a single micro-framework to write tests against ptvsd, with all tests uniformly using that framework. The framework should be pytest-based, and should abstract away lifecycle management in a way that makes it clear what the test is doing by looking solely at the test code itself, but without too much repeated scaffolding. The framework itself should be properly covered by tests.

**Comment by int19h** [comment]
In particular, it should be possible to run thsame high-level test to be automatically in local launch, socket ("remote") attach, and PID ("local") attach scenarios, to detect bugs that are due to initialialization sequence between them - e.g. a breakpoint being hit immediately after socket attach, but not hit immediately after PID attach - without duplicating the test code.

**Comment by karthiknadig** [comment]
This is required refactoring needed to simplify tests, debugging of tests, and overall stability going forward. Currently we have to fight with the infrastructure to identify issues in the product code.
