### ISSUE TITLE
Test refactoring: functional tests

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#833]
We need more functional tests - i.e. those that test ptvsd as a black box (including pydevd) against the requirements imposed by clients such as VS and VSCode. This is partially reflected in the existing `system_tests` sub-suite, but there are many things missing there that should be ported from the corresponding VS and VSCode test suits.

**Comment by int19h** [comment]
The initial step here is to look at VS and VSC Python test suites, and determine which tests in them don't have a ptvsd equivalent, or such equivalent is substandard. Then separate work items can be created to cover the specific tests that need porting.

**Comment by karthiknadig** [comment]
I will turn this into an epic and add smaller items to this
