### ISSUE TITLE
Attach to pid fails to attach in 3.7

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#846]
## Environment data

- PTVSD version: master
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VSC

## Actual behavior

Follow error message is shown:
```
Connecting to 64 bits target
Injecting dll
Dll injected
Allocating code in target process
Writing code in target process
Allocating return value memory in target process
Injecting code to target process
Waiting for code to complete
Error when injecting code in target process. Error code: 3 (on windows)
```

## Expected  behavior

Should attach.

## Steps to reproduce:
1. Use this test code, `test.py`:
```python
import time
for x in range(10000):
    time.sleep(1)
    print(x)
```
2. Open command prompt and run test code: `C:\Python37\python.exe test.py`
3. Open another command prompt and run ptvsd:
`C:\Python37\python.exe -m ptvsd --host localhost --port 5678 --pid <pid_of _test>`

**Comment by fabioz** [comment]
Attach to process needs support for Python 3.7 (please assign to me to add it).

**Comment by andyneff** [comment]
This also fails the exact same way in python 3.6.6. Is this a separate issue?

**Comment by fabioz** [comment]
This one is only to track the issue with python 3.7 on Windows. 

The issue with python 3.6 on Linux seems to be something different (so, please create a separate report).

**Comment by fabioz** [comment]
@karthiknadig I'm updating the native code here... right now, in the `pydevd` repo I compile the resulting dlls (for x86 and x64) on my machine and commit those to the repo to ease on deployment, so, my question is: should I provide those compiled dlls in a pull request (as happens in `pydevd`) or just the source code? 

-- as a note, in the current master, the committed version on `ptvsd` and `pydevd` are equal (binary-wise), so, it seems that it's using the same binary I compiled/committed in `pydevd`.

**Comment by karthiknadig** [comment]
Committing the binary is fine. We will also need the symbols for the dlls in windows.
