### ISSUE TITLE
Error "No module named ptvsd.__main__" with ptvsd version greater than 4.1.1

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#848]
## Environment data

- PTVSD version: 4.1.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Using VS Code or Visual Studio: VS Code

## Actual behavior

After upgrading ptvsd to 4.1.2 or 4.1.3, getting below error when I try to debug any Python file.
C:\Python27\python.exe: No module named ptvsd.main; 'ptvsd' is a package and cannot be directly executed.

After 5-10 seconds, a message window appears which says "Timeout waiting for debugger connection"

Workaround is to go back to ptvsd 4.1.1

## Expected  behavior

Debugging should be possible for Python scripts with "Python: Current File" as well as "Python: Flask" configurations

## Steps to reproduce:
Open a flask application or a single .py file in VS code.
Make sure you have ptvsd version 4.1.2 or 4.1.3
Set the debugging configuration to 'Python: Current File' or "Python: Flask"
Try to debug using F5.

An observation:
I started a Python prompt on integrated terminal and imported ptvsd.
ptvsd.file refers to
"....vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\init.pyc'

The ptvsd.version returns 4.1.1 although I have pip installed ptvsd 4.1.2

Original issue https://github.com/Microsoft/vscode-python/issues/2698

**Comment by karthiknadig** [comment]
Does not repro.
