### ISSUE TITLE
Debugging in VS Code breaks with 'Unable to open <frozen importlib._bootstrap>' error

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#85]
When debugging using the latest version of PTVSD I'm getting the following error:

`Unable to open '<frozen importlib._bootstrap>': File not found (file:///Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/debuggerTests/`

Tested with yesterdays with a snapshot of yesterdays repo (around lunchtime) and it works.

Commenting out the following [line of code](https://github.com/Microsoft/ptvsd/blob/master/ptvsd/wrapper.py#L276) fixes the issue :
```python
            self.proc.pydevd_notify(
                pydevd_comm.CMD_ADD_EXCEPTION_BREAK, msg)
```

Possibly specific to Macs only, as this is required for VS.

**Comment by Maransatto** [comment]
Hi, I still didn't get the idea of how to set this value of Raised Exeptions to false.
How can I do it?
I couldn't find it on VS Code settings nor launcher.

It wall happened when I started to use modules from sibling folders using ```sys.path.insert(0,'../sibling-foler'')```

Now I can even run my code but I can't debug due this error.

**Comment by The-any-Key** [comment]
I still getting this error when using breakpoints (works fine when no breakpoints is used):
  File "E:\Program Files\Reallusion\iClone 7\Bin64\lib\site-packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command.py", line 687, in process_net_command
    f = open(path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'e:\\program files\\reallusion\\iclone 7\\&lt;frozen importlib._bootstrap&gt;'

**Comment by karthiknadig** [comment]
@The-any-Key This was caused by https://github.com/Microsoft/ptvsd/issues/1077 The fix is in master, but not released yet.
