### ISSUE TITLE
Undefined variable error in breakpoint condition on for line

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#853]
## Environment data

- PTVSD version: 4.1.3
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: VS

## Actual behavior

Undefined variable error, breakpoint never hit
```
Error while evaluating expression: i>1600 
Traceback (most recent call last): 
  File "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 52, in handle_breakpoint_condition 
    return eval(condition, new_frame.f_globals, new_frame.f_locals) 
  File "<string>", line 1, in <module> 
NameError: name 'i' is not defined 
The program 'python.exe' has exited with code -1 (0xffffffff).
```

## Expected  behavior

Undefined variable error ignored and breakpoint hit once it is defined. That was the behavior in ptvsd 3.x. 

## Steps to reproduce:
1. Write this code:

```
from math import cos, radians 
def make_dot_string(x): 
    rad = radians(x) 
    numspaces = int(20 * cos(radians(x)) + 20) 
    st = ' ' * numspaces + 'o' 
    return st 
def main(): 
    for i in range(0, 1800, 12): 
        s=make_dot_string(i) 
        print(s) 
main()
```

2. set a conditions breakpoint on the `for i in range...` line, hover on red dot and click breakpoint setting, set condition `i>1600`

3. start debugging

Note: of course if you put the breakpoint inside the for loop instead, that works as expected.

**Comment by fabioz** [comment]
A question: should all errors be silenced or just name errors?

**Comment by fabioz** [comment]
@karthiknadig this one needs additional integration work (which was removed because of failing ptvsd tests).

**Comment by karthiknadig** [comment]
@fabioz with the fix, i don't see `NameError` but the break point does not hit after `i` gets defined.
