### ISSUE TITLE
Connection*Error in JsonMessageChannel worker should be handled in _process_incoming_messages

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#865]
## Environment data

- PTVSD version: master
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: Any

## Actual behavior

When using JsonMessageChannel on server side, if clinet closes connection without calling socket.shutdown the worker thread raises this exception and fails.
```
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\GIT\pyscratch2\mymodule\messaging.py", line 341, in _process_incoming_messages
    message = self.stream.read_json()
  File "c:\GIT\pyscratch2\mymodule\messaging.py", line 97, in read_json
    line = self._read_line()
  File "c:\GIT\pyscratch2\mymodule\messaging.py", line 80, in _read_line
    line += self._reader.readline()
  File "C:\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

## Expected  behavior

Should not crash thread. This is expected when client socket connection is disrupted.

## Steps to reproduce:
1. Start JsonMessageChannel using server mode socket.
2. Start another JsonMessageChannel using client mode socket and connect to the server mode socket
3. Connect to the socket in (1)
4. exchange few messages
5. Close the client socket, without calling shutdown.

**Comment by karthiknadig** [comment]
@int19h This is fixed right?

**Comment by int19h** [comment]
Yep!
