### ISSUE TITLE
Stop on entry stops in stdlib in Mac

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#869]
## Environment data

- PTVSD version: master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VSC

## Actual behavior

@DonJayamanne Created this to track the potential issue that you mentioned. Can you provide details on where it actually stops? Also, please change any of environment data if it is wrong.

## Expected  behavior

Should stop in user code.

## Steps to reproduce:
1.

**Comment by karthiknadig** [comment]
@DonJayamanne Does this repro with `ptvsd` master?

**Comment by DonJayamanne** [comment]
Works now, thanks
