### ISSUE TITLE
pyfile adds an additional new line in every line of code

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#875]
## Environment data

- PTVSD version: master
- OS and version: any
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio:

## Actual behavior

code:
```python
@pyfile
def foo():
    print('one')
    print('two')
```
The file generated by pyfile, `foo.py`:
```python
print('one')

print('two')

```

## Expected  behavior

The file generated by pyfile, `foo.py`:
```python
print('one')
print('two')
```

Having the extra blank lines makes it confusing to set breakpoints in tests.

**Comment by rozuur** [comment]
Can I work on fixing this?
