### ISSUE TITLE
Instructions to log everything to diagnoze PTSVD

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#880]
I'm trying to diagnose a debugger issue https://github.com/Microsoft/vscode-python/issues/2732#issuecomment-427437573 in VSC Python.
From what we can tell this is isolated to Anaconda distro.

The problem is simple:
* PTVSD does not connect to the debug adapter host
* Its specific to Anaconda.

We have the logs for the JSON comms, and there's nothing in there.
Please could you provide the instructions to enable **full tracing** in PTVSD (and pydev).

I'd like to see see everything (going on in PTVSD and PyDev) and hopefully we can find, some errors, warnings, or the like being logged to determine the root cause of this issue.

**Comment by karthiknadig** [comment]
Setting environment variable `PTVSD_DEBUG` to `1` gives some info. I think the log-file option is broken, it is not passed all the way through. 
/cc @int19h  

@fabioz any suggestion on logging from `pydevd`?

**Comment by DonJayamanne** [comment]
PTVSD_DEBUG should be sufficient for now. Thanks

**Comment by karthiknadig** [comment]
#890 should allow logging to file and control verbosity. When that is done, I will add the instructions to read me.

**Comment by int19h** [comment]
I added the instructions here.

https://github.com/Microsoft/ptvsd/blob/master/README.md#debugger-logging

@DonJayamanne, for F5 from VSC, using the environment variable is currently the only way to do this in `launch.json` - but you could add an explicit separate option, and translate it to `--log-dir`.
