### ISSUE TITLE
subprocess: support Django and Flask

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#885]
The current implementation only support `python -c`. It needs to be changed to use a different pydevd hook to also support running Python files and modules, which is the mode used by Django and Flask.

**Comment by int19h** [comment]
When running in multiprocess mode, pydevd rewrites the command line of the started process if it is invoking the Python interpreter. As part of that rewrite, it calls `_get_python_c_args`, which is what ptvsd detours to set itself up. However, that function only gets called when the child process is started with `python -c` (i.e. a code blurb, not file or module). When child processes are launched with `python file.py` or `python -m module`, that code path is not involved.

To handle the latter cases, ptvsd needs to detour `patch_args` instead, and replace it with an implementation that invokes itself. The following steps are necessary for that:

- #886 - support `-c` (so that we can properly rewrite command lines that involve it)
- #856 - support `--port-range` for child ports
- #887 - do the actual command line rewriting

This is a meta-issue to track these. Its successful completion shall be indicated by the ability to successfully multiproc-debug Django and Flask apps in debug/autoreload mode.

**Comment by karthiknadig** [comment]
I added these issues to the subprocess epic that is tracking Django and Flask. I will close this and we can track this there.
