### ISSUE TITLE
Changes in CLI arguments between versions

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#896]
## Environment data

- PTVSD version: 4.1.3
- Using VS Code or Visual Studio: N/A

## Actual behavior

* CLI args for starting apps for remote debugging has changed 
* Now the arg requires `--server-host`, this wasn't the case in the past.
* This is a breaking change.

## Expected  behavior

* We need to revert if possible as existing users will not be able to use PTSVD for remote debugging scenarios.

Reported here https://github.com/Microsoft/vscode-python/issues/2833#issuecomment-428422616

**Comment by DonJayamanne** [comment]
Please feel free to change the Priority label.

**Comment by jarshwah** [comment]
FWIW I think the `--server-host` came in on the previous version? I could not get remote debugging working with 2018.8.0 / 4.1.2, and specifically waited for these combination of versions to work again, so please don't just revert if you can manage it.

**Comment by DonJayamanne** [comment]
> so please don't just revert if you can manage it.

No decision had been made yet.

**Comment by karthiknadig** [comment]
Verify using this branch `v4.1.4-branch`

**Comment by DonJayamanne** [comment]
Oops, tested there too, no luck.
Have to use `--host 0.0.0.0` for it to work.
