### ISSUE TITLE
Improve test timeout handling on Windows

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#898]
On Windows, when a test times out, pytest-timeout kills the entire test process (because it can't shut things down with signals), so further tests aren't run at all. This is very vexing for automated runs, especially since "waiting for a ptvsd message that never came" is a fairly common failure mode when tests fail.

I think it is possible to implement a "soft" timeout scheme, that would basically work [same as pytest-timeout does](https://bitbucket.org/pytest-dev/pytest-timeout/src/fe7aed25207c1bc37cd5b76a799dc4738be44fb6/pytest_timeout.py), but instead of killing the process, it would just close the ptvsd session socket. This would immediately cause the test to fail, and ptvsd to exit. 

pytest-timeout can still be used as the ultimate fallback to ensure no stuck test runs.

**Comment by karthiknadig** [comment]
Is this still needed?
