### ISSUE TITLE
User cannot update local variables' values in runtime

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ptvsd#905]
## Environment data

- PTVSD version: 4.1.3
- OS and version: Ubuntu 18.04 & Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7, 3.6.5
- Using VS Code or Visual Studio: VSCode (insiders and stable), vscode-python 2018.9.0.

## Details

See Microsoft/vscode-python#2859

**Comment by karthiknadig** [comment]
This was a issue in VSC.
