### ISSUE TITLE
Vagrant (Windows host, client, Linux guest, server) breakpoints don't work

### ISSUE THREAD

**Issue by skqr** [Microsoft/ptvsd#947]
## Environment data

- PTVSD version: 4.1.4
- OS and version: Windows 10 host / CentOS 7 guest (on Vagrant w/VirtualBox)
- Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.15 (Windows), 2.7.5 (Linux)
- Using VS Code or Visual Studio: VS Code

## Actual behavior

I'm using VS Code on Windows 10, running my script on the Vagrant CentOS guest machine as follows:

```bash
python -m ptvsd --host 0.0.0.0 --port 5678 --wait -m debugger_test
```

I'm then running the same script on VS Code, by attaching its debugger:

```json
        {
            "name": "Python Attach (Remote Debug 55.55.55.5)",
            "type": "python",
            "request": "attach",
            "debugOptions": [
                "WindowsClient"
            ],
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/vagrant"
                }
            ],
            "port": 5678,
            "host": "55.55.55.5"
        },
```

So far, so good. Any break point on the initial script works just fine. However, any break points on any imported file have a big problem; the execution stops on the break point, but VS Code, for some reason, thinks execution is still going. The button to pause execution is displayed, instead of the one to resume it, even though execution has already paused.

## Expected  behavior

VS Code should be able to tell whether the script is executing regardless of which script the break points are on, even on an attached debugger on a process running on a Vagrant guest machine, and even if the host is running Windows.

## Steps to reproduce:
1. Use this Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# requires install of guest additions plugin `vagrant plugin install vagrant-vbguest`
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7" # using 7 bc it has py 2.7
  config.vbguest.auto_update = true
  config.vbguest.no_remote = false

  config.vm.network "forwarded_port", guest: 5678, host: 5678  # VScode debugger
  config.vm.network "private_network", ip: "55.55.55.5"
end
```
2. To run any script with an import in it with the VS Code ptvsd configuration above and add a break point on the imported script.
3. Run the debugger with the attached _attach_ profile.

**Comment by karthiknadig** [comment]
Looks like this does not repro with master:
![image](https://user-images.githubusercontent.com/3840081/48022550-4c333f80-e0f0-11e8-8839-5ec165ef83fa.png)

I do see that we have bug with `enable_attach` where we get `NonType` Type Error. https://github.com/Microsoft/ptvsd/issues/987
