### ISSUE TITLE
Debugging Django in VSC with subprocess debugging is very slow

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#967]
## Environment data

- PTVSD version: Master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7
- Using VS Code or Visual Studio:VSC

## Actual behavior

Debugging django with live reload (subprocess debugging) is very slow.
To the extent, its almost unusable - i thought it wasn't working.

It takes over 30seconds to start django.
Reloading takes around 10 seconds or longer.

## Expected  behavior

Should be fast.

## Steps to reproduce:
Start debugging django with the following config:
```js
        {
            "name": "Django2",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver"
            ],
            "django": true,
            "subProcess": true
        },
```

**Comment by karthiknadig** [comment]
This repros on windows as well. Starting the new process seems to take a long time. could this be because of #648 ?

**Comment by ihakh** [comment]
I am developing on Linux and it is slow on Linux too
It seems that it get slow on serving the static file
when it enters the python code (views.py) the speed is okay
