### ISSUE TITLE
Uncaught Exceptions are not always detected

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#971]
## Environment data

- PTVSD version: master
- OS and version: any
- Python version (& distribution if applicable, e.g. Anaconda): any
- Using VS Code or Visual Studio: vsc

## Actual behavior

uncaught exceptions are not always caught when attached to remote.

## Expected  behavior

Should break on uncaught exceptions.

## Steps to reproduce:
1. use the following script:
```
import ptvsd
ptvsd.enable_attach()
ptvsd.wait_for_attach()

raise ValueError()
```

**Comment by fabioz** [comment]
As a note, I've noticed something similar with regular breakpoints too and investigating a bit it seems that the `wait_for_attach` is not waiting for all breakpoints to be sent before proceeding.
