### ISSUE TITLE
VS Code opening duplicate window while debugging (invalid paths in stack trace)

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#973]
## Environment data

- PTVSD version: master
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.0
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Opens a parallel editor buffer for the file under debugging.

## Expected  behavior

Not to open a parallel editor buffer. :)

## Steps to reproduce:
```python
from flask import Flask
app = Flask(__name__)


@app.route('/')
def hello():
    return "Hello J-💰!"

if __name__ == '__main__':
    app.run()
```
```json
{
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py",
                "FLASK_DEBUG": "1"
            },
            "args": [
                "run"
                //"--no-debugger",
                //"--no-reload"
            ],
            "jinja": true,
            "subProcess": true,
            "logToFile": true
        }
```

[debug6232.log](https://github.com/Microsoft/ptvsd/files/2531947/debug6232.log)
[debug18056.log](https://github.com/Microsoft/ptvsd/files/2531948/debug18056.log)

**Comment by DonJayamanne** [comment]
> @brettcannon couldn't enable subprocess using the flag in the insiders build. Is that not updated yet to have this option?

Thats because we're not bundling the dev version of PTVSD with the dev version of the extension. You'll need to install it your self.

**Comment by karthiknadig** [comment]
Sorry if this wasn't clear. I was using master ptvsd with the latest insiders version of the extension. I still got the squiggly under the "subprocess" (on that that day). The latest insiders has the "subprocess" option, so I can try this without forcing multiproc in the debugger itself.

**Comment by karthiknadig** [comment]
I am not able to repro this either. In the logs I don't see any strange paths.

**Comment by karthiknadig** [comment]
@DonJayamanne this is probably same as #983?
