### ISSUE TITLE
SystemExit raised when debugging test via code lens

### ISSUE THREAD

**Issue by potens1** [microsoft/ptvsd#982]
## Environment data

- VS Code version: 1.28.2
- Extension version (available under the Extensions sidebar): 2018.9.1
- OS and version: Linux Arch
- Python version (& distribution if applicable, e.g. Anaconda): python 3.6.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv 
- Relevant/affected Python packages and their versions: ?

## Actual behavior
When debugging tests, on some of my workpaces, at the end of the test, the testlauncher.py file open and red stacktrace appears on line [58](https://github.com/Microsoft/vscode-python/blob/master/pythonFiles/experimental/testlauncher.py#L58) 
```python
Exception has occurred: SystemExit
0
  File "/home/nic/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/testlauncher.py", line 58, in run
    pass
  File "/home/nic/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/testlauncher.py", line 64, in <module>
    run(cwd, testRunner, args)
```
## Expected  behavior

No stacktrace and the testlauncher.py file should not open

## Steps to reproduce:
1. I created only a little test_fake.py with
```
def test_fake():
    return True
```
and then debug it

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Nothing 
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
Nothing
```

**Comment by djbrown** [comment]
# Same here

## Environment data
* VS Code version: 1.28.2
* Extension version (available under the Extensions sidebar): 2018.9.**2**
* OS and version: **Ubuntu 18.04 .1 LTS**
* Python version (& distribution if applicable, e.g. Anaconda): python 3.**7.1**
* Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv
* Relevant/affected Python packages and their versions: **unittest**?

```
Exception has occurred: SystemExit
True
  File "/home/djbrown/.vscode/extensions/ms-python.python-2018.9.2/pythonFiles/PythonTools/visualstudio_py_testlauncher.py", line 344, in main
    pass
  File "/home/djbrown/.vscode/extensions/ms-python.python-2018.9.2/pythonFiles/PythonTools/visualstudio_py_testlauncher.py", line 347, in <module>
    main()
```

## Workaround
This does not happen when I turn off `Uncaught Exceptions` from the Breakpoints Menu.
But then I have to catch Exceptions specifically.

**Comment by PaulStubbs** [comment]
I have the same issue. Running Ubuntu 16.04, python 3.5.2, pytest, in a virtual environment.
Running python -m pytest runs correctly with a pass or a fail test, both work fine. But when I click on the debugtest above the test function it fails with this exception.

Exception has occurred: SystemExit
0
  File "/home/marvin/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/testlauncher.py", line 58, in run
    pass
  File "/home/marvin/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/testlauncher.py", line 64, in <module>
    run(cwd, testRunner, args)

**Comment by Adanteh** [comment]
Same one here. Using 3.5.4 pipenv and unittests and clicking the Debug Test

```
Exception has occurred: SystemExit
True
  File "C:\Users\<user>\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\visualstudio_py_testlauncher.py", line 344, in main
    pass
  File "C:\Users\<user>\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\visualstudio_py_testlauncher.py", line 347, in <module>
    main()
```

**Comment by AndreaCitrolo** [comment]
Same also here, using, vscode 1.30.2, conda 4.5.11, python 3.7.0, on ubuntu 16.04.

Exception has occurred: SystemExit
False
  File "/home/<user>/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/visualstudio_py_testlauncher.py", line 344, in main
    pass
  File "/home/<user>/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/visualstudio_py_testlauncher.py", line 347, in <module>
    main()

**Comment by DonJayamanne** [comment]
@karthiknadig @int19h 
Solution is #997 
I'd close this issue in favour of #997

**Comment by Cartman0** [comment]
I have same issue yet \.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\visualstudio_py_testlauncher.py".
can solve when exclude "visualstudio_py_testlauncher.py"?

**Comment by Rainningme** [comment]
same here.

**Comment by ManPython** [comment]
@alexr00 this issue mading VSC sadly life : )
"Me too" rapid by VSC Debuger in Django

https://stackoverflow.com/questions/52372810/visual-studio-code-python-debugging-exception-has-occurred-systemexit

**Comment by Thisisguillermo** [comment]
Still hasn't been fixed as of June 2020.

With my code being:

```python
import sys

while True:
  print('Type exit to exit')
  response = input()
  if response == 'exit':
      sys.exit()
  print('You typed ' + response + '.')
```

**Comment by ManPython** [comment]
Still problems when starting debug on any work with python, not only DJango. But after 2,3 time of "play" runing normaly. In my opinion it's sabotage by MS..

**Comment by int19h** [comment]
@Thisisguillermo This issue is specifically for debugging tests. Your snippet looks like a plain console app - are you starting it via F5? If so, can you please file a separate issue, and include your launch.json and other steps necessary to repro?

**Comment by karthiknadig** [comment]
@ManPython If you are running into any issue other than SystemExit during testing, then please file separate bugs for them, in the debugpy repo: https://github.com/microsoft/debugpy

@Thisisguillermo Please file issue on https://github.com/microsoft/debugpy

**Comment by karthiknadig** [comment]
Locking this thread since any further discussion or solution will be handled on the `debugpy` repo.
