### ISSUE TITLE
VS Code opening duplicate window while debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#983]
## Environment data

- PTVSD version: Release & Master
- OS and version: Windows
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio: VSC

## Actual behavior

Duplicate editor window opens up.

## Expected  behavior

Should not open a duplicate folder.
This is a regression.

## Steps to reproduce:
1. Open VSC
2. Create a file named `xyz.py` with a simple loop.
```python
import time

for i in range(10):
	print(i)
	time.sleep(1)
```
1. Start the python program as follows:
`python -m ptvsd --wait --host localhost --port 5678 xyz.py`
2. Add a breakpoint in `xyz.py`
2. Attach to the above program in VSC (same instance of VSC)
3. VSC opens a duplicate window

**Comment by DonJayamanne** [comment]
Similar to https://github.com/Microsoft/ptvsd/issues/973
Or perhaps we should close #973 in favor of this as it is not specific to subprocess.

**Comment by karthiknadig** [comment]
We have a separate issue that affects XML specific special characters. I think this is different.

**Comment by karthiknadig** [comment]
This does not repro for me. Let me know when you are free, so we can see what is going on. I tried this with ptvsd master and extension 2018.10.0-beta

**Comment by karthiknadig** [comment]
![image](https://user-images.githubusercontent.com/3840081/47932428-e72cdf00-de8e-11e8-9dfb-e37d17214cc4.png)

**Comment by int19h** [comment]
@DonJayamanne, can you share launch.json for the repro?

**Comment by karthiknadig** [comment]
Looks like providing explicit path mappings works, but the default path mappings that the extension adds causes VSC to bring up the duplicate source. confirmed this with @DonJayamanne

**Comment by karthiknadig** [comment]
Adding estimates to track the amount of time spent on unplanned work.
