### ISSUE TITLE
Debug console displaying incorrect key order for Python 3.7

### ISSUE THREAD

**Issue by brettcannon** [microsoft/ptvsd#998]
Microsoft/vscode-python#3236

Insertion order is preserved in Python 3.7 (and unofficially in 3.6), but in the debug console the keys seem to be sorted.

**Comment by brettcannon** [comment]
This is also affecting `OrderedDict`.

**Comment by fabioz** [comment]
Note: I'm currently taking a look at this.

**Comment by kbakk** [comment]
Is this working as it should? I'm getting a different order when printing:

![image](https://user-images.githubusercontent.com/24817039/101609690-8f66e780-3a07-11eb-99c2-841f207740fd.png)

**Comment by fabioz** [comment]
> Is this working as it should? I'm getting a different order when printing:

If you believe you have an issue, please create a new issue with more details (i.e.: Python version and code to reproduce).

Note: new issues should be created in `debugpy`: https://github.com/microsoft/debugpy/issues as `ptvsd` is discontinued.
